go/integration/end2end/main.go, go/lib/infra/infraenv/infraenv.go, go/lib/pathmgr/pathmgr.go, go/lib/pathmgr/pathmgr_test.go, go/lib/snet/snet.go
Fixes #2875
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2885)
=> log: Use ctx logger for snet path resolver

go/lib/scrypto/BUILD.bazel, go/lib/scrypto/keymeta.go, go/lib/scrypto/keymeta_test.go, go/lib/scrypto/trc/v2/keychanges.go, go/lib/scrypto/trc/v2/pop.go, go/lib/scrypto/trc/v2/primary.go, go/lib/scrypto/trc/v2/primary_json_test.go, go/lib/scrypto/trc/v2/primary_test.go, go/lib/scrypto/trc/v2/signed.go, go/lib/scrypto/trc/v2/signed_test.go, go/lib/scrypto/trc/v2/trc.go, go/lib/scrypto/trc/v2/trc_json_test.go, go/lib/scrypto/trc/v2/trc_test.go, go/lib/scrypto/trc/v2/update_test.go, go/lib/scrypto/validity.go, go/lib/scrypto/validity_test.go, go/lib/scrypto/version.go, go/lib/scrypto/version_test.go
Previously, the TRC package defined its own KeyMeta and Version format. 
However, this will be reused by the issuer and AS certificates.
This PR moves the definitions to scrypto.
Additionally, fixes #2911
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2912)
=> scrpto: Move KeyMeta + Version

go/lib/scrypto/cert/v2/BUILD.bazel, go/lib/scrypto/cert/v2/base.go, go/lib/scrypto/cert/v2/base_json_test.go, go/lib/scrypto/cert/v2/base_test.go, go/lib/scrypto/trc/v2/trc.go, go/lib/scrypto/validity.go
This change introduces the base certificate struct that holds the shared fields between the issuer an AS certificates. 
(Contributes to #2853)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2910)
=> cert: Add base certificate

go/lib/infra/common.go, go/lib/infra/messenger/messenger.go, go/lib/infra/messenger/messenger_with_metrics.go, go/lib/infra/messenger/messenger_with_metrics_test.go, go/lib/infra/messenger/quic_response_writer.go, go/lib/infra/messenger/udp_response_writer.go, go/lib/infra/mock_infra/infra.go, go/lib/sciond/sciond.go
Fixes #2896
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2914)
=> HP: Add HP messages to the messenger

go/beacon_srv/internal/beaconing/extender.go, go/beacon_srv/internal/beaconing/propagator.go, go/beacon_srv/internal/beaconing/registrar.go
Currently, the propagator and registrar attempt to execute their
operations even if no interface is active.
This leads to a lot of noise output.
This PR introduces the following changes:
- Propagator: Early return when no interfaces are active.
- Registrar: Ignore all beacons with inactive ingress interface.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2921)
=> BS: Ignore inactive interfaces in Propagator/Registrar

go/lib/scrypto/cert/v2/base.go, go/lib/scrypto/cert/v2/base_json_test.go, go/lib/scrypto/trc/v2/primary.go, go/lib/scrypto/trc/v2/primary_json_test.go, go/lib/scrypto/trc/v2/signed_json_test.go
Currently some map keys are string types that implement the
`json.Unmarshaler` interface. Unfortunately, json.Unmarshal will ignore
string types' UnmarshalJSON method and simply set the string.
The same holds for the `encoding.TextUnmarshaler`.
(see: https://github.com/golang/go/issues/33298)
This PR makes those keys of integer type to ensure the parsing will
catch malformed map inputs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2927)
=> scrypto: Make map keys integers

go/lib/scrypto/cert/v2/BUILD.bazel, go/lib/scrypto/cert/v2/as.go, go/lib/scrypto/cert/v2/as_json_test.go, go/lib/scrypto/cert/v2/as_test.go, go/lib/scrypto/cert/v2/base.go, go/lib/scrypto/cert/v2/base_json_test.go
This PR adds the AS certificate with parsing and validation.
contributes to #2853
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2936)
=> cert: Add AS certificate

go/lib/infra/modules/combinator/combinator.go, go/lib/pathmgr/pathmgr.go, go/lib/pathmgr/watch.go, go/lib/pathpol/BUILD.bazel, go/lib/pathpol/acl.go, go/lib/pathpol/acl_test.go, go/lib/pathpol/hop_pred.go, go/lib/pathpol/hop_pred_test.go, go/lib/pathpol/pathset.go, go/lib/pathpol/policy.go, go/lib/pathpol/policy_test.go, go/lib/pathpol/sequence.go, go/lib/sciond/types.go, go/lib/spath/spathmeta/apppath.go, go/sciond/internal/fetcher/fetcher.go
Instead of accepting an interface{} which must be a spathmeta.AppPathSet, define a type in the pathpol package that must be given as an input.
This way we will get more flexibility in what we pass in.
Everything that implements the accepted type can now be filtered by the policy.
Also remove goconvey dependency from pathpol testing.
Fixes #2939
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2943)
=> path-policy: Change Act method signature

go/lib/pathpol/acl.go, go/lib/pathpol/acl_test.go, go/lib/pathpol/hop_pred.go, go/lib/pathpol/policy_test.go, go/sciond/internal/fetcher/BUILD.bazel, go/sciond/internal/fetcher/filter.go, go/sciond/internal/fetcher/filter_test.go
Filters paths with the given policy, using the policy's Act method.
Fixes #2821
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2945)
=> sciond: Add method to filter paths with a policy

scion.sh
With this PR, no-color mode is only enabled on CI.
This reduces the output of `./scion.sh test` to the relevant parts
and makes it useful for humans again.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2954)
=> Test: Make bazel output useful

BUILD.bazel, Makefile
Fixes https://github.com/scionproto/scion/issues/2963
Also:
- Clean bin/* before untarring binaries into it, to prevent old binaries
from lying around.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2964)
=> Separate out CI binaries from scion.tar

go/sig/egress/session/sessmon.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2977)
=> SIG: Fix bug with not pushing the changed path to the Session

WORKSPACE, nogo.json
https://github.com/capnproto/go-capnproto2/pull/146 fixed
non-determinism in the `schema_X` var in generated capnp.go files.
Also:
- Add exception for unreachable check for go-capnp as it currently
fails.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2981)
=> Update go-capnp to version with deterministic output.

go/lib/pathdb/pathdbtest/BUILD.bazel, go/lib/pathdb/pathdbtest/pathdbtest.go, go/lib/pathdb/sqlite/sqlite_test.go, go/lib/periodic/BUILD.bazel, go/lib/periodic/periodic_test.go, go/lib/util/BUILD.bazel, go/lib/util/checksum_test.go, go/lib/util/duration_test.go, go/lib/util/padding_test.go, go/lib/util/yaml_test.go
Remove goconvey from
-pathdb
-periodic
-util
tests.
Without convey we have better insights into failures that happen in CI.
Contributes #2986
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2988)
=> Remove goconvey from {pathdb,periodic,util} tests

go/lib/pathdb/BUILD.bazel, go/lib/pathdb/metrics.go, go/lib/pathdb/metrics_test.go, go/lib/pathdb/mock_pathdb/pathdb.go, go/lib/pathdb/pathdb.go, go/lib/pathdb/pathdbtest/pathdbtest.go, go/lib/pathdb/sqlite/sqlite.go
This is needed for the new path lookup strategy and for the policy integration in path lookup.
Contributes #2454
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2990)
=> pathdb: Add next query deletion methods

go/tools/scion-pki/internal/cmd/BUILD.bazel, go/tools/scion-pki/internal/cmd/cmd.go, go/tools/scion-pki/internal/pkicmn/pkicmn.go, go/tools/scion-pki/internal/v2/cmd/BUILD.bazel, go/tools/scion-pki/internal/v2/cmd/cmd.go, go/tools/scion-pki/internal/v2/conf/BUILD.bazel, go/tools/scion-pki/internal/v2/conf/as.go, go/tools/scion-pki/internal/v2/conf/as_test.go, go/tools/scion-pki/internal/v2/conf/isd.go, go/tools/scion-pki/internal/v2/conf/isd_test.go, go/tools/scion-pki/internal/v2/tmpl/BUILD.bazel, go/tools/scion-pki/internal/v2/tmpl/as.go, go/tools/scion-pki/internal/v2/tmpl/cmd.go, go/tools/scion-pki/internal/v2/tmpl/isd.go
This PR adds the v2 control plane PKI templating to the scion-pki tool.
Until everything is moved to the new format, this command will live
under the sub-command `v2`.
fixes #2989
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2991)
=> SPKI: Generate templates

go/sig/base/core/as.go, go/sig/main.go
The goal here is to narrow down the interface between main and egress
and thus make changes to egress easier.
Also removes unused ASEntry.AddNet and ASEntry.DelNet functions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2994)
=> SIG: Split egress setup into a single function

go/lib/common/errors.go, go/sciond/internal/fetcher/fetcher.go
- The logger does not expect an `error` after the string, so removing
`nil`.
- The logger does not do a good job with `[]error`, so created
`common.FmtErrors` to handle this.
Before:
```
2019-08-21 09:01:33.830842+0000 [WARN] Failed to verify reply debug_id=747f80c4 trace_id=64dc60702aa9bf7 LOG15_ERROR="Key(<nil>) is not a string: <nil>" LOG15_ERROR="Key([]error) is not a string: [Failed to verify seg seg="55c11074ec66 2019-08-21 09:01:31+0000 1-ff00:0:110 1>41 1-ff00:0:111"
DEBUGTHISTHING 2 Failed to verify seg seg="55c11074ec66 2019-08-21 09:01:31+0000 1-ff00:0:110 1>41 1-ff00:0:111"
DEBUGTHISTHING 2]" LOG15_ERROR="Normalized odd number of arguments by adding nil"
```
After:
```
2019-08-20 15:59:05.693430+0000 [WARN] Failed to verify reply debug_id=e544675c trace_id=6963201a9432fbae …
```
=> Fix sciond logging for processing path replies.

docker/Dockerfile.base, docker/perapp/base/Dockerfile.base, docker/perapp/base/Dockerfile.builder, docker/perapp/base/Dockerfile.debug, docker/perapp/files/bazelrc.quiet, env/zlog/deps, scion.sh
When `bazel test` runs in CI, it outputs about 3k lines that are just
noise due to the "progress" output. This change makes bazel
build/test/run quiet in CI.
Also:
- Make curl quieter when downloading some packages.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3023)
=> Make bazel quiet in CI.

go/lib/pathdb/pathdbtest/pathdbtest.go, go/lib/pathdb/query/query.go, go/lib/pathdb/sqlite/sqlite.go
This can be helpful when processing the results, without knowing beforehands what type of segments the query will get,
e.g. when querying by interfaces.
Fixes #3025
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3028)
=> pathdb: Return segment type in result

go/lib/scrypto/cert/v2/as_json_test.go, go/lib/scrypto/cert/v2/as_signed_test.go, go/lib/scrypto/cert/v2/as_test.go, go/lib/scrypto/cert/v2/base_test.go, go/lib/scrypto/cert/v2/issuer_json_test.go, go/lib/scrypto/cert/v2/issuer_signed_test.go, go/lib/scrypto/cert/v2/issuer_test.go, go/lib/scrypto/cert/v2/verify_test.go, go/lib/scrypto/trc/v2/signed_test.go, go/lib/scrypto/trc/v2/trc_json_test.go, go/lib/scrypto/trc/v2/trc_test.go, go/lib/scrypto/trc/v2/update_test.go, go/lib/scrypto/trc/v2/verify_test.go
Always provide the not_before time of the validity period to avoid
flaky tests at second boundaries.
fixes #2993
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3022)
=> scrypto: Fix flaky tests

go/lib/keyconf/keyconf.go, go/tools/scion-pki/internal/v2/cmd/BUILD.bazel, go/tools/scion-pki/internal/v2/cmd/cmd.go, go/tools/scion-pki/internal/v2/conf/as.go, go/tools/scion-pki/internal/v2/keys/BUILD.bazel, go/tools/scion-pki/internal/v2/keys/cmd.go, go/tools/scion-pki/internal/v2/keys/gen.go
Add key generation capability for v2 to scion-pki tool.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3004)
=> SPKI: Generate keys

go/beacon_srv/internal/config/config.go, go/border/brconf/params.go, go/cert_srv/internal/config/config.go, go/godispatcher/internal/config/config.go, go/lib/env/BUILD.bazel, go/lib/env/features.go, go/lib/env/sample.go, go/path_srv/internal/config/config.go, go/sciond/internal/config/config.go, go/sig/internal/sigconfig/conf.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3030)
=> Feature flags

go/beacon_srv/internal/beacon/beacondbtest/beacondbtest.go
-Give more time
-Fix revocation test it should return 2 beacons
-Use channel for empty check to make sure go routines can properly clean up after them (e.g. call rows.Close())
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3032)
=> Add some fixes to the beacon db test suite

go/tools/logdog/BUILD.bazel, go/tools/logdog/main.go, go/tools/logdog/main_test.go
Adds a `-contains` flag to logdog, which will help to filter output only to contain specific lines.
For example `logdog -contains="trace_id=5255b3b0583d6a0a" *.log` will only contain log entries with the given trace_id.
Fixes #3031
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3033)
=> logdog: Add contains filter

go/lib/topology/braddr.go, go/lib/topology/topology_test.go
Both PublicOverlay and BindOverlay methods on TopoBRAddr would panic
there is no address set for the requested overlay type.
This change fixes that and also makes OverBindAddr a public type so it
is easier to work with it as the only way to get such objects is by
parsing a topology file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3034)
=> topology: fix panic and make overBindAddr public

go/lib/infra/common.go, go/lib/infra/mock_infra/infra.go, go/lib/infra/modules/trust/BUILD.bazel, go/lib/infra/modules/trust/signhelper.go, go/lib/infra/modules/trust/signhelper_test.go, go/proto/sign.go
This PR makes the acceptable timestamp range for signatures
configurable.
Additionally, allow small time diffs in the future to allow for clock
drift.
fixes #3002
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3003)
=> verifier: Make acceptable TS range configurable

go/lib/env/BUILD.bazel, go/lib/env/features_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3036)
=> Add test to check that all feature flags are boolean

go/sciond/internal/fetcher/fetcher.go
The error handling for remote TRCs not found locally is brittle.
By simply checking the error message with `common.GetErrMsg`, catching
wrapped errors is not possible.
fixes #3037
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3043)
=> sciond: Fix TRC not found locally error logic

go/lib/infra/modules/segfetcher/BUILD.bazel, go/lib/infra/modules/segfetcher/fetcher.go, go/lib/infra/modules/segfetcher/requester_test.go, go/lib/infra/modules/segfetcher/resolver.go, go/lib/infra/modules/segfetcher/resolver_test.go
For sciond we don't want to return segments that are revoked.
Also test some more cases in the resolver tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3045)
=> segfetcher: Consider revocations in resolver

go/hidden_path_srv/internal/hiddenpathdb/BUILD.bazel, go/hidden_path_srv/internal/hiddenpathdb/adapter/BUILD.bazel, go/hidden_path_srv/internal/hiddenpathdb/adapter/pathdb_adapter.go, go/hidden_path_srv/internal/hiddenpathdb/adapter/pathdb_adapter_test.go, go/hidden_path_srv/internal/hiddenpathdb/hiddenpathdb.go, go/lib/xtest/matchers/matchers.go
Adds a HiddenPathDB interface to HPS together with an adapter implementation for the existing PathDB.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3044)
=> HP: HiddenPathDB interface and PathDB Adapter

go/lib/hpkt/BUILD.bazel, go/lib/hpkt/extension_test.go, go/lib/hpkt/hpkt_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3039)
=> Remove goconvey from go/lib/hpkt

go/lib/scrypto/asym.go, go/tools/scion-pki/internal/pkicmn/pkicmn.go, go/tools/scion-pki/internal/v2/cmd/BUILD.bazel, go/tools/scion-pki/internal/v2/cmd/cmd.go, go/tools/scion-pki/internal/v2/conf/isd.go, go/tools/scion-pki/internal/v2/keys/gen.go, go/tools/scion-pki/internal/v2/trc/BUILD.bazel, go/tools/scion-pki/internal/v2/trc/ases.go, go/tools/scion-pki/internal/v2/trc/cmd.go, go/tools/scion-pki/internal/v2/trc/proto.go, go/tools/scion-pki/internal/v2/trc/prototype.go, go/tools/scion-pki/internal/v2/trc/util.go
This change allows generating prototype TRC payloads.
A prototype TRC will be signed and then combined to a signed TRC.
Signing and combining is left for a future PR.
For convenience, a 'gen' command will also be added in the future that
executes the three phases in a single call.
contributes to #2983
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3049)
=> SPKI: Generate prototype TRC

go/lib/infra/modules/segfetcher/fetcher.go, go/path_srv/internal/segreq/handler.go, go/path_srv/internal/segreq/helpers.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3054)
=> segfetcher: Improve logging / documentation

go/lib/layers/BUILD.bazel, go/lib/layers/extensions.go, go/lib/layers/extensions_layer_test.go, go/lib/layers/extensions_test.go
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3051)
=> Remove Convey from layers package

.buildkite/steps/integration, go/lib/infra/modules/segfetcher/fetcher.go, go/lib/infra/modules/segfetcher/revocation.go, go/lib/infra/modules/segfetcher/segreplyhandler.go, go/lib/infra/modules/segfetcher/segreplyhandler_test.go
In the PS and SD we invalidate the NextQuery for all segments that have received a revocation. But currently we only do this for explicit revocations that come in as Revocation message, we should also do it for revocations that we receive in a SegReply from another PS.
This commit also invalidates NextQuery cache for revocations received in the SegReply.
Fixes #3057 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3058)
=> PS,SD: Use revocations from SegReply to invalidate NextQuery

doc/PathPolicy.md, go/lib/pathpol/BUILD.bazel, go/lib/pathpol/policy.go, go/lib/pathpol/policy_test.go
Change policy in pathpol.Options to ExtPolicy. This is required so an option can not only have anonymous policies, but also extend others. 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2349)
=> Pathpol: Change policy in options

go/beacon_srv/internal/beacon/beacondbsqlite/db_test.go, go/lib/pathdb/sqlite/sqlite_test.go
Currently, we see DB unit test failures due to context expiration.
This change adds a new context in the tests for pathdb and beacondb
sqlite to make sure long database loads to not trigger an expired
context.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3062)
=> db-test: Create new context after reopening DB

go/proto/cereal.go, go/proto/cereal_test.go
The recover defer was removed by a code refactor in #2707.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3059)
=> proto: Re-enable catching panics in proto library

WORKSPACE, go/lib/addr/isdas.go, go/lib/common/BUILD.bazel, go/lib/common/errors.go, go/lib/common/errors_test.go, go/lib/env/env.go, go/lib/infra/messenger/messenger.go, go/lib/infra/modules/trust/trust.go, go/lib/overlay/conn/conn.go, go/lib/pathpol/policy.go, go/sciond/main.go, go/tools/scion-pki/internal/conf/as.go, go/tools/scion-pki/internal/v2/conf/as.go
This commit adds Unwrap and Is methods to the BasicError type.
It also adds a SimpleError type that can be used for error string constants.
This will allow us to get rid of brittle error checks with GetErrorMsg=="some string".
Contributes #3042
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3048)
=> errors: add support for Is and Unwrap

go/proto/BUILD.bazel, go/proto/cereal_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3073)
=> proto: Make test run in bazel

go/tools/scion-pki/internal/v2/trc/BUILD.bazel, go/tools/scion-pki/internal/v2/trc/cmd.go, go/tools/scion-pki/internal/v2/trc/human.go
This PR adds a command to scion-pki that displays signed TRCs in
a human readable way. I.e. the payload and protected metadata are
parsed and shown as JSON objects.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3068)
=> SPKI: Display human readable TRCs

go/border/rctrl/BUILD.bazel, go/border/rctrl/ctrl.go, go/border/router.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3040)
=> BR: reconnect to dispatcher support

go/path_srv/internal/handlers/common.go, go/path_srv/internal/handlers/ifstateinfo.go, go/path_srv/internal/handlers/segreg.go, go/path_srv/internal/handlers/segrevoc.go, go/path_srv/internal/handlers/segsync.go, go/path_srv/internal/segreq/handler.go
The messenger already creates a context with a timeout, which is by default smaller (10s).
So we just use that one instead of creating a superfluous context with deadline.
Fixes #3077
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3080)
=> PS: Remove superfluous handler timeout

doc/ControlPlanePKI.md
Add the 'optimistic' qualifier to the certificate revocation process to
make the known limitations more explicit.
Specify that the TRC update must be synchronized amongst the available
authoritative ASes to show which property of CAP we sacrifice.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2932)
=> CPPKI: Emphasize best-effort revocation + CAP trade-off

go/border/main.go, go/godispatcher/BUILD.bazel, go/godispatcher/main.go, go/sig/main.go
Fixes #3067
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3074)
=> Disp: Do not allow running as root

go/tools/scion-pki/internal/certs/gen.go, go/tools/scion-pki/internal/tmpl/BUILD.bazel, go/tools/scion-pki/internal/tmpl/cmd.go, go/tools/scion-pki/internal/tmpl/topo.go, go/tools/scion-pki/internal/v2/cmd/cmd.go, go/tools/scion-pki/internal/v2/tmpl/BUILD.bazel, go/tools/scion-pki/internal/v2/tmpl/as.go, go/tools/scion-pki/internal/v2/tmpl/cmd.go, go/tools/scion-pki/internal/v2/tmpl/topo.go
This PR enables templating the isd.ini and as.ini from `.topo` files.
To template the config files for the `Default.topo` run
`scion-pki v2 tmpl topo topology/Default.topo`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3079)
=> SPKI: Generate templates from topology file

go/lib/pathmgr/pathmgr.go, go/lib/pathpol/pathset.go, go/lib/pathpol/policy_test.go, go/path_srv/internal/segutil/BUILD.bazel, go/path_srv/internal/segutil/filter.go, go/path_srv/internal/segutil/filter_test.go, go/sciond/internal/fetcher/filter.go
This method pre-filters a list of segments with a given path policy.
Note that filtering with sequences is not easily possible since we do not know where a segment would fit into the sequence (up, core, down).
A possibility to add sequence filtering for segments would be to split the sequence into up, core, and down parts.
Note that filtering with ACLs should only be done on core segments.
Up and down segments contain peering interfaces which might be used in the final path, eventhough the ACL would filter it.
Fixes #2820
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3072)
=> Add method to filter segments with a path policy

acceptance/cert_renewal_acceptance/test, go/tools/scion-pki/internal/certs/BUILD.bazel, go/tools/scion-pki/internal/certs/cmd.go, go/tools/scion-pki/internal/certs/customers.go, python/topology/cert.py, python/topology/config.py
Use scion-pki tool in the generator to have one way of generating
crypto material.
fixes #1491
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3084)
=> generator: Use scion-pki tool

.buildkite/acceptance-pipeline.sh, acceptance/sig_short_exp_time_acceptance/test
Currently, the next query does not consider path expiration time. (see #2979)
This PR reduces the query interval for sciond in the `sig_short_exp_time` expiration test.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3089)
=> Acceptance: Reduce query interval on sciond

.buildkite/acceptance-pipeline.sh, acceptance/discovery_br_fetches_dynamic_acceptance/test, acceptance/discovery_br_fetches_static_acceptance/test, acceptance/discovery_infra_fetches_dynamic_acceptance/test, acceptance/discovery_infra_fetches_static_acceptance/test, acceptance/discovery_util/util.sh
This PR increases the timings in the `discovery_*_fetches_*` tests to account for revocations.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3095)
=> Acceptance: Increase timings in discovery tests

go/lib/sciond/sciond.go, go/sciond/internal/config/config.go, go/sciond/internal/config/config_test.go, go/sciond/internal/config/sample.go, go/sciond/internal/servers/server.go, go/sciond/main.go
sciond sets the file mode for both its Reliable and Unix socket files.
The file mode comes from the configuration value SocketFileMode,
specified in octal as a string.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3099)
=> sciond socket file mode.

go/beacon_srv/internal/ifstate/metrics.go
Remove the state label from the ifstate metric.
before:
````
beacon_srv_ifstate{elem="bs1-ff00_0_110-1",ifid="1",state="Active"} 1
````
now:
````
beacon_srv_ifstate{elem="bs1-ff00_0_110-1",ifid="1"} 0
````
fixes #3103
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3105)
=> BS: Make ifstate metric useful

go/godispatcher/internal/config/BUILD.bazel, go/godispatcher/internal/config/config.go, go/godispatcher/internal/config/config_test.go, go/godispatcher/internal/config/sample.go, go/godispatcher/main.go, go/godispatcher/main_test.go, go/godispatcher/network/dispatcher.go, go/lib/sock/reliable/reliable.go, go/lib/util/BUILD.bazel, go/lib/util/file_mode.go, go/sciond/internal/config/config.go
Makes the file mode of the socket file configurable. (default 0770)
Abstracts the sciond FileMode type into util package and uses it in both configs.
Relates to #3099
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3124)
=> dispatcher socket file mode.

go/lib/keyconf/keyconf.go, go/tools/scion-pki/internal/cmd/BUILD.bazel, go/tools/scion-pki/internal/cmd/cmd.go, go/tools/scion-pki/internal/v2/cmd/BUILD.bazel, go/tools/scion-pki/internal/v2/cmd/cmd.go, go/tools/scion-pki/internal/v2/conf/as.go, go/tools/scion-pki/internal/v2/conf/isd.go, go/tools/scion-pki/internal/v2/keys/cmd.go, go/tools/scion-pki/internal/v2/keys/gen.go, go/tools/scion-pki/internal/v2/tmpl/as.go, go/tools/scion-pki/internal/v2/tmpl/cmd.go, go/tools/scion-pki/internal/v2/tmpl/isd.go, go/tools/scion-pki/internal/v2/tmpl/topo.go, go/tools/scion-pki/internal/v2/trcs/BUILD.bazel, go/tools/scion-pki/internal/v2/trcs/ases.go, go/tools/scion-pki/internal/v2/trcs/cmd.go, go/tools/scion-pki/internal/v2/trcs/human.go, go/tools/scion-pki/internal/v2/trcs/prototype.go, go/tools/scion-pki/internal/v2/trcs/sign.go, go/tools/scion-pki/internal/v2/trcs/util.go
This PR is in preparation to the scion-pki testing pipeline.
Instead of calling os.Exit() the tests now use cobra to return errors.
With this change, unit tests can check the exit codes of the application
without building and running the binary by directly invoking the
commands.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3102)
=> SPKI: Use RunE in cobra commands

python/topology/jaeger.py
Version 1.12 for me tried to allocate all the ram which would result in the machine no longer reacting.
With 1.14 I no longer saw this behavior.
Also use the new tmp volume (see https://github.com/jaegertracing/jaeger/pull/1571)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3128)
=> Update jaeger all-in-one image to 1.14

WORKSPACE, go/lib/addr/isdas.go
ANTLR had a problem with ARM 32:
https://github.com/antlr/antlr4/issues/1858
So we take v4.7.2 of ANTLR which fixes the issue.
Also use AS and ISD types for Max constants.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3129)
=> Fix build for ARM 32 bit

python/topology/jaeger.py, scion.sh
In #3128 we switched to temp storage, but that is deleted after calling down on the container.
That would mean on CI we can't access the traces, therefore switch back to the old storage approach.
Also update the version in scion.sh
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3131)
=> jaeger: Fix storing segments

.buildkite/steps/build_all.yml, docker/perapp/debug/Dockerfile.beacon, docker/perapp/debug/Dockerfile.border, docker/perapp/debug/Dockerfile.cert, docker/perapp/debug/Dockerfile.dispatcher_go, docker/perapp/debug/Dockerfile.path, docker/perapp/debug/Dockerfile.sciond
Previously app_builder was built as a dependency of the dispatcher docker image, this is no longer the case, therefore we need to explicitly pull it to be able to build the tester image.
Also remove old unused docker files.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3155)
=> CI: Fix build by making app_builder dependency explicit

.buildkite/acceptance-pipeline.sh, .buildkite/steps/build_all.yml, .buildkite/steps/docker-integration.yml, .buildkite/steps/integration, .buildkite/steps/setup.yml, .buildkite/steps/test.yml
Jobs where the agent is lost are not automatically retried, see https://github.com/buildkite/docs/pull/355. And docs: https://buildkite.com/docs/pipelines/command-step#automatic-retry-attributes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3156)
=> BK: Add automatic retry for jobs that lost their agent

go/beacon_srv/internal/keepalive/BUILD.bazel, go/beacon_srv/internal/keepalive/handler.go, go/beacon_srv/internal/keepalive/handler_test.go, go/beacon_srv/internal/keepalive/sender.go, go/beacon_srv/internal/keepalive/sender_test.go, go/beacon_srv/internal/metrics/BUILD.bazel, go/beacon_srv/internal/metrics/keepalive.go, go/beacon_srv/internal/metrics/metrics.go, go/lib/prom/prom.go
This PR works the first bullet on https://github.com/scionproto/scion/issues/3104
```
bs_keepalive_receive_msgs_total{ifid="1",result="success"} 118
bs_keepalive_receive_msgs_total{ifid="2",result="success"} 118
bs_keepalive_transmit_msgs_total{ifid="1",result="process_err"} 118
bs_keepalive_transmit_msgs_total{ifid="2",result="process_err"} 118
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3151)
=> BS: Add metrics for the keepalive messages

go/beacon_srv/internal/beacon/beacon_test.go, go/beacon_srv/internal/beacon/beacondbtest/beacondbtest.go, go/beacon_srv/internal/beacon/metrics_test.go, go/border/rpkt/BUILD.bazel, go/border/rpkt/rpkt_test.go, go/lib/as_conf/BUILD.bazel, go/lib/as_conf/conf_test.go, go/lib/ctrl/seg/BUILD.bazel, go/lib/ctrl/seg/segs_test.go, go/lib/log/logparse/BUILD.bazel, go/lib/log/logparse/logentry_test.go, go/lib/pathdb/pathdbtest/pathdbtest.go, go/lib/sciond/BUILD.bazel, go/lib/sciond/types_test.go, go/lib/snet/BUILD.bazel, go/lib/snet/raw_test.go, go/lib/snet/router_test.go, go/lib/sock/reliable/reconnect/util_test.go, go/lib/svc/internal/proto/BUILD.bazel, go/lib/svc/internal/proto/proto_test.go, go/tools/scion-pki/internal/pkicmn/BUILD.bazel, go/tools/scion-pki/internal/pkicmn/pkicmn_test.go
Contributes #3016
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3158)
=> Remove more Convey

Makefile, tools/gomocks
This changes allows generating the mock files for specific packages.
Sample usage: `PKG_MATCHER=svc make mocks`
generates only packages that contain `svc` in the import path.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3150)
=> mock: Generate mocks for matched packages

go/lib/serrors/BUILD.bazel, go/lib/serrors/errors.go, go/lib/serrors/errors_test.go
This should in the long term replace:
-errors.New
-common.NewBasicError
The package is ready to be used with Go1.13 (or xerrors) Is and As.
Also it provides all the functionality that was provided by common.BasicError/common.MultiError.
By putting it in a serrors package we can make the API slightly nicer to use.
Contributes #3042
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3159)
=> serrors: Add serrors package

go/border/rpkt/BUILD.bazel, go/border/rpkt/l4.go, go/border/rpkt/parse.go, go/border/rpkt/path.go, go/border/rpkt/rpkt.go, go/lib/addr/BUILD.bazel, go/lib/addr/host.go, go/lib/infra/modules/db/BUILD.bazel, go/lib/infra/modules/db/errors.go, go/lib/infra/modules/db/errors_test.go, go/lib/infra/modules/db/metrics.go, go/lib/infra/modules/trust/BUILD.bazel, go/lib/infra/modules/trust/helpers.go, go/lib/infra/modules/trust/trust.go, go/lib/scrypto/cert/BUILD.bazel, go/lib/scrypto/cert/chain.go, go/lib/serrors/errors.go, go/lib/spath/BUILD.bazel, go/lib/spath/hop.go
Those checks are dangerous since a refactor could easily break them.
Using xerrors.Is instead is safer against refactors.
Contributes #3042
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3172)
=> Start removing GetErrMsg == "xx" tests

go/beacon_srv/internal/beacon/beacondbsqlite/db.go, go/beacon_srv/internal/beacon/beacondbtest/beacondbtest.go, go/beacon_srv/internal/beacon/db.go, go/beacon_srv/internal/beacon/metrics.go, go/beacon_srv/internal/beacon/mock_beacon/beacon.go
In order to expose in metrics the result `ok_new` or `ok_update` when we have received a beacon,
the insert function to the db must return back this information.
Contributes #3104
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3182)
=> bs: return stats when insert beacon in db

go/lib/infra/modules/idiscovery/BUILD.bazel, go/lib/infra/modules/idiscovery/idiscovery.go, go/lib/infra/modules/idiscovery/internal/metrics/BUILD.bazel, go/lib/infra/modules/idiscovery/internal/metrics/metrics.go, go/lib/infra/modules/itopo/BUILD.bazel, go/lib/infra/modules/itopo/cleaner.go, go/lib/infra/modules/itopo/internal/metrics/BUILD.bazel, go/lib/infra/modules/itopo/internal/metrics/metrics.go, go/lib/infra/modules/itopo/itopo.go
Metrics added for idiscovery:
```
idiscovery_file_writes_total{result="ok_success",type="static"} 1
idiscovery_sent_requests_total{result="err_request",type="dynamic"} 1
idiscovery_sent_requests_total{result="ok_success",type="dynamic"} 8
idiscovery_sent_requests_total{result="ok_success",type="static"} 1
```
Metrics added for itopo:
```
itopo_creation_time_seconds{type="static"} 0
itopo_creation_time_seconds{type="dynamic"} 1.5693351735612462e+09
itopo_dynamic_active 0
itopo_expiry_time_seconds{type="static"} +Inf
itopo_expiry_time_seconds{type="dynamic"} 1.5693351735612462e+09
itopo_last_updates{result="ok_success",type="dynamic"} 1.56933517356125e+09
itopo_last_updates{result="ok_success",type="static"} 1.5693351375621483e+09
itopo_updates_total{result="ok_success",type="dynamic"} 8 …
```
=> discovery: Add metrics for itopo and idiscovery

go/lib/infra/modules/itopo/cleaner.go, go/lib/infra/modules/itopo/itopo.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3189)
=> discovery: Call correct callback when cleaning dynamic

go/beacon_srv/internal/metrics/keepalive.go, go/beacon_srv/internal/metrics/revocation.go
We're standardising on sent+received in metric names.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3191)
=> Fix metric names for consistency

go/lib/infra/modules/trust/internal/metrics/metrics.go, go/lib/infra/modules/trust/trust.go, go/lib/scrypto/version.go
Fixes https://github.com/scionproto/scion/issues/3194
This also changes the logic for determining if the trust store is
authoritative or not for a given query. The rules are:
- A CS is authoritative for its own certs for its own AS.
- A core CS is authoritative for all AS certs in the local ISD.
- A core CS is authoritative for TRCs for the local ISD.
Also:
- Make logging/errors a bit more consistent/useful in getChain.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3197)
=> Fix circular lookup when AS cert not found.

README.md
Using `--recursive` and SSH no longer necessary when cloning because there are no more submodules.
Instruct to use https, because it's simpler -- no instructions about `.insteadOf` necessary.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3205)
=> README: https clone, not recursive

.buildkite/acceptance-pipeline.sh, acceptance/sig_short_exp_time_acceptance/test, go/lib/infra/modules/segfetcher/fetcher.go, go/lib/infra/modules/seghandler/result.go, go/lib/infra/modules/seghandler/seghandler.go, go/lib/infra/modules/seghandler/seghandler_test.go
With this PR, the next query is dependent on the verified segments.
The next query interval is at least minQueryInterval and at most
the configured query interval.
However, if only segments are found where the time until segment
expiration minus the `expirationLeadTime` (2 minutes) are found that are
less than the configured query interval, then that is chosen.
I.e. the query interval is:
````
maxExpirationDiff = max(seg.Exp().Add(-expirationLeadTime).Sub(now))
min(max(minQueryInterval, maxExpirationDiff), QueryInterval)
````
fixes #2979
Also, revert band-aid fix introduced by #3089
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3208)
=> Segfetcher: Make NextQuery dependent on segments 

acceptance/reconnecting_acceptance/test
The test implicitly checks that the link between as 1-ff00:0:112 and
1-ff00:0:110 is not broken.
It BS does not reconnect withing 3 seconds, the link is revoked.
Increase the sleep to 15 seconds to ensure the revocation has passed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3212)
=> acceptance: Increase reconnect wait time

go/lib/infra/modules/trust/v2/provider_test.go
The "TRC in database, outside graceperiod" test could fail when the
crypto material was generated less than a second before the test is run.
This change makes sure the test is no longer time dependent.
fixes #3214
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3216)
=> TrustStore: Fix flaky unit test

go/lib/snet/BUILD.bazel, go/lib/snet/mock_snet/snet.go, go/lib/snet/router.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3221)
=> Add AllRoutes function to snet.Router

go/lib/infra/messenger/addr_test.go, go/lib/snet/mock_snet/snet.go, go/lib/snet/router.go, go/lib/svc/resolver.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3224)
=> snet: Add Fingerprint and MTU to Path interface

go/lib/infra/modules/trust/v2/BUILD.bazel, go/lib/infra/modules/trust/v2/recurser.go, go/lib/infra/modules/trust/v2/recurser_test.go
Adds:
- Recurser that decides whether recursion is allowed for a given client.
- ASLocalRecurser allows all clients in the local AS.
- LocalOnlyRecurser allows only the local application.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3222)
=> TrustStore: Implement recurser

go/lib/util/duration_wrap.go, go/tools/scion-pki/internal/v2/conf/BUILD.bazel, go/tools/scion-pki/internal/v2/conf/key.go, go/tools/scion-pki/internal/v2/conf/key_test.go, go/tools/scion-pki/internal/v2/conf/testdata/BUILD.bazel, go/tools/scion-pki/internal/v2/conf/testdata/keys.go, go/tools/scion-pki/internal/v2/conf/testdata/keys.toml, go/tools/scion-pki/internal/v2/conf/validity.go, go/tools/scion-pki/internal/v2/tmpl/BUILD.bazel, go/tools/scion-pki/internal/v2/tmpl/cmd.go, go/tools/scion-pki/internal/v2/tmpl/keys.go, go/tools/scion-pki/internal/v2/tmpl/topo.go
Adds:
- support for key configuration parsing.
- key template generation from topo file
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3217)
=> SPKI: Add key configuration

go/lib/infra/modules/trust/v2/BUILD.bazel, go/lib/infra/modules/trust/v2/export_test.go, go/lib/infra/modules/trust/v2/inserter.go, go/lib/infra/modules/trust/v2/inserter_test.go, go/lib/infra/modules/trust/v2/router.go, go/lib/infra/modules/trust/v2/router_test.go
Adds:
- Implement TRC verification and insertion logic.
- The forwarding inserter registers the new trust material with the
local certificate server before inserting into the database.
It is supposed to be used by the beacon and path server.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3225)
=> TrustStore: Implement inserter

go/lib/keyconf/key.go, go/lib/keyconf/key_test.go, go/tools/scion-pki/internal/pkicmn/pkicmn.go, go/tools/scion-pki/internal/v2/conf/key.go, go/tools/scion-pki/internal/v2/conf/validity.go, go/tools/scion-pki/internal/v2/keys/BUILD.bazel, go/tools/scion-pki/internal/v2/keys/priv.go, go/tools/scion-pki/internal/v2/keys/priv_test.go, go/tools/scion-pki/internal/v2/keys/util.go, go/tools/scion-pki/internal/v2/tmpl/topo.go
Adds:
- support to generate private keys form keys.toml
`runGenKey` is not replaced currently, because it is in use by the
trust/v2 tests. It will be replaced as soon as TRC and certificate
signing with the new key format is available.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3218)
=> SPKI: Generate private keys

go/lib/infra/messenger/addr_test.go, go/lib/snet/mock_snet/snet.go, go/lib/snet/router.go, go/lib/svc/resolver.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3229)
=> Add ExpTime() to Path interface

go/integration/cert_req/main.go, go/lib/hostinfo/hostinfo.go, go/lib/sciond/types.go, go/sciond/internal/servers/handlers.go, go/sig/mgmt/addr.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3233)
=> Clean up host type in SCIOND-API RPC messages

go/lib/infra/modules/segfetcher/fetcher.go, go/lib/infra/modules/segfetcher/request.go, go/lib/infra/modules/segfetcher/requester.go, go/lib/infra/modules/segfetcher/requester_test.go, go/lib/infra/modules/segfetcher/resolver.go, go/lib/infra/modules/segfetcher/resolver_test.go, go/path_srv/internal/handlers/segrevoc.go, go/sciond/internal/servers/handlers.go
Instead of deleting next query entries when receiving revocation, be smarter when querying:
That means if a query returns no result after being filtered with revocations, try to refetch, otherwise return cached result to clients.
Fixes #3234 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3235)
=> segfetcher: Keep next query entries when receiving revocations

go/lib/addr/isdas.go, go/lib/prom/prom.go, go/lib/prom/promtest/promtest.go, go/path_srv/internal/metrics/BUILD.bazel, go/path_srv/internal/metrics/metrics.go, go/path_srv/internal/metrics/requests.go, go/path_srv/internal/metrics/requests_test.go, go/path_srv/internal/segreq/BUILD.bazel, go/path_srv/internal/segreq/handler.go
Adds metrics:
```
ps_requests_replied_revocations_total{cache_only="false",dst_isd="1",seg_type="down"} 0
ps_requests_replied_segments_total{cache_only="false",dst_isd="1",seg_type="down"} 4
ps_requests_total{cache_only="false",dst_isd="1",result="ok_success",seg_type="down"} 4
```
Contributes #3106
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3232)
=> PS: Expose request metrics

Makefile
We no longer have a `c` directory so the `tags` target is no longer needed.
Fixes #3248
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3249)
=> Remove tags make target

go/lib/infra/messenger/BUILD.bazel, go/lib/infra/messenger/addr_test.go, go/lib/snet/mock_snet/BUILD.bazel, go/lib/snet/mock_snet/snet.go, go/lib/snet/router.go, go/lib/svc/BUILD.bazel, go/lib/svc/resolver.go
This allows to retreive the list of AS/IFID pairs from a path.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3252)
=> snet: Add Interfaces() to Path interface

go/sciond/internal/fetcher/fetcher.go
Fixes #3246
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3250)
=> SD: returns ErrNoPaths if no paths were found

go/sciond/internal/metrics/BUILD.bazel, go/sciond/internal/metrics/metrics.go, go/sciond/internal/metrics/metrics_test.go, go/sciond/internal/servers/BUILD.bazel, go/sciond/internal/servers/handlers.go
Adds metrics:
```
sd_path_request_duration_seconds_bucket{result="ok_success",le="0.01"} 1
sd_path_request_duration_seconds_bucket{result="ok_success",le="0.02"} 6
sd_path_request_duration_seconds_bucket{result="ok_success",le="0.04"} 11
sd_path_request_duration_seconds_bucket{result="ok_success",le="0.08"} 15
sd_path_request_duration_seconds_bucket{result="ok_success",le="0.16"} 16
sd_path_request_duration_seconds_bucket{result="ok_success",le="0.32"} 17
sd_path_request_duration_seconds_bucket{result="ok_success",le="0.64"} 17
sd_path_request_duration_seconds_bucket{result="ok_success",le="1.28"} 18
sd_path_request_duration_seconds_bucket{result="ok_success",le="2.56"} 20
sd_path_request_duration_seconds_bucket{result="ok_success",le="5.12"} 21 …
```
=> SD: Add request metrics

go/lib/addr/host.go, go/lib/prom/prom.go, go/lib/sock/reliable/BUILD.bazel, go/lib/sock/reliable/internal/metrics/BUILD.bazel, go/lib/sock/reliable/internal/metrics/metrics.go, go/lib/sock/reliable/internal/metrics/metrics_test.go, go/lib/sock/reliable/reconnect/BUILD.bazel, go/lib/sock/reliable/reconnect/conn.go, go/lib/sock/reliable/reconnect/conn_io_test.go, go/lib/sock/reliable/reconnect/errors.go, go/lib/sock/reliable/reconnect/internal/metrics/BUILD.bazel, go/lib/sock/reliable/reconnect/internal/metrics/metrics.go, go/lib/sock/reliable/reconnect/network.go, go/lib/sock/reliable/reconnect/reconnecter.go, go/lib/sock/reliable/reconnect/reconnecter_test.go, go/lib/sock/reliable/reliable.go
Metrics:
```
lib_reliable_dials_total{result="err_not_classified"} 1
lib_reliable_dials_total{result="ok_success"} 3
lib_reliable_registers_total{result="ok_success",svc="CS"} 1
lib_reliable_registers_total{result="ok_success",svc="UNKNOWN"} 3
lib_reliable_reads_total_bucket{result="err_not_classified",le="1"} 2
lib_reliable_reads_total_bucket{result="err_not_classified",le="+Inf"} 2
lib_reliable_reads_total_sum{result="err_not_classified"} 0
lib_reliable_reads_total_count{result="err_not_classified"} 2
lib_reliable_reads_total_bucket{result="ok_success",le="1"} 0
lib_reliable_reads_total_bucket{result="ok_success",le="+Inf"} 422
lib_reliable_reads_total_sum{result="ok_success"} 148709
lib_reliable_reads_total_count{result="ok_success"} 422 …
```
=> Add metrics to reliable socket and reconnecting libs

go/lib/prom/prom.go, go/path_srv/internal/handlers/segreg.go, go/path_srv/internal/handlers/segsync.go, go/path_srv/internal/metrics/BUILD.bazel, go/path_srv/internal/metrics/metrics.go, go/path_srv/internal/metrics/registration.go, go/path_srv/internal/metrics/sync.go, go/path_srv/internal/metrics/sync_test.go, go/path_srv/internal/segreq/handler.go, go/path_srv/internal/segsyncer/BUILD.bazel, go/path_srv/internal/segsyncer/segsyncer.go, go/sciond/internal/metrics/metrics.go
Adds metrics:
```
ps_segment_sync_pushes_total{dst="1-ff00:0:120",result="err_nopath"} 5
ps_segment_sync_pushes_total{dst="1-ff00:0:120",result="ok_success"} 139
ps_segment_sync_pushes_total{dst="1-ff00:0:130",result="err_nopath"} 1
ps_segment_sync_pushes_total{dst="1-ff00:0:130",result="ok_success"} 143
ps_segment_sync_registrations_total{result="ok_new",src="1-ff00:0:120"} 4
ps_segment_sync_registrations_total{result="ok_new",src="1-ff00:0:130"} 6
ps_segment_sync_registrations_total{result="ok_updated",src="1-ff00:0:120"} 93
ps_segment_sync_registrations_total{result="ok_updated",src="1-ff00:0:130"} 142
```
Contributes #3106
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/sci …
=> PS: Add segsyncer metrics

go/lib/sciond/BUILD.bazel, go/lib/sciond/internal/metrics/BUILD.bazel, go/lib/sciond/internal/metrics/metrics.go, go/lib/sciond/sciond.go
Added metrics:
```
attempts.
lib_sciond_conn_connections_total{result="ok_success"} 5
lib_sciond_path_request_total{result="ok_success"} 4
```
Metrics for the other client API calls are also included.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3254)
=> Add metrics for SCIOND client API

go/lib/snet/BUILD.bazel, go/lib/snet/dispatcher.go, go/lib/snet/internal/metrics/BUILD.bazel, go/lib/snet/internal/metrics/metrics.go, go/lib/snet/packet_conn.go, go/lib/snet/snet.go
Fixes https://github.com/scionproto/scion/issues/3107
Adds the following metrics:
```
lib_snet_closes_total 0
lib_snet_dials_total 0
lib_snet_dispatcher_error_total 0
lib_snet_listens_total 2
lib_snet_parse_error_total 0
lib_snet_read_total_bytes 1.163921e+06
lib_snet_read_total_pkts 3105
lib_snet_scmp_error_total 0
lib_snet_write_total_bytes 579712
lib_snet_write_total_pkts 3037
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3257)
=> Add metrics to snet

doc/BeaconService.md, doc/ControlPlanePKI.md, doc/DRKeyInfra.md, doc/Environments.md, doc/PathReversal.md, doc/PathService.md, doc/RevocationAuthentication.md, go/beacon_srv/main.go
Multiple typos and minor text improvements in `doc/*` and `go/beacon_srv/main.go`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3261)
=> Fix typos and increase consistency of docs

go/lib/infra/modules/segfetcher/fetcher.go, go/lib/prom/prom.go, go/path_srv/internal/handlers/segrevoc.go, go/path_srv/internal/metrics/BUILD.bazel, go/path_srv/internal/metrics/metrics.go, go/path_srv/internal/metrics/revocation.go, go/path_srv/internal/metrics/revocation_test.go, go/sciond/internal/metrics/metrics.go
Adds the following metrics:
```
ps_revocations_received_total{result="ok_success",src="notification"} 11
```
Contributes #3106
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3262)
=> PS: Add metrics for revocation notifications

README.md
Fixes a wrong URL format for checking out scionproto/scion via git.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3266)
=> Fix wrong git checkout path in README

python/topology/config.py
path_policy.yml and as.yml are not used by Go services so don't generate them when we use Go only.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3280)
=> topogen: Don't generate unused config files for Go

acceptance/sig_failover_acceptance/Test.topo, acceptance/topo_br_reload_util/Tinier.topo, python/topology/config.py, python/topology/topo.py, topology/Default.topo, topology/Tiny.topo, topology/Wide.topo
For pure golang topologies we don't require zookeeper anymore,
so we should also not require zookeeper to be specified in the topo file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3278)
=> Make specifying zookeeper in topo files optional

go/lib/infra/modules/segfetcher/BUILD.bazel, go/lib/infra/modules/segfetcher/fetcher.go, go/lib/infra/modules/segfetcher/internal/metrics/BUILD.bazel, go/lib/infra/modules/segfetcher/internal/metrics/fetcher.go, go/lib/infra/modules/segfetcher/internal/metrics/fetcher_test.go, go/lib/infra/modules/segfetcher/internal/metrics/metrics.go, go/lib/infra/modules/seghandler/BUILD.bazel, go/lib/infra/modules/seghandler/result.go, go/lib/infra/modules/seghandler/seghandler.go, go/path_srv/internal/metrics/revocation.go, go/path_srv/internal/segreq/handler.go, go/proto/structs.gen.go, go/sciond/internal/fetcher/BUILD.bazel, go/sciond/internal/fetcher/fetcher.go, go/sciond/internal/metrics/metrics.go
Add metrics for received revocations and sent segment requests.
Also changes the naming of SD and PS revocation metrics to match.
```
ps_fetcher_seg_requests_total{result="ok_success"} 1
ps_received_revocations_total{result="err_db",src="path_reply"} 0
ps_received_revocations_total{result="err_verify",src="path_reply"} 0
ps_received_revocations_total{result="ok_success",src="notification"} 1
ps_received_revocations_total{result="ok_success",src="path_reply"} 0
```
Contributes #3106
Fixes #3255
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3264)
=> segfetcher: Add segreq & revocation metrics

acceptance/brutil/common.sh
Currently, braccept needs capabilities that are set during acceptance
test setup. Thus everytime time we do make, we get a new binary that
needs capabilities.
This change moves setting the capabilities to the acceptance test run,
allowing to rebuild braccept without having to teardown->setup the
acceptance test every time.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3284)
=> br: acceptance setcap on test run

go/lib/topology/topology.go, go/lib/topology/topology_test.go
This makes it easier to see what functionality is still required.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3277)
=> topology: Reduce exposed types, remove unused code

go/lib/sciond/pathprobe/paths.go, go/lib/snet/conn.go, go/lib/snet/interface.go, go/lib/snet/snet.go
So far we forgot to set the deadline on the connection therefore the timeout was ignored, setting it fixes that.
Also slightly improve snet documentation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3291)
=> showpaths: respect timeout arg

go/lib/snet/dispatcher.go, go/lib/snet/snet.go
The previous argument type was a path resolver, but most of the
interface was not needed. The new smaller interface simplifies
simplifies mocking and improves clarity.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3305)
=> Minimized interface argument needed to create default SCMP handler

go/lib/periodic/periodic_test.go
There is a flake in periodic tests. In this commit
we put the close(done) in the defer so we make sure
always is executed (in case there is a return earlier).
Also we guard with a timeout wrapper all functions that
can be blocked.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3309)
=> periodic: add timeout to all function calls in the tests

go/lib/infra/messenger/messenger.go, go/lib/infra/modules/segfetcher/fetcher.go, go/lib/infra/modules/segfetcher/request.go, go/lib/infra/modules/segfetcher/resolver.go, go/lib/infra/modules/segfetcher/resolver_test.go, go/lib/infra/rpc/rpc.go, go/sciond/internal/servers/handlers.go
If we have an error we should not simply ignore it and continue processing.
Instead the fetcher now returns the error immediately.
Also
* do not continue resolving&fetching when 0 up/down segments are cached
* log sciond error code in debug
* remove duplicated log about convergence problem
* improve returned error when a timeout occurs in QUIC
Fixes #2721
Fixes #3293
Fixes #3294
Fixes #3094
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3306)
=> segfetcher: Stop fetch loop on errors

go/lib/infra/modules/trust/v2/inserter_test.go, go/lib/infra/modules/trust/v2/inspector_test.go, go/lib/infra/modules/trust/v2/provider_test.go, go/lib/infra/modules/trust/v2/recurser_test.go, go/lib/infra/modules/trust/v2/resolver_test.go, go/lib/infra/modules/trust/v2/router_test.go, go/lib/infra/modules/trust/v2/testdata/gen_crypto_tar.sh
The unit tests rely on generated trust material. The scion-pki tool
that generates the material is currently under rework and having tests
that require full operability is time consuming during the rewrite.
This change temporarily disables the unit tests to allow faster rework.
Tracking issue  #3317
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3311)
=> TrustStore: Disable unit tests

python/topology/common.py, python/topology/docker.py, python/topology/go.py
This commit changes the topology generator to create a BR dispatcher per BR.
This is required since otherwise non -1 BR will not receive control plane traffic.
Fixes #3318
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3321)
=> topo-gen: Create BR dispatcher per BR

go/lib/healthpool/BUILD.bazel, go/lib/healthpool/pool.go, go/lib/healthpool/pool_test.go
The TestPoolExpiresFails test no longer is flaky.
Additionally, remove goconvey.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3307)
=> healthpool: fix flaky test

.bazelrc, .gitignore
https://docs.bazel.build/versions/master/remote-caching.html#disk-cache
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3336)
=> Use bazel disk cache

go/lib/snet/BUILD.bazel, go/lib/snet/addr_test.go, go/lib/snet/internal/ctxmonitor/BUILD.bazel, go/lib/snet/internal/ctxmonitor/ctxmonitor_test.go, go/lib/snet/writer_test.go
Contributes #3016
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3350)
=> snet: remove goconvey

WORKSPACE, go/lib/overlay/conn/BUILD.bazel, nogo.json
This patch works around some issues in rules_go/nogo from v0.19.0+
where it fails to exclude paths appropiately for packages that use cgo.
See issue below:
https://github.com/bazelbuild/rules_go/issues/2172
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3325)
=> update gazelle and rules_go

go/tools/scion-pki/internal/v2/tmpl/BUILD.bazel, go/tools/scion-pki/internal/v2/tmpl/topo.go, go/tools/scion-pki/internal/v2/tmpl/topo_test.go
This PR adds the capability to generate issuer and AS certificate
config files for a given topology description.
Additionally, adds missing tests for generated keys.toml.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3363)
=> SPKI: Generate issuer and AS config for topo

go/beacon_srv/internal/onehop/sender_test.go, go/border/BUILD.bazel, go/border/io_test.go, go/border/rpkt/route.go, go/godispatcher/main_test.go, go/godispatcher/network/app_socket.go, go/godispatcher/network/dispatcher.go, go/integration/end2end/main.go, go/lib/hostinfo/hostinfo.go, go/lib/infra/messenger/addr_test.go, go/lib/overlay/BUILD.bazel, go/lib/overlay/addr.go, go/lib/overlay/conn/BUILD.bazel, go/lib/overlay/conn/conn.go, go/lib/snet/router.go, go/lib/snet/router_test.go, go/lib/snet/snet.go, go/lib/snet/writer.go, go/lib/sock/reliable/reconnect/main_test.go, go/lib/sock/reliable/reliable.go, go/lib/svc/svc_test.go, go/lib/topology/addr.go, go/lib/topology/addr_test.go, go/lib/topology/braddr.go, go/lib/topology/raw.go, go/lib/topology/topology_test.go, go/tools/scmp/cmn/common.go, go/tools/scmp/main.go
We currently do not support any other overlay L3. Also, the overlay
connection objects always expect IP addresses. This makes the
net.IP address requirement explicit in the overlay address constructor.
Also, the constructor can no longer error out.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3332)
=> Refactor overlay addresses to always use net.IP

go/lib/infra/modules/trust/v2/inserter_test.go, go/lib/infra/modules/trust/v2/inspector_test.go, go/lib/infra/modules/trust/v2/provider_test.go, go/lib/infra/modules/trust/v2/recurser_test.go, go/lib/infra/modules/trust/v2/resolver_test.go, go/lib/infra/modules/trust/v2/router_test.go, go/lib/infra/modules/trust/v2/testdata/gen_crypto_tar.sh, go/tools/scion-pki/internal/v2/trcs/BUILD.bazel, go/tools/scion-pki/internal/v2/trcs/cmd.go, go/tools/scion-pki/internal/v2/trcs/gen.go, go/tools/scion-pki/internal/v2/trcs/gen_test.go, go/tools/scion-pki/internal/v2/trcs/loader_test.go, go/tools/scion-pki/internal/v2/trcs/prototype_test.go
This change adds the ability to prototype, sign and combine a TRC
with a single command. The only the final signed TRC is stored on the
file system.
This PR also re-enables the trust store unit tests.
fixes #3317
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3371)
=> SPKI: Prototype, sign and combine in one command

go/lib/infra/infraenv/infraenv.go, go/lib/sciond/BUILD.bazel, go/lib/sciond/sciond.go, go/lib/snet/snet.go, go/tools/scmp/main.go, go/tools/showpaths/paths.go
Instead of having one with timeout and one without just have one method with context.
Also remove the request ID counter, it's no longer needed since we do single-shot connections anyway.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3374)
=> sciond-API: Only have a single Connect method

.bazelrc
This fixes the problem introduced by new version of go_rules,
the symptom being that StartupVersion was not set properly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3380)
=> Bazel: Use --stamp command line flag

go/godispatcher/internal/registration/iatable_test.go, go/godispatcher/internal/registration/table_test.go
Contributes #3016
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3358)
=> godispatcher: remove convey

go/examples/pingpong/pingpong.go, go/integration/cert_req/main.go, go/integration/common.go, go/integration/end2end/main.go, go/lib/snet/conn.go, go/lib/snet/snet.go, go/lib/snet/squic/squic.go, go/sig/egress/session/session.go, go/sig/ingress/dispatcher.go, go/sig/sigcmn/common.go
Do not use snet global state
* Changes the code of {pingpong, integration, sig} to not use the
global state of snet pkg
*Remove code around global state in snet pkg
Fixes #3135
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3366)
=> Do not use snet global state

go/lib/hostinfo/hostinfo.go, go/sig/egress/session/sessmon.go, go/sig/internal/base/pollhdlr.go, go/sig/mgmt/BUILD.bazel, go/sig/mgmt/addr.go
We can't use UDPAddr on the wire format, instead use hostinfo again.
Fixes tests broken by  #3370
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3386)
=> Fix sig/mgmt/Addr

go/lib/pathmgr/pathmgr.go, go/lib/snet/snet.go, go/sig/sigcmn/BUILD.bazel, go/sig/sigcmn/common.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3387)
=> Change default normalRefire duration in pathmgr

go/lib/infra/messenger/BUILD.bazel, go/lib/infra/messenger/addr_test.go, go/lib/pathmgr/pathmgr_test.go, go/lib/pathpol/hop_pred.go, go/lib/pathpol/pathset.go, go/lib/pathpol/policy_test.go, go/lib/pathpol/sequence.go, go/lib/sciond/mock_sciond/sciond.go, go/lib/sciond/types.go, go/lib/snet/BUILD.bazel, go/lib/snet/mock_snet/BUILD.bazel, go/lib/snet/mock_snet/snet.go, go/lib/snet/path.go, go/lib/snet/router.go, go/lib/svc/BUILD.bazel, go/lib/svc/resolver.go, go/path_srv/internal/segutil/filter.go, go/sciond/internal/fetcher/filter.go
The PathInterface is required to loosen the dependency on sciond.
Contributes #3348
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3384)
=> snet: Split paths to own file, add PathInterface

.buildkite/scripts/build_scion_img, WORKSPACE
This also upgrades the GoConvey dependency as it is required for Go 1.13.
Fixes #3349
Fixes #3009
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3362)
=> Upgrade to Go 1.13

go/beacon_srv/internal/beaconing/originator_test.go, go/beacon_srv/internal/beaconing/propagator_test.go, go/beacon_srv/internal/keepalive/BUILD.bazel, go/beacon_srv/internal/keepalive/sender_test.go, go/beacon_srv/internal/onehop/sender.go, go/beacon_srv/internal/onehop/sender_test.go, go/beacon_srv/main.go, go/examples/discovery_client/BUILD.bazel, go/examples/discovery_client/client.go, go/lib/discovery/BUILD.bazel, go/lib/discovery/common.go, go/lib/discovery/discovery.go, go/lib/discovery/discoveryinfo/BUILD.bazel, go/lib/discovery/discoveryinfo/info.go, go/lib/discovery/discoveryinfo/info_test.go, go/lib/discovery/discoverypool/pool.go, go/lib/discovery/discoverypool/pool_test.go
Contributes #3344
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3375)
=> BS, DISP: Use net.UDPAddr instead of addr.AppAddr

go/sig/egress/session/sessmon.go, go/sig/internal/disp/disp.go, go/sig/main.go
Control message dispatcher can now be run in two different
modes: Either is dispatches the packets based on IA+session,
or based on IA+session+msgID.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3403)
=> SIG: Allow using message ID for control message dispatching

WORKSPACE
Recently we saw SIG acceptance tests fail more often that usual.
Since the Go1.13 change (#3362) we saw in some SIGs problems with the TUN device.
Investigating further we came across https://github.com/golang/go/issues/30624.
From there we saw that water library is very old and still uses os.OpenFile,
which was replaced in other similar libs to mitigate afformentioned Go issue.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3406)
=> Upgrade water dependency

acceptance/sigutil/common.sh, go/sig/egress/api.go
1. Sleep a while after config reload to make sure that the new config
is already being used.
2. A log record after the config is reloaded.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3418)
=> SIG: Some improvements to acceptance tests

go/lib/infra/messenger/BUILD.bazel, go/lib/infra/messenger/addr_test.go, go/lib/infra/messenger/export_test.go
As part of the remote `add.AppAddr` effort.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3420)
=> messenger: use addr.AppAddr less in tests

go/beacon_srv/internal/beaconing/registrar.go
"No beacons propagated" should be "No beacons registered" in the registrar.
Fixes #3388
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3426)
=> BS: Fix error message in registrar

go/beacon_srv/main.go, go/cert_srv/setup.go, go/lib/infra/infraenv/infraenv.go, go/lib/infra/messenger/addr.go, go/lib/infra/messenger/addr_test.go, go/lib/infra/modules/itopo/topology.go, go/lib/sciond/mock_sciond/BUILD.bazel, go/lib/sciond/mock_sciond/sciond.go, go/lib/snet/addr.go, go/lib/snet/dispatcher.go, go/path_srv/main.go, go/sciond/main.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3423)
=> invraenv: use net.UDPAddr for public/bind addr

go.mod, go.sum, go_deps.bzl
This was already done by #3406 but then got reverted by the go.mod change (#3419)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3430)
=> Upgrade water dependency again

docker/perapp/scion_app.bzl
We still need package_bundle_debian10 because distroless base loads this unconditionally.
(see https://github.com/GoogleContainerTools/distroless/blob/b54513ef989c81d68cb27d9c7958697e2fedd2c4/base/base.bzl#L5)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3436)
=> Use debian 9 packages for perapp containers

go/lib/infra/modules/segfetcher/fetcher.go, go/lib/infra/modules/segfetcher/request.go, go/lib/infra/modules/segfetcher/resolver.go, go/lib/infra/modules/segfetcher/resolver_test.go, go/sciond/internal/fetcher/BUILD.bazel, go/sciond/internal/fetcher/fetcher.go, go/sciond/internal/fetcher/splitter.go, go/sciond/internal/fetcher/splitter_test.go
Instead of deleting next query entries, just always request at the PS.
This can prevent a weird interaction between concurrent requests, which would lead to 0 cached paths.
Marked as breaking because the behavior changes, i.e., sciond no longer deletes anything in the DB on the refresh flag.
Fixes #2871
Fixes #3416
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3434)
=> sciond: Change refresh mechanism to be safer

go/lib/infra/modules/segfetcher/fetcher.go, go/lib/infra/modules/segfetcher/resolver.go, go/lib/infra/modules/segfetcher/resolver_test.go, go/path_srv/internal/segreq/handler.go, go/sciond/internal/fetcher/fetcher.go
This is to make sure that we never try to fetch segments that are locally cached.
This happened some times in the past.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3437)
=> segfetcher: Add LocalInfo to resolver

go/lib/scrypto/asym.go
Remove the verification input msg from the error context.
It unnecessarily pollutes the error message.
If calling code cares about logging it, it should attach.
Additionally, translate common.BasicError to serrors.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3382)
=> scrypto: Remove msg from Verify log context

go/border/io.go
When forwarding an incoming packet, ENETUNREACH can be caused by trying
to send the packet to a different address family than what the socket is
listening on (e.g. IPv6 destination address, but border routers internal
address is configured to use IPv4).
As the destination address is controlled by an end host outside the AS,
the router should not abort in this case.
Similiarly, EHOSTUNREACH can be caused by a bad destination address;
from the manual:
> No valid routing table entry matches the destination address.  This error can be caused by an ICMP message from a remote router or for the local routing table.
So this error can be caused by any of:
- a misconfiguration of IP routes on the border router
- specific configuration on the border router to ensure packets are only
forwarded to the …
=> Ignore ENETUNREACH, EHOSTUNREACH in border io

go/sciond/internal/config/BUILD.bazel, go/sciond/internal/config/config.go, go/sciond/internal/config/config_test.go, go/sciond/internal/config/sample.go, go/sciond/main.go, python/topology/go.py
sciond config needs only the listening IP address.
The IA is being taken from topo `itopo.Get().IA()`
This commit introduces a breaking change in the sciond config.
The public now should be of `<ip>:<port>`, not `ia,<ip>:port`
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3444)
=> sciond: do not use snet.Addr in config

go/lib/infra/rpc/rpc.go
When dialing a QUIC connection, a UDP address is turned into a string which is then again parsed by the QUIC library.
When passing an IPv6 address, the host part of address must be enclosed in brackets, otherwise the parsing  will fail with 'too many colons in address'.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3452)
=> Fix address string for IPv6 for QUIC Infra RPC

go/godispatcher/internal/registration/udptable.go, go/godispatcher/internal/registration/udptable_test.go
The godispatcher uses two separate port tables for IPv4 and IPv6
addresses. While the lookup has selected the applicable table based on
the address type, the registration was always using the table for IPv4.
Also enhance the tests for UDPTable to check that a lookup actually
succeeds after a registration.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3451)
=> Fix IPv6 registrations in godispatcher

go/lib/infra/modules/trust/v2/main_test.go, go/lib/infra/modules/trust/v2/resolver.go, go/lib/infra/modules/trust/v2/resolver_test.go, go/lib/infra/modules/trust/v2/testdata/gen_crypto_tar.sh
Check that the reply for a TRC rpc contains a TRC with the correct
ISD and version.
Additionally, refactor the test to use actual TRC updates instead of
fake ones.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3456)
=> TrustStore: Sanity check resolved TRCs

go/tools/scion-pki/internal/v2/certs/BUILD.bazel, go/tools/scion-pki/internal/v2/certs/cmd.go, go/tools/scion-pki/internal/v2/certs/human.go, go/tools/scion-pki/internal/v2/certs/util.go
Add support for displaying issuer certificates and certificate chains
in a human readable format.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3454)
=> SPKI: Display certs in a human readable format

go/lib/infra/modules/trust/handlers.go, go/lib/infra/modules/trust/trust.go, go/lib/infra/modules/trust/v2/recurser.go, go/lib/infra/modules/trust/v2/recurser_test.go, go/lib/infra/modules/trust/v2/router.go, go/lib/infra/modules/trust/v2/router_test.go, go/lib/snet/addr.go
which replaces the snet.Addr
Contributes: #3344
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3464)
=> trust: start using snet.UDPAddr

go/lib/infra/modules/trust/v2/testdata/gen_crypto_tar.sh, go/tools/scion-pki/internal/v2/certs/BUILD.bazel, go/tools/scion-pki/internal/v2/certs/loader.go
This change adds certificate generation for tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3493)
=> TrustStore: Generate certificates for tests

acceptance/sig_reload_acceptance/test, acceptance/sigutil/common.sh, go/acceptance/sig_ping_acceptance/main.go
This change reduces the logging interval to one second.
Before, the interval was 5 seconds with a sleep of 3 seconds when
checking the logs for some lines. This leads to a lot of unnecessary
flakiness.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3502)
=> Acceptance: Fix sig reload test

go/lib/infra/common.go, go/lib/infra/modules/trust/v2/BUILD.bazel, go/lib/infra/modules/trust/v2/export_test.go, go/lib/infra/modules/trust/v2/handlers.go, go/lib/infra/modules/trust/v2/handlers_test.go
Add certificate chain push handler to the trust store.
Currently, unit tests are missing.
fixes #3486
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3501)
=> TrustStore: Add chain push handler

go/lib/infra/modules/trust/v2/export_test.go, go/lib/infra/modules/trust/v2/handlers.go, go/lib/infra/modules/trust/v2/handlers_test.go
Add TRC push handler to the trust store.
~Currently, the PR is missing unit tests.~ Edit by @scrye: added unit tests
fixes #3483
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3498)
=> TrustStore: Add TRC push handler

go/lib/infra/modules/trust/v2/main_test.go, go/lib/infra/modules/trust/v2/resolver.go, go/lib/infra/modules/trust/v2/resolver_test.go
This PR adds the capability to resolve certificate chains to the
resolver.
fixes #3469
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3495)
=> TrustStore: Resolver handles certificate chains

go/beacon_srv/internal/ifstate/pusher_test.go, go/beacon_srv/internal/ifstate/revoker.go, go/beacon_srv/internal/ifstate/revoker_test.go, go/beacon_srv/main.go, go/border/rctrl/ctrl.go, go/lib/discovery/discoverypool/BUILD.bazel, go/lib/discovery/discoverypool/pool.go, go/lib/discovery/discoverypool/pool_test.go, go/lib/healthpool/svcinstance/BUILD.bazel, go/lib/healthpool/svcinstance/info.go, go/lib/healthpool/svcinstance/pool_test.go, go/lib/integration/integration.go, go/lib/topology/interface.go, go/lib/topology/mock_topology/topology.go, go/lib/topology/raw.go, go/lib/topology/topology.go, go/lib/topology/topology_test.go
Inside topology, the TopoAddr struct changed
```
TopoAddr struct {
SCIONAddress    *addr.AppAddr	-->  *net.UDPAddr
UnderlayAddress net.Addr		
}
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3507)
=> topology: replace SCIONAddress to net.UDPAddr os

go/lib/infra/modules/trust/v2/export_test.go, go/lib/infra/modules/trust/v2/handlers.go, go/lib/infra/modules/trust/v2/handlers_test.go
Add certificate chain request handler.
fixes #3485
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3500)
=> TrustStore: Add chain request handler

.bazelrc_ci, .buildkite/hooks/pre-artifact, .buildkite/hooks/pre-command, .buildkite/pipeline.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3505)
=> CI: Initial new pipeline

go/lib/infra/modules/trust/v2/export_test.go, go/lib/infra/modules/trust/v2/handlers.go, go/lib/infra/modules/trust/v2/provider.go, go/lib/infra/modules/trust/v2/provider_test.go, go/lib/infra/modules/trust/v2/resolver.go, go/lib/infra/modules/trust/v2/rpc.go
fixes #3508
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3510)
=> TrustStore: Purge CacheOnly flag from network requests

go/lib/infra/common.go, go/lib/infra/modules/trust/handlers.go, go/lib/infra/modules/trust/v2/handlers.go, go/lib/infra/modules/trust/v2/handlers_test.go, go/lib/infra/modules/trust/v2/provider.go, go/lib/infra/modules/trust/v2/provider_test.go
This PR adds support for certificate chains to the CryptoProvider in the
trust store.
fixes #3470
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3496)
=> TrustStore: Provider handles certificate chains

go/lib/sock/reliable/registration.go
Make sure that an IPv4 is always 4 bytes long otherwise the parsing will fail.
Creating an IP from string via net.ParseIP/net.ResolveUDPAddr creates an IPv4 with a byte slice of length 16.
This was a problem for example for sciond.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3512)
=> dispatcher: Fix registration with length 16 IPv4 addresses 

go/lib/sciond/apitypes.go, go/lib/sciond/mock_sciond/BUILD.bazel, go/lib/sciond/mock_sciond/sciond.go, go/lib/sciond/sciond.go, go/lib/sciond/types.go
Add `IFInfo` function back to sciond connector interface, with updated type, so that a map containing the addresses is returned instead of the raw IFInfoReply type.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3514)
=> sciond-lib: Add IFInfo function back to connector interface

go/lib/sciond/apitypes.go
A sciond.Path with a nil-overlay could not be printed.
Fixed by using UDPAddr.String instead of manually formatting IP:port.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3519)
=> Fix nil-pointer dereference in sciond.Path.String

go/border/rctrl/ctrl.go, go/examples/pingpong/BUILD.bazel, go/examples/pingpong/pingpong.go, go/integration/cert_req/main.go, go/lib/infra/infraenv/infraenv.go, go/lib/sciond/pathprobe/paths.go, go/lib/snet/base.go, go/lib/snet/export_test.go, go/lib/snet/interface.go, go/lib/snet/snet.go, go/lib/snet/squic/squic.go, go/lib/snet/writer.go, go/lib/snet/writer_test.go, go/sig/egress/session/session.go, go/sig/internal/ingress/dispatcher.go, go/sig/sigcmn/common.go
- Remove bind
- Use a single method Listen / Dial
- Use {s}net.UDPAddr as arguments
- Improve naming of arguments
Contributes #3136
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3521)
=> snet: refactor Listens and Dials (#1694)

go/lib/infra/modules/trust/v2/rpc.go
Fixes #3523
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3527)
=> TrustStore: implement RPC interface

go/border/rctrl/ctrl.go, go/integration/cert_req/main.go, go/lib/infra/infraenv/infraenv.go, go/lib/sciond/pathprobe/paths.go, go/lib/snet/base.go, go/lib/snet/reader.go, go/lib/snet/snet.go, go/lib/snet/squic/squic.go, go/sig/egress/session/session.go, go/sig/internal/ingress/dispatcher.go, go/sig/sigcmn/common.go
Explicitly allow Dial/Listen using IPv6 addresses, by removing the fixed `"udp4"` network string. The actual address type checks have already been removed very recently in #3521.
Pass "udp" as network in all Dial/Listen calls.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3522)
=> snet: Allow dial/listen using IPv6 addresses

go/lib/infra/common.go, go/lib/infra/modules/trust/v2/db.go, go/lib/infra/modules/trust/v2/handlers.go, go/lib/infra/modules/trust/v2/handlers_test.go, go/lib/infra/modules/trust/v2/inserter.go, go/lib/infra/modules/trust/v2/inserter_test.go, go/lib/infra/modules/trust/v2/inspector.go, go/lib/infra/modules/trust/v2/inspector_test.go, go/lib/infra/modules/trust/v2/mock_v2/v2.go, go/lib/infra/modules/trust/v2/provider.go, go/lib/infra/modules/trust/v2/provider_test.go, go/lib/infra/modules/trust/v2/resolver.go, go/lib/infra/modules/trust/v2/resolver_test.go, go/lib/infra/modules/trust/v2/router.go, go/lib/infra/modules/trust/v2/router_test.go, go/lib/infra/modules/trust/v2/rpc.go, go/lib/infra/modules/trust/v2/signer.go, go/lib/infra/modules/trust/v2/signer_test.go, go/lib/infra/modules/trust/v2/trustdbsqlite/db.go, go/lib/infra/modules/trust/v2/trustdbtest/trustdbtest.go, go/lib/infra/modules/trust/v2/verifier.go, go/lib/infra/modules/trust/v2/verifier_test.go
Introduce TRCID and use ChainID and TRCID consistently in trust package.
Use value types for simple structs instead of pointers.
Fixes #3525
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3532)
=> TrustStore: unify interface

go/lib/addr/appaddr.go, go/lib/ctrl/ctrl.go, go/lib/ctrl/seg/seg.go, go/lib/l4/udp.go, go/lib/layers/extensions.go, go/lib/sciond/types.go, go/lib/scmp/hdr.go, go/lib/scmp/info.go, go/lib/scmp/info_recordpath.go, go/lib/scmp/info_traceroute.go, go/lib/scmp/meta.go, go/lib/scmp/pld.go, go/lib/scrypto/cert/cert.go, go/lib/scrypto/cert/chain.go, go/lib/snet/path.go, go/lib/spath/path.go, go/lib/spkt/spkt.go, go/lib/spse/scmp_auth/drkey.go, go/lib/spse/scmp_auth/hashtree.go, go/lib/spse/spse.go, go/lib/svc/resolver.go, go/lib/xtest/graph/graph.go, go/sig/internal/snetmigrate/path.go
Check for `nil`-receiver in `Copy`.
The trigger for this change is a recently introduced small bug in `snet.Dial` where copying a `nil`-Path causes a panic.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3534)
=>  Consistently handle nil in Copy implementations 

.buildkite/pipeline.yml
If an agent is reused the STEP_ID can be the same, therefore delete the tmp directory first and recreate it cleanly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3533)
=> CI: Fix failure in lint steps of new pipeline

go/godispatcher/internal/registration/udptable.go, go/godispatcher/internal/registration/udptable_test.go
Analogous to #3451, but now for removing registrations.
This time, I double checked: there should be no further instances of this particular bug. :)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3531)
=> Fix removing IPv6 registrations in godispatcher

go/beacon_srv/main.go
Register one-hop packet dispatcher without timeout similar to all
other registration calls.
It has happened on CI that the dispatcher took slightly longer than the timeout of 1 second.
Resulting in tests failing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3546)
=> BS: Register one-hop dispatcher without timeout

go/border/BUILD.bazel, go/border/io.go, go/border/io_test.go
When an irrecoverable error happens, the posix output routine just
hangs and never terminates.
With this change, the border router fatals out instead of running in a
broken state, because there is no easy way for an operator to
re-initialize the interface with a new output routine.
fixes #3050
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3547)
=> BR: Fatal on irrecoverable errors

.buildkite/hooks/pre-artifact, .buildkite/hooks/pre-command
The ACCEPTANCE_ARTIFACTS env var should only be updated in the new
pipeline during CI pre-command hooks.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3557)
=> Fix BR acceptance tests in old CI pipeline

go/lib/common/errors.go, go/lib/sock/reliable/reconnect/BUILD.bazel, go/lib/sock/reliable/reconnect/conn_io_test.go, go/lib/xtest/BUILD.bazel, go/lib/xtest/convey.go
We should no longer use it and instead use `errors.Is`
Fixes #3334
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3554)
=> Remove common.GetErrorMsg

go/border/error.go, go/lib/scmp/error.go, go/lib/spkt/BUILD.bazel, go/lib/spkt/cmnhdr.go, go/lib/spkt/cmnhdr_test.go
Remove ToError, instead use errors.As
Add Unwrap method
Also remove Convey from spkt test.
Fixes #3312
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3558)
=> Make scmp.Error compatible with go 1.13 error funcs

acceptance/common/scion.py, acceptance/showpaths_status_acceptance/test, go/beacon_srv/internal/onehop/network.go, go/beacon_srv/main.go, go/border/rctrl/ctrl.go, go/integration/cert_req/main.go, go/integration/end2end/main.go, go/lib/infra/infraenv/infraenv.go, go/lib/sciond/pathprobe/paths.go, go/lib/snet/dispatcher.go, go/lib/snet/interface.go, go/lib/snet/mock_snet/snet.go, go/lib/snet/snet.go, go/lib/snet/squic/squic.go, go/lib/sock/reliable/reconnect/network.go, go/lib/sock/reliable/reconnect/network_test.go, go/lib/svc/resolver.go, go/lib/svc/resolver_test.go, go/lib/svc/svc.go, go/lib/svc/svc_test.go, go/sig/egress/session/session.go, go/sig/internal/ingress/dispatcher.go, go/sig/internal/sigcmn/common.go
- snet.PacketDispatcherService now has a context aware Register method.
- snet.Network's Listen and Dial now both take a context.
Contributes #3136
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3562)
=> snet: Add context to Dispatcher and Listen and Dial

.buildkite/hooks/pre-artifact, .buildkite/hooks/pre-command, .buildkite/hooks/pre-exit, .buildkite/pipeline2.sh, .buildkite/pipeline_buildlint.yml
Also:
- introduce test artifacts variable as a dir that always exists ready for tests to be used.
- use test artifacts for diff tests in check generated tasks, this dir always exists also on the local CI.
- generate acceptance steps for bazelified acceptance tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3563)
=> CI: add revocation tests to pipeline 2

.buildkite/hooks/pre-artifact, .buildkite/pipeline_buildlint.yml, .gitignore
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3526)
=>  Add go integration tests with supervisord

.buildkite/hooks/pre-artifact, .buildkite/hooks/pre-command
This will allow us to rename the pipeline.
Contributes #3574 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3573)
=> CI: Remove explicit scionproto2 references

.buildkite/pipeline_buildlint.yml, BUILD.bazel, acceptance/cert_renewal_acceptance_disabled/test, acceptance/common/scion.py, acceptance/discovery_util/util.sh, acceptance/reconnecting_acceptance/test, acceptance/sigutil/common.sh, acceptance/topo_br_reload_util/util.sh, acceptance/topo_invalid_reloads_acceptance/test, acceptance/topo_ps_reloads_br_acceptance/test, acceptance/topo_ps_reloads_cs_acceptance_disabled/test, acceptance/topo_sd_reloads_br_acceptance/test, acceptance/topo_sd_reloads_cs_acceptance_disabled/test, acceptance/topo_sd_reloads_ps_acceptance/test, scion.sh, tools/ci/integration
The topology generator only uses two binaries when running.
With this change, scion.sh only builds the necessary binaries instead
of all binaries.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3566)
=> SH: Only build necessary binaries

.buildkite/hooks/pre-command, .buildkite/pipeline2.sh, Makefile, docker.sh, docker/perapp/build-images.sh
Also make sure local CI can easily be run.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3582)
=> CI: Use bazel cache also for acceptance tests

go/sig/egress/session/sessmon.go, go/sig/egress/siginfo/BUILD.bazel, go/sig/egress/siginfo/sig.go, go/sig/egress/worker/mock_worker/BUILD.bazel, go/sig/egress/worker/mock_worker/worker.go, go/sig/egress/worker/worker.go, go/sig/egress/worker/worker_test.go, go/sig/internal/base/pollhdlr.go, go/sig/internal/ingress/dispatcher.go, go/sig/internal/sigcmn/common.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3578)
=> Remove AppAddr from SIG code

doc/BeaconService.md, go.mod, go/beacon_srv/internal/ifstate/BUILD.bazel, go/beacon_srv/internal/ifstate/export_test.go, go/beacon_srv/internal/ifstate/handler_test.go, go/beacon_srv/internal/ifstate/ifstate.go, go/beacon_srv/internal/ifstate/ifstate_test.go, go/beacon_srv/internal/ifstate/pusher_test.go, go/beacon_srv/internal/ifstate/revoker.go, go/beacon_srv/internal/ifstate/revoker_test.go, go/beacon_srv/internal/keepalive/handler_test.go
Contributes #2926
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3572)
=> BS: reduce interface state to active/revoked

acceptance/topo_br_reload_util/Tinier.topo, go/tools/scion-pki/internal/v2/tmpl/topo.go, go/tools/scion-pki/internal/v2/tmpl/topo_test.go, python/topology/topo.py, topology/Default.topo, topology/Tiny.topo, topology/Wide.topo
The source file for topology generation now has support for  primary attributes as listed in
https://github.com/scionproto/scion/blob/master/doc/ControlPlanePKI.md#primary-ases
Also add support to scion-pki for those properties.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3586)
=> Topo file: add support for v2 trust attributes

.bazelrc, .bazelrc_ci, .buildkite/hooks/pre-artifact, .buildkite/hooks/pre-command, .buildkite/hooks/pre-exit, .buildkite/pipeline_buildlint.yml, acceptance/lib.sh
This PR adds timestamps in bazel and hardcodes the test-artifact folder in order to 
enable local run. Now everything runs locally  apart from acceptance test that require 
some sudo interactive action.
Contributes #3286 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3589)
=> CI: add bazel timestamps and enable local run of the pipeline

go/border/rctrl/ctrl.go, go/border/rctrl/ifstate.go, go/border/rctrl/revinfo.go, go/lib/infra/messenger/messenger.go, go/lib/pktdisp/disp.go, go/lib/sciond/pathprobe/paths.go, go/lib/snet/interface.go, go/lib/snet/mock_snet/snet.go, go/lib/snet/reader.go, go/lib/snet/snet.go, go/lib/snet/udpaddr.go, go/lib/snet/writer.go, go/sig/internal/disp/disp.go, go/sig/internal/ingress/dispatcher.go
Remove the {write,read}FromSCION function from the snet interface
in order to simplify it. Client of snet/interface should transfer
the net.Addr interface.
Also, it removes appaddr references
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3583)
=> SNET: remove snet.Addr usage in read/write functions

python/integration/set_ipv6_addr.py, python/lib/defines.py, python/topology/common.py, python/topology/config.py, python/topology/generator.py, python/topology/go.py, python/topology/prometheus.py, python/topology/topo.py, topology/Default.topo
Add the possibility to specify the underlay in the topo file format.
Change the topology generator to support the new option.
With this we test IPv4 and IPv6 ASes in the CI integration.
Also remove bind support from the generator, it is no longer supported by Go services.
Fixes #2775
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3593)
=> Add IPv6 ASes to test topology

go/beacon_srv/internal/config/BUILD.bazel, go/beacon_srv/internal/config/config.go, go/beacon_srv/internal/config/config_test.go
The types `BSConfig` and `Policies` were forgotten inside `beacon_srv/internal/config`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3603)
=> Remove forgotten configuration types from beacon_srv

go/beacon_srv/main.go, go/border/brconf/BUILD.bazel, go/border/main.go, go/cert_srv/main.go, go/cs/main.go, go/godispatcher/main.go, go/lib/env/env.go, go/lib/infra/modules/itopo/itopo.go, go/path_srv/main.go, go/sciond/main.go, go/sig/main.go
The HTTP pages are exposed via the existing monitoring port.
1. Add config page to all SCION services (content of the toml config)
2. Add info page to all SCION services (just the build version at the moment)
3. Add topology page to all SCION services (content of loaded topology)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3608)
=> Add HTTP status pages

.bazelrc_ci, .buildkite/hooks/pre-command, .buildkite/pipeline.sh, .buildkite/pipeline.yml, Makefile, docker.sh, docker/perapp/build-images.sh, scion.sh
By default bazel merges multiple bazelrc as described here:
https://docs.bazel.build/versions/master/guide.html#where-are-the-bazelrc-files
Therefore we just move the CI bazelrc file into the home folder so the remote-cache is applied.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3591)
=> CI: Use bazelrc_ci always on CI

go/lib/log/BUILD.bazel, go/lib/log/log.go, go/lib/log/log_test.go
Our code base tries to create the log dir if does not exists.
It returns an error if the above is not possible.
Removes also some convey.
Fixes #2340
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3601)
=> Make sure file logging works

go/beacon_srv/BUILD.bazel, go/beacon_srv/main.go, go/cs/BUILD.bazel, go/cs/beaconing/BUILD.bazel, go/cs/beaconing/handler_test.go, go/cs/ifstate/BUILD.bazel, go/cs/ifstate/revoker_test.go, go/cs/keepalive/BUILD.bazel, go/cs/keepalive/handler_test.go, go/cs/main.go, go/cs/metrics/beaconing.go, go/cs/metrics/ifstate.go, go/cs/metrics/keepalive.go, go/cs/metrics/metrics.go, go/cs/metrics/originator.go, go/cs/metrics/propagator.go, go/cs/metrics/registrar.go, go/cs/metrics/registration.go, go/cs/metrics/requests.go, go/cs/metrics/revocation.go, go/cs/metrics/sync.go, go/cs/revocation/BUILD.bazel, go/cs/revocation/handler_test.go, go/cs/segreq/handler.go, go/path_srv/BUILD.bazel, go/path_srv/main.go
This reverts the metric changes accidentally introduced by
https://github.com/scionproto/scion/pull/3590.
Fixes https://github.com/scionproto/scion/issues/3610.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3611)
=> Fix metric names

acceptance/sig_failover/BUILD.bazel, acceptance/sig_failover/test, acceptance/sig_short_exp_time/BUILD.bazel, acceptance/sig_short_exp_time/test
We can just use the relative path for loading the docker images, the complicated rlocation is not required.
See also https://docs.bazel.build/versions/master/build-ref.html#data
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3616)
=> Simplify bazel SIG tests

go/lib/snet/writer.go
Minimal fix for `snet.Conn.Write`.
Previously, passing `nil` into `WriteTo` would automatically pick the
connected remote address, if available. With some of the previous
refactoring (amongst other, in #3571), this is no longer the case. Right
now, `Write` is simply broken.
Apply the simplest fix, just specify to use the connected address
(`base.remote`) in `Write`. Note that the behaviour is still subtly
different than it used to be (e.g. no error if WriteTo is invoked on a
connected socket), but this seems to be the accepted behaviour change
within the refactoring in #3571.
Additionally, add a specific error message for the `nil` address case
in `WriteTo`, as "Unable to write to non-SCION address" was misleading.
---
This change is [<img src="https://reviewable.io/review_button.svg" …
=> Fix connected Write on snet.Conn

go/beacon_srv/main.go, go/border/main.go, go/cert_srv/main.go, go/cs/main.go, go/path_srv/main.go, go/sciond/main.go, go/sig/main.go
Fixes #3413
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3624)
=> Add more context when config loading or log init fails

.buildkite/pipeline.yml, acceptance/common.sh, acceptance/discovery_util/util.sh, acceptance/showpaths_status_acceptance/test, acceptance/sigutil/common.sh, python/topology/docker.py, python/topology/docker_utils.py, python/topology/sig.py, python/topology/topo.py, scion.sh, topology/Tiny.topo, topology/Tiny4.topo
Re-enables the dockerized tests that we had in the old CI pipeline.
Also add support for ipv6 to the docker generator
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3627)
=> ci: Add dockerized integration tests

go/godispatcher/dispatcher/dispatcher.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3637)
=> Fix bug in dispatcher

go/cs/segutil/filter.go, go/lib/pathpol/acl.go, go/lib/pathpol/hop_pred.go, go/lib/pathpol/pathset.go, go/lib/pathpol/policy_test.go, go/lib/snet/path.go, go/sciond/internal/fetcher/filter.go, go/sig/internal/pathmgr/pathmgr.go
Adapt `pathpol.Path` so that `snet.Path` is compliant. Rename `Key` to `Fingerprint` and use `snet.PathInterface`  instead of the equivalent/redundant `pathpol.PathInterface` type.
This allows to create `pathpol.Pathset` from `snet.Path` objects without intermediate wrappers, and thereby makes application access to `pathpol.Filter` a bit more convenient.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3640)
=> Adapt pathpol.Path interface to snet.Path

go/lib/addr/BUILD.bazel, go/lib/addr/isdas_test.go
Contributes #3016
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3643)
=> Remove convey from tests in lib/addr

go/sig/internal/sigcmn/BUILD.bazel, go/sig/internal/sigcmn/common.go, go/sig/internal/sigconfig/conf.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3646)
=> SIG: Dispatcher bypass

go/lib/infra/messenger/addr.go, go/lib/infra/messenger/addr_test.go
This fixes a bug where SVC is not resolved in a UDP-only configured host.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3649)
=> Msgr: Fix svc redirect in UDP only mode

go/lib/infra/modules/trust/mock_trust/trust.go, go/lib/infra/modules/trust/provider.go, go/lib/infra/modules/trust/provider_test.go, go/lib/infra/modules/trust/verifier.go, go/lib/infra/modules/trust/verifier_test.go
When verifying a signature, the verifier now makes sure to have the
referenced TRC available locally.
This is one mechanism how TRC updates are disseminated.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3629)
=> TrustStore: Ensure referenced TRC is available

BUILD.bazel, go/border/rctrl/ifstate.go, go/godispatcher/main.go, go/sig/internal/disp/disp.go, go/sig/internal/ingress/api.go, tool_deps.bzl
Adds linter for log statements.
Also, fix all the places the linter flagged in the codebase.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3663)
=> Lint: Add linter for log statements

go/lib/snet/udpaddr.go
Parse the host IP, port directly instead of using net.ResolveUDPAddr, which also resolves hostnames. Hostnames should not be considered inside SCION addresses.
Fixes #3654
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3662)
=> Avoid net.ResolveUDPAddr in snet.UDPAddrFromString

env/debian/pkgs.txt, env/pip3/requirements.txt, python/lib/packet/host_addr.py, python/test/lib/log_test.py, tools/gomocks
Updates flake8 to 3.7.9 to have type annotation support.
Install flake8 via pip instead of debian, remove from debian deps.
Also fix issues flagged by the new version.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3559)
=> Lint: Update flake8

acceptance/topo_cs_reload/testdata/cs.toml, go/cs/config/config.go, go/lib/env/testdata/cs.toml, python/topology/go.py
The control service does not use the `sd_client` option, as it does not use SCIOND (c.f. #3652, "routing is done directly on top of the path database, instead of going through SCIOND").
Also removes the old `EnableQUICTest` flag, that isn't used.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3668)
=>  Remove unused sd_client config from control service 

go/lib/snet/snet.go
Include the local `IA` in the debug log after registering to the dispatcher. This allows to verify that the application is running in the correct networking context.
As a bonus, this allows to copy-paste the logged address from the debug log to connect to a server application.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3669)
=> snet: Include local IA in debug log when registering to dispatcher

WORKSPACE
Apparently someone updated a binary wrongly, see also:
https://github.com/GoogleContainerTools/distroless/pull/473
https://github.com/GoogleContainerTools/distroless/issues/471#issuecomment-588482860
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3673)
=> Fix distroless build error

go/border/io.go, go/lib/overlay/conn/conn.go
The timestamp returned from the kernel is in system time. This means
it's possible for the kernel received time to appear after the
application receives the packet, which then can cause logic errors to
occur in code that depends on the ordering of these timestamps.
Also guard against this in the BR's packet processing time metric
calculation, as system time could move backwards during the processing
of a packet.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3679)
=> Guard against system clock moving backwards.

go/border/rpkt/extns.go, go/border/rpkt/parse.go
The router could crash if a packet arrived with data resulting in the function `go/border/rpkt/extn_scmp.go/rSCMPExtFromRaw(...)` receiving a `start >= end`, which would panic on line 38.
The error is caused by `go/border/rpkt/parse.go/rp.parseHopExtns()` calling `rp.extnParseHBH(...)` on line 123, which then calls `rSCMPExtFromRaw(...)` with no checks for `start` or `end`.
I decided to add an error check in `rp.extnParseHBH(...)` instead of where the panic happens (`rSCMPExtFromRaw(...)`), because a header of invalid offset or length should fail, even when `start` or `end` are not read, such as in `rOneHopPathFromRaw`.
The problem might also be fixed earlier, in `rp.parseHopExtns()`, where the erroneous values are actually read in. However, I was unsure if this is better and so left the …
=> Fixed HBH ext parse panic when start >= end

go/lib/ctrl/sig_mgmt/addr.go, go/proto/sig.capnp.go, go/sig/egress/session/session.go, go/sig/egress/session/sessmon.go, go/sig/egress/worker/BUILD.bazel, go/sig/egress/worker/worker.go, go/sig/internal/base/pollhdlr.go, go/sig/internal/ingress/api.go, go/sig/internal/sigcmn/common.go, go/sig/main.go, proto/sig.capnp
This changes the SIG wire format. It is a breaking change.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3689)
=> SIG: Pass both control and data address in probes

python/integration/set_ipv6_addr.py
Some `gen` folders (e.g. coming from SCIONLab) will not have a `networks.conf` file. Do not throw an exception in this case while configuring IPv6.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3696)
=> No exception when networks.conf is not present

go/border/main.go, go/cs/beacon/hp_policy.go, go/cs/beacon/policy.go, go/cs/main.go, go/godispatcher/main.go, go/sciond/main.go, go/sig/main.go, python/topology/go.py
Error on ignored keys in config files. 
Misspelled keys in the config files, especially whenever the keys are changed, have cost me embarrassingly many hours of debugging followed by a face-palm. This should fix this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3697)
=> config: strict parsing of config files

go/cs/main.go
The AllowISDLoop on the beacon propagator is never set.
Thus, ISD loops are always filtered, even though the default is to allow
loops.
This PR sets the AllowISDLoop to the value specified in the propagation
policy, or to the default value, if the policy does not exist.
fixes #3698
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3699)
=> cs: allow ISD loops in propagation

go/lib/ctrl/colibri_mgmt/BUILD.bazel, go/lib/ctrl/colibri_mgmt/colibri_mgmt.go, go/lib/ctrl/colibri_mgmt/colibri_mgmt_test.go, go/lib/ctrl/colibri_mgmt/response.go, go/lib/ctrl/colibri_mgmt/segment_setup.go, go/lib/ctrl/colibri_mgmt/segment_teardown.go
This PR adds the response types for colibri control messages.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3710)
=> colibri: ctrl response types 

acceptance/topo_br_reload_if_ip_acceptance/test, acceptance/topo_br_reload_if_port_acceptance/test
Occasionally, the test is so slow that a revocation is issued.
This introduces a sleep of 10 seconds, such that all revocations
have expired and the test can correctly check if there is connectivity.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3712)
=> acceptance: make topo_br_reload more reliable

BUILD.bazel, go/cs/beacon/beacondbsqlite/db_test.go, go/cs/beacon/metrics_test.go, go/lib/infra/modules/db/sqlite.go, go/lib/infra/modules/trust/trustdbmetrics/metrics_test.go, go/lib/infra/modules/trust/trustdbsqlite/db_test.go, go/lib/pathdb/metrics_test.go, go/lib/pathdb/sqlite/sqlite_test.go, go/tools/pathdb_dump/BUILD.bazel, go/tools/pathdb_dump/README.md, go/tools/pathdb_dump/pathdb_dump.go
Dumps the contents of a sqlite3 path DB.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3707)
=> add pathdb_dump tool

go/cs/beaconing/registrar.go
There was a regression that the beaconing registrar does not fast recover
after a stale period for registering down segments.
This PR fixes it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3718)
=> cs: fix fast beaconing recovery

.buildkite/pipeline.yml, go/examples/pingpong/pp_integration/main.go, go/integration/BUILD.bazel, go/integration/cert_req_integration/main.go, go/integration/common.go, go/integration/end2end/main.go, go/integration/end2end_integration/BUILD.bazel, go/integration/end2end_integration/main.go, go/lib/integration/BUILD.bazel, go/lib/integration/binary.go, go/lib/integration/cmd.go, go/lib/integration/docker.go, go/lib/integration/done.go, go/lib/integration/integration.go, go/lib/integration/progress/BUILD.bazel, go/lib/integration/progress/progress.go, topology/Default.topo
The overhead of running a binary in a docker container with
docker-compose exec is around 1 second.
Since our integration tests are serialized and a cartesian product between
all ASes is taken, this overhead easily amounts to multiple minutes.
With this PR, all servers are started in parallel for the end2end test.
All pairs with the same source are executed in on single docker exec
command. And all executions are done in parallel.
To get a progress update, the end2end binary talks through a unix socket
to the integration binary.
We can eventually move the server wait to this RPC framework as well.
With this style of invoking the end2end test, we can reduce the execution
time on CI from >10 minutes (timeout) to a bit more than 1 minute.
Most of the execution time is actually spent in …
=> integration: speed up dockerized end2end test

WORKSPACE, acceptance/bs_add_link_acceptance/test, acceptance/common/BUILD.bazel, acceptance/common/base.py, acceptance/common/go.py, acceptance/common/scion.py, acceptance/common/tools.py, acceptance/showpaths_status_acceptance/test, env/pip3/BUILD.bazel
Also:
- refactors some names to be compatible with the Python coding style.
- Python acceptance testing common libs are now in Bazel.
- pip dependencies can now be specified in Bazel dependencies.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3723)
=> remove global state from Python acceptance

go/lib/sciond/fake/fake.go, go/lib/sciond/sciond.go, go/sciond/internal/servers/handlers.go
This is a workaround for all the EOF errors.
Should be solved properly with a sciond health check RPC.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3727)
=> sciond: avoid EOF errors on every connect

BUILD.bazel, WORKSPACE, acceptance/sig_failover/BUILD.bazel, acceptance/sig_short_exp_time/BUILD.bazel, acceptance/topo_common/BUILD.bazel, acceptance/topo_cs_reload/BUILD.bazel, acceptance/topo_sd_reload/BUILD.bazel, docker/BUILD.bazel, docker/scion_app.bzl, docker/sig_tester.bzl, docker/tester.bzl, go/lib/infra/modules/trust/testdata/BUILD.bazel, go/lint/BUILD.bazel, licenses/BUILD.bazel, nogo.json, scion.bzl, scion.sh
Adds 2 new bazel targets:
- `bazel run //:buildifier` runs buildifier in the repo.
- `bazel run //:buildifier_check` checks that all files are up to date.
The latter command is invoked in ./scion.sh lint and is thus also a check for CI.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3733)
=> lint: add buildifier

doc/PathService.md
The down-segment synchronization mechanism in the core is
deprecated (see #3731).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3736)
=> remove segment synchronization from PS docs

.buildkite/pipeline.yml, scion.sh
This PR adds the SCION buildkite plugin that does a clean shutdown of
the topology after the command.
Additionally, jaeger is started and stopped with `./scion.sh {run,stop}`
such that it is included in the clean shutdown.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3749)
=> ci: clean shutdown

go/cs/beaconing/extender.go, go/cs/beaconing/extender_config.go, go/cs/beaconing/staticinfo_config.go, go/cs/beaconing/staticinfo_config_test.go, go/cs/main.go, go/lib/ctrl/seg/staticinfo_extn.go
Currently static info was always added to the beacons even if there was no configuration,
This PR changes this behavior to only add static info if there is a configuration.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3755)
=> staticinfo extension, only add if configured

go/lib/infra/modules/itopo/BUILD.bazel, go/lib/infra/modules/itopo/validate.go, go/lib/topology/interface.go, go/lib/topology/topology.go
Change the `Attributes` field type to []trc.Attribute in order to
allow marshalling the RWTopology for non-primary ASes.
fixes #3745
With the X509 style certificates, the `trc` package will eventually be removed, and we need to revisit this to have a clean solution.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3746)
=> topo: allow marshalling RWTopology

python/topology/go.py
With #3751 the log collection is broken on CI.
This is a workaround that logs to console in a docker topology, such
that the logs are not lost on CI.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3757)
=> topogen: enable console logging

go/cs/reservation/e2e/BUILD.bazel, go/cs/reservation/e2e/index.go, go/cs/reservation/e2e/reservation.go, go/cs/reservation/e2e/reservation_test.go, go/cs/reservation/index.go, go/cs/reservation/segment/BUILD.bazel, go/cs/reservation/segment/export_test.go, go/cs/reservation/segment/path_test.go, go/cs/reservation/segment/reservation.go, go/cs/reservation/segment/reservation_test.go, go/cs/reservation/segmenttest/BUILD.bazel, go/cs/reservation/segmenttest/common.go, go/lib/colibri/reservation/types.go
Adds the E2E reservation and refactors some tests to be reused.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3752)
=> Add COLIBRI E2E application level types

go/cs/reservation/e2e/BUILD.bazel, go/cs/reservation/e2e/request.go, go/cs/reservation/e2e/request_test.go, go/cs/reservation/segment/BUILD.bazel, go/cs/reservation/segment/request.go, go/cs/reservation/segment/request_test.go, go/lib/colibri/reservation/BUILD.bazel, go/lib/colibri/reservation/types.go, go/lib/colibri/reservation/types_test.go, go/lib/ctrl/colibri_mgmt/colibri_mgmt_test.go, go/lib/ctrl/colibri_mgmt/reservation_ids.go
Add functions to convert between application level types and control messages from Capnp.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3763)
=> colibri: application level types requests

go/cs/segreq/helpers.go
An arbitrary limit to 9 path segments in a SegReply was implemented some time ago as a hack to avoid exceeding MTU. This is no longer necessary as QUIC is now used as transport for these path segment requests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3765)
=> Remove obsolete limit on path segments in SegReply

go/cs/main.go, go/lib/infra/messenger/tcp/messenger.go, go/sciond/main.go
SCIOND runs a tcp-messenger in client mode. There was a superfluous
deferred `CloseServer` call that panicked on shutdown.
Changes:
- Remove deferred `CloseServer` call on tcp-messenger in client mode
- Don't panic when calling `CloseServer` on a tcp-messenger with nil listener
- Move deferred `CloseServer` call in CS to the appropriate place
fixes #3766
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3769)
=> sciond: don't panic on shutdown

go/border/rctrl/ctrl.go, go/examples/pingpong/pingpong.go, go/integration/common.go, go/lib/infra/infraenv/infraenv.go, go/lib/sciond/pathprobe/paths.go, go/lib/snet/conn.go, go/lib/snet/snet.go, go/lib/snet/writer.go, go/sig/internal/sigcmn/common.go
Remove unused `querier` from `snet.NewNetworkWithPR`.  Rename `snet.NewNetworkWithPR` to `snet.NewNetwork` and `snet.NewCustomNetworkWithPR` to `snet.NewCustomNetwork`, accordingly.
This is an API breaking change.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3771)
=> remove unused path resolver from snet.NewNetwork

go/lib/infra/rpc/rpc.go
If we don't get a session within the context we should error out instead of trying to OpenStream on a nil session.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3770)
=> fix nil pointer panic in rpc backoff logic

tools/install_bazel
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3782)
=> upgrade bazel to 3.2

go/lib/topology/topology_test.go
`foo` is used in a test to represent a name that will fail to resolve. But it
works sometimes (e.g. in the ETH). Change it to some more weird name so
it fails resolving it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3786)
=> topology: replace 'foo' in the tests with a hostname that fails

go/sig/main.go
The default port doesn't match the official port ranges
as described in https://github.com/scionproto/scion/wiki/Default-port-ranges
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3793)
=> fix default monitoring port for sig

go/tools/scmp/BUILD.bazel, go/tools/scmp/cmn/BUILD.bazel, go/tools/scmp/cmn/common.go, go/tools/scmp/echo/echo.go, go/tools/scmp/main.go, go/tools/scmp/scmp_integration/main.go
Also simplifies argument processing by refactoring scmp echo
to use cobra.
The remote address as a positional argument instead of a -remote flag.
For example, `scmp echo 64-2:0:a,[10.0.2.162]`.
`scmp` now uses POSIX style flags (prefixed with double dash, --)
instead of Go style flags (in other words, now use `--refresh` instead of
`-refresh`). scmp command lines that use Go style flags now have changed
semantics (e.g., `-refresh` actually means setting the `-r`, `-e`, `-f`,
etc. flags). Please ensure all scripts containing the old CLI flags have
been inspected and updated.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3795)
=> scmp: add payload size support to scmp echo

go/border/BUILD.bazel, go/border/error.go, go/border/router.go
At the moment, this is used by path probes. (see #1801)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3797)
=> border: do not log an error for SVC_NONE dst addresses

acceptance/cert_renewal_acceptance/test, go/scion-pki/certs/BUILD.bazel, go/scion-pki/certs/renew.go, go/scion-pki/certs/renew_test.go, go/scion-pki/certs/testdata/renew/ISD1-ASff00_0_111.csr.json, go/scion-pki/certs/testdata/renew/no_isd_as.json, go/scion-pki/conf/testdata/update_certs.sh, go/scion-pki/conf/trc_test.go
Improve the usability of the cert renewal tool.
No longer require the `out` and `template` flags.
No longer require the positional argument that indicates the CA to send
the certificate chain request to.
If the `template` flag is not set, the subject of the CSR is filled with
with the subject of the transport certificate chain.
If the `out` flag is not set, the resulting chain is written to the
directory of the transport certificate chain as `ISDx-ASy.s.pem`,
where `x` is the ISD, `y` is the AS number, and `s` is the hex encoded
serial number of the AS certificate in the certificate chain.
If the positional argument is not set, the CSR is sent to the subject
of the CA certificate in the transport certificate chain.
In case verification fails against the TRC, the chain is now still
written …
=> spki: make cert renewal easier to use

go/pkg/sig/sigconfig/conf.go
This is not used anywhere.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3803)
=> sig: remove ConfigName from sigconfig

go/cs/reservation/BUILD.bazel, go/cs/reservation/e2e/index.go, go/cs/reservation/index.go, go/cs/reservation/index_test.go, go/cs/reservation/reservationdbtest/BUILD.bazel, go/cs/reservation/reservationdbtest/reservationdbtest.go, go/cs/reservation/segment/BUILD.bazel, go/cs/reservation/segment/index.go, go/cs/reservation/segment/index_test.go, go/cs/reservation/segment/path.go, go/cs/reservation/segment/path_test.go, go/cs/reservation/segment/reservation.go, go/cs/reservation/segment/reservation_test.go, go/cs/reservation/sqlite/db.go, go/cs/reservation/sqlite/db_test.go, go/cs/reservation/sqlite/schema.go, go/cs/reservationstorage/backend/db.go, go/lib/colibri/reservation/types.go, go/lib/colibri/reservation/types_test.go
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3787)
=> COLIBRI backend continuation

go/examples/pingpong/pingpong.go, go/integration/common.go, go/integration/end2end/main.go, go/lib/infra/infraenv/infraenv.go, go/lib/sciond/pathprobe/paths.go, go/lib/snet/base.go, go/lib/snet/dispatcher.go, go/lib/snet/packet_conn.go, go/pkg/cs/main.go, go/pkg/showpaths/showpaths.go, go/scion-pki/certs/renew.go, go/sig/internal/sigcmn/common.go, go/sig/main.go, go/tools/showpaths/paths.go
Also:
- plugs feature flag support to all snet using applications
with the exception of the border router. Note that CLI tools need
need a CLI flag to be added to enable the feature.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3810)
=> snet: add support for new SCION header

go/lib/log/config.go, go/lib/log/log.go, go/lib/log/logtest/config.go, go/lib/log/sample.go
Add JSON format to set of supported logging output formats.
It can be enabled by setting `log.console.format` and/or `log.file.format`
to `json`. The default remains the structured `human`-readable approach.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3816)
=> log: add json logging

go/cs/config/config.go, go/cs/config/config_test.go, go/cs/config/sample.go, go/pkg/cs/BUILD.bazel, go/pkg/cs/http.go, go/pkg/cs/main.go, go/pkg/cs/trust/BUILD.bazel, go/pkg/cs/trust/ca_signer_gen.go, go/pkg/cs/trust/internal/metrics/BUILD.bazel, go/pkg/cs/trust/internal/metrics/metrics.go, go/pkg/cs/trust/internal/metrics/signer.go, go/pkg/cs/trust/signer_gen.go, go/pkg/trust/internal/metrics/signer.go, go/pkg/trust/signer_gen.go, go/pkg/trust/signer_gen_test.go
Add additional metrics that expose the state of the signer and CA signer
in the control service. Both signers are cached for a certain amount
of time. The metrics expose the last time each signer was successfully
generated.
BREAKING CHANGE: renaming one metric, see below.
As the CA signer can be unavailable, i.e., if the key is removed from
disk, the metrics expose whether it is active or not.
The new metrics are:
trustengine_ca_signer_active_boolean 1
trustengine_ca_signer_expiration_time_second 1.655025547e+09
trustengine_generated_ca_signers_total{result="ok_success"} 1
trustengine_generated_signers_total{result="ok_success"} 103
trustengine_last_ca_signer_generation_time_second 1.5919535885081732e+09
trustengine_signed_certificate_chains_total{result="ok_success"} 3 …
=> cs: add metrics for signer and ca signer

scion.sh
nosetests require logs directory to exist
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3820)
=> fix nosetests

go/cs/ifstate/revoker_test.go, go/cs/revocation/BUILD.bazel, go/cs/revocation/handler.go, go/cs/revocation/handler_test.go, go/lib/ctrl/path_mgmt/rev_info.go, go/lib/infra/modules/segverifier/segverifier.go, go/lib/xtest/matchers/matchers.go
This will allow us to proceed with the new revocation mechanism in a
non-breaking way. In this commit we disable verification later we can
disable signing. Then we can gradually move revocation
creation to the dataplane.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3822)
=> disable revocation verification

go/cs/onehop/sender.go, go/lib/hpkt/BUILD.bazel, go/lib/hpkt/write.go, go/lib/spath/BUILD.bazel, go/lib/spath/path.go, go/pkg/cs/main.go
Instead of converting OHP packets in hpkt write we need to do it
correctly in the onehop sender, so that we can set the correct MAC value.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3826)
=> properly send ohp packet for header v2

go/lib/log/context.go
Avoid wrapping a span logger inside of another span logger.
When calling `log.FromCtx`, the logger inside the context is wrapped
with a span logger. If the logger is already a span logger, it is not
wrapped.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3833)
=> log: avoid double span wrapping

go/cs/segreq/fetcher.go, go/lib/infra/modules/segfetcher/BUILD.bazel, go/lib/infra/modules/segfetcher/requester.go
The destination provider might itself fetch segments and thus might take
quite some time. We should not let the first request block other
requests. Therefore execute the dst provider also in the request go
routine.
This should improve stability of the new path lookup.
Also create separate spans for each request so that it becomes easier to
debug what is going on.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3836)
=> segfetcher: do recursive request in parallel

go/cs/beacon/beacon.go, go/cs/beaconing/extender.go, go/cs/beaconing/extender_test.go, go/cs/beaconing/handler.go, go/cs/beaconing/handler_test.go
Also for v2 don't set it.
Since we want to get rid of keepalives, which also detect remote
interfaces we have to stop using remote interface IDs. Except for
peering links we don't really need to know the remote interface ID. For
peering links we should add the remote ID to the topology file once we
implement support for peering links.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3832)
=> cs: don't verify RemoteOutIf in beaconing

acceptance/common.sh, go/integration/BUILD.bazel, go/integration/common.go, integration/common.sh, integration/integration_test.sh, python/topology/common.py, python/topology/config.py, python/topology/docker.py, python/topology/docker_utils.py, python/topology/generator.py, python/topology/go.py, python/topology/jaeger.py, python/topology/net.py, python/topology/prometheus.py, python/topology/sig.py, python/topology/topo.py, scion.sh, tools/dc
If we just specify an IPv6 subnet in a docker network, docker-compose chooses
an IPv4 subnet which might overlap with another IPv4 network that we allocated.
This will make the topology fail able to start. This commit prevents this and
should fix a few CI errors.
Also remove the `--in-docker` flag and supporting code, because it is no longer needed.
Also add extra_hosts entry for jaeger tracing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3840)
=> topogen: allocate ipv4 subnets for docker

acceptance/sig_failover/testdata/1-ff00_0_110/sig/fake_sciond.json, acceptance/sig_failover/testdata/1-ff00_0_111/sig/fake_sciond.json, acceptance/sig_short_exp_time/testdata/1-ff00_0_110/sig/fake_sciond.json, acceptance/sig_short_exp_time/testdata/1-ff00_0_111/sig/fake_sciond.json, go/cs/segutil/router.go, go/lib/infra/messenger/addr.go, go/lib/infra/messenger/addr_test.go, go/lib/pathmgr/pathmgr.go, go/lib/pathmgr/syncpaths.go, go/lib/pathmgr/util_test.go, go/lib/pathpol/pathset.go, go/lib/pathpol/policy_test.go, go/lib/sciond/apitypes.go, go/lib/sciond/fake/fake.go, go/lib/sciond/fake/fake_test.go, go/lib/sciond/fake/testdata/sd.json, go/lib/snet/mock_snet/snet.go, go/lib/snet/path.go, go/lib/spath/spathmeta/apppath.go, go/lib/svc/resolver.go, go/pkg/sciond/fetcher/filter.go, go/pkg/showpaths/showpaths.go, go/scion/ping.go, go/sig/egress/iface/sesspath.go, go/sig/egress/session/sessmon.go, go/sig/egress/worker/worker.go, go/sig/internal/snetmigrate/path.go, go/tools/scmp/main.go, go/tools/showpaths/paths.go
Add additional interface for (optional) path metadata on snet.Path.
This new snet.PathMetadata interface will be extended to add support for
the information in the StaticInfo beacon extension (Geo information,
Latency, Bandwidth, etc) as a next step.
Having a separate interface for the metadata clarifies that some
instances of snet.Path (e.g. the `partialPath` constructed from raw
forwarding information) do not have any of this metadata available.
Thus, moving the existing MTU and Expiry fields to this new interface
feels quite natural.
Additionally, remove `Fingerprint` from the `snet.Path` interface.
`Fingerprint` can be implemented in terms of snet.Path, so it does not
need to be part of the interface. Make this a simple helper function 
in `snet` instead.
---
This change is [<img …
=> snet: move MTU/Expiry to separate snet.PathMetadata interface

tools/md/Dockerfile
This pins the mdl version to 0.9.0 thus avoiding the failing 0.10.0
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3848)
=> lint: fix mdlint problem

go/tools/pathdb_dump/pathdb_dump.go
When looping over the responses from the DB the error of the response should be returned.
Now no error is returned since err will always be nil; otherwise it either stops before at line 68; or after at line 77.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3851)
=>  Return correct err on response error from DB query

go/sig/main.go
The SIG was setting a default prometheus address, contrary to what is
documented; the docs explicitly say that if the address is unset, the
metrics will not be exported. This default value would also make it
impossible to disable exporting metrics.
Remove the undocumented, unneeded default value.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3850)
=> sig: remove default prometheus address

go/lib/env/env.go, go/lib/env/envtest/config.go, go/lib/env/features.go, go/lib/env/sample.go, go/sig/internal/sigcmn/common.go
The following configs change:
- default path for configuration file
- default path for QUIC certificate file
- default path for QUIC key file
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3857)
=> change default configs to docker-friendly values

doc/protocols/scmp.rst
Introduce error code to differentiate between unknown ingress and egress
interface, where the pointer is the offset to the hop field.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3861)
=> doc: update SCMP spec

go/cs/reservation/segment/response.go, go/cs/reservationstorage/BUILD.bazel, go/cs/reservationstorage/store.go, go/cs/reservationstore/store.go
- Segment request operations are complete
- E2E request operations with the exception of the admission one are complete
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3859)
=> colibri: advance request handling

doc/protocols/bfd.rst, doc/protocols/index.rst, doc/protocols/scion-header.rst
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3873)
=> [doc] BFD/SCION protocol specification

go/pkg/app/path.go
Using "white" as text color is invisible in color schemes with light backgrounds.
Just use the default text color instead to make this legible for both light and dark background color schemes.
Before (unreadable :boom: ):
After:
Before:
After (basically unchanged):
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3876)
=> scion: use default text color to fix light-mode

go/pkg/grpc/BUILD.bazel, go/pkg/grpc/dialer.go
TLSQUICDialer dials a gRPC connection over TLS/QUIC/SCION, which can be used for secure inter-AS communication
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3886)
=> trust: add gRPC Dialer over TLS/QUIC/SCION

BUILD.bazel, acceptance/brutil/conf/as.yml, acceptance/brutil/docker-compose.yml, acceptance/bs_add_link_acceptance/test, acceptance/cert_renewal_acceptance/test, acceptance/common/README.md, acceptance/common/scion.py, acceptance/common/test_scion.py, acceptance/sig_failover/BUILD.bazel, acceptance/sig_reload_acceptance/test, acceptance/sig_short_exp_time/BUILD.bazel, acceptance/topo_cs_reload/BUILD.bazel, acceptance/topo_cs_reload/testdata/gen_crypto.sh, acceptance/topo_sd_reload/BUILD.bazel, acceptance/trc_update_acceptance/test, docker/BUILD.bazel, docker/caps.bzl, docker/scion_app.bzl, go/lib/integration/integration.go, go/scion-pki/testcrypto/testcrypto.go, python/topology/cert.py, python/topology/common.py, python/topology/docker.py, python/topology/go.py, python/topology/sig.py, python/topology/supervisor.py, python/topology/topo.py, scion.sh, supervisor/supervisord.conf
Make the `gen/` directory structure flatter to make it easier to navigate. Avoid the replication of `topology.json`, certs, keys etc. in per-service configuration subdirectories, to allow straight-forward manipulation of e.g. the topology configuration.
Additionally, some clean-up of the supervisor config; set `stdout_logfile` and enable `redirect_stderr` instead of doing this manually in the invoked command with `bash -c 'exec %s &>logs/%s.log'`.
The flatter hierarchy is simpler to navigate and easier to manipulate as there are no replicated configuration files to worry about.
For these reasons, I would like to adopt this flatter configuration tree for the configuration that we generate from SCIONLab (installed in `/etc/scion`). Technically, this is unrelated to whether or not this PR is …
=> topogen: create flatter gen/ structure

doc/hidden-paths.rst
This adapts the original proposal to changes we made to the rest of the
SCION ecosystem:
- No longer speaks of PS/BS etc.
- Uses service discovery instead of a separate SVC address.
- Services are defined in gRPC.
- Configs use snake_case.
Apart from that small functional adaptions are proposed:
- The SCION daemon is configured with the hidden path group IDs it
should query for, instead of having this in the path lookup request.
This makes everything a bit simpler, doesn't need a special lookup for
the hidden path config etc.
[doc]
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3900)
=> doc: hidden path design update

go/cs/cs.go, go/integration/common.go, go/lib/env/env.go, go/lib/env/envtest/config.go, go/lib/infra/infraenv/infraenv.go, go/lib/integration/binary.go, go/lib/integration/cmd.go, go/lib/integration/integration.go, go/lib/sciond/sciond.go, go/lib/snet/squic/squic.go, go/pkg/router/dataplane.go, go/pkg/router/dataplane_test.go, go/pkg/router/export_test.go, go/pkg/sciond/BUILD.bazel, go/pkg/sciond/config/config.go, go/pkg/sciond/config/config_test.go, go/pkg/sciond/sciond.go, go/pkg/sciond/sciond_test.go, go/pkg/sig/config/config.go, go/pkg/sig/config/configtest/configtest.go, go/pkg/sig/config/sample.go, go/scion-pki/certs/renew.go, go/scion/ping.go, go/scion/showpaths.go, go/scion/traceroute.go, go/sciond/BUILD.bazel, go/sciond/main.go, go/sig/internal/sigcmn/common.go, python/topology/sig.py
Various other changes
- cs: deregister discovery API from TCP server
- intra-AS bfd uses underlay source address/port
- daemon: use default API port if unspecified 
Co-authored-by: Dominik Roos <roos@anapaya.net>
Co-authored-by: Lukas Vogel <vogel@anapaya.net>
Co-authored-by: Sergiu Costea <costea@anapaya.net>
Co-authored-by: Martin Sustrik <sustrik@anapaya.net>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3902)
=> BFD: enable underlay implementation

doc/protocols/bfd.rst
Update the doc for the change in #3902
Fixes: #3891
[doc]
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3903)
=> doc: intra-AS bfd uses underlay source address/port

acceptance/common/scion.py, acceptance/lib.sh, scion.sh
Calling make directly does some extra work that is not needed.
For example it rebuilds all protobufs etc, we check in a separate
build step that those files are still up to date.
Also remove the nobuild option in the acceptance libs, it's always
true.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3910)
=> build/test: reduce make usage

.buildkite/pipeline.yml, Makefile, go/pkg/proto/control_plane/BUILD.bazel, go/pkg/proto/crypto/BUILD.bazel, go/pkg/proto/daemon/BUILD.bazel, go/pkg/proto/discovery/BUILD.bazel, go/pkg/proto/gateway/BUILD.bazel, tools/godeps.sh
By default, `make` (or `make build`) only builds.
An explicit `make all` will additionally run all the code-generation
steps for the checked-in generated code, in the right order.
For the protobuf code generation step, the multiple bazel invocations
are combined to both improve readablity of the Makefile and the output,
and to make make run quiter.
Note that the order of the code generation steps is different than
before; previously `protobuf` forced itself to run before generating
`go_deps.bzl` -- this doesn't seem to make sense as the protobuf code
generation will never automatically affect the `go.mod` file. The other
way around is more conceivable, changes to `go.mod` propagating to
`go_deps.bzl` and so affecting the protobuf code generation.
Additionally, `all` now also includes the …
=> make: build without code gen by default

go/pkg/showpaths/showpaths.go, go/scion/ping.go, go/scion/showpaths.go
Amendment to #3876, missed one value.
Additionally, change the `--no_color` option to the more traditional
kebab case `--no-color`, same for the (few) other occurrences of snake
case in flags.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3914)
=> cmd/scion: showpaths color, --no-color flag

go/lib/log/config.go, go/lib/log/log.go, go/lib/log/logtest/config.go, go/lib/log/sample.go
Add a config option to set the stacktrace level for logging.
Also allow disabling it completely.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3913)
=> log: allow configuring stacktrace level

go/lib/env/env.go, go/lib/env/sample.go, go/lib/infra/infraenv/infraenv.go, python/topology/generator.py, python/topology/go.py
If the QUIC address is not set, infer it from the public address and
run it on a high port.
Additionally, remove the service resolution fraction, as it is no longer
used.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3917)
=> cs: infer QUIC address

go/pkg/router/dataplane.go, go/pkg/router/metrics.go, go/posix-router/main.go
Add two metrics to track the number of service instances known to the
data plane.
router_service_instance_changes_total{isd_as="1-ff00:0:110",service="CS"} 11
router_service_instance_changes_total{isd_as="1-ff00:0:110",service="DS"} 11
router_service_instance_count{isd_as="1-ff00:0:110",service="CS"} 3
router_service_instance_count{isd_as="1-ff00:0:110",service="DS"} 3
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3918)
=> router: add metric to track service instance count

go/lib/topology/json/json.go, go/lib/topology/testdata/basic.json, go/lib/topology/topology.go, go/lib/topology/topology_test.go
The DS will then attach the mapping to Gateway discovery replies. This
means all traffic that targets a remote gateway should flow only through
the interface IDs attached to it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3919)
=> topology: add gateway,interface ID mapping

go/cs/beaconing/originator_test.go
Fix racy access to MAC object in the originator test.
This is hitting us only now, because the originator now does parallel
beacon origination to avoid HOL blocking.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3920)
=> cs: fix testing race

go/lib/underlay/conn/conn.go
Fix nil pointer dereference panic in error case of Read from unconnected
underlay conn.
This is only a minor edge case; the problem only occured on read errors
which the dispatcher considers fatal anyway.  However, the panic did
mask the cause for the read error (in my case, too many open files) from
the logs.
Note that the router uses connected underay conns, which use a different
code path.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3925)
=> dispatcher: fix panic on read error

go/lib/snet/addrutil/BUILD.bazel, go/lib/snet/addrutil/addrutil.go, go/pkg/showpaths/showpaths.go, go/posix-gateway/BUILD.bazel, go/posix-gateway/main.go, go/scion-pki/certs/renew.go
Determine default local IP for SIG as documented in config sample,
analogous to old SIG implementation.
Instead of copying the findDefaultLocalIP logic again, move to
addrutil.DefaultLocalIP library function.
~~Additionally includes losely related small cleanup in sciond.TopologyQuerier.~~ (was included in 3938).
Closes #3933.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3936)
=> gateway: determine default local IP

go/lib/infra/modules/combinator/BUILD.bazel, go/lib/infra/modules/combinator/combinator.go, go/lib/infra/modules/combinator/combinator_test.go, go/lib/infra/modules/combinator/export_test.go, go/lib/infra/modules/combinator/graph.go, go/lib/infra/modules/combinator/testdata/00_loops.txt, go/lib/infra/modules/segfetcher/pather.go
Duplicate paths can occur when multiple combinations of different path
segments result in identical sequences of path interfaces path after
applying short-cuts.
The old behaviour was to return all paths found. The rationale for this
was that from a crypto point of view the paths are different; this made
sense with the old path header format, where shortcuts would include a
verify-only hop field that was really separate from the effectively used
hop fields.
Now with the new path header format, the sequence of the hop fields for
such duplicate paths is really identical, the only differences are the
segment IDs and the MACs. While it's still conceivable that an AS could
misbehave and change the forwarding behaviour based on the segment IDs
or MACs, this would be really an exceptional case. …
=> combinator: avoid returning duplicate paths

go/pkg/gateway/config/config.go, go/pkg/gateway/config/configtest/configtest.go, go/pkg/gateway/config/loader.go, go/pkg/gateway/config/loader_test.go, go/pkg/gateway/config/sample.go
The interpretation of the configured `ip_routing_policy_file`
configuration option was:
- if the value is identical to the default file path and the file does
not exist, ignore it and return a default routing policy
- otherwise, read the file at the specified location (and fail if it
doesn't exist)
Not only does this seem a bit convoluted, but it can also fail in
interesting ways; when the user does not want to specify an
`ip_routing_policy_file` and there is an error stat-ing the file at the
default location (e.g. no permission to read directory, error while
accessing network file system, etc.), the SIG would refuse to start.
Simplified to only handle the empty value as special default.
The consequence of this is that the configuration files now _must_
specify the `ip_routing_policy` …
=> gateway: simplify defaults for policy file config

acceptance/hidden_paths/BUILD.bazel, go/cs/cs.go
The hidden paths server handlers were registered after the server
was already running, causing the gRPC library to shut down the app.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3949)
=> control: fix HP server setup and enable acceptance

go.mod, go.sum, go/pkg/gateway/dataplane/BUILD.bazel, go/pkg/gateway/dataplane/encoder.go, go/pkg/gateway/dataplane/ipforwarder_test.go, go/pkg/gateway/dataplane/sender.go, go/pkg/gateway/dataplane/sender_test.go, go/pkg/gateway/dataplane/session.go, go/pkg/gateway/dataplane/session_test.go, go_deps.bzl
Fix a go routine leak in the dataplane session.
Before this patch, the gateway would leak go routines whenever paths
are updated, or when path updates fail.
With this patch, both of these cases are handled, and no go routines
are leaked in `Session.SetPaths` anymore.
Additionally, this patch fixes a bug where tiny MTU would cause a
uint16 underflow, resulting in a huge frame size.
GitOrigin-RevId: 30e7715fe84820f0c39384497c85cbcc9509f90b
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3979)
=> posix-gateway: fix go routine leak in dataplane session

Makefile, scion.sh
Because after running `make` I want to run `make test` (and also `make lint` but that'd be a bit more work).
Also: replace `build_binaries` in scion.sh with equivalent `make build`.
This `build_binaries` snippet had been copied explicitly because `make build` used to do what is now `make all`, which was too much.
Closes #3996
GitOrigin-RevId: d8db5071246e14433e957bab14af0fb79591fa81
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3997)
=> make: add make test

go/lib/addr/BUILD.bazel, go/lib/addr/host.go, go/lib/addr/host_test.go
Add a bounds-check when parsing a `HostTypeSVC` address.
Fixes #4080
Closes #4081
GitOrigin-RevId: eb035aef1d31b14d3aa1a3de8b5f4e88ba884f91
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/4086)
=> addr: add bounds-check when parsing HostTypeSVC

.buildkite/pipeline.yml
Occasionally, the adjusted steps take a bit longer to run when starting
and 10 minutes is not enough. This change sets the timeout higher.
GitOrigin-RevId: 9e994416580ac32a25e5e47c5c111cf9e6a68e7b
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/4199)
=> ci: increase timeouts to avoid flaky failures

.semgrepignore, gateway/control/remotemonitor.go, tools/lint.sh, tools/lint/semgrep/loopvar_capture.yml
Detect loop variable captured by function in go or defer statement.
The loop variable is reassigned when stepping in the loop, and so
by the time the go routine is run, the value may have changed.
Fix the single occurrence of the pattern.
Update semgrep, as the rules did not appear to work as expected with the
older version.
With this newer version, we now need an (empty) .semgrepignore file, as
by default semgrep ignores all _test.go files, which seems undesirable.
The docker command for semgrep is also changed to explicitly invoke
`semgrep`, as directed by a deprecation warning.
Closes #2164.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/4202)
=> lint: detect captured loop var in go/defer statement

.buildkite/hooks/go-module-proxy.yml, .buildkite/hooks/pre-exit, tools/update_testdata.sh
Adapt configuration of go-module-proxy to improve performance, in
particular for `/list` queries, which occur for example during gazelle's
`update-repos` during `make go_deps.bzl`.
Upload go-module-proxy logs and metrics as artifacts.
Do not stop go-module-proxy or bazel-remote-cache on agent after exiting
between jobs to keep warmed up in-memory state. Any changes to the
docker configuration of these services between jobs are automatically
handled by docker-compose.
Aside; in tools/update_testdata.sh, put bazel's go_sdk first into the
path, so that the script picks up these binaries for running the
tests. This only makes a difference for local execution of the script,
the buildkite agents don't have go installed.
---
This change is [<img src="https://reviewable.io/review_button.svg" …
=> ci: speed up go-module-proxy

pkg/private/serrors/errors.go, private/mgmtapi/segments/api/testdata/segments-malformed-query.json
When calling `WithCtx` on an existing wrapped `serrors.basicError`,
append the new context to the existing context `fields`.
To illustrate, the following two blocks below create the same error:
```go
cause := serrors.New("base error")
err := serrors.WrapStr("wrapped", cause, "ctx1", 1, "ctx2", 2)
fmt.Println(err)
// -> wrapped {ctx1=1; ctx2=2}: base error
err = serrors.WrapStr("wrapped", cause, "ctx1", 1)
err = serrors.WithCtx(err, "ctx2", 2)
fmt.Println(err)
// -> wrapped {ctx1=1; ctx2=2}: base error
```
This tidies up the string representation of the error; previously
the second block would have returned the somewhat confusing
```
wrapped {ctx1=1}: base error {ctx2=2}
```
Fixes #3364
--- …
=> serrors: append to existing context in WithCtx

private/storage/drkey/BUILD.bazel, private/storage/drkey/level1/BUILD.bazel, private/storage/drkey/level1/db.go, private/storage/drkey/level1/db_test.go, private/storage/drkey/level1/dbtest/BUILD.bazel, private/storage/drkey/level1/dbtest/dbtest.go, private/storage/drkey/level1/sqlite/BUILD.bazel, private/storage/drkey/level1/sqlite/db.go, private/storage/drkey/level1/sqlite/db_test.go, private/storage/drkey/metrics.go, private/storage/drkey/secret/BUILD.bazel, private/storage/drkey/secret/db.go
This PR is the third in a series of PRs that add support for DRKey.
- Sqlite implementation of the Level1 DB interface
- Metrics support
- UTs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/4221)
=> drkey: Add Level1 DB

private/trust/mock_trust/mock.go, private/trust/tls_handshake.go, private/trust/tls_handshake_test.go
This PR includes the following changes:
- Adds extKeyUsage verification for TLS HS [1] [2].
- Replaces `VerifyPeerCertificate` with `VerifyClientCertificate` and `VerifyServerCertificate`.
- Extends `X509KeyPairLoader` with two separate functions to load a client and a server certificate.
- Adds `VerifyConnection` callback implementation, available as of Go1.16.
[1] https://scion.docs.anapaya.net/en/latest/cryptography/certificates.html?highlight=extKeyUsage#extended-key-usage-extension
[2] https://scion.docs.anapaya.net/en/latest/cryptography/certificates.html#id34.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/4222)
=> trust: extend TLSCryptoManager with support for verifying correctness of extKeyUsage extensions

pkg/slayers/path/epic/epic.go
Hello 👋 , currently one of the guaranteed post-conditions of the Path interface Reverse method is that "if the error return value is `nil`, then the returned Path is well-formed". This is a general pattern in Go when returning an error value, but especially in the context of the VerifiedSCION project.
In the case of the Epic path's Reverse function, if the type assertion fails, the returned `err` value would still be `nil` from the assignment on line 101, seen [here](https://github.com/scionproto/scion/blob/39b8fd4acbc2773e04e022bd66cf7cffae1f48a7/pkg/slayers/path/epic/epic.go#L101-L107).
I would say that this is invalid and propose that a new error should be returned. I simply threw in an error message there, however, I am unconvinced that it is the correct message. Better suggestions …
=> path.Epic Reverse method error handling. 

daemon/internal/servers/grpc.go, pkg/proto/control_plane/drkey.pb.go, pkg/proto/daemon/daemon.pb.go, private/proto/drkey/eq_definiton_test.go, proto/control_plane/v1/drkey.proto, proto/daemon/v1/daemon.proto
This PR is the 6th in a series of PRs that add support for DRKey started with https://github.com/scionproto/scion/pull/4217.
- The protobuf drkey RPC call definitions for the CS and the daemon
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/4226)
=> drkey: add RPC cs/daemon

control/config/BUILD.bazel, control/config/drkey.go, control/config/drkey_test.go, control/config/sample.go, private/storage/BUILD.bazel, private/storage/storage.go
This PR is the 7th in a series of PRs that add support for DRKey started with https://github.com/scionproto/scion/pull/4217.
- The drkey configuration for the CS.
- Adding initiators for DB backends + defaults.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/4227)
=> drkey: add config for control

daemon/drkey/BUILD.bazel, daemon/drkey/client_engine.go
This PR is the 10th in a series of PRs that add support for DRKey started with https://github.com/scionproto/scion/pull/4217.
-  The DRKey client engine for the daemon. It encompasses the logic for managing/requesting Lvl2/3Keys
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/4232)
=> drkey: add daemon client engine

daemon/internal/servers/BUILD.bazel, daemon/internal/servers/grpc.go
This PR is the 12th in a series of PRs that add support for DRKey started with https://github.com/scionproto/scion/pull/4217.
- implementation for DRKey gRPC methods in the daemon service
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/4234)
=> drkey: daemon grpc RPC methods implementation

pkg/grpc/BUILD.bazel, pkg/grpc/dialer.go
This PR removes the dependency to the `grpc/balancer/roundrobin` package.
The use of the `roundrobin` package is deprecated and is removed in a future version of the `grpc` package.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/4237)
=> grpc: remove roundrobin dependency from dialer.go

daemon/BUILD.bazel, daemon/config/config.go, daemon/daemon.go, pkg/daemon/BUILD.bazel, pkg/daemon/daemon.go, pkg/daemon/grpc.go, pkg/daemon/mock_daemon/BUILD.bazel, pkg/daemon/mock_daemon/mock.go
This PR is the 14th in a series of PRs that add support for DRKey started with https://github.com/scionproto/scion/pull/4217.
- Daemon API calls
- Config for daemon
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/4238)
=> drkey: add daemon api + daemon config

scion/cmd/scion/ping.go
Correct the behavior of the `--max-mtu` flag for `scion ping`.
Previously, there was a bug where the calculated payload size was ignored and the value from `--payload-size` was taken.
In most cases, this would be the default.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/4250)
=> cmd/scion: set payload size appropriately if --max-mtu is set

private/segment/segfetcher/pather.go
Include the error when debug logging that path segment fetching failed. Used to always log a nil error (wrong error variable).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/4258)
=> segfetcher: log fetch error

doc/protocols/scion-header.rst, pkg/slayers/scion.go, pkg/slayers/scion_test.go
The maximum for the representable value for HdrLen was incorrectly documented as 1024 bytes, but it is 255*4 == 1020 bytes.
Add sanity checks for the header length (which in essence are checks for the path length) when serializing the SCION header, to avoid silently creating malformed packets.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/4259)
=> doc, slayers: correct maximum for HdrLen

README.md, doc/contribute.rst
Add shared invite link to allow anyone to join our slack workspace without additional interaction to ask for an invitation.
The invitation link can be used by up 400 people and is set to never expire. In case of misuse, the link can be deactivated.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/4260)
=> doc: shared invite link to join scionproto slack

tools/wireshark/scion.lua
The MAC for the SHA1-AES-CBC algorithm starts at an offset of 32 bytes.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/4289)
=> tools: fix wireshark dissector SPAO MAC offset

router/dataplane.go, tools/braccept/cases/BUILD.bazel, tools/braccept/cases/scmp_invalid_hop.go, tools/braccept/cases/scmp_traceroute.go, tools/braccept/main.go
Similar to the existing checks for segment switching, add checks for the
case in which the router forwards a packet along a single segment. This
check only allows child-to-parent, parent-to-child, and core-to-core
combinations, as well as packets coming from an internal interface
(peering links are not yet considered).
This explicit check ensures valley-free forwarding, even if an attacker
knows all AS hop keys.
Invalid hops result in an SCMP Error message with type `Parameter
Problem` and code `Invalid Path`.
Add new braccept cases for the invalid hops child-to-child and
parent-to-parent. Additional cases would be child-to-core and
core-to-child, but these cannot be checked in the current braccept
framework.
Adapt existing braccept case SCMPTracerouteEgress, where a child-to-peer
hop was …
=> router: add checks for intra-segment forwarding

pkg/log/wrappers.go
I saw that even if the log level is info a call to log.Debug(...) requires on my system 135ns because convertCtx() is executed before checking the log level. Therefore I added a check to the log.Debug(...) function. With the help of the following benchmark tests I was able to reduce the execution time from 135ns to 30ns.
func BenchmarkLog(b *testing.B) {
err := log.Setup(log.Config{Console: log.ConsoleConfig{Level: "info"}})
assert.NoError(b, err)
for i := 0; i < b.N; i++ {
log.Debug("hello world", "i", i)
}
}
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/4304)
=> pkg/log: improve performance of log.Debug()

.golangcilint.yml, dispatcher/underlay.go, gateway/pktcls/cond_test.go, pkg/slayers/scmp.go, pkg/slayers/scmp_test.go, pkg/slayers/slayers_test.go, pkg/slayers/udp.go, router/dataplane.go, tools/braccept/cases/bfd.go, tools/braccept/cases/child_to_child_xover.go, tools/braccept/cases/child_to_internal.go, tools/braccept/cases/child_to_parent.go, tools/braccept/cases/internal_to_child.go, tools/braccept/cases/jumbo.go, tools/braccept/cases/onehop.go, tools/braccept/cases/parent_to_child.go, tools/braccept/cases/parent_to_internal.go, tools/braccept/cases/scmp_dest_unreachable.go, tools/braccept/cases/scmp_expired_hop.go, tools/braccept/cases/scmp_invalid_hop.go, tools/braccept/cases/scmp_invalid_ia.go, tools/braccept/cases/scmp_invalid_mac.go, tools/braccept/cases/scmp_invalid_pkt.go, tools/braccept/cases/scmp_invalid_segment_change.go, tools/braccept/cases/scmp_invalid_segment_change_local.go, tools/braccept/cases/scmp_traceroute.go, tools/braccept/cases/scmp_unknown_hop.go, tools/braccept/cases/svc.go, tools/pktgen/cmd/pktgen/main.go
Change parameter for slayers.UDP/SCMP.SetNetworkLayerForChecksum to *slayers.SCION, from previously gopacket.Layer. Remove error from signature, as explicit type check is no longer needed.
Note that in the gopacket/layer.UDP and TCP layers, SetNetworkLayerForChecksum takes a generic gopacket.Layer for because it accepts either IPv4 or IPv6.
There is no reason to keep this for the slayers layers, there is no common interface covering this functionality.
Cleanup exceptions for errcheck in golangci-lint: removed all files that use SetNetworkLayerForChecksum from exception list, assuming that not checking the return code of this function was the errcheck violation.
Fix various small other errcheck issues in these files; in particular, one frequent case was to explicitly ignore the error from …
=> slayers: type-safe SetNetworkLayerForChecksum

.buildkite/pipeline-doc.yml, .buildkite/pipeline.sh, .buildkite/pipeline.yml, .buildkite/pipeline_lib.sh
Run short pipeline with only documentation linting for PRs that only touch documentation.
Replaces previous manual mechanism based on a `[doc]` tag in the commit comment.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/4302)
=> ci: doc pipeline for doc-only PRs

.golangcilint.yml, pkg/private/serrors/errors.go, pkg/private/serrors/errors_test.go, private/segment/seghandler/storage.go, private/segment/seghandler/storage_test.go, private/storage/db/sqler.go
Check returned error of tx.Rollback where this had previously just been a `defer tx.Rollback`. The errcheck linter (rightly) complains about this. The Rollback was previously also be called after a successful commit, in which case it would have returned the error `ErrTxDone`. Now, Rollback is only called in error cases.
Not fixed the `defer tx.Rollback` pattern in colibri code, as this appears to be pretty much dead code by now.
Add a `serrors.Join` helper function to make it easier to return multiple potential errors. This API is modeled closely after `errors.Join`, which will be available in the go standard library in the next release (go 1.20).
- - - …
=> db: check tx.Rollback error / serrors: add Join

.github/CODEOWNERS
Add CODEOWNERS file. For details about the file format, see https://help.github.com/articles/about-codeowners/
The overall owner over the implementation is the SCION Association's Technical Committee Implementation, represented as @scionproto/scion-core-team. Note that the CODEOWNERS file does not contain a '*' pattern to specify this, as this would notify the entire core team by default. Instead, we only define owners for specific modules that require particular attention.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/4306)
=> github: add codeowners

control/beaconing/extender_test.go, pkg/segment/seg.go, pkg/segment/seg_test.go
During creating the signed protobuf body for an ASEntry in PathSegment.AddASentry, a reference to a member of the loop variable (`peer.HopField.MAC[:]`) was stored into newly created protobuf PeerEntries. As a result, all protobuf PeerEntries ended up with the same Mac buffer reference.
Fixed by the usual `peer := peer`.
Add tests for the case of multiple peers, both on the beacon extender and the path segment level.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/4315)
=> seg: fix AddASEntry with multiple PeerEntries

private/svc/BUILD.bazel, private/svc/internal/ctxconn/ctxconn.go, private/svc/internal/ctxconn/ctxconn_test.go, private/svc/resolver.go, private/svc/resolver_test.go
When performing a service address resolution with `svc.Resolver.LookupSVC`, a new connection was opened but never closed.
One possible reason for this bug was that the unclear responsibility for closing the connection; the `svc.RoundTripper.RoundTrip` function closes the connection if the context ends, but not otherwise.
Fix this by always closing the conn in `CloseConnOnDone`.
The cancel function of `CloseConnOnDone` now also blocks until the connection is closed (relevant mostly for testing) and returns any errors from closing.
Also move the `CloseConnOnDone` to `LookupSVC`, so the responsibility for closing the connection is right next to where it's opened.
- - - …
=> control: close connection in SVC resolver

pkg/spao/BUILD.bazel, pkg/spao/mac.go, pkg/spao/mac_test.go
PR #4300 will enable the use of SPAO also for AS internal communication. This PR then implements support for empty path values as inputs for the SPAO MAC computation.
The additional type switch case contains the struct type instead of the pointer type because the snet path method Empty.SetPath sets an empty path struct value as the path of the provided SCION layer.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/4317)
=> pkt/spao: support empty path value as input for SPAO MAC computation

pkg/spao/mac.go, pkg/spao/mac_test.go
The length of the SCION header is part of the metadata flowing into the computation of the MAC value for SPAO [0]. The corresponding common header field value is stored in multiples of 4-bytes [1].
This PR makes sure that indeed multiples of 4-bytes are used instead of the actual length in bytes of the SCION header.
The problem did not appear in testing up till now, because all endpoints are based on the same implementation so far.
[0] https://docs.scion.org/en/latest/protocols/authenticator-option.html#authenticated-data
[1] https://docs.scion.org/en/latest/protocols/scion-header.html#common-header
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/4318)
=> pkt/spao: Fix computation of header length metadata item

acceptance/topo_common/topology.json, acceptance/topo_cs_reload/testdata/topology_reload.json, acceptance/topo_daemon_reload/testdata/topology_reload.json, control/beaconing/testdata/topology-core.json, private/topology/interface.go, private/topology/json/BUILD.bazel, private/topology/json/json.go, private/topology/json/json_test.go, private/topology/json/testdata/topology-deprecated-attrs.json, private/topology/json/testdata/topology.json, private/topology/mock_topology/mock.go, private/topology/reload.go, private/topology/testdata/core.json, private/topology/topology.go, private/topology/topology_test.go, private/topology/validator.go, private/topology/validator_test.go, router/control/testdata/topology.json, tools/topology/config.py, tools/topology/go.py, tools/topology/topo.py
Deprecate unused attributes `authoritative`, `voting` and `issuing` from the topology.json configuration. These are no longer considered by any service or tool and the functionality has been moved into the cs.toml (containing a `[ca]` section for "issuing" ASes) or into the TRC and the configuration of the corresponding tooling.
Only the `core` attribute option remains. In the long run, this should either disappear entirely from the topology configuration or be changed to a boolean flag.
In the internal `private/topology`, remove the unused `CA() bool` from the interface, and simplify the representation of the state from a list of attributes to a simpler `IsCore`.
The goal here is mainly to avoid confusion caused by the unused attributes.
- - -
This change is [<img …
=> topology: deprecate unused attributes

scion.sh
Thanks to @matzf and its suggestions, I fixed a bug at line 58 of the scion.sh file. It was giving a "too much colons" error when finding an IPv6 address instead of IPv4, in the scion local topology. The problem was about trying to add a port number to an IPv6  address
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/4341)
=> scion.sh: fix IPv6 address bug in sciond-addr subcommand

router/dataplane.go, router/dataplane_test.go, router/export_test.go
There is a small number of of packet processing test cases that cover cases resulting in SCMPs.
The packet processor signals SCMPs by returning an `scmpError`. Previously, the test cases just asserted that any error is returned from processing and so they would pass even if an internal error occurred. In this instance there was an internal error while serializing the SCMP message, as the internal IP of the dataplane, the source address of the SCMP message, was not initialized in the test setup.
Add a dummy internal IP address to the test dataplane setup, and change the type of the dataplane's internal IP so that a missing initialization of the IP leads to a panic instead of a runtime error.
Assert that an `scmpError` is returned for the relevant test cases, and check the SCMP type/code. …
=> router: fix minimal SCMP checks in dataplane tests

doc/dev/dependencies.rst
Found a couple grammar errors with past/present tense and capitalizing the nouns, very simple and minimal modifications.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/4349)
=> doc: fix grammar in dependencies.rst

pkg/drkey/generic/generic.go, pkg/drkey/protocol.go, pkg/drkey/specific/specific.go, pkg/slayers/scion.go, pkg/slayers/scion_test.go, pkg/spao/mac.go
Both decoding and serializing of the address type fields (DstAddrType and SrcAddrType) was truncating the most significant bit. This has not caused any issues so far as no address type with type greater than 1 is defined and used.
This bug was introduced in #4160, by consistently using the wrong (!) value 0x7, instead of 0xF, to mask the lowest four bits. Fixed the same mistake in copies of the serialization logic.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/4352)
=> slayers: fix decoding and serializing wide DT/ST

private/app/flag/env.go, scion/cmd/scion/showpaths.go, scion/showpaths/config.go
The Daemon was called Deamon in some places. This commit fixes that.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/4354)
=> fix spelling of Daemon

doc/dev/design/EPIC.md
Hi there,
just a small fix cause I am getting annoyed over having to fix the link manually all the time.
Current Link goes to a PR for a COLIBRI design document instead of EPIC.
Best Regards
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/4358)
=> doc: fix link to EPIC-HP design doc

doc/beacon-metadata.rst, doc/conf.py, doc/control-plane.rst, doc/cryptography/ca-operations.rst, doc/cryptography/drkey.rst, doc/glossary.rst, doc/manuals/common.rst, doc/manuals/control.rst, doc/manuals/control/http-api.rst, doc/manuals/router.rst, doc/manuals/router/http-api.rst, doc/overview.rst, doc/protocols/scion-header.rst, doc/requirements.in, doc/requirements.txt
Add a conceptual description of the control plane and a reference manual for the control service.
The control plane description is mostly based on the [IETF SCION control plane specification draft](https://www.ietf.org/archive/id/draft-dekater-scion-controlplane-00.html).
The reference manual for the control service describes the many command line flags, environment variables, configuration files and APIs. This documentation highlights a variety of usability shortcomings, redundancies and inconsistencies that should be addressed eventually.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/4361)
=> doc: control service manual

scion/ping/ping.go
Wait for the ping sender go routine to terminate before we return the stats. With bad luck, the receiver go routine receives all the replies before the sender go routine has terminated. Because only the sender go routine increments the stats.Sent count at the end, we can end up with wrong stats that claim more packets were received then sent.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/4392)
=> scion/ping: wait for send go routine to terminate

acceptance/router_multi/test.py, demo/file_transfer/tc_setup.sh, doc/dev/testing/buildkite.rst, tools/env/rhel/pkgs.txt
Fixes for update of buildkite elastic stack to v6.7.1.
Update package "rhel" dependency list for Amazon Linux 2023:
- `bridge-utils`: no longer available. Replace deprecated `brctl` with iproute2's `bridge`
- `moreutils`: no longer available, not used
- `sqlite3`: no longer available, not used
- `ethtool`: required for router_multi test, seems to have previously been installed by default.
For the router_multi test, set the default TTL to 64, so that the packets sent back by the router match the expected value. This is the default value on many other systems, so we did not previously need to worry about this.
The value is only set in a net-namespace, so we don't need to worry about resetting it.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" …
=> ci: fixes for updated buildkite elastic stack version 

acceptance/cert_renewal/test.py, acceptance/common/base.py, acceptance/common/topogen.bzl, acceptance/hidden_paths/test.py, tools/BUILD.bazel, tools/await-connectivity
These tests have become even more flaky with the updated CI runners; it seems that this is triggered due to using the significantly quicker docker-compose v2.
Use the existing await-connectivity script to determine when a test can safely start to run, instead of sleeping for arbitrary number of seconds.
Closes #4301
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/4399)
=> acceptance: de-flake cert_renewal and hidden_paths

control/beaconing/BUILD.bazel, control/beaconing/extender.go, control/beaconing/extender_test.go, control/beaconing/originator_test.go, control/beaconing/propagator_test.go, control/beaconing/writer_test.go, control/cmd/control/main.go, control/mgmtapi/testdata/TestAPI_beacon, control/mgmtapi/testdata/TestAPI_beacon_id_prefix, control/mgmtapi/testdata/TestAPI_beacons, control/mgmtapi/testdata/TestAPI_beacons_descending_order, control/mgmtapi/testdata/TestAPI_beacons_existing_usages, control/mgmtapi/testdata/TestAPI_beacons_sort_by_ingress_interface, control/observability.go, control/tasks.go, pkg/experimental/hiddenpath/beaconwriter_test.go, pkg/segment/seg.go, pkg/slayers/path/hopfield.go, pkg/slayers/path/hopfield_test.go, private/app/appnet/intra_as.go, private/mgmtapi/segments/api/testdata/segments-by-id.json, private/path/combinator/expiry_test.go, private/path/combinator/graph.go, private/segment/segfetcher/pather.go
Update the `beaconing.DefaultExtender` to not create Segments with expiration date that is later than the current AS certificate expiration.
Instead the extender uses `min(segmentExpiration,certificateExpiration)` when creating an AS Hop.
Contributes to #4286
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/4369)
=> cppki: limit segment expiration by certificate lifetime

.readthedocs.yaml, doc/Makefile, doc/control-plane.rst, doc/manuals/common.rst, doc/manuals/control.rst, doc/manuals/router.rst, doc/protocols/authenticator-option.rst
- add missing documentation for `remote_interface_id` in `topology.json` for peering links (fix-up for #4390)
- fix duplicate envvar documentation in router.rst and control.rst (envvars can only have one definition in rst), and expand the description (fix-up for #4300). Consistent  formatting for envvar documentation.
- fix references in SPAO doc
- enable fail-on-warning for read-the-docs builds: this makes PR fail the the read-the-docs check if there are build warnings. Also enable the same build flags in the Makefile for local documentation builds.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/4416)
=> doc: touch up manuals, enable fail-on-warning for docs

acceptance/router_multi/conf/br.toml, doc/manuals/router.rst, private/env/features.go, router/cmd/router/main.go, router/dataplane.go
The experimental implementation of DRKey-based authentication for SCMP messages is incomplete and, in the current form, not practically useful. Add a feature flag to explicitly opt-in to the experimental SCMP authentication in the router.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/4418)
=> router: feature toggle for experimental SCMP authentication

control/cmd/control/main.go, daemon/cmd/daemon/main.go, doc/manuals/control.rst, private/trust/config/BUILD.bazel, private/trust/config/config.go
The `trustengine.cache.expiration` configuration option would accept durations as number of nanoseconds. Most likely, this was accidental, all other configuration options for durations accept formatted duration strings, with unit suffix.
Change `trustengine.cache.expiration` to accept (only) formatted duration strings.
This is a potentially compatibility breaking change for existing control service configuration files.
The `trustengine.cache` configuration block is marked as experimental and is likely not widely used, so no transition mechanism is added.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/4417)
=> control: formatted duration for config trustengine.cache.expiration

pkg/snet/metrics/metrics.go
The options were not correctly passed in to `NewSCMPErrors` in `snet/metrics`. This commit fixes that.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/4423)
=> snet/metrics: use registry in snet metrics

control/cmd/control/main.go, daemon/cmd/daemon/main.go, gateway/gateway.go, go.mod, go.sum, go_deps.bzl, pkg/grpc/interceptor.go
Bump google.golang.org/grpc from 1.57.0 to 1.57.2 due to a security patch.
Skipping 1.57.1, because that contained a bug.
From vulnerability alert "gRPC-Go HTTP/2 Rapid Reset vulnerability":
> Impact
>
> In affected releases of gRPC-Go, it is possible for an attacker to send
> HTTP/2 requests, cancel them, and send subsequent requests, which is
> valid by the HTTP/2 protocol, but would cause the gRPC-Go server to
> launch more concurrent method handlers than the configured maximum
> stream limit. Patches
>
> This vulnerability was addressed by #6703 and has been included in patch
> releases: 1.56.3, 1.57.1, 1.58.3. It is also included in the latest
> release, 1.59.0.
>
> Along with applying the patch, users should also ensure they are using
> the grpc.MaxConcurrentStreams server option to …
=> deps: bump google.golang.org/grpc, set MaxConcurrentStreams

proto/daemon/v1/daemon.proto
This was probably an oversight in #4005.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/4443)
=> daemon: fix docstring for latencies in protobuf file

scion.sh
The `supervisorctl shutdown` command does not block for the supervisor or its child processes to terminate.
This can occasionally lead to situations where SCION processes were still running after the `scion.sh stop` command returned. In the CI system, which immediately proceeds to bundle up the log files, this led to `tar` reporting an error that the log file was still being written to (e.g. [here](https://buildkite.com/scionproto/scion-nightly/builds/1895#018bfa57-7ab1-4f15-9b7f-ed511ebb783d/2886-2888)).
Fixed by invoking `supervisorctl stop all`, which does block, to terminate all child processes before `shutdown`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/4445) …
=> scion.sh: block for child processes at shutdown

pkg/private/processmetrics/processmetrics_linux.go
When building SCION in a VM on my MacBook, I got an error about mismatched types:
```
pkg/private/processmetrics/processmetrics_linux.go:127:17: invalid operation: newCount != c.lastTaskCount (mismatched types uint32 and uint64)
pkg/private/processmetrics/processmetrics_linux.go:133:21: cannot use newCount (variable of type uint32) as uint64 value in assignment
```
This modification doesn't change the behavior on amd64 but makes SCION compile also for arm64.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/4446)
=> processmetrics: explicit type conversion to support arm64

tools/install_bazel
Bazel and bazilisk do support ARM64 by now. Unfortunately, I get an error when building `//:scion-ci`, but building `//:scion` works perfectly (after applying #4446). So I suggest to lift the restriction on AMD64 and, while we're at it, update bazelisk to the latest version.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/4447)
=> bazel: update bazelisk and support arm64

pkg/metrics/prometheus.go
When copying metric labels we assumed that `append` will always create a copy of the label array. This is not necessarily the case. In such case two metrics may end up with the same underlaying array of labels and change to one of them also overwrites the labels in the other one.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/4450)
=> prometheus: fix copying of metrics labels

daemon/internal/servers/grpc.go
I found a bug in the SCION daemon. If you create a SCION daemon connection and call one of the drkey endpoints without first setting the configuration value "drkey_level2_db.Connection" to something meaningful, the SCION daemon will encounter an error like that and crash:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xb82d33]
```
This bug can easily be reproduced by running a code snippet like this for a SCION daemon that has no drkey configured:
```
sd, _ := daemon.NewService(daemonAddr).Connect(ctx)
sd.DRKeyGetASHostKey(ctx, drkey.ASHostMeta{})
```
The problem is that in the file "daemon/internal/servers/grpc.go", when the drkey endpoints are called, DaemonServer.DRKeyClient is nil if it is not …
=> daemon: error out when using drkey endpoints without configured drkey

pkg/log/context.go
log.FromCtx could panic if a custom Logger was used and a span was present in the context. This commit allows the custom logger to implement the `WithOptions(...zap.Option) Logger` method so that the CallerSkip can still be applied. In case the logger can't be casted to anything the caller skip is not applied, but we also don't panic anymore.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/4452)
=> pkg/log: fix panic when using custom Logger

.buildkite/pipeline_lib.sh, acceptance/router_benchmark/test.py, router/config/config.go
In the router. Compute a better default for the number of processors based on multiple observations: given enough streams to occupy all processors, performance is degraded if there are as many processors as cores. Best performance is obtained by setting aside two cores for other tasks. Making this the default simplifies the benchmarking process by not having to configure an override for each type of target machine being tested.
In the benchmark. Run the test with many streams. It reflects reality and allows a very parallel router to perform at its best without distorting the performance of a less-parallel one. Make sure that the number of streams is likely to be a multiple of the number of cores so the cores are loaded evenly in spite of there being typically fewer streams than in real …
=> router: make the benchmark and the router more adaptive to core count

.buildkite/hooks/pre-command, .buildkite/pipeline.yml, .buildkite/pipeline_lib.sh, .gitignore, Makefile, README.md, dist/BUILD.bazel, dist/conffiles/dispatcher.toml, dist/conffiles/sciond.toml, dist/conffiles/sig.json, dist/conffiles/sig.toml, dist/debian/scion.postinst, dist/git_version.bzl, dist/package.bzl, dist/platform.bzl, dist/systemd/scion-control@.service, dist/systemd/scion-daemon.service, dist/systemd/scion-dispatcher.service, dist/systemd/scion-ip-gateway.service, dist/systemd/scion-router@.service, dist/test/BUILD.bazel, dist/test/Dockerfile, dist/test/README.md, dist/test/deb_test.sh, doc/dev/build.rst, doc/dev/setup.rst, doc/index.rst, doc/manuals/install.rst, nogo.json, private/mgmtapi/api.bzl
Build debian packages for amd64, arm64, i386 and armel.
- There are separate packages for router, control, daemon, dispatcher, gateway and tools (scion and scion-pki).
- The packages include systemd unit files to run the services. For the daemon, dispatcher and gateway one instance per host is supported by the systemd service, and a default configuration file is included. For router and control, multiple instances per host are supported, and as a consequence of this, no default configuration file is provided.
- Currently, there is no man page contained in the packages. We should be able to build these from our existing manuals, but it seems to require a significant amount of fiddling to get something useful.
Building the .deb packages uses bazel with `rules_pkg`.
The target …
=> dist: build debian packages for multiple platforms

tools/wireshark/scion.lua
Dissecting TLV options crashes the wireshark plugin, if the `data` field is empty. This happens always for Pad1 options and for PadN options if `data_len` is 0.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/4458)
=> tools: fix wireshark dissector TLV options without data

doc/dev/testing/buildkite.rst
Documenting that we've bumped the buildkite instance type from t3 to m6i.
The main reason for the switch is that the "burstable" nature of the t*-instances makes them extremely unsuitable for running benchmarks. The m6i are also much faster, but not much more expensive.
Also, the agent pool is now at most 6 agents. Spinning up 10 agents and having to warm up all the caches, and then scaling back in after a single build, seemed excessive.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/4459)
=> doc: update buildkite instance type

control/beaconing/BUILD.bazel, control/beaconing/extender.go, control/beaconing/writer_test.go, control/cmd/control/main.go, pkg/experimental/hiddenpath/beaconwriter_test.go, private/trust/signer.go
Make the segment signer pluggable. This decouples the beacon extender from the trust signer implementation and allows plugging in different implementations.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/4460)
=> control: pluggable segment signer

doc/tutorials/deploy.rst
It seems like this is a typo, since this subnet is not established anywhere else in the document
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/4466)
=> doc: fix subnet typo in deploy tutorial 10.0.1.x -> 10.0.0.x

doc/tutorials/deploy.rst
Fix copying of certificates to individual hosts in the "freestanding deployment" tutorial.
Was suggesting to copy all certificates to `/etc/scion/crypto/`. Instead, it should copy the AS certificates to `/etc/scion/crypto/as/`.
Originally the instructions had been correct; the problem was introduced with the custom script to generate the crypto material. This script uses flatter paths (for brevity) than the originally used `scion-pki testcrypto` tool, and the copy instruction were not correctly updated (and not tested, duh).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/4467)
=> doc: fixup certificate copying in deploy tutorial

pkg/slayers/path/scion/BUILD.bazel, pkg/slayers/path/scion/base.go, pkg/slayers/path/scion/decoded.go, pkg/slayers/path/scion/decoded_test.go, pkg/slayers/path/scion/raw_test.go, router/dataplane_test.go
Added unit test for deserialization and unit test for router ingress.
Fixes #4482
=> paths: Add check for hopfield count <= 64 when deserializing a scion path

pkg/slayers/path/scion/decoded.go
`Decode.Reverse` seems to have a loop where one isn't needed. For the loop that I changed, there is at most one iteration (the original value of `i` is 0 and the original value of `j` is at most 2; after one iteration, the loop condition will always be broken). Besides being harder to read, it is also harder to reason about and this complicates our proofs and maintenance in the VerifiedSCION project.
To preserve the behaviour that stores on slices and arrays are only performed when `s.NumINF` is at least 2, I added an if statement. If you prefer, we can drop that as well.
=> pkg/slayers: simplify Decoded.Reverse

doc/tutorials/deploy.rst
We had another situation where users were confused about the difference of endhost vs AS. It seems that it was caused by this tutorial which could be clarified regarding it's intention and that the acronym AS used in SCION really refers to "Autonomous System" as used in inter-domain networking..
=> doc: clarify tutorial description

private/env/logging.go
This PR tries to remove a Linux-only dependency for running SCION applications of other platforms. The `RunsUnDocker()` method is the Linux-only call, thus we check whether we are running in Docker only in Linux platform. I am in favor of even removing this log line, supporting @matzf comment on https://reviewable.io/reviews/scionproto/scion/4344#-Nt_IGRG4RbvC-PCVToV.
=> private/env: remove RunsInDocker during startup log

scion-pki/trcs/sign_test.go
Add `--rm` to docker run invocation, to remove the container after it finishes and so avoid littering the system with stopped containers.
=> test: cleanup docker in scion-pki TestOpenSSLCompatible

tools/lint/python/BUILD.bazel, tools/lint/python/flakelint.py
Fix flake8 bazel integration after updating from version 3.8.4 to 7.0.0. While the linter was running and working, it always returned a zero exit code, making bazel think everything is ok.
This problem was caused by our wrapper script, flakelint.py, and a change in the internal API. `cli.main` no longer sets/raises the exit code, this is done by the caller now.
See https://github.com/PyCQA/flake8/commit/81a4110338496714c0bf2bb0e8dd929461d9d492
To fix this, and avoid similar issues in the future, replace the wrapper script with an "entry_point" declaration. This serves the same purpose of creating a runnable bazel target for flake8. I assume that this was not already done when creating this flake8 integration, because either this entry_point mechanism did not yet exist or it was just too …
=> lint: fix flake8 bazel integration after update

router/dataplane.go, tools/braccept/cases/scmp_unknown_hop.go, tools/braccept/main.go
A packet received on the internal interface would previously be "bounced" to the responsible egress router.
This is forbidden in the SCION design and was an accidental mis-feature of the processing logic.
Fixes #4497
=> router: forbid bouncing packets internally

router/BUILD.bazel, router/dataplane.go, router/dataplane_internal_test.go, router/fnv1aCheap.go
=> router: optimize computeProcID

.buildkite/hooks/pre-command, .buildkite/pipeline.yml, dist/openwrt/ipk.bzl, tools/bazel-build-env
Fix handling of release version (e.g. "0.11.0") in openwrt package build. Was only working for intermediate versions, like "0.10.0-32-asdlkjslka".
Fix variable interpolation issue for package builds; need to use `$${version}` to ensure interpolation of this variable at "runtime" with bash; otherwise buildkite attempts to interpolate with when creating the pipeline jobs. See https://buildkite.com/docs/pipelines/environment-variables#runtime-variable-interpolation.
Allow overwriting the version used for the builds consistently. Previously there was an envar GIT_VERSION that could do this partially. Renamed to SCION_VERSION and supported now also fully for the package builds. Setting this variable in buildkite pipelines should now allow, for example, building release builds before explicitly …
=> ci: fix build for openwrt package, enable setting version from env var

.buildkite/hooks/pre-command, .buildkite/pipeline.yml
Previously the artifacts had static, generic names. This has always felt a bit clumsy, as downloading artifacts from multiple builds with a browser would usually result in automatically deduplicated file names like `scion(5).tar`.
After learning how the buildkite agent can interpolate variables in the pipeline during the pipeline upload (https://buildkite.com/docs/pipelines/environment-variables#variable-interpolation), it seems easy to improve this.
Now the artifacts include the version, matching the name of the artifacts in releases.
=> ci: include build version in file name of build artifacts

doc/dev/design/index.rst, doc/dev/design/router-port-dispatch.rst
Design document for proposal #3961.
[doc]
---
In a separate PR, once this is merged, I will attempt to improve the organisation of these design documents and add a template.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/4280)
=> doc: design doc for end host without dispatcher

.bazelrc, doc/command/scion-pki/scion-pki_certificate_renew.rst, doc/command/scion/scion_address.rst, doc/command/scion/scion_ping.rst, doc/command/scion/scion_showpaths.rst, doc/command/scion/scion_traceroute.rst
Run `bazel run //:write_all_source_files` to fix up generated documentation after removing the dispatcher flag from scion/scion-pki binaries.
This was missed during the PR because the existing check for this was not active in the CI. Extend the bazel configuration `test:lint` to enable running this in `make lint`.
=> doc: fixup generated documentation files after removing dispatcher flags

doc/dev/setup.rst
Setup documentation contained wrong path of bazel binary.
=> doc: fix bazel bin path in setup instructions

doc/dev/design/index.rst, doc/dev/design/scmp-authentication.rst, doc/manuals/router.rst, doc/protocols/scmp.rst
The SCMP "specification" document described support for SCMP as mandatory. Furthermore, it mandates the use of SPAO+DRKey authentication for SCMPs. This does not correspond to what is currently implemented. SCMP support has been treated as at least semi-optional e.g. in discussions around the dispatcher-less end host stack.
Regarding the authentication, there is no full implementation of this neither in router (support in "our" router is experimental/demo-level, no other router implementation supports it at all) nor in end hosts (currently, nothing at all). There is not sufficiently clear consensus around this to pretend that we'll realize this ambition shortly.
Update the documentation specs to reflect this reality. Move the SCMP authentication description into a design document.
Closes …
=> doc: clarify SCMP reality vs. ambition

tools/topogen.py, tools/topology/config.py, tools/topology/defines.py, tools/topology/net.py
The argument `-n` or `--network` in [topogen.py](https://github.com/scionproto/scion/blob/9d52e2f8d2211427707dfe5b4028158759ebddeb/tools/topogen.py) is ignored when generating a topology, the default network is always used.
There exists no argument for the user to specify a different IPv6 network with respect to the default one.
I have added the argument `-n6` or `--network-v6` which is the IPv6 version of the `--network` argument.
I moved for consistency the variables like `DEFAULT_NETWORK` from [net.py](https://github.com/scionproto/scion/blob/9d52e2f8d2211427707dfe5b4028158759ebddeb/tools/topology/net.py) to [defines.py](https://github.com/scionproto/scion/blob/9d52e2f8d2211427707dfe5b4028158759ebddeb/tools/topology/defines.py) where the IPv6 network defines are already present.
=> tools: topogen: Fix network argument. Added IPv6 network argument.

acceptance/topo_cs_reload/testdata/cs.toml, control/config/config.go, private/env/env.go, private/env/sample.go
And the type `env.QUIC`, as it's also unused.
Also relates to #2810 
Closes #2810
=> Remove unused QUIC config field from CS

.github/CODEOWNERS, doc/dev/contribute.rst, doc/dev/testing/buildkite.rst
JC has been appointed to the TC Implementation by the SCION Association Board on 21.5.2024, replacing matzf.
Remove matzf from CODEOWNERS, and other docs.
=> doc: add Jean-Christophe to list of TC members

doc/tutorials/deploy.rst, doc/tutorials/deploy/topology1.json, doc/tutorials/deploy/topology2.json, doc/tutorials/deploy/topology3.json, doc/tutorials/deploy/topology4.json, doc/tutorials/deploy/topology5.json
Update link to download v0.11.0 packages.
Update topology.json files:
- Use simpler "local" address configuration without explicitly binding to a specific local IP.
- Use hostnames for remote hosts to avoid having to explicitly patch the placeholder IP addresses in the topology files.
=> doc: update deploy tutorial to release v0.11.0

WORKSPACE, licenses/data/coreutils_linux_amd64/LICENSE, private/mgmtapi/tools/package.json, private/mgmtapi/tools/pnpm-lock.yaml
Updated tooling allows to use lockfile version 9 in pnpm-lock.yaml. We've recently seen that dependabot PRs for dependency updates seem to create lock files with that lockfile version; as the tooling did not support it, the dependabot changes could not be used. Plausibly, dependabot PRs will work after this change.
Note that pnpm cannot be upgraded to the very latest version 9.5.0, as this needs to be explicitly enabled in aspect_rules_js first.
Note that I've explicitly "downgraded" the nodejs node_version to the default version used in the previous rules_nodejs version. The default version of the current rules_nodjs version requires a too new glibc for my ancient setup.
This might be hard to review manually because of all the formatting changes in pnpm-lock.yaml.
Comparing only the …
=> build: update rules_js and pnpm version

go.mod, go.sum, go_deps.bzl, private/revcache/BUILD.bazel, private/revcache/memrevcache/BUILD.bazel, private/revcache/memrevcache/memrevcache_test.go, private/revcache/revcache.go, private/revcache/revcachetest/BUILD.bazel, private/revcache/revcachetest/revcachetest.go, private/revcache/util.go, private/revcache/util_test.go
Remove use of goconvey from private/revcache, replacing it with the default go testrunner with subtests and stretchr/testify/assert.
Remove some unused functions instead of updating their tests.
Completely aside: change NewKey to return a Key by value instead of a reference. It is used as value everywhere and it just hurt my eyes.
Fixes #3016
=> revcache: remove goconvey

tools/braccept/cases/BUILD.bazel, tools/braccept/cases/malformed_path.go, tools/braccept/main.go
Add test cases for checks added in #4556;
- invalid (non-peer) segments with a single hop field
- hop field pointer not pointing into current segment
=> router: add test cases for malformed paths

.github/workflows/pr-title.yml
Github workflow to check that the PR title follows the contribution guidelines:
- Starts with `<subsystem>:`
- Uses lowercase letters for subject line (and does not end with a period)
Could also be done in buildkite, but github action seems appropriate.
=> github: add check for PR title

BUILD.bazel, Makefile, tools/update_testdata.sh
Just a tiny, random cleanup; I've noticed to obtain the effective go tags in the Makefile and scripts, instead of building a dummy target ":dummy_setting" we can also use the bazel info subcommand.
=> build: replace dummy build target with bazel info

router/dataplane.go, router/dataplane_internal_test.go, router/export_test.go
The "running" flag is now accessed as an atomic (so with sequential ordering per the Go memory model). Added a shutdown entry point which cannot race with initialization.
Fixes #4116
=> router: implement a proper shutdown mechanism

router/dataplane.go, router/dataplane_internal_test.go, router/dataplane_test.go
The check is done on the first hop for src and on the last hop for dst.
Fixes #4415
Fixes #4558
=> router: drop packets with v4 mapped v6 src/dst or unspecified dst hosts

control/beaconing/propagator.go
Include the beacon ID in the propagator when logging errors. This helps the operator to easily track down the offending beacon and take appropriate action.
=> control/beaconing: include the beacon ID in the propagator

control/trust/grpc/proto.go
Currently querying for the latest TRC was not allowed, because TRC ID validation would fail. However it should be completely fine to query for the latest TRC. This commit fixes it.
=> control: allow to query for latest TRC

control/trust.go, control/trust/crypto_loader.go, daemon/cmd/daemon/main.go, private/trust/store.go, private/trust/store_test.go
This commit introduces a TRC loader that keeps track of what TRC files have already been read. By doing so we can omit duplicate work of parsing TRC files and storing them in the DB.
This applies to the control service and the daemon.
=> crypto: do not load already loaded TRC files

go.mod, go.sum, go_deps.bzl, licenses/data/at_zgo_zcache_v2/LICENSE, private/revcache/memrevcache/BUILD.bazel, private/revcache/memrevcache/memrevcache.go, private/revcache/memrevcache/memrevcache_test.go, private/revcache/mock_revcache/mock.go, private/revcache/revcache.go, private/revcache/revcachetest/revcachetest.go, private/revcache/util.go, private/revcache/util_test.go, private/segment/segfetcher/pather.go, private/segment/segfetcher/resolver_test.go
When dealing with a lot of paths the current implementation is not optimal. Specifically filterRevoked showed up quite prominently in a pprof. See image below:
- Use a typed cache, to prevent string key conversion.
- Only support single key lookups to prevent map allocation on lookup.
Overall this even simplifies the code.
=> daemon: improve revcache performance

.buildkite/pipeline.yml, control/beaconing/originator.go, control/beaconing/originator_test.go, control/beaconing/testdata/topology-core.json, private/path/combinator/combinator_test.go, private/path/combinator/testdata/00_core_core_invalid_peering.txt, private/path/combinator/testdata/00_multi_peering.txt, private/topology/topology.go, tools/await-connectivity
=> topology: allow peering links between core ASes

private/underlay/sockctrl/BUILD.bazel, private/underlay/sockctrl/sockctrl.go, private/underlay/sockctrl/sockctrl_windows.go, private/underlay/sockctrl/sockopt.go, private/underlay/sockctrl/sockopt_windows.go
Hey all,
I  tried to build all the major SCION binaries for windows to see if it's possible to run an AS also on this platform. However, there is an issue that `syscall.GetsockoptInt` and `syscall.SetsockoptInt` have different signatures on windows than on all other platforms. One fix is to have extra windows code to support this, but I'm not sure what you prefer, so let me know if this fits or if I can do some other changes. In the end it would be great to have Windows support for all SCION services, too.
PS: The issue popped up when building the router, not sure if it affects other services.
Cheers,
Marten
=> underlay: support SockOptInt on all platforms incl Windows

router/dataplane.go
Fixes issue #4282.
With this change, the implementation of `AddLinkType` matches that of the other setters and the comment that precedes it.
=> router: make `AddLinkType` acquire the DataPlane mutex

private/tracing/context.go
When starting a span from Context add the debug_id and tracing_id to the logger on the context (if it exists) instead of creating a new one.
This preserves the logger that is attached to the parentCtx.
=> tracing: wrap existing logger instead of creating a new one

doc/command/scion-pki/scion-pki_trc_payload.rst, doc/command/scion-pki/scion-pki_trc_payload_dummy.rst, doc/command/scion-pki/scion-pki_trc_sign.rst, scion-pki/trcs/BUILD.bazel, scion-pki/trcs/payload.go, scion-pki/trcs/sign.go, tools/cryptoplayground/crypto_lib.sh, tools/cryptoplayground/trc_ceremony.sh
The dummy TRC payload allows to create a TRC payload without much setup. This is useful for testing access to the necessary cryptographic material, especially in preparation of a TRC ceremony.
=> scion-pki: support dummy TRC payload

doc/index.rst
After an offline discussion from SCION contributors, we reached the conclusion that `docs.scion.org` is the best-suited candidate to host technical information about SCION applications (ideally already in a certain maturity level) since they can be run on different environments, i.e., production network, SCIONLab or local dev environment. It may also help to centralize a little bit the information and making the documentation environment a bit less hairy for the users/developers.
~~In this PR, I ported the `Applications` section in the [SCIERA docs](https://sciera.readthedocs.io/en/latest/index.html) , adding the file  `doc/applications/access.rst` as a preliminary documentation as how to connect the application host to the diverse SCION networks.~~
We can revisit, if some of …
=> doc: update index.rst to include references to scion-application-docs

private/path/combinator/combinator.go, private/path/combinator/combinator_test.go, private/path/combinator/export_test.go, private/path/combinator/graph.go, private/revcache/util.go
A profile shows that ID calculation is a big part of the CPU time of the daemon:
Therefore this change memoizes IDs where possible.
Also re-use buffer for fingerprint calculation.
Use slices package for sorting in the combinator.
=> daemon/combinator: memoize calculated fingerprints (IDs)

doc/dev/contribute.rst, doc/dev/design/BeaconService.md, doc/dev/design/BorderRouter.rst, doc/dev/design/ColibriService.md, doc/dev/design/EPIC.md, doc/dev/design/NAT-address-discovery.rst, doc/dev/design/PathPolicy.md, doc/dev/design/PathService.md, doc/dev/design/TEMPLATE.rst, doc/dev/design/endhost-bootstrap.rst, doc/dev/design/forwarding-key-rollover.rst, doc/dev/design/grpc.rst, doc/dev/design/index.rst, doc/dev/design/router-perf-model.rst, doc/dev/design/router-port-dispatch.rst, doc/dev/design/scmp-authentication.rst, doc/dev/design/uri.rst
=> doc/design: clarify the life-cycle of a design doc and update existing accordingly

tools/topology/topo.py
Change the limit for interface IDs in topofiles from 12bit to 16bit.
=> tools: support 16bit interface IDs in topo files

doc/dev/design/router-port-dispatch.rst
The current implementation does not use the "underlay" element.
I propose to adapt the docment to reflect the current implementation
=> doc: dispatched_ports syntax

pkg/snet/udpaddr.go, pkg/snet/udpaddr_test.go
Change the snet.UDPAddr.String() method to return the address in a format that is compatible with net.SplitHostPort. This will allow non SCION aware applications to extract the host and port part without the need to understand it is a SCION address.
=> pkg/snet: format UDPAddr to comply with net.SplitHostPort

.buildkite/pipeline.yml, WORKSPACE, dist/BUILD.bazel, dist/package.bzl, dist/rpm/rpm_rules.patch, licenses/data/platforms/LICENSE
This is enabled by a pending PR to the rules_pkg project: https://github.com/bazelbuild/rules_pkg/pull/729
I just added the patch to our build while we wait for the PR to get merged.
=> build: add support for cross-compiled rpms

router/control/conf.go, router/dataplane.go, router/dataplane_internal_test.go, router/dataplane_test.go, router/export_test.go, router/mock_router/mock.go
WriteTo needs to be given the destination address explicitly. WriteBatch, on the other end, can either find it in each packet structure, or rely on the connection's destination. WriteTo is only used to send BFD packets. It turns out that BFD packets can also very easily be sent via the regular forwarders that use WriteBtach.
The motivation to do that is to simplify the interface between the dataplane and the forwarders, in view of supporting multiple underlays with possibly very different interfaces. So the channels around the processor tasks seems like a good universal interface.
In passing, also removed a duplicate field. Slightly off-topic but still in the spirit of noise abatement.
As this is to facilitate the necessary refactoring...
Contributes to #4593
=> router: small refactoring to remove the need for a batchconn.WriteTo

dist/package.bzl
Since rpmbuild v4.20, the _builddir variable is forcefully set to <chosen_builddir>/<pkg_name> (which is created if it doesn't exist). Any files that are not built/copied by the %prep% phase must be already present in <chosen_builddir>/<pkg_name>/[%buildsubdir].
pkg_rpm doesn't expect that and places the files to be packaged in <chosen_builddir>. Since %buildsubdir is not used (=="."), we compensate by setting it to "..". As a result <chosen_builddir>/<pkg_name>/[%buildsubdir] evaluates to <chosen_buildir> thereby restoring pre-4.20 behavior.
Since 4.20, debug-info rpms are built by default. We don't support or want that, so we now set "don't-do-it" explicitly.
Fixes #4653
=> build: work around issues between pkg_rpm and rpmbuild after 4.20

tools/topology/config.py, tools/topology/scion_addr.py
Local topologies (created using the scion.sh topology command) do not support ASN < 2^32. If such ASNs are written in decimal notation, validation of the ISD-ASN fails. Writing the ASN in hexadecimal also fails, because the crytographic material is generated in the wrong directory.
All that seems to be missing to support BGP ASNs is allowing the decimal format and making sure that all ASNs < 2^32 are converted to decimal format as expected by the scion-pki tool.
=> support BGP ASNs in local topologies

pkg/snet/packet_conn.go
So far, the `snet/SCIONPacketConn` was bubbling up decoding/parsing errors to the calling applications. In principle, these errors are not recoverable by the application. The current solution simulates that the network stack simply discards incorrect/malformated packets. Otherwise,some libraries/applications would misbehave (similar to what would happen if were to receive SCMP errors). If we believe that SCION-aware applications using the low-level `SCIONPacketConn` should receive the error, we can move this up to `Conn`.
=> pkg/snet: ignore decoding/parsing reading errors on SCIONPacketConn

pkg/snet/packet_conn.go
The condition was missing brackets around the IP. While at it this also simplifies the code a bit.
=> pkg/snet: fix isShimDispatcher condition

pkg/daemon/BUILD.bazel, pkg/daemon/grpc.go
Dial and DialContext is deprecated in newer version of gRPC. (See https://pkg.go.dev/google.golang.org/grpc#Dial)
=> pkg/daemon: use grpc.NewClient instead of Dial

control/cmd/control/main.go, gateway/gateway.go, pkg/daemon/BUILD.bazel, pkg/daemon/topology.go, pkg/daemon/topology_test.go, pkg/snet/conn.go, pkg/snet/packet_conn.go, pkg/snet/snet.go, private/app/path/path.go, scion-pki/certs/renew.go, scion/cmd/scion/ping.go, scion/cmd/scion/traceroute.go, scion/showpaths/showpaths.go, tools/end2end/main.go
Instead of having the snet.Topology as an interface, change it to a struct.
This makes the contract clearer, LocalIA and PortRange are only considered when
creating a connection. The Interface information however can dynamically change.
The daemon API now exposes an adapter to load the topology information once
or to load the information periodically.
=> pkg/snet: change snet.Topology to a struct

doc/dev/design/router-port-dispatch.rst
Fix typos and clarify comment on SCMP on legacy hosts.
=> doc: typos and comment on SCMP on legacy hosts

gateway/cmd/gateway/main.go
Some tests start sig in the same time as sciond and have become flaky (presumably due to ordering or timing changes in docker). This resolves it.
=> sig: retry when connecting to sciond

control/trust/grpc/BUILD.bazel, control/trust/grpc/proto_test.go, daemon/drkey/grpc/BUILD.bazel, daemon/drkey/grpc/fetching_test.go, daemon/internal/servers/BUILD.bazel, daemon/internal/servers/grpc.go, demo/drkey/BUILD.bazel, demo/drkey/main.go, go.mod, pkg/experimental/hiddenpath/grpc/BUILD.bazel, pkg/experimental/hiddenpath/grpc/discovery.go, pkg/experimental/hiddenpath/grpc/requester.go, pkg/grpc/BUILD.bazel, pkg/grpc/dialer.go, pkg/private/xtest/grpc.go, pkg/scrypto/signed/BUILD.bazel, pkg/scrypto/signed/msg.go, pkg/snet/squic/BUILD.bazel, pkg/snet/squic/net_test.go, private/trust/BUILD.bazel, private/trust/grpc/BUILD.bazel, private/trust/grpc/proto.go, private/trust/grpc/proto_test.go, private/trust/signer_test.go
- replace deprecated `github.com/golang/protobuf` with `google.golang.org/protobuf`
- replace deprecated `ptypes.TimestampProto` from `github.com/golang/protobuf/ptypes` with `google.golang.org/protobuf/types/known/timestamppb`
- replace deprecated `grpc.WithInsecure()` with `google.golang.org/grpc/credentials/insecure`
Deprecation notice: https://pkg.go.dev/github.com/golang/protobuf
=> refactor: replace deprecated grpc packages

dist/test/BUILD.bazel, pkg/private/xtest/helpers.go, pkg/scrypto/cppki/certs_test.go, pkg/scrypto/cppki/signed_trc_test.go, private/ca/renewal/ca_signer_gen_test.go, private/storage/trust/fspersister/db_test.go, private/trust/dbtest/dbtest_test.go, private/trust/store_test.go, scion-pki/certs/create_test.go, scion-pki/conf/trc_test.go, scion-pki/file/BUILD.bazel, scion-pki/file/file_test.go, scion-pki/key/BUILD.bazel, scion-pki/key/private_test.go, scion-pki/key/public_test.go, scion-pki/key/symmetric_test.go, scion-pki/testcrypto/BUILD.bazel, scion-pki/testcrypto/testcrypto_test.go, scion-pki/testcrypto/update_test.go, scion-pki/trcs/combine_test.go, scion-pki/trcs/format_test.go, scion-pki/trcs/sign_test.go, scion-pki/trcs/verify_test.go
The original helper function written 7 years ago is no longer useful since Go 1.15 introduced [`TempDir`](https://pkg.go.dev/testing#B.TempDir).
=> test: replace xtest.MustTempDir with t.TempDir

pkg/snet/conn.go
The error description of `snet.OpError` does now include the revocation information (if present). This ensures that logs contain the information about which interface is reported down which can be helpful for troubleshooting.
=> snet: include revocation info in snet.OpError

private/mgmtapi/tools/pnpm-lock.yaml
resolve https://github.com/scionproto/scion/security/dependabot/82 by running `pnpm install` in `private/mgmtapi/tools` that automatically sets `'@types/jsonpath-plus': '>=10.0.7'`.
=> chore: resolve dependabot security alert #82

doc/command/scion-pki/scion-pki_certificate_renew.rst, gateway/cmd/gateway/main.go, pkg/daemon/daemon.go, pkg/snet/addrutil/BUILD.bazel, pkg/snet/addrutil/addrutil.go, scion-pki/certs/renew.go, scion/cmd/scion/address.go
Implementing https://github.com/scionproto/scion/issues/3378. The issue suggests moving the interface to `snet` package, but `Connector` is used in other packages as well, hence the simpler approach.
Fixed a couple of typos on the way too.
=> refactor: remove pkg/daemon dependency from pkg/snet

router/dataplane.go
This PR resolves #4698. 
I followed the same principle that we use for the other protocols, i.e., we dispatch to the mapped port if the destination port is within the dispatched port range. Otherwise, it is sent to the fix `EndhostPort`. 
This makes it compatible with implementations following the "Wireguard"-model, i.e., sending the encapsulated traffic over a fix UDP port, e.g., the [SCION-IP translator]( https://github.com/netsys-lab/scion-ip-translator); or alternative implementations that map the underlay port to the application port, e.g., what we do with SCMP or UDP/SCION, provided proper `dispatched_ports` configuration.
=> router: add tcp support for dispatching to endhost

acceptance/router_benchmark/brload/main.go, pkg/slayers/scion_test.go, pkg/slayers/slayers_test.go, private/file/periodicview_test.go, private/trust/verifier_bench_test.go
test: Remove `require.NoError` and similar functions which skew benchmark results.
test: Use `b.Loop()` to simplify benchmarks and reset timers properly.
refactor: Use `range` over integers to simplify code.
=> test: remove testify from benchmarking code

doc/tutorials/deploy/cs.toml, doc/tutorials/deploy/topology1.json, doc/tutorials/deploy/topology2.json, doc/tutorials/deploy/topology3.json, doc/tutorials/deploy/topology4.json, doc/tutorials/deploy/topology5.json
Hi,
minor updates to adapt tutorial to v.0.12.0.
Removing "reconnect_to_dispatcher" field from cs.toml and adding "dispatched_ports" field to topology files.
Best,
Noah
=> docs: fix tutorial config cs.toml and topology files to reflect tutorial version update to v.0.12.0

README.md, code_of_conduct.md, doc/code_of_conduct.md, doc/dev/contribute.rst
It's been brought to the attention of the association that our GH pages lacked any kind of published code of conduct. Hopefully this one is fair and widely accepted.
=> doc: proposed adoption of the contributor's covenant as our code of conduct

router/bfd/session.go, router/dataplane.go, router/underlayproviders/udpip/udpip.go
This PR only changes sentinel error naming according to https://go.dev/wiki/Errors#naming
This is part of moving to golangci-lint v2.
=> refactor: apply error naming convention

.golangcilint.yml, control/beaconing/originator_test.go, control/beaconing/propagator_test.go, control/cmd/control/main.go, control/drkey/grpc/drkey_service.go, control/drkey/grpc/fetcher_test.go, control/drkey/grpc/mock_grpc/mock.go, control/drkey/service_engine.go, control/drkey/service_engine_test.go, control/trust.go, control/trust_test.go, daemon/cmd/daemon/main.go, daemon/daemon.go, daemon/internal/servers/grpc.go, daemon/internal/servers/metrics.go, gateway/control/remotemonitor.go, gateway/gateway.go, gateway/pathhealth/monitor.go, gateway/pathmonitor.go, private/app/appnet/infraenv.go, private/periodic/periodic.go, tools/await-connectivity
- ci: enable linter `contextcheck`
- fix: potentially incorrect uses of `context.Context`.
=> fix: enable linter contextcheck and fix potential problems

doc/overview.rst, doc/sig.rst
This pull request includes minor documentation updates to fix typographical errors and improve clarity in SCION's technical documentation.
Typographical corrections:
* [`doc/overview.rst`](diffhunk://#diff-6cc65603a3c60d4383d1e05dd6388e73773844c2f8e981f30d1ed116a7177e1bL14-R14): Corrected a grammatical error by changing "focuses on providing" to "focus on providing" in the description of SCION's aspirations for inter-AS routing.
* [`doc/sig.rst`](diffhunk://#diff-c28ddb50c1be3aaf4c126dd3dbc0ae78e427b6d23017c717cd570bd9783ba544L88-R88): Fixed a typographical error by correcting "out-ot-order" to "out-of-order" in the explanation of SIG frame handling.
=> doc: typos

MODULE.bazel, MODULE.bazel.lock, tools/env/debian/deps, tools/env/debian/pkgs.txt
Some deps were deleted in #4760 and were incorrectly merged back in #4759. Also, one of the dependencies added in #4759 is not being installed via the `install_deps` script on Ubuntu.
=> fix: update deps

scion-pki/certs/certformat.go, scion-pki/certs/certinfo.go, scion-pki/certs/fingerprint.go, scion-pki/certs/renew.go, scion-pki/certs/sign.go, scion-pki/certs/validate.go, scion-pki/certs/verify.go
fixes `QF1012`, `QF1008` and `errcheck` in `scion-pki`. This is a sub-task of #4769.
=> refactor: scion-pki preparation for golangci-lint v2

doc/cryptography/trc-signing-ceremony-builder.rst
The TRC Ceremony Builder had a typo where in the instructions to create certificates the key and certificate arguments are flipped. This PR fixes this typo.
=> doc: fix scion-pki certificate create command in TRC Ceremony Builder

.gitignore, doc/tutorials/deploy.rst, doc/tutorials/deploy/Makefile, doc/tutorials/deploy/vagrantfile
Most of this was done during the Hackathon on Wednesday
- Add vagrant for setting up tutorial VMs.
- Improve shell instructions that were causing permission issues.
- Clarify the difference between the core and non-core ASes.
- Upgrade to Ubuntu 24.04 LTS.
co-authored by @nicorusti @vincent10400094 @lsj0410
=> docs: improve tutorial

gateway/control/BUILD.bazel, gateway/control/engine.go, go.mod, go.sum, licenses/data/com_github_olekukonko_errors/LICENSE, licenses/data/com_github_olekukonko_ll/LICENSE
[olekukonko/tablewriter v0.0.5](https://github.com/olekukonko/tablewriter/releases/tag/v0.0.5) is long obsolete. Use latest [v1.0.7](https://github.com/olekukonko/tablewriter/releases/tag/v1.0.7)
old API: https://go.dev/play/p/KRK3OLB_keG
new API: https://go.dev/play/p/IuvksGrAC4b
=> chore: use tablewriter latest version v1.0.7

private/underlay/ebpf/BUILD.bazel, private/underlay/ebpf/port_filter_test_cap.sh
Bazel doesn't deal properly with extended file attributes. The original plan was to produce the capabilities enabled binary by copying the normal one and applying setcap to the result, but in some cases the copy can be left without the attributes and bazel considering the goal reached anyway. To work around that, wrapped the test in a script that executes the normal binary via capsh.
=> test: use capsh at runtime instead of setcap at buildtime
