- infrastructure/scion_elem.py
- lib/socket.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/895)
> TCP fixes (continuation of #890)

- go/border/packet/extn_traceroute.go
- go/border/packet/extns.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/897)
> Finish go router support for traceroute extension.

- endhost/scion_proxy.py
This means that one does not have to start scionds manually to run the proxy.
Convenient for deploying and testing on remote machines.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/907)
> SCION Proxy starts sciond automatically and cleans up when shut-down.

- endhost/scion_proxy.py
This way proxy can handle not only SIGINT, but also others such
as SIGTERM, SIGHUP etc.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/908)
> Proxy uses SCION's handle_signals() for signal handling.

- .gitmodules
This facilitates recursive checkouts by people without github accounts.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/910)
> Update git submodule URLs to https://

- lib/packet/cert_mgmt.py
- lib/packet/packet_base.py
- lib/packet/path_mgmt/seg_req.py
- lib/packet/pcb.py
- lib/packet/scion_addr.py
- lib/zk/id.py
- proto/cert_mgmt.capnp
- proto/path_mgmt.capnp
- proto/pcb.capnp
- proto/zkid.capnp
- test/lib/packet/pcb_test.py
- test/lib/packet/scion_addr_test.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/919)
> Changed encoding of ISD_AS for various payloads.

- deps.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/924)
> Update scion-web version

- infrastructure/scion_elem.py
- lib/defines.py
- lib/msg_meta.py
- lib/socket.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/912)
> CircleCI + TCP: another test

- go/border/hsr/hsr.go
- go/border/rpkt/payload.go
- go/border/rpkt/payload_ctrl.go
- go/border/rpkt/payload_scmp.go
- go/border/rpkt/process.go
- go/border/rpkt/route.go
- go/border/rpkt/rpkt.go
- go/border/rpkt/validate.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/931)
> Rename missed RPkt vars from p to rp.

- endhost/scion_proxy.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/936)
> Make it very clear that the proxy kbase is insecure.

- go/vendor/vendor.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/937)
> Go dependency license audit

- go/zkutil/party.go
- go/zkutil/util.go
@kormat
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/946)
> Switch zkutil to use log15 instead of glog

- doc/PathReversal.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/948)
> Add doc describing path reversal.

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/954)
> Ubuntu 16.04 in README.md

- lib/zk/id.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/957)
> Fix ZkID address indexes.

- infrastructure/beacon_server/base.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/963)
> Handle ZKNoConnection when storing revocations in BS.

- infrastructure/router/errors.py
- infrastructure/router/main.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/956)
> Added a check for the current interface and the router's interface.

- go/lib/addr/isdas.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/965)
> Minor refactoring of isdas.go to allow parsing from a string.

- go/lib/addr/isdas.go
- infrastructure/beacon_server/base.py
- infrastructure/router/errors.py
- infrastructure/router/main.py
- lib/crypto/certificate.py
- lib/crypto/certificate_chain.py
- lib/crypto/trc.py
- lib/util.py
- topology/generator.py
TRC synchronized with book. (Online/offline root keys added, verification adjusted.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/962)
> Trc certificate update

- go/border/error.go
- go/border/rpkt/path.go
- go/border/rpkt/route.go
- go/lib/scmp/scmp.go
- go/lib/topology/topology.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/967)
> Enforce forwarding rules in router.

- lib/crypto/trc.py
- lib/util.py
- pkgs_debian.txt
- topology/Default.topo
- topology/Tiny.topo
- topology/Wide.topo
- topology/generator.py
Root CA generation for ISDs. Added CA certificates to TRC.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/966)
> Ca certificate implementation

- go/border/error.go
- go/border/rpkt/l4.go
- go/border/rpkt/process.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/970)
> Support running the go router on the same IP as other services.

- infrastructure/scion_elem.py
Before passing a meta to an app it is necessary to drop an one-hop-path extension, otherwise an app cannot respond using the meta.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/971)
> Skipping one-hop-path extentions while creating meta

- go/border/conf/conf.go
- infrastructure/beacon_server/base.py
- infrastructure/router/main.py
- lib/crypto/symcrypto.py
Although, sha1 is ok for this purpose, few months ago we decided to update to sha2 (and the yesterday's news was a good reminder ;-).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/978)
> PBKDF2 based on sha2

- README.md
- go/border/rpkt/route.go
- go/lib/topology/testdata/basic.yml
- go/lib/topology/topology.go
- go/lib/topology/topology_test.go
- infrastructure/router/main.py
- infrastructure/sibra_server/steady.py
- lib/topology.py
- lib/types.py
- test/lib/topology_test.py
- topology/Default.topo
- topology/Wide.topo
- topology/brite/topology_generator.py
CORE is a more direct representation of what they are.
https://github.com/netsec-ethz/scion/issues/989
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/991)
> Rename ROUTING links to CORE links.

- infrastructure/beacon_server/core.py
- infrastructure/cert_server/main.py
- infrastructure/sibra_server/core.py
- infrastructure/sibra_server/main.py
- lib/topology.py
- test/lib/topology_test.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/993)
> Fix some lingering references to ROUTING links.

- infrastructure/scion_elem.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/994)
> fixed scmp_type_name call and updated submodules

- lib/crypto/trc.py
- lib/packet/cert_mgmt.py
- topology/generator.py
There was an expression without assignment in trc class
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/998)
> Bug fix in TRC

- infrastructure/cert_server/main.py
@kormat
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1014)
> Fix off-by one error in the certificate server

- go/border/rpkt/extn_onehoppath.go
Dispatcher will love this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1015)
> fix one hop path extension

- endhost/sciond.py
- lib/defines.py
- topology/generator.py
This makes it easier for the CS to find its sciond, both with and
without mininet.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1018)
> Generate a SCIOND_PATH env var for the CS.

- .gitignore
@kormat
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1022)
> Ingore more vim swap files

- test/integration/base_cli_srv.py
- tools/pktgen.py
- tools/pktprint.py
- tools/zkls.py
pktgen: generates packets at a high rate.
pktprint: turns hex-encoded packets into pretty-printed output.
zkls: list the contents of zookeeper paths.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1030)
> Add some small tools for dev/debug/op purposes.

- infrastructure/scion_elem.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1032)
> Logging fix in scion_elem

- lib/app/sciond.py
- lib/sciond_api/host_info.py
- test/lib/app/sciond_test.py
Unit tests for `lib.app.sciond.py` (#986)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1020)
> lib.app.sciond unit tests

- tools/ci/build_prep
- tools/ci/env_setup
- tools/ci/post_check
- tools/ci/run
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1046)
> Build prep fix

- lib/defines.py
- topology/generator.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1033)
> Enhance generator.py to produce Prometheus config files

- tools/pktgen.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1043)
> add waiting time to the packet generator.

- .circleci/config.yml
- docker.sh
- docker/Dockerfile
- docker/Dockerfile.base
- docker/deps_check
- env/common.sh
- env/debian/check
- env/debian/deps
- env/debian/pkgs.txt
- env/go/check
- env/go/deps
- env/pip2/check
- env/pip2/deps
- env/pip3/check
- env/pip3/deps
- env/pip3web/check
- env/pip3web/common.sh
- env/pip3web/deps
- env/zlog/check
- env/zlog/deps
- tools/ci/build_prep
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1048)
> Simplify handling of dependency changes

- lib/sciond_api/if_req.py
@shitz I believe that was a leftover from renaming.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1054)
> Tiny fix to sciond_api/if_req.py doc.

- lib/crypto/asymcrypto.py
add asymmetric encryption/decryption based on nacl PublicKey/PrivateKey.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1052)
> Add asymmetric encryption/decryption

- topology/Default.topo
- topology/Tiny.topo
- topology/Wide.topo
- topology/generator.py
Currently, certificate generation does not add the common name field, that PR fixes it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1039)
> Added CN field to CA certificates

- endhost/sciond.py
- infrastructure/beacon_server/base.py
- infrastructure/beacon_server/core.py
- infrastructure/beacon_server/local.py
- infrastructure/cert_server/main.py
- infrastructure/path_server/base.py
- infrastructure/scion_elem.py
- infrastructure/sibra_server/steady.py
- lib/packet/pcb.py
- lib/path_seg_meta.py
- lib/trust_store.py
- proto/pcb.capnp
- test/lib/packet/pcb_test.py
- topology/generator.py
…ot contained in pcbs anymore
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1000)
> Requesting TRCs and certs implemented for BS/PS/sciond

- lib/packet/scmp/types.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1062)
> Fix order of BAD_{SRC,DST}_TYPE in python

- endhost/dispatcher.c
- lib/dispatcher.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1072)
> Make the port byte-order consistent in the dispatcher protocol.

- lib/crypto/asymcrypto.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1066)
> Make asymcrypto.py work with pynacl 1.0.1

- endhost/sciond.py
- infrastructure/path_server/core.py
- infrastructure/scion_elem.py
- lib/packet/ext/path_transport.py
- lib/packet/path_mgmt/parse.py
- lib/packet/scion_addr.py
- scion.sh
Also add `./scion.sh start` as an alias for `run`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1074)
> Various fixes to logging and exceptions.

- infrastructure/beacon_server/base.py
- infrastructure/beacon_server/core.py
- infrastructure/beacon_server/local.py
- infrastructure/path_server/base.py
- infrastructure/path_server/core.py
- infrastructure/path_server/local.py
- infrastructure/scion_elem.py
- lib/crypto/asymcrypto.py
- lib/crypto/certificate.py
- lib/crypto/certificate_chain.py
- lib/errors.py
- lib/log.py
- lib/msg_meta.py
- lib/packet/path_mgmt/seg_req.py
- lib/packet/pcb.py
- lib/packet/scion_addr.py
- lib/path_store.py
- test/lib/log_test.py
- test/lib/path_store_test.py
Cleaned up logging in path server and beacon server. Introduced custom path request logger. Moved logging from PathStore and asymcrypto to applications. This part of the effort to clean up logging in Python (see #984)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1076)
> Cleaned up logging in path server and beacon server.

- .circleci/config.yml
- env/debian/pkgs.txt
- env/pip3/requirements.txt
- go/border/conf/conf.go
- go/border/rpkt/extn_onehoppath.go
- go/border/rpkt/path.go
- go/lib/spath/hop.go
- go/lib/util/mac.go
- infrastructure/cert_server/main.py
- infrastructure/path_server/base.py
- lib/crypto/hash_tree.py
- lib/crypto/symcrypto.py
- lib/packet/opaque_field.py
- lib/packet/pcb.py
- lib/sibra/ext/sof.py
- test/integration/path_store_test.py
- test/lib/crypto/hash_tree_test.py
- test/lib/packet/opaque_field_test.py
- test/lib/sibra/ext/sof_test.py
- topology/generator.py
fixes #985
~~CMAC.py is taken from the current version of pycrypto (unfortunately, currently neither `apt` nor `pip` provide it)~~
fixes #1003 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/999)
> CMAC instead of CBC-MAC

- .circleci/config.yml
- updates scion_base
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1088)
> Image update

- docker.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1091)
> Fix docker.sh to work with non-english locales.

- go/tools/logdog/main.go
@shitz
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1092)
> Fix line length

- topology/generator.py
This is useful when creating ASes for importing into scion-web, for example.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1095)
> Allow .topo files without links.

- go/tools/logdog/main.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1097)
> Fix multi-line output

- go/border/metrics/metrics.go
- go/border/setup.go
- topology/generator.py
This makes it possible to export metrics on an interface that the BR
isn't using itself.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1096)
> Add BR cmdline flag to specify metric export address.

- infrastructure/cert_server/main.py
- test/integration/cert_req_test.py
Fixes fetching of certificate chains on the certificate server.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1087)
> Fix CertChain fetching in Cert server

- scion.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1082)
> Remove stale sockets on shutdown

- tools/pktgen.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1070)
> Add randomized option to pktgen

- go/Makefile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1103)
> Fix handling of GOTAGS make variable.

- go/border/main.go
- go/border/router.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1100)
> Reload configs on HUP

- endhost/dispatcher.c
- endhost/sciond.py
- infrastructure/beacon_server/base.py
- infrastructure/beacon_server/core.py
- infrastructure/scion_elem.py
- infrastructure/sibra_server/main.py
- lib/defines.py
- lib/topology.py
- test/lib/topology_test.py
- topology/generator.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1093)
> Merge topo_update branch into master

- infrastructure/scion_elem.py
- lib/crypto/certificate.py
- lib/crypto/certificate_chain.py
- topology/generator.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1104)
> Add issuing TRC version to Certificates

- go/border/router.go
- tools/pktprint.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1113)
> Fix pktprint, and make it optionally parse ctrl payloads.

- infrastructure/beacon_server/base.py
- infrastructure/path_server/base.py
- lib/packet/asm_exts.py
- lib/packet/pcb.py
- lib/types.py
- proto/asm_exts.capnp
- proto/pcb.capnp
- test/lib/packet/pcb_test.py
ASMs can contain extensions now. Routing Policy extension was added for testing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1068)
> PCB format update.

- infrastructure/cert_server/main.py
- lib/drkey/drkey_mgmt.py
- lib/drkey/suite.py
- lib/drkey/types.py
- lib/drkey/util.py
- lib/packet/scion.py
- lib/types.py
- proto/drkey_mgmt.capnp
- proto/scion.capnp
Add first order DRKey fetching to certificate server
Add basic types used for first order DRKeys
Add first order DRKey part of DRKeySuite
Add payload class DRkeyMgmt
Add payload types : - DRKeyRequest
- DRKeyReply
(based on work in PR #1087)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1099)
> Add first order DRKey functionality.

- .circleci/config.yml
- docker/Dockerfile.base
- docker/profile
- env/debian/pkgs.txt
- env/go/check
- env/go/common.sh
- env/go/deps
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1120)
> go 1.8 WIP

- scion.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1122)
> Fix to start SCIOND using scion.sh again

- python/lib/defines.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1124)
> Fix the PROJECT_ROOT define, that's used by scion-web.

- python/cert_server/main.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1132)
> small fix DRKey request

- c/dispatcher/dispatcher.c
- python/lib/dispatcher.py
- python/lib/socket.py
- python/scion_elem/scion_elem.py
- python/sciond/sciond.py
This is a continuation of #1123.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1134)
> Support Bind Addresses in Dispatcher

- c/dispatcher/dispatcher.c
- c/lib/scion/packet.c
- python/integration/scmp_echo_test.py
-Fix dispatcher crashing on SCMP echo request
-Add mapping SCMP echo request -> socket
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1128)
> SCMP echo capability

- python/beacon_server/base.py
- python/cert_server/main.py
- python/path_server/base.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1145)
> Add is_master metric to BS, PS, and CS

- python/lib/crypto/certificate_chain.py
@shitz
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1146)
> Fix a bug where core AS cert verification error is not instantiated.

- .circleci/config.yml
- docker.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1150)
> Switch over to docker hub organization

- .circleci/config.yml
Updates scion-web submodule to commit cdc8f9d5f199831593311083d156fd16170f9c47.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1149)
> scion-web submodule update

- python/topology/generator.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1154)
> Fix TRC generation in generator

- python/cert_server/main.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1155)
> CS TRC request fix

- python/lib/trust_store.py
- python/path_server/base.py
- python/scion_elem/scion_elem.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1157)
> Adding more metrics to SCIONElem and PS

- python/beacon_server/base.py
- python/cert_server/main.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1147)
> Don't update metrics if not exporting at all

- python/lib/defines.py
- python/lib/trust_store.py
- python/scion_elem/scion_elem.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1162)
> Automatically make gen cache dir and add define for it

- python/beacon_server/base.py
- python/cert_server/main.py
- python/lib/path_db.py
- python/lib/requests.py
- python/lib/rev_cache.py
- python/lib/trust_store.py
- python/path_server/base.py
- python/path_server/core.py
- python/scion_elem/scion_elem.py
Also: Added metrics initialization.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1163)
> Added new metric tracking if an element is registered with the dispatcher

- Makefile
Also update sub/lwip-contrib which just had the same change made.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1166)
> Use $(MAKE) to allow `make -q` to work.

- go/sig/base/forward.go
- go/sig/base/sdb.go
Also:
- Add padding of packets to 8B boundaries
- Add proper index offsets
- Add epoch support
N.B.: this won't work with the current IngressWorker, but @shitz will be
merging an updated IngressWorker right after this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1171)
> Refactor EgressWorker

- go/sig/base/forward.go
- go/sig/sig.go
Also enable pprof profiling over http.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1173)
> Don't release pkt twice in egress logic.

- go/sig/base/ingress.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1174)
> Fix reassembly when packet spawns >2 frames

- go/sig/base/ingress.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1175)
> Rename fragment0 and fragmentN

- go/sig/base/ingress.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1178)
> Simplified IngressWorker to not handle reordering anymore

- go/sig/base/forward.go
- go/sig/base/ingress.go
- go/sig/metrics/metrics.go
- go/sig/sig.go
This PR adds metrics for the SIG. The current metrics are Bytes/Packets Sent/Received labelled by tunnel interface, e.g. "scion.local", "scion.100-1", etc.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1179)
> Metrics for the SIG

- .circleci/config.yml
- go/sig/base/framebuf.go
- go/sig/base/rlist.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1186)
> Swtich `sig` branch to use `scion_base:sig`

- python/lib/defines.py
- python/path_server/base.py
- python/path_server/core.py
- python/path_server/local.py
- python/sciond/sciond.py
Also: SCIOND retries cert/trc requests
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1194)
> Path server now expires path requests.

- c/dispatcher/dispatcher.c
If the dispatcher is too slow (e.g. it's blocking waiting on an
application to read from the unix domain socket), incoming packets can
be dropped by the kernel when the udp socket buffer fills up. This
change reports dropped packet counts once per second.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1197)
> Track incoming dispatcher packets dropped by the kernel.

- .gitignore
- c/lib/scion/Makefile
- c/lib/scion/checksum_bench.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1199)
> Add a simple checksum benchmark utility.

- go/sig/lib/scion/scion.go
Also cleanup.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1195)
> SCION data packet creation no longer alloc's

- .circleci/config.yml
- .gitignore
- c/dispatcher/dispatcher.c
- go/lib/spkt/spkt.go
- go/sig/README.md
- go/sig/base/asinfo.go
- go/sig/base/forward.go
- go/sig/base/framebuf.go
- go/sig/base/ingress.go
- go/sig/base/rlist.go
- go/sig/base/sdb.go
- go/sig/control/static.go
- go/sig/lib/scion/addr.go
- go/sig/lib/scion/paths.go
- go/sig/lib/scion/scion.go
- go/sig/management/console.go
- go/sig/metrics/metrics.go
- go/sig/mod/hello/hello.go
- go/sig/sig.go
- go/sig/xnet/xnet.go
- go/vendor/vendor.json
- proto/scion.capnp
- proto/sig.capnp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1200)
> Merge the sig branch into master.

- go/border/metrics/metrics.go
- go/border/setup.go
- go/lib/nethack/reflect.go
- go/lib/overlay/conn/conn.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1203)
> Add receive buffer overflow counts for border router.

- go/sig/lib/scion/scion.go
This commit got lost in the merge of the `sig` branch into `master`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1204)
> Re-merge pr/1195 (SCION data packet creation no longer alloc's)

- go/border/metrics/metrics.go
- go/lib/overlay/conn/conn.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1205)
> Fix overflow metric and actually export it.

- go/lib/sring/rb.go
- go/lib/sring/sring.go
- go/lib/sring/sring_test.go
This means that the BR can use it for RtrPkts, for example.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1206)
> Make SRing type-agnostic

- go/border/error.go
- go/border/gen.go
- go/border/io.go
- go/border/rcmn/dir.go
- go/border/router.go
- go/border/rpkt/create.go
- go/border/rpkt/extn_onehoppath.go
- go/border/rpkt/hooks.go
- go/border/rpkt/parse.go
- go/border/rpkt/path.go
- go/border/rpkt/process.go
- go/border/rpkt/route.go
- go/border/rpkt/rpkt.go
- go/border/setup.go
This removes a circular dependency for my next PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1207)
> Move rpkt.Dir to a new router common package.

- go/lib/sring/metrics.go
- go/lib/sring/rb.go
- go/lib/sring/sring.go
- go/lib/sring/sring_test.go
Also:
- Add missing copyright notices to other sring files.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1210)
> Add metrics to SRing.

- go/lib/l4/udp.go
restruct is slow, as it uses reflection. This didn't matter much for the
BR, as it doesn't parse the vast majority of UDP headers. However this
speed issue becomes a problem for other applications, like the SIG.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1211)
> Hand-parse udp header

- go/border/error.go
- go/border/gen.go
- go/border/io.go
- go/border/main.go
- go/border/metrics/metrics.go
- go/border/rctx/io.go
- go/border/rctx/rctx.go
- go/border/router.go
- go/border/rpkt/route.go
- go/border/rpkt/rpkt.go
- go/border/setup.go
- go/lib/overlay/conn/conn.go
- go/lib/ringbuf/ringbuf.go
- go/lib/topology/addr.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1212)
> Rewrite posix i/o to use SRing, remove per-packet callbacks.

- go/lib/sock/reliable/appaddr.go
- go/lib/sring/sring_test.go
- go/lib/util/checksum_test.go
- go/sig/base/asinfo.go
- go/sig/base/forward.go
- go/sig/base/framebuf.go
- go/sig/base/ingress.go
- go/sig/base/rlist.go
- go/sig/base/sdb.go
- go/sig/control/static.go
- go/sig/lib/scion/addr.go
- go/sig/lib/scion/paths.go
- go/sig/lib/scion/scion.go
- go/sig/management/console.go
- go/sig/metrics/metrics.go
- go/sig/mod/hello/hello.go
- go/sig/sig.go
- go/sig/xnet/xnet.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1219)
> Added missing copyright headers

- go/lib/hpkt/hpkt.go
- go/lib/hpkt/hpkt_test.go
- go/lib/spkt/spkt.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1220)
> Added SCION packet creation function for Go end-hosts

- go/lib/sciond/sciond.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1223)
> Make the SCIOND Go library thread-safe

- .gitignore
- go/border/conf/conf.go
- go/lib/topology/raw.go
- go/lib/topology/strip.go
- go/lib/topology/topology_test.go
- go/tools/topopruner/topopruner.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1230)
> Add a tool to prune/reduce topologies

- go/border/gen.go
- go/border/io.go
- go/border/main.go
- go/border/revinfo.go
- go/border/router.go
- go/lib/log/log.go
- go/sig/sig.go
This prevents cases where a go routine crashes, but the process keeps
running obliviously.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1231)
> Change panic logger to also exit the process.

- go/lib/snet/integration_test.go
- go/lib/util/aslist.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1238)
> Move Go YAML AS parser to lib/util

- python/cert_server/main.py
- python/scion_elem/scion_elem.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1241)
> Adding path lookup via SCIOND to SCIONElem

- go/lib/ctrl/seg/seg.go
- python/lib/packet/pcb.py
This fixes https://github.com/netsec-ethz/scion/issues/1244
Note: this change requires cached paths to be flushed, as they won't be
replaced by newer versions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1246)
> Fix segment ID to use the appropriate interface IDs.

- python/cert_server/main.py
- python/lib/crypto/asymcrypto.py
- python/lib/crypto/certificate.py
- python/lib/drkey/suite.py
- python/sibra_server/main.py
- python/topology/generator.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1156)
> Add consistency to asymcrypto

- python/lib/config.py
- python/lib/defines.py
- python/topology/generator.py
This prevents breakage of existing running infrastructure.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1255)
> Add default value for path segment TTL in case none is configured

- go/lib/pathmgr/apppath.go
- go/lib/pathmgr/defines.go
- go/lib/pathmgr/revtable.go
This allows it to be used by other modules.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1266)
> Export the path key type from PathMgr

- go/lib/sciond/types.go
- go/lib/snet/addr.go
- go/lib/snet/conn.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1274)
> Add PathEntry field to snet.Addr to allow apps to specify a path.

- go/lib/sciond/infra_test.go
- go/lib/snet/conn.go
- go/lib/sock/reliable/reliable.go
Based on work by @jpcsmith 
Replaces #1253
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1276)
> Make reliable.Conn and snet.Conn thread-safe.

- python/beacon_server/base.py
- python/lib/crypto/hash_tree.py
- python/lib/packet/path_mgmt/rev_info.py
- python/path_server/base.py
- python/scion_elem/scion_elem.py
- python/sciond/sciond.py
Also: Move `_validate_revocation` to `rev_info.py` #1279 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1281)
> Validate TreeTTL of received Revocations

- python/lib/msg_meta.py
- python/scion_elem/scion_elem.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1284)
> Fixed crash in SCIOND when printing revocation origin

- go/border/error.go
- go/border/rpkt/route.go
- go/lib/pathmgr/apppath.go
- go/lib/sciond/types.go
- go/lib/snet/addr.go
- go/lib/snet/conn.go
- go/lib/snet/integration_test.go
- go/sig/base/egress_worker.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1283)
> Update snet to accept and fill in path/nexthop info in snet.Addr.

- go/lib/pktcls/action_map.go
- go/lib/pktcls/class_map.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1285)
> Change pktcls maps type to built-in maps

- env/go/deps
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1304)
> Add support for 64-bit arm (aarch64)

- python/lib/packet/spse/ext.py
- python/lib/packet/spse/scmp_auth/ext_drkey.py
- python/lib/packet/spse/scmp_auth/ext_hashtree.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1313)
> Fix SPSE hdr len

- go/border/gen.go
- go/border/revinfo.go
- go/border/rpkt/process.go
- go/lib/ctrl/ctrl.go
- go/lib/ctrl/signed.go
- go/sig/base/pollhdlr.go
- go/sig/disp/disp.go
- go/sig/egress/sessmon.go
The previous PR overlooked a number of call-sites.
Also add some helper constructors for signed ctrl pld types.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1314)
> Use Signed Ctrl Pld consistently.

- go/sig/egress/dispatcher.go
Deleting an AS Entry from the SIG would cause the associated egress dispatcher to continuously raise errors, polluting logs and depleting the free buffer pool for all dispatchers, thus causing the entire SIG to stop forwarding. This fix:
- releases buffers on errors now, so buffers are never leaked
- causes the egress dispatcher to cleanly shut down when the tunnel interface is closed
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1318)
> Fix buffer leaks in egress dispatcher

- tools/wireshark/scion.lua
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1320)
> Add SCION path support to wireshark dissector.

- tools/wireshark/README.md
- tools/wireshark/scion.lua
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1321)
> Add extn/udp support to wireshark dissector.

- go/lib/disp/disp.go
- go/lib/pktdisp/disp.go
- go/sig/disp/disp.go
- go/sig/egress/session.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1324)
> Refactor packet dispatcher out of snet

- go/lib/pathmgr/pathmgr.go
- go/sig/base/as.go
- go/sig/base/map.go
- go/sig/base/nets.go
- go/sig/config/config.go
- go/sig/egress/dispatcher.go
- go/sig/egress/session.go
- go/sig/egress/sessmon.go
- go/sig/sig.go
- go/sig/siginfo/sig.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1322)
> SIG can reload configs

- proto/ctrl_extn.capnp
- proto/ctrl_pld.capnp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1331)
> Add extension support to CtrlPld

- go/lib/pktcls/doc.go
- go/lib/pktcls/json.go
- go/lib/pktcls/pred_ipv4.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1338)
> Add pktcls support for DSCP field (subset of ToS field).

- python/beacon_server/base.py
- python/path_server/base.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1342)
> Close gaps in detection of bad RevocationInfo messages.

- .gitmodules
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1347)
> Migrate lwip repos to scionproto

- go/lib/pathmgr/pathmgr.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1350)
> Path manager now correctly counts Watch references

- go/lib/ctrl/extn/extn.go
- go/lib/ctrl/union.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1351)
> Add CtrlPld extension support to Go

- go/lib/pktdisp/disp.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1358)
> Temporary fix for error handling in pktdisp

- go/border/error.go
- go/border/io-hsr.go
- go/border/io.go
- go/border/rctx/io.go
- go/cert_srv/cert.go
- go/cert_srv/io.go
- go/cert_srv/main.go
- go/cert_srv/trc.go
- go/lib/crypto/trc/entries.go
- go/lib/hpkt/read.go
- go/lib/infra/messaging/udp.go
- go/lib/pathdb/sqlite/sqlite_test.go
- go/lib/pathmgr/infra_test.go
- go/lib/pathmgr/pathmgr.go
- go/lib/pathmgr/resolver.go
- go/lib/pktdisp/disp.go
- go/lib/snet/conn.go
- go/sig/base/as.go
- go/sig/base/pollhdlr.go
- go/sig/disp/disp.go
- go/sig/egress/dispatcher.go
- go/sig/egress/sessmon.go
- go/sig/egress/worker.go
- go/sig/ingress/dispatcher.go
- go/sig/ingress/framebuf.go
- go/sig/sig.go
- go/tools/echoscion/echo.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1372)
> Consistently use common.FmtError to format errors for logging.

- python/beacon_server/base.py
- python/lib/defines.py
- python/scion_elem/scion_elem.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1374)
> Restrict HF ExpTime to the validity period of CertChain/TRC

- go/lib/crypto/cert/cert.go
- go/lib/crypto/cert/chain.go
- go/lib/crypto/cert/chain_test.go
- go/lib/crypto/cert/testdata/ISD1-V2.trc
- go/lib/util/time.go
- python/lib/crypto/certificate.py
- python/lib/crypto/certificate_chain.py
Verify core certificate based on a trusted TRC.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1373)
> Add CertChain verification based on TRC

- go/cert_srv/cert.go
- go/cert_srv/conf/conf.go
- go/cert_srv/main.go
- go/cert_srv/trc.go
Add config to go certificate server containing:
- Topology
- Bind and public address
- KeyConf
- config directory
(based on PR #1371)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1375)
> Add CS-Go config

- python/path_server/core.py
- python/path_server/local.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1362)
> Log path _requests_.

- python/topology/generator.py
This reduces noise when they are stored in a source control system.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1384)
> Add trailing newline to generated JSON files

- python/beacon_server/base.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1393)
> Export interface state metrics from the BS

- go/lib/crypto/cert/cert.go
- go/lib/crypto/cert/chain.go
Add: 
- Copy function to certificate
- Copy function to certificate chain. 
- Default validity times for certificates.
- VerifyTime function to check if certificate is active at a given point in time.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1378)
> Add Copy function to Cert/Chain

- go/border/main.go
- go/sig/sig.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1397)
> Disallow running br/sig as root, check for required caps.

- go/lib/ctrl/signed_util.go
- go/proto/gen.go
- go/proto/sign.go
- proto/sign.capnp
Add default SignSrc which includes:
- ISD-AS of singer
- Certificate chain version of signer
- TRC version of signer
Additionally:
- add Timestamp to SignS
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1399)
> Add default SignSrc

- tools/ci/env_setup
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1405)
> Include the github org in the circleci artifacts file name.

- .circleci/config.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1406)
> Don't run go coverage, as it take ~5mins.

- go/tools/showpaths/Readme.md
- go/tools/showpaths/paths.go
The tool displays the paths returned by SCIOND
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1400)
> Add simple show SCION paths tool

- go/border/ifstate/ifstate.go
- go/border/rpkt/path.go
- go/border/setup.go
- python/beacon_server/base.py
Fixes #1395
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1398)
> Handle partial IFState updates in the BR.

- .circleci/config.yml
- env/go/common.sh
- env/go/deps
This addresses https://github.com/golang/go/issues/23672, which allows
arbitrary code execution during "go get".
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1411)
> Update to go1.9.4

- python/integration/scmp_echo_test.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1417)
> fix scmp_echo_test.py

- go/sig/config/config.go
- go/sig/metrics/metrics.go
- go/sig/sig.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1425)
> Add SIG config version as a metric

- python/beacon_server/base.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1432)
> Only issue revocations if there are any

- go/lib/pathdb/sqlite/sqlite.go
- go/lib/pathdb/sqlite/sqlite_test.go
- go/lib/sqlite/sqlite.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1433)
> Move database creation so other packages can use it

- go/sig/config/config.go
- go/sig/metrics/metrics.go
- go/sig/sig.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1434)
> Export SIG config version as uint

- go/lib/util/duration.go
- go/lib/util/duration_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1441)
> Add a ParseDuration that supports years/weeks/days.

- go/lib/sciond/sciond.go
- go/lib/snet/snet.go
- python/lib/packet/scion_addr.py
- python/sciond/sciond.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1442)
> Make it easy for an app to get the local ASInfo from sciond.

- go/tools/scion-pki/internal/certs/gen.go
- go/tools/scion-pki/internal/certs/verify.go
- go/tools/scion-pki/internal/pkicmn/pkicmn.go
- go/tools/scion-pki/internal/trc/gen.go
Also:
* Fixed a bug in the iteration-order for `certs gen`
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1446)
> Write TRC to ISDx/trcs/ISDx-Vy.trc

- go/examples/pingpong/README.md
- go/examples/pingpong/pingpong.go
Basically adding 'interactive' mode, to choose a path.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1429)
> Add flag to choose a path in pingpong

- go/examples/pingpong/pingpong.go
Fixes ReadDeadline handling: previously a missed deadline invalidated all further measurements, since unconsumed packets from previous deadlines were used to infer the RTT.
Only treat errors as Fatal when necessary. Avoid Fatal errors after the initialization on the server since (a broken connection to a client should not bring down the server)
Close sessions also on the server side.
Sending and receiving messages is no longer lock-stepped.
Thanks for the suggestions in #dev
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1450)
> Add timestamp to messages

- go/lib/common/defs.go
- go/lib/pathmgr/main_test.go
- go/lib/pathmgr/pathmgr_test.go
- go/lib/pathmgr/pred.go
- go/lib/pathmgr/pred_test.go
- go/lib/sciond/graph/graph.go
- go/lib/sciond/mock.go
- go/lib/sciond/sciond.go
- go/lib/sciond/types.go
- go/lib/xtest/graph/graph.go
Also includes miscellaneous unit test cleanup/improvements.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1443)
> Implement mock sciond for testing

- go/border/main.go
- go/cert_srv/main.go
- go/examples/pingpong/pingpong.go
- go/lib/log/log.go
- go/sig/sig.go
- Only need to import liblog for logging
- Rename liblog as log package
- Split log file vs log console functions
- Functions to dynamically add flags for log file/console
- Setup returns error instead of directly exiting
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1426)
> Log and Flags rework

- go/border/rctx/rctx.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1458)
> Remove lock around Get/Set Router Ctx

- go/border/rctx/rctx.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1459)
> Use atomics to Get/Set Ctx

- go/border/error.go
- go/border/router.go
- go/border/rpkt/route.go
- go/border/rpkt/rpkt.go
- go/border/rpkt/rpkt_hook_test.go
- go/border/setup.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1460)
> border: dedicated Goroutine for SCMP error generation

- go/lib/scmp/info_recordpath.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1463)
> Fix RecordPath entry description and reorder fields

- c/lib/scion/checksum_bench.c
Fixes #1262.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1475)
> Use platform-independent print formats in checksum_bench.c

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1506)
> Update README (#1311)

- go/tools/scion-pki/internal/certs/gen.go
- go/tools/scion-pki/internal/certs/verify.go
- go/tools/scion-pki/internal/keys/gen.go
- go/tools/scion-pki/internal/pkicmn/pkicmn.go
- go/tools/scion-pki/internal/trc/gen.go
Fixes #1496
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1517)
>   scion-pki: Read signing algorithm from TRC when signing new issuer cert

- go/lib/pathmgr/cache.go
- go/lib/pathmgr/pathmgr.go
- go/lib/sciond/mock.go
- go/lib/sciond/types.go
- proto/sciond.capnp
- python/lib/path_combinator.py
- python/lib/sciond_api/path_meta.py
- python/sciond/sciond.py
- python/test/lib/path_combinator_test.py
Add expiration time to `FwdPathMeta`
Modify SCION Deamon to attach expiration time to path.
Modify `pathmgr.cache` to ignore expired path.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1525)
> Add expiration time to FwdPathMeta

- go/cert_srv/conf/customers.go
- python/topology/generator.py
Fix the topology generator to create customer verifying key files with prefixes.
Adjust customer mapping to accept new AS format.
BREAKING COMMIT:
Changes file name of customer verifying key file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1533)
> CS: Fix customer map loading

- go/tools/scion-pki/internal/certs/gen.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1532)
> Fixed minor formatting issues in scion-pki/certs/gen.go

- go/tools/scion-pki/README.md
- go/tools/scion-pki/internal/certs/cmd.go
- go/tools/scion-pki/internal/conf/as.go
- go/tools/scion-pki/internal/trc/gen.go
Fixes #1492
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1520)
> scion-pki: Add option to configure signing algorithms for online/offline keys

- go/lib/xtest/helpers.go
- go/tools/scion-pki/internal/conf/as.go
- go/tools/scion-pki/internal/conf/as_test.go
- go/tools/scion-pki/internal/conf/isd.go
- go/tools/scion-pki/internal/conf/isd_test.go
- go/tools/scion-pki/internal/pkicmn/pkicmn.go
- go/tools/scion-pki/internal/pkicmn/pkicmn_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1542)
> scion-pki: Add unit-tests for pkicmn and conf packages

- doc/RevocationAuthentication.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1550)
> Revocation Authentication Design

- python/lib/packet/path_mgmt/rev_info.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1553)
> Re-add __eq__ on SignedRevInfo

- go/border/rpkt/validate.go
The ifid from a packet must match the ifid of the interface it was
received on. This prevents a number of nasty attacks.
Thanks to Tobias Klenze for spotting this!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1560)
> Check that ifids match

- python/path_server/base.py
- python/scion_elem/scion_elem.py
- python/sciond/sciond.py
- python/test/scion_elem_test.py
- python/test/sciond_test.py
Fixes #1564 .
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1567)
> SCIOND: Do not add revoked segments

- go/lib/ctrl/path_mgmt/seg_req.go
- go/lib/ctrl/seg/meta.go
Also fixes #1572.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1574)
> Sync Go capnp libraries with protocol definition

- go/tools/scion-pki/internal/certs/gen.go
- go/tools/scion-pki/internal/certs/verify.go
- go/tools/scion-pki/internal/cmd/cmd.go
- go/tools/scion-pki/internal/conf/as.go
- go/tools/scion-pki/internal/conf/isd.go
- go/tools/scion-pki/internal/keys/gen.go
- go/tools/scion-pki/internal/pkicmn/pkicmn.go
- go/tools/scion-pki/internal/tmpl/as.go
- go/tools/scion-pki/internal/tmpl/isd.go
- go/tools/scion-pki/internal/trc/gen.go
- go/tools/scion-pki/internal/version/version.go
Fixes #1497 
Also:
Arbitrarily bump version to 0.2
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1593)
> Add quiet mode to scion-pki

- go/examples/pingpong/pingpong.go
- go/tools/scmp/main.go
Fixes #1583
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1590)
> cannonicalize the SCIOND socket selection process

- go/border/rpkt/rpkt_hook_test.go
- go/lib/addr/host.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1591)
> Simply return the object instead of a pointer in HostFromIP

- .circleci/config.yml
- go/cert_srv/conf/customers.go
- go/lib/crypto/asym.go
- go/lib/trust/key_conf.go
- go/tools/scion-pki/internal/certs/gen.go
- go/tools/scion-pki/internal/keys/gen.go
- go/tools/scion-pki/internal/trc/gen.go
- go/vendor/vendor.json
- python/lib/crypto/asymcrypto.py
- python/lib/crypto/util.py
- python/topology/generator.py
Also, make load for ed25519 key compatible with RFC 8032.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1604)
> Update crypto dependencies

- c/dispatcher/dispatcher.c
SCION TCP is outdated and currently not supported, so do not create a thread for it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1609)
> Do not create TCP middleware thread

- go/border/router.go
- go/border/rpkt/validate.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1612)
> Allow pkt validation hooks to filter packets.

- python/beacon_server/base.py
- python/lib/defines.py
- python/lib/packet/cert_mgmt.py
- python/lib/packet/path_mgmt/rev_info.py
- python/lib/packet/proto_sign.py
- python/path_server/base.py
- python/scion_elem/scion_elem.py
- python/sciond/sciond.py
Fixes #1545 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1600)
> Fetch certificates for revocations

- go/lib/ctrl/path_mgmt/rev_info.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1625)
> Use go's time library more consistently in RevInfo.

- c/dispatcher/dispatcher.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1630)
> Make the dispatcher socket be connectable by anyone.

- python/lib/socket.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1631)
> Make the SCIOND socket be connectable by anyone.

- go/sig/base/core/as.go
- go/sig/base/core/map.go
- go/sig/main.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1633)
> Cleaner separation of base AS package

- go/border/router.go
- go/border/rpkt/create.go
- go/border/rpkt/process.go
- go/border/rpkt/route.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1607)
> BR: support for multiple external interfaces

- python/bin/sciond
- python/sciond/sciond.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1646)
> Change sciond default listening socket, FIXES #1644

- go/lib/sciond/types.go
- go/sciond/internal/fetcher/fetcher.go
- proto/sciond.capnp
- python/integration/base_cli_srv.py
- python/lib/app/sciond.py
- python/lib/sciond_api/path_req.py
- python/scion_elem/scion_elem.py
- python/sciond/sciond.py
- python/test/lib/app/sciond_test.py
Fixes #1622
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1648)
> Change SCIOND API path request flags

- go/border/netconf/interface.go
- go/border/rpkt/process.go
- go/border/rpkt/route.go
- go/lib/topology/doc.go
- go/lib/topology/topology.go
- go/lib/topology/topology_test.go
- go/lib/topology/types.go
Fixes #1653
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1654)
> Delete LinkType in go/topology/types.go

- go/tools/scion-pki/internal/conf/as.go
- go/tools/scion-pki/internal/conf/as_test.go
Fixes #1547
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1650)
> scion-pki: Validate sign/enc algos in as.ini

- c/lib/scion/opaque_field.h
- c/lib/scion/scmp.h
- go/border/rpkt/path.go
- go/border/rpkt/route.go
- go/lib/scmp/scmp.go
- go/lib/spath/hop.go
- python/lib/flagtypes.py
- python/lib/packet/opaque_field.py
- python/lib/packet/scmp/errors.py
- python/lib/packet/scmp/types.py
- python/test/lib/packet/opaque_field_test.py
- tools/wireshark/scion.lua
Fixes #1586
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1656)
> Drop FORWARD_ONLY hop-field flag

- go/lib/crypto/cert/cert.go
- go/lib/crypto/cert/cert_test.go
- go/lib/crypto/cert/chain.go
- go/lib/crypto/cert/chain_test.go
- go/lib/crypto/cert/json.go
- go/lib/crypto/trc/entries.go
- go/lib/crypto/trc/json.go
- go/lib/crypto/trc/trc.go
- go/lib/crypto/trc/trc_test.go
fixes #1649
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1661)
> Crypto: Throw error when parsing malformed TRC/CertChains

- go/border/rpkt/path.go
- go/border/rpkt/route.go
Fixes #1584
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1655)
> BR:  Disallow shortcuts on core segments

- go/proto/sign.go
avoid alteration of message during sigPack
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1671)
> Fix sigPack

- go/sig/config/config.go
- go/sig/config/config_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1647)
> Verify network address in sig.json fixes #1596

- go/examples/pingpong/pingpong.go
This can be used to test sending/receiving larger amounts of data.
Used in #1658
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1668)
> Add file argument to pingpong example

- python/scion_elem/scion_elem.py
Fetch correct version of TRC from trust store.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1672)
> SE: fix cert chain verification

- go/lib/sciond/mock.go
- go/lib/sciond/sciond.go
- go/lib/sciond/types.go
- go/sciond/internal/servers/handlers.go
- go/sciond/server_test.go
- proto/common.capnp
- proto/sciond.capnp
- python/beacon_server/base.py
- python/beacon_server/core.py
- python/beacon_server/local.py
- python/cert_server/main.py
- python/lib/defines.py
- python/lib/packet/svc.py
- python/lib/topology.py
- python/lib/types.py
- python/lib/zk/zk.py
- python/path_server/base.py
- python/scion_elem/scion_elem.py
- python/sciond/sciond.py
- python/sibra_server/main.py
Fixes #1638
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1652)
>  Remove sciond.SvcBR from SCIOND API

- go/sig/sigcmn/common.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1679)
> Fix default path for sciond socket in SIG

- .circleci/config.yml
- go/vendor/vendor.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1682)
> Update quic-go to version 0.8.0

- go/border/rpkt/create.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1685)
> Add missing path flags

- go/examples/pingpong/pingpong.go
* Server can now handle clients with different payloads
* Improve error handling in server
* Introduce structs to make methods bound to a type
* Handle interrupts in client to properly close the connection
* Update quic-go to version 0.8
Handle interrupt in client
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1676)
> Refactor pingpong example

- c/dispatcher/dispatcher.c
- c/lib/scion/address.h
- c/lib/scion/checksum_bench.c
- go/lib/addr/isdas.go
- go/lib/sciond/sciond.go
In particular, rearrange a field in Go's sciond.connector struct, due to a existing
issue https://github.com/golang/go/issues/599 .
The rest are just minor build issues.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1687)
> Patch for ARM 32bit.

- c/dispatcher/dispatcher.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1684)
> Enable dispatcher to delete socket

- go/sciond/main.go
- python/bin/sciond
- python/sciond/sciond.py
Fixes #1666
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1692)
> Enable sciond to delete socket

- go/lib/infra/modules/combinator/combinator.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1697)
> Fix misleading docstring

- go/lib/log/log.go
Also fix an error message
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1698)
> Log to Stderr instead of Stdout

- c/dispatcher/dispatcher.c
Fixes #1700 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1707)
> Fix pointer freeing in dispatcher

- go/lib/as_conf/conf.go
- go/lib/trust/key_conf.go
- go/tools/logdog/main.go
Fixes #1706.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1717)
> Prevent AS master key from being logged.

- go/cert_srv/main.go
- go/examples/pingpong/pingpong.go
- go/lib/snet/integration_test.go
- go/lib/snet/snet.go
- go/lib/sock/reliable/reliable.go
- go/sciond/main.go
- go/sig/sigcmn/common.go
- go/tools/scmp/main.go
Instead of having the same string all over the place.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1721)
> Introduce DefaultDispPath constant

- docker/perapp/base/Dockerfile.base
- docker/perapp/docker_build
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1726)
> Add /tmp to all containers

- python/path_server/core.py
- python/path_server/local.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1730)
> PS: take lock when accessing/updating pending_req

- go/lib/spath/hop.go
- go/lib/spath/info.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1727)
> Add some doc to HopField, InfoField

- go/lib/pathdb/conn/conn.go
- go/lib/pathdb/pathdb.go
- go/lib/pathdb/sqlite/sqlite.go
- go/lib/pathdb/sqlite/sqlite_test.go
- go/sciond/internal/fetcher/fetcher.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1729)
> Contextualize the pathdb conn.Conn interface

- go/lib/revcache/revcache.go
- go/sciond/internal/fetcher/fetcher.go
- go/sciond/internal/fetcher/revcache.go
- go/sciond/internal/servers/handlers.go
Also fix the current revcache, it was calling add without checking the return code.
If the ttl changed that would have no impact. Now we check and update the ttl
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1732)
> Introduce revcache interface

- scion.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1708)
> Fix misleading help on scion.sh

- python/scion_elem/scion_elem.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1742)
> Use locks when updating missing certs and trcs in scion_elem

- go/border/conf/conf.go
- go/lib/crypto/mac.go
- go/lib/spath/hop.go
mac.go should be part of the crypto package
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1743)
> Move mac.go to lib/crypto

- go/lib/infra/disp/disp_test.go
- go/lib/infra/modules/trust/trust_test.go
Fixes https://github.com/scionproto/scion/issues/1528.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1734)
> More tolerant timers in flaky unit tests

- go/lib/crypto/trc/trc.go
- go/lib/crypto/trc/trc_test.go
- go/sciond/internal/fetcher/fetcher.go
- go/sciond/internal/servers/handlers.go
So that we can easily check if a certain IA is contained,instead of
creating a slice for it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1745)
> Introduce CoreASes type

- integration/integration_test.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1744)
> Run disp tests during integration tests

- go/lib/sciond/mock.go
- go/lib/sciond/sciond.go
- go/lib/sciond/sciond.goconvey
Fixes #1701.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1738)
> Add context support to SCIOND client API

- go/lib/revcache/memrevcache/memrevcache.go
- go/sciond/main.go
So that it can also be used by the future go PS
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1737)
> Move revcache implementation to lib

- .circleci/config.yml
- go/examples/pingpong/pp_integration/main.go
- integration/common.sh
- integration/integration_test.sh
- integration/revocation_test.sh
- python/topology/generator.py
- scion.sh
- tools/ci/clean_up
- tools/ci/integration
- tools/ci/setup_container
- tools/dc.sh
- topology/Default.topo
- topology/Tiny.topo
- topology/Wide.topo
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1755)
> Run dockerized topology on the CI

- go/lib/infra/modules/trust/trust_test.go
- go/lib/infra/modules/trust/trustdb/db_test.go
Instead of always creating a temp file, which has significant overhead.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1760)
> testing: Use in memory DB

- .circleci/config.yml
- docker/README.md
- integration/common.sh
- integration/integration_test.sh
- integration/revocation_test.sh
- scion.sh
- tools/ci/clean_up
- tools/ci/common
- tools/ci/common.sh
- tools/ci/docker_update
- tools/ci/integration
- tools/ci/local
- tools/ci/setup_container
- tools/dc.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1765)
> Fix CI slow infra startup timeouts

- go/lib/infra/modules/segsaver/segsaver.go
- go/lib/infra/modules/segverifier/segverifier.go
- go/sciond/internal/fetcher/fetcher.go
We will need the same code as in fetcher in the path server's
segReg handler
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1746)
> Introduce SegStorage

- go/lib/sqlite/sqlite.go
Also make sure to close the db in sqlite.go if the initialization fails.
Fixes #1752
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1756)
> Use write ahead logging in sqlite

- go/lib/infra/modules/trust/trustdb/db.go
Thanks to @benrothen for pointing out.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1773)
> Add missing defer

- c/dispatcher/dispatcher.c
- c/lib/filter/filter.c
- c/lib/scion/address.c
- c/lib/scion/address.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1777)
> Proper AS format support for C

- python/path_server/local.py
Fixes #1735
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1757)
> PS: improve segments returned

- doc/PathService.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1767)
> Add PS design doc

- .circleci/config.yml
- go/vendor/vendor.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1784)
> Update go-sqlite to master

- go/sciond/internal/fetcher/fetcher.go
Fixes #1780
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1795)
> go-sciond: Do not lookup pathDB with empty start/ends at

- go/lib/topology/addr.go
- go/lib/topology/addr_test.go
Fixes #1792
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1793)
> topo: Ensure that bind address != pub address

- go/lib/snet/conn.go
Currently the nexthop address when writting to a destination in the
local AS is ignored.
With this change the nexthop address will be used regardless of the
destination being in the local AS or not, while still having the same
functionality in the case of not specifying a nexthop.
Also returns an error if a path without a nexthop has been provided.
Fixes #1503
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1789)
> snet: do not ignore nexthop address for local AS dst

- go/lib/pathdb/sqlite/sqlite.go
Fixes #1791
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1794)
> pathdb: Don't do manual string interpolation for queries

- go/cert_srv/setup.go
- go/sig/sigcmn/common.go
Sometimes supervisord might be slow and it takes some time, until sciond
is initialized.
Fixes #1621
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1802)
> SIG: Add retry and timeout while connecting to SCIOND

- go/lib/sciond/sciond.go
- go/lib/snet/conn.go
- go/lib/snet/integration_test.go
- go/lib/snet/snet.go
- go/lib/snet/squic/squic.go
- go/lib/sock/reliable/reliable.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1809)
> Timeout of 0 in snet and reliable now means infinity

- go/lib/ctrl/seg/seg.go
So a segment can be used as a path for example when creating a snet.Addr.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1811)
> Add RawWriteTo method to PathSegment in seg.go

- doc/PathService.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1798)
> PS-DD: Add details about down seg sync

- go/lib/ctrl/path_mgmt/seg_recs.go
- go/lib/ctrl/path_mgmt/seg_reply.go
- go/lib/ctrl/seg/meta.go
- go/lib/ctrl/seg/seg.go
- go/lib/env/env.go
- go/lib/infra/common.go
- go/lib/infra/messenger/messenger.go
- go/lib/infra/messenger/mock.go
- go/lib/infra/modules/segsaver/segsaver.go
- go/lib/pathdb/sqlite/sqlite.go
- go/lib/topology/topology.go
- go/lib/xtest/graph/graph.go
- go/path_srv/internal/handlers/common.go
- go/path_srv/internal/handlers/segreg.go
- go/path_srv/internal/handlers/segreq.go
- go/path_srv/internal/handlers/segreqcore.go
- go/path_srv/internal/handlers/segreqnoncore.go
- go/path_srv/internal/handlers/segreqnoncore_test.go
- go/path_srv/internal/handlers/segrevoc.go
- go/path_srv/internal/handlers/segsync.go
- go/path_srv/internal/handlers/testdata/topology_as1_132.json
- go/path_srv/internal/handlers/testdata/topology_as2_211.json
- go/path_srv/internal/handlers/testdata/topology_as2_222.json
- go/path_srv/main.go
- go/sciond/internal/fetcher/fetcher.go
- python/topology/generator.py
Still many open TODOs, some of them:
* Prometheus metrics
* Result pruning
* Reduce code duplication between sciond and PS and in PS itself
* Add more tests
* Periodically delete expired segs/revocation
* New down seg replication between cores
* Better caching logic
...
In this state the go PS should not be used yet.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1783)
> Initial go PS

- go/cert_srv/reiss_handler.go
- go/cert_srv/reiss_tasks.go
- go/lib/ctrl/cert_mgmt/cert_mgmt.go
- go/lib/infra/modules/trust/trust.go
- go/lib/infra/modules/trust/trust_test.go
- go/lib/infra/modules/trust/trustdb/db.go
- go/lib/infra/modules/trust/trustdb/db_test.go
- go/lib/scrypto/cert/cert.go
- go/lib/scrypto/defs.go
- go/lib/scrypto/trc/trc.go
- go/path_srv/internal/handlers/segreg.go
- go/path_srv/internal/handlers/segreq.go
Use the constant `cert_mgmt.NewestVersion` instead of 0. (fixes #1813)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1822)
> trust: Use constant for latest version

- go/lib/ctrl/path_mgmt/seg_req.go
- go/path_srv/internal/handlers/segreqnoncore_test.go
- go/sciond/internal/fetcher/fetcher.go
- proto/path_mgmt.capnp
Fixes #1825
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1827)
> Use a named struct for SegReq flags

- go/lib/pathdb/query/query.go
- go/lib/pathdb/sqlite/sqlite.go
- go/lib/pathdb/sqlite/sqlite_test.go
-Enable the usage of multiple SegIDs
-Add MinLastUpdate value to query for the LastUpdate value
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1832)
> pathdb: Enhance query.Params

- go/lib/ctrl/seg/seg.go
- go/lib/ctrl/seg/signed.go
- go/lib/pathdb/pathdb.go
- go/lib/pathdb/sqlite/schema.go
- go/lib/pathdb/sqlite/sqlite.go
- go/lib/pathdb/sqlite/sqlite_test.go
- go/path_srv/internal/cleaner/cleaner.go
- go/path_srv/main.go
Fixes #1818
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1830)
> Introduce cleaner, to periodically clean the pathDB

- go/lib/pathdb/query/query.go
- go/lib/pathdb/sqlite/sqlite.go
- go/path_srv/internal/addrutil/addrutil.go
- go/path_srv/internal/handlers/common.go
- go/path_srv/internal/handlers/segreg.go
- go/path_srv/internal/handlers/segreq.go
- go/path_srv/internal/handlers/segreqcore.go
- go/path_srv/internal/handlers/segreqnoncore.go
- go/path_srv/internal/handlers/segsync.go
- go/path_srv/internal/periodic/periodic.go
- go/path_srv/internal/segsyncer/segsyncer.go
- go/path_srv/main.go
This decouples the down sync logic from the segReg handler.
It will also lead to less messages since we can send multiple segments in a single message.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1841)
> PS: Sync downSegs periodically not on receive

- doc/PathService.md
- go/lib/ctrl/path_mgmt/path_mgmt.go
- go/lib/ctrl/path_mgmt/seg_changes.go
- go/lib/infra/common.go
- go/lib/infra/messenger/messenger.go
- go/lib/infra/messenger/mock.go
- proto/path_mgmt.capnp
Contributes #1817
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1848)
> PS: Introduce messages for the new down segment sync

- go/lib/pathdb/pathdb.go
- go/lib/pathdb/sqlite/schema.go
- go/lib/pathdb/sqlite/sqlite.go
- go/lib/pathdb/sqlite/sqlite_test.go
- go/path_srv/internal/handlers/common.go
- go/path_srv/internal/handlers/segreq.go
- go/path_srv/internal/handlers/segreqcore.go
- go/path_srv/internal/handlers/segreqnoncore.go
- go/path_srv/internal/psconfig/psconfig.go
- go/path_srv/main.go
Fixes #1816
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1856)
> PS: Periodically refetch segments for a dst

- .circleci/config.yml
- go/Makefile
- go/border/io.go
- go/border/metrics/metrics.go
- go/border/rpkt/create.go
- go/border/rpkt/rpkt_hook_test.go
- go/border/setup.go
- go/examples/pingpong/pingpong.go
- go/lib/infra/disp/disp.go
- go/lib/infra/messenger/messenger.go
- go/lib/infra/modules/trust/key_conf.go
- go/lib/infra/modules/trust/trust.go
- go/lib/l4/udp_test.go
- go/lib/pathmgr/syncpaths_test.go
- go/lib/scrypto/trc/trc_test.go
- go/lib/sock/reliable/reliable_test.go
- go/lib/topology/topology_test.go
- go/tools/scion-pki/internal/cmd/cmd.go
- go/tools/scmp/main.go
- go/vendor/vendor.json
Fixes #1713
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1860)
> lint: Use lll to check line len in go code

- go/lib/topology/topology.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1871)
> Disallow illegal link types in lib/topology.

- go/sciond/internal/fetcher/fetcher.go
The PS can handle that just fine and will return segments to any cPS in the requested ISD.
This also resolves the FIXME since the PS will only return segments to reachable cores.
Also Fixes #1778
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1865)
> sciond: Remove special handling of ISD-0 request

- go/lib/pathdb/sqlite/sqlite.go
- go/sciond/internal/fetcher/fetcher.go
- go/sciond/internal/sdconfig/sdconfig.go
- go/sciond/main.go
Also fix the rollback logic in sqlite, it should b.tx should be nil after rollback.
Fixes #1868
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1872)
> sciond: Refetch path segments after some time

- go/lib/infra/modules/combinator/combinator.go
- go/lib/infra/modules/combinator/combinator_test.go
- go/lib/infra/modules/combinator/graph.go
- go/lib/infra/modules/combinator/testdata/00_loops.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1874)
> Path combinator fixes

- go/lib/pathdb/pathdb.go
- go/lib/pathdb/query/query.go
- go/lib/pathdb/sqlite/sqlite.go
- go/lib/pathdb/sqlite/sqlite_test.go
- go/sciond/internal/fetcher/fetcher.go
This is a workaround for #1876, it is solution 3.5 (partial flush of the DB).
In the long term we should find a better solution.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1877)
> sciond: Workaround for first hop border router outage

- go/path_srv/internal/handlers/common.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1882)
> PS: Add missing initialization of config

- go/lib/snet/snetproxy/conn.go
- go/lib/snet/snetproxy/conn_io_test.go
Previously, `snetproxy.Conn` had a common lock that was taken both during reads and writes. This caused problems in servers, which are always blocked trying to read new messages from the network; thus, writes never get through.
This fixes the issue, by using separate locks for reads and writes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1905)
> snetproxy can do reads and writes in parallel

- go/sciond/internal/sdconfig/sdconfig.go
- go/sciond/main.go
Fixes #1892 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1920)
> Let SD_go create socket directories by default

- python/integration/base_cli_srv.py
- python/integration/cert_req_test.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1917)
> Fix integration tests to not loop forever when failing

- go/lib/infra/messenger/messenger.go
Initialize path
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1942)
> Init path in infra messenger

- scion.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1954)
> Prevent scion.sh from exiting if host zk isn't running.

- go/lib/infra/modules/segsaver/segsaver.go
- go/lib/pathdb/pathdb.go
- go/lib/pathdb/sqlite/sqlite.go
- go/lib/pathdb/sqlite/sqlite_test.go
- go/path_srv/internal/handlers/segreqnoncore_test.go
We never insert multiple types together with a single segment.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1936)
> Change pathdb insert to accept seg.Meta

- go/lib/env/env.go
- go/lib/infra/infraenv/infraenv.go
- go/path_srv/main.go
- go/sciond/main.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1915)
> Integrate topology reloading in Go infra

- go/lib/topology/topology.go
- go/lib/topology/topotestutil/topotestutil.go
- proto/common.capnp
- python/lib/topology.py
- python/lib/types.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1953)
> DS: Add service type

- env/go/common.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1957)
> Expand env/go to allow >= go 1.9.4

- go/lib/pathdb/pathdbtest/pathdbtest.go
- go/lib/pathdb/sqlite/sqlite_test.go
So we can reuse the same testing code for multiple backend implementations.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1940)
> Create a pathdbtest test suite

- go/lib/log/wrappers.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1964)
> Fix sublogger context initialization

- go/lib/ctrl/path_mgmt/seg_recs.go
- go/lib/ctrl/seg/seg.go
- go/lib/ctrl/seg/segs_test.go
- go/lib/infra/messenger/messenger.go
- go/lib/infra/modules/segsaver/segsaver.go
- go/path_srv/internal/handlers/common.go
- go/path_srv/internal/handlers/log.go
- go/path_srv/internal/handlers/segreg.go
- go/path_srv/internal/handlers/segreq.go
- go/path_srv/internal/handlers/segsync.go
- go/sciond/internal/fetcher/fetcher.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1947)
> Simplify some PS logging

- python/test/lib/topology_test.py
- python/topology/generator.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1962)
> DS: generate DS entry

- go/border/router.go
- go/cert_srv/conf/conf.go
- go/cert_srv/main.go
- go/cert_srv/reiss_tasks.go
- go/lib/env/env.go
- go/lib/infra/messenger/counter.go
- go/lib/scrypto/rand.go
- go/lib/snet/integration_test.go
- go/lib/sock/reliable/bench_test.go
- go/path_srv/internal/handlers/segreq.go
- go/path_srv/internal/handlers/segreqnoncore.go
- go/path_srv/internal/segsyncer/segsyncer.go
- go/sciond/internal/fetcher/fetcher.go
- go/tools/scmp/cmn/common.go
Also make sure there can only be one counter per app.
Fixes #1951
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1965)
> Make sure the reqId counter is initialized

- go/lib/pathdb/sqlite/sqlite.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1978)
> Prepare statement once instead of in loop.

- python/lib/path_store.py
- python/test/lib/path_store_test.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1990)
> Allow some grace period for BS PCB policy.

- go/border/rpkt/parse.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1983)
> border: properly print dereferenced pointer value

- c/lib/scion/opaque_field.h
- go/lib/spath/hop.go
- python/lib/flagtypes.py
- python/lib/packet/opaque_field.py
- tools/wireshark/scion.lua
Fixes #1664
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1993)
> Drop RECURSE hop-field flag

- .gitignore
- doc/PathPolicy.md
- go/lib/pathmgr/pathmgr_test.go
- go/lib/pathpol/acl.go
- go/lib/pathpol/hop_pred.go
- go/lib/pathpol/hop_pred_test.go
- go/lib/pathpol/policy.go
- go/lib/pathpol/policy_test.go
- go/lib/sciond/types.go
- go/lib/spath/spathmeta/pred_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1976)
> Refactor pathpol for better serialization and prepare removal of Action

- go/lib/ctrl/seg/segs.go
- go/lib/revcache/memrevcache/memrevcache.go
- go/lib/revcache/revcache.go
- go/path_srv/internal/handlers/common.go
- go/path_srv/internal/handlers/ifstateinfo.go
- go/path_srv/internal/handlers/segreq.go
- go/path_srv/internal/handlers/segrevoc.go
- go/path_srv/internal/segsyncer/segsyncer.go
- go/path_srv/internal/segutil/segutil.go
- go/sciond/internal/fetcher/fetcher.go
- go/sciond/internal/servers/handlers.go
Also add error return values.
If we want to have a more complex backend like a DB we need error and ctx.
Fixes #1992
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1995)
> revcache: Contextualize interface

- go/lib/pathdb/pathdbtest/pathdbtest.go
- go/lib/pathdb/sqlite/sqlite.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1991)
> pathdb: Use context in GetNextQuery

- c/lib/scion/packet.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1998)
> dispatcher: update src/dst address type when reversing a packet

- tools/docker-ip
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2002)
> Add tools/docker-ip.

- go/lib/infra/infraenv/infraenv.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2011)
> Fix no-op timeout in infraenv's init network code.

- go/lib/snet/snetproxy/reconnecter_test.go
Fixes https://github.com/scionproto/scion/issues/1979
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2018)
> Fix racey unit test in snetproxy

- go/lib/ctrl/path_mgmt/rev_info.go
- go/lib/revcache/memrevcache/memrevcache.go
- go/lib/revcache/memrevcache/memrevcache_test.go
- go/lib/revcache/revcachetest/revcachetest.go
- go/proto/gen.go
So we have some tests for memrevcache and other possible backends.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2003)
> Introduce test suite for revcache

- tools/ci/integration
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2024)
> Use go SCIOND and PS on the CI

- go/border/netconf/interface.go
- go/lib/topology/topology.go
- go/lib/topology/topology_test.go
- python/lib/topology.py
- python/test/lib/topology_test.py
fixes #2004
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2005)
> lib: Support parsing stripped topology file

- go/lib/env/logging.go
- go/path_srv/main.go
- go/sciond/main.go
Fixes #2036
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2044)
> PS,SD: Make sure log is flushed on exit

- go/tools/showpaths/paths.go
fixes #2040
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2042)
> Showpaths: Add refresh flag

- go/lib/topology/topology.go
fixes #2006
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2043)
> lib: Disallow reserved values in topology ISD-AS

- go/path_srv/internal/handlers/segrevoc.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2034)
> Refactor revocation handler message

- go/lib/infra/dedupe/dedupe.go
- go/lib/infra/dedupe/dedupe_test.go
- go/lib/infra/modules/trust/trust.go
So that we can easily mock this during tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2028)
> Make Deduper an interface

- .buildkite/pipeline.yml
- docker.sh
- tools/ci/bk_clean_up
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2008)
> Switch to Buildkite

- go/lib/pathstorage/pathstorage.go
- go/path_srv/internal/psconfig/psconfig.go
- go/path_srv/internal/psconfig/sample.go
- go/path_srv/internal/psconfig/sample_test.go
- go/path_srv/main.go
- go/sciond/internal/sdconfig/sample.go
- go/sciond/internal/sdconfig/sample_test.go
- go/sciond/internal/sdconfig/sdconfig.go
- go/sciond/main.go
- python/topology/generator.py
A factory for PathDB and the RevCache.
With this we can configure what backend we want to use.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2048)
> Introduce pathstorage

- go/lib/infra/modules/segverifier/segverifier.go
This was currently missing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2055)
> Call log.LogPanicAndExit in go routines

- .buildkite/pipeline.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2058)
> Fix buildkite on master

- python/topology/topo.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2062)
> gen: Respect DS flag

- go/lib/integration/binary.go
- go/lib/integration/integration.go
fixes #2063
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2065)
> lib: Add timeout to binaryIntegration.StartServer

- acceptance/topo_ps_reloads_br_acceptance/test
- go/path_srv/internal/handlers/segreq.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2082)
> Add acceptance test: PS reloads known BRs

- go/path_srv/main.go
If we need deeper insights into the PS this will be helpful.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2086)
> PS: Import net/http/pprof

- go/lib/ctrl/seg/seg.go
- go/lib/pathdb/pathdbtest/pathdbtest.go
- go/lib/pathdb/sqlite/schema.go
- go/lib/pathdb/sqlite/sqlite.go
- go/path_srv/internal/handlers/segreqnoncore_test.go
Fixes #1946
With this commit we also introduce FullId which contributes to #1817
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2064)
> pathdb: Update IntfToSeg mapping

- go/cert_srv/setup.go
- go/lib/infra/example/main.go
- go/lib/infra/modules/trust/trust.go
- go/lib/infra/modules/trust/trust_test.go
- go/path_srv/main.go
- go/sciond/main.go
fixes #2073
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2087)
> trust: Use messenger.NextId()

- go/lib/infra/modules/trust/trust.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2091)
> PS: Push TRC to local CS

- go/sciond/internal/fetcher/fetcher.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2095)
> Asking SD for 0 paths means all paths

- python/topology/common.py
- python/topology/config.py
- python/topology/docker.py
- python/topology/net.py
- python/topology/prometheus.py
- python/topology/supervisor.py
- python/topology/topo.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2097)
> Add PortGenerator for deterministic port allocation

- go/lib/infra/modules/trust/trust.go
- go/lib/infra/modules/trust/trustdb/db.go
- go/lib/infra/modules/trust/trustdb/db_test.go
- go/lib/infra/modules/trust/trustdb/testdata/ISD2-ASff00_0_212-V1.crt
- go/lib/infra/modules/trust/trustdb/testdata/ISD2-V1.trc
- go/path_srv/internal/cryptosyncer/cryptosyncer.go
- go/path_srv/main.go
This is a temporary workaround for #2083
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2100)
> PS: Push crypto to CS periodically

- acceptance/topo_ps_reloads_br_acceptance/test
- acceptance/topo_ps_reloads_cs_acceptance/test
- acceptance/topo_sd_reloads_br_acceptance/test
- acceptance/topo_sd_reloads_cs_acceptance/test
- acceptance/topo_sd_reloads_ps_acceptance/test
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2107)
> Add acceptance test: PS reloads known CSes

- python/topology/generator.py
- python/topology/topo.py
- topology/Default.topo
- topology/Tiny.topo
Fixes #2106
Did not update the IFIDs in `xtest/graph`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2110)
> Use IFIDs from topology file

- go/cert_srv/internal/csconfig/conf.go
- go/cert_srv/internal/csconfig/conf_test.go
- go/cert_srv/internal/csconfig/sample.go
- go/cert_srv/internal/csconfig/testdata/csconfig.toml
- go/cert_srv/main.go
- go/lib/infra/modules/trust/trust.go
- python/topology/config.py
Fixes #1642
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2109)
> Switch to CS:GO

- go/tools/showpaths/paths.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2117)
> Add copyright notice for commit dff8442ff37d507d1c5b4ff1e2fcc2dbebf63cb1

- .buildkite/setup.yml
- .circleci/config.yml
- acceptance/topo_sd_reloads_cs_acceptance/test
- go/vendor/vendor.json
- scion.sh
Contains a formatting fix:
https://github.com/kormat/fmt15/commit/ee69fecb2656a4de8ac47df338ad7e7f9e056dd5
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2118)
> Update fmt15 dependency.

- go/sig/egress/session/sessmon.go
Fixes #2070
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2124)
> Honor path TTLs

- go/lib/snet/base.go
- go/lib/snet/conn.go
- go/lib/snet/reader.go
- go/lib/snet/snet.go
- go/lib/snet/writer.go
This allows safer refactoring in the future (and paves the way for #1702).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2134)
> Split reader, writer and basic info in snet.

- acceptance/lib.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2135)
> Fix issue with run_command and set -e in acceptance/lib.sh

- go/cert_srv/main.go
- go/examples/discovery_client/client.go
- go/lib/periodic/periodic.go
- go/lib/periodic/periodic_test.go
- go/path_srv/internal/segsyncer/segsyncer.go
- go/path_srv/main.go
- go/sciond/main.go
- python/topology/topo.py
Also slightly refactor the topo generator
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2136)
> Add Kill method to periodic

- python/topology/generator.py
- python/topology/go.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2143)
> Trace logging in test topology can now be toggled

- go/cert_srv/internal/csconfig/conf_test.go
- go/cert_srv/internal/csconfig/sample.go
- go/cert_srv/main.go
- go/cert_srv/setup.go
- go/lib/env/env.go
- go/lib/env/env_test.go
- go/lib/truststorage/truststorage.go
- go/path_srv/internal/psconfig/sample.go
- go/path_srv/internal/psconfig/sample_test.go
- go/path_srv/main.go
- go/sciond/internal/sdconfig/sample.go
- go/sciond/internal/sdconfig/sample_test.go
- go/sciond/main.go
- python/topology/go.py
Introduce truststorage so that backend of trustdb can be configurable.
Fixes #2142
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2144)
> trustdb: Make backend configurable

- go/lib/addr/isdas.go
- go/lib/env/env.go
- go/lib/topology/topology.go
- go/sig/base/core/as.go
- go/sig/base/core/map.go
- go/sig/egress/router/router.go
- go/sig/internal/sigconfig/conf.go
- go/sig/internal/sigconfig/conf_test.go
- go/sig/internal/sigconfig/sample.go
- go/sig/main.go
- go/sig/metrics/metrics.go
- go/sig/sigcmn/common.go
- go/sig/xnet/xnet.go
- go/tools/scion-pki/internal/conf/isd.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2114)
> SIG: Port to lib/env

- go/sig/egress/session/sessmon.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2149)
> Expiration of path statistics

- .buildkite/clean_env.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2150)
> Fix buildkite env cleanup

- go/Makefile
- go/lib/snet/conn.go
- go/lib/snet/internal/ctxmonitor/ctxmonitor.go
- go/lib/snet/internal/ctxmonitor/ctxmonitor_test.go
- go/lib/snet/snet.go
- go/lib/snet/writer.go
- go/lib/snet/writer_test.go
Fixes #1702.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2152)
> Enforce deadlines in snet path resolution

- go/integration/common.go
- go/integration/end2end/main.go
Also always wait between attempts.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2167)
> Return better errors in end2end tests

- .buildkite/acceptance.sh
- .buildkite/docker-integration.yml
#2161 Broke the CI build, this commit fixes it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2172)
> Fix build after test logging changes

- go/lib/snet/internal/ctxmonitor/ctxmonitor_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2174)
> Fix flaky ctxmonitor unit test

- go/sig/internal/sigconfig/conf.go
- go/sig/main.go
- go/sig/xnet/xnet.go
Fixes #2023
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2190)
> Specify source hint in SIG routing table

- go/lib/infra/disp/disp.go
- go/lib/infra/disp/wtable.go
- go/lib/infra/errors.go
- go/lib/snet/rpt/rpt.go
Fixes #2147
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2199)
> Replace context canceled by real error

- go/lib/pktdisp/disp.go
- go/sig/config/config.go
- go/sig/disp/disp.go
- go/sig/egress/session/session.go
Fixes #2181 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2185)
> SIG: Stop dispatcher when remote IA is removed

- go/lib/sciond/types.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2211)
> Add missing error descriptions for SCIOND errors

- go/cert_srv/internal/csconfig/sample.go
- go/lib/env/logging.go
- go/lib/env/testdata/cs.toml
- go/lib/log/flags.go
- go/lib/log/log.go
- go/path_srv/internal/psconfig/sample.go
- go/sciond/internal/sdconfig/sample.go
- go/sig/internal/sigconfig/sample.go
fixes #2202
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2214)
> log: Support MaxBackups log rotation

- docker/perapp/app/Dockerfile.border
- go/border/brconf/conf.go
- go/border/brconf/params.go
- go/border/brconf/sample.go
- go/border/main.go
- go/border/metrics/metrics.go
- go/border/rctx/rctx.go
- go/border/router.go
- go/border/rpkt/rpkt_test.go
- go/border/setup.go
- go/lib/env/logging.go
- go/lib/profile/profile.go
- python/topology/common.py
- python/topology/config.py
- python/topology/docker.py
- python/topology/go.py
- python/topology/supervisor.py
- scion.sh
fixes #2223
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2240)
> BR: Port to lib/env

- go/lib/pathmgr/pathmgr_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2243)
> Fix flaky unit test

- python/lib/crypto/trc.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2246)
> Fix typo in TRC update verification error message

- go/sig/config/testdata/01-loadfromfile.json
- python/topology/common.py
- python/topology/sig.py
- python/topology/topo.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2244)
> Only generate SIG configs if necessary

- acceptance/brutil/br-conf/brconfig.toml
- acceptance/brutil/br-core-conf/brconfig.toml
- acceptance/brutil/common.sh
- acceptance/brutil/docker-compose.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2248)
> Accept: Fix BR acceptance tests

- go/path_srv/main.go
This simplifies the main code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2255)
> PS: Introduce struct for periodic tasks.

- go/lib/infra/modules/trust/trustdb/trustdb.go
- go/lib/infra/modules/trust/trustdb/trustdbsqlite/db.go
- go/lib/infra/modules/trust/trustdb/trustdbtest/trustdbtest.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2251)
> TrustDB: Make it possible to use transactions

- go/lib/revcache/memrevcache/memrevcache_test.go
- go/lib/revcache/revcachetest/revcachetest.go
Test that expired revocations are never returned.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2197)
> Add more revcache tests

- go/lib/pathstorage/pathstorage.go
- go/lib/revcache/cleaner.go
- go/lib/revcache/memrevcache/memrevcache.go
- go/lib/revcache/memrevcache/memrevcache_test.go
- go/lib/revcache/revcache.go
- go/lib/revcache/revcachetest/revcachetest.go
- go/path_srv/internal/handlers/common_test.go
- go/path_srv/internal/handlers/segreqnoncore_test.go
- go/path_srv/main.go
- go/sciond/main.go
If we want to add metrics, or more complex backends we need to have full control over the deletion of expired data.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2260)
> Add periodic cleaner for revCache

- .buildkite/pipeline.sh
- .buildkite/scripts/agent_startup
- acceptance/lib.sh
- acceptance/reconnecting_acceptance/test
- go/sig/egress/worker/worker.go
- go/sig/main.go
Also remove SIG debug log.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2261)
> Acceptance: Fix reconnecting

- acceptance/common.sh
- acceptance/sig_iperf_acceptance/test
- acceptance/sig_ping_acceptance/test
- acceptance/sig_reload_acceptance/test
- acceptance/sigutil/SIG.topo
- acceptance/sigutil/common.sh
- docker/Dockerfile.tester
- go/acceptance/sig_iperf_acceptance/main.go
- go/acceptance/sig_ping_acceptance/main.go
- go/acceptance/sigcmn.go
- go/integration/cli_srv_ext_pyintegration/main.go
- go/lib/integration/binary.go
- go/lib/integration/docker.go
- go/lib/integration/integration.go
- go/tools/scmp/scmp_integration/main.go
- integration/bin_wrapper.sh
- python/topology/docker_utils.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2179)
> SIG: iperf and reload acceptance tests

- python/topology/docker.py
- python/topology/sig.py
Leftover from #2121
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2263)
> Remove SIGs from sig.json

- go/lib/infra/modules/trust/trust.go
We saw many problems during tests. As a next step we will also add ACKs and wait until we received the ACk.
(See also #2262)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2266)
> Push Chains & TRC in sync instead of async

- docker.sh
- docker/Dockerfile
- go/Makefile
- tools/git-version
git is not available in docker otherwise.
Fixes #2227
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2275)
> Pass git version into docker container

- .buildkite/steps/acceptance
- go/lib/integration/binary.go
- go/lib/integration/integration.go
- integration/bin_wrapper.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2273)
> Integration tests: Fix log time

- go/lib/pathdb/cleaner.go
- go/path_srv/main.go
- go/sciond/main.go
It makes more sense to have it in the same package.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2279)
> Move pathDB cleaner to pathdb package

- go/godispatcher/main_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2290)
> Fix race in dispatcher integration test

- go/lib/pathpol/hop_pred.go
- go/lib/pathpol/hop_pred_test.go
This patch also adds a serialization unit test.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2288)
> Fix a bug in HopPredicate serialization

- go/godispatcher/internal/config/config.go
- go/godispatcher/internal/config/config_test.go
- go/godispatcher/internal/config/sample.go
- go/godispatcher/main.go
- go/godispatcher/main_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2291)
> Integrate dispatcher backend with application env

- go/path_srv/internal/handlers/segreq.go
- go/path_srv/internal/handlers/segreqnoncore.go
Print destination for remote requests
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2286)
> PS: Improve logging

- go/examples/pingpong/pingpong.go
- go/lib/infra/modules/trust/trust.go
- go/lib/pathmgr/pathmgr.go
- go/lib/pathmgr/pathmgr_test.go
- go/lib/snet/internal/pathsource/pathsource.go
- go/lib/snet/writer_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2293)
> PathMgr: Add flags to Query()

- go/path_srv/internal/handlers/segreqnoncore.go
Fixes #2281
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2284)
> PS: Handle ISD-local AS-wildcard seg requests

- go/lib/topology/topology.go
- go/lib/topology/topology_test.go
To add a helper method to get interface infos by link type.
This will be useful for the BS.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2292)
> topology: Add IfInfoMap type

- go/path_srv/internal/handlers/common.go
- go/path_srv/internal/segsyncer/segsyncer.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2298)
> PS: Handle error from revcache in segment filtering

- go/sciond/internal/fetcher/fetcher.go
Fixes #2282
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2283)
> sciond: Handle ISD-local AS-wildcard path requests

- go/border/brconf/conf.go
Expose `WithNewTopo` to copy config except for fields related to topology.
In a follow-up PR this will be used to set an updated topology without the need to setup a completely new config.
Additionally, refactor code into smaller functions.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2301)
> BR: Refactor config loading

- go/Makefile
- go/path_srv/internal/handlers/common_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2305)
> PS: Add a test for fetchDB helper method

- go/godispatcher/internal/config/config.go
- go/godispatcher/internal/config/config_test.go
- go/godispatcher/internal/config/sample.go
- go/godispatcher/internal/registration/iatable.go
- go/godispatcher/internal/registration/iatable_test.go
- go/godispatcher/internal/registration/portlist.go
- go/godispatcher/internal/registration/svctable.go
- go/godispatcher/internal/registration/svctable_test.go
- go/godispatcher/internal/registration/table.go
- go/godispatcher/internal/registration/table_test.go
- go/godispatcher/main.go
- go/godispatcher/network/app_socket.go
- go/godispatcher/network/defines.go
- go/godispatcher/network/overlay.go
- go/lib/addr/host.go
- go/lib/hpkt/read.go
Go dispatcher now passes end to end, but still lacks SCMP support.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2309)
> Add SVC Multicast capabilities to Go dispatcher

- python/topology/common.py
- python/topology/config.py
- python/topology/go.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2318)
> Fix custpk tool usage in topology generation

- .buildkite/steps/integration
- tools/ci/integration
Split integration tests in different parts such that they can run in parallel on the CI.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2276)
> Split integration tests on CI

- go/lib/infra/modules/segverifier/segverifier.go
- go/lib/scrypto/asym.go
- go/proto/sign.go
Fixes #2175
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2196)
> Better signature verification error

- go/lib/infra/common.go
- go/lib/infra/messenger/messenger.go
Add support for IfId and Seg messages, this will be needed for the BS.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2327)
> messenger: Support more message types

- go/lib/infra/messenger/utils.go
- go/lib/infra/modules/trust/handlers.go
- go/path_srv/internal/handlers/segreg.go
- go/path_srv/internal/handlers/segrevoc.go
- go/path_srv/internal/handlers/segsync.go
Send app level acks for received SegSync, SegRevoc, and SegReg messages.
Fixes #2331
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2332)
> PS: Send app level Acks for pushes

- c/dispatcher/dispatcher.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2334)
> Dispatcher: verify result of parse_request() before using it

- go/godispatcher/network/app_socket.go
- go/godispatcher/network/overlay.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2333)
> Go dispatcher: Register SCMP Request IDs

- acceptance/common.sh
- python/topology/common.py
- python/topology/docker.py
- python/topology/go.py
- python/topology/prometheus.py
- python/topology/supervisor.py
* Use scion port for docker topo, so that we have a different port per instance.
* Add prom config to Go PS and CS
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2335)
> generator: Fix prometheus setup

- go/lib/scmp/pld.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2337)
> Delete private field from SCMP Payload

- python/topology/common.py
- python/topology/config.py
- python/topology/go.py
- python/topology/prometheus.py
- python/topology/topo.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2341)
> generator: Generate prom addr for sciond

- python/topology/common.py
- python/topology/docker.py
- python/topology/topo.py
The previous pr #2341 broke it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2342)
> Fix generator for dockerized topo

- go/border/braccept/main.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2315)
> braccept: use log to have timestamps on messages

- go/border/metrics/metrics.go
- go/cert_srv/internal/metrics/metrics.go
- go/cert_srv/setup.go
- go/godispatcher/main.go
- go/godispatcher/main_test.go
- go/lib/prom/prom.go
- go/lib/ringbuf/metrics.go
- go/path_srv/internal/metrics/metrics.go
- go/path_srv/main.go
- go/sciond/internal/metrics/metrics.go
- go/sciond/main.go
- go/sig/metrics/metrics.go
While that is generally not recommended by prometheus, it is what applies best for our usecase.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2347)
> Prometheus: Use elem label for all metrics.

- go/Makefile
Force users to pay attention to lint.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2363)
> Lint: Make misspell throw error

- README.md
- docker/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2365)
> README: Add docker install instructions

- .buildkite/steps/acceptance
- .buildkite/steps/build.yml
- .buildkite/steps/build_all.yml
- .buildkite/steps/docker-integration.yml
- .buildkite/steps/setup.yml
- .buildkite/steps/test.yml
- acceptance/brutil/common.sh
- acceptance/common.sh
- acceptance/reconnecting_acceptance/test
- acceptance/sigutil/common.sh
- acceptance/topo_br_reload_if_ip_acceptance/test
- acceptance/topo_br_reload_if_port_acceptance/test
- acceptance/topo_br_reload_util/util.sh
- acceptance/topo_ps_reloads_br_acceptance/test
- acceptance/topo_ps_reloads_cs_acceptance/test
- acceptance/topo_sd_reloads_br_acceptance/test
- acceptance/topo_sd_reloads_cs_acceptance/test
- acceptance/topo_sd_reloads_ps_acceptance/test
Also add timeout to all BK jobs, s.t. a hanging job will not keep blocking agents.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2367)
> Acceptance: List docker containers

- acceptance/reconnecting_acceptance/test
- acceptance/sig_reload_acceptance/test
- acceptance/topo_br_reload_if_ip_acceptance/test
- acceptance/topo_br_reload_if_port_acceptance/test
- acceptance/topo_ps_reloads_br_acceptance/test
- acceptance/topo_ps_reloads_cs_acceptance/test
- acceptance/topo_sd_reloads_br_acceptance/test
- acceptance/topo_sd_reloads_cs_acceptance/test
- acceptance/topo_sd_reloads_ps_acceptance/test
- scion.sh
- tools/ci/integration
- tools/dc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2369)
> WIP: add collect_logs method to tools/dc

- go/godispatcher/internal/registration/iatable.go
- go/godispatcher/internal/registration/iatable_test.go
- go/godispatcher/internal/registration/table.go
- go/godispatcher/main_test.go
- go/godispatcher/network/overlay.go
- go/godispatcher/network/table.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2372)
> Go dispatcher: SCMP ID routing takes IA into account

- go/integration/cert_req/main.go
- go/lib/hostinfo/hostinfo.go
- go/lib/sciond/mock.go
- go/lib/sciond/types.go
- go/sciond/internal/fetcher/fetcher.go
- go/sciond/internal/servers/handlers.go
- go/sig/mgmt/addr.go
HostInfo is not only used by sciond but also by sig mgmt therefore we move it to its own package.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2376)
> Move HostInfo to its own package

- go/border/braccept/brB.go
- go/border/braccept/brC.go
- go/border/braccept/main.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2381)
> braccept: fix timeout

- .buildkite/steps/acceptance
- .buildkite/steps/common.sh
Also add --interactive=never to rm, s.t. it doesn't hang.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2378)
> BK Acceptance: Set hostname in container

- python/topology/common.py
- python/topology/docker.py
- python/topology/go.py
- python/topology/prometheus.py
- python/topology/supervisor.py
Docker topology not supported yet.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2374)
> Topology generator: Add Prometheus for Go Dispatcher

- go/integration/cert_req/main.go
- go/lib/infra/messenger/messenger.go
- go/lib/infra/messenger/messenger_test.go
- go/lib/infra/messenger/metrics.go
- go/lib/infra/modules/trust/trustdb/metrics.go
- go/lib/pathdb/metrics.go
- go/lib/prom/prom.go
- go/path_srv/main.go
Contributes #2329
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2380)
> messenger: Add metrics

- go/godispatcher/internal/metrics/metrics.go
- go/godispatcher/internal/registration/iatable.go
- go/godispatcher/internal/respool/packet.go
- go/godispatcher/main.go
- go/godispatcher/main_test.go
- go/godispatcher/network/app_socket.go
- go/godispatcher/network/overlay.go
- go/lib/addr/host.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2388)
> Go dispatcher: Add metrics

- go/lib/pathmgr/pathmgr.go
- go/lib/pathmgr/watch.go
This should makes polling policy changes much easier to handle, and
simplifies the implementation for
https://github.com/scionproto/scion/issues/2383
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2397)
> Refactor path watch management in Go path manager

- go/lib/pathmgr/pathmgr.go
- go/lib/pathmgr/pathmgr_test.go
- go/lib/pathmgr/polling_policy.go
- go/lib/pathmgr/watch.go
Fixes https://github.com/scionproto/scion/issues/2383.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2404)
> Path manager: revoking all paths causes immediate refresh

- acceptance/brutil/dispatcher-conf/dispconfig.toml
- acceptance/brutil/docker-compose.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2417)
> braccept: use GO dispatcher

- acceptance/common.sh
This can be helpful if tests need to output something with a timestamp.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2418)
> acceptance: add log method to common.sh

- go/lib/snet/raw.go
- go/lib/snet/raw_test.go
This needs https://github.com/scionproto/scion/pull/2422 to be merged first to work.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2423)
> Add extension sorting to raw snet

- go/lib/layers/extensions.go
- go/lib/layers/extensions_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2427)
> Fix acceptance; remove strict length test in extension parsing

- go/lib/snet/snetproxy/conn_io_test.go
- go/lib/snet/snetproxy/main_test.go
- go/lib/snet/snetproxy/network_test.go
This should make the test less flaky.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2437)
> Independent reconnecter unit tests; also adjusted one test timer

- go/path_srv/internal/segutil/segutil_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2474)
> Add unit tests for segutil

- proto/sign.capnp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2479)
> Fix SignedCtrlPld comment in capnp schema

- .buildkite/scripts/agent_startup
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2492)
> BK: Install specific docker version

- .buildkite/scripts/agent_startup
Restart the docker server and set the correct docker version as a tag for the buildkite agent.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2494)
> BK: Set docker version

- scion.sh
- tools/ci/test
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2498)
> Copy testlogs only in the CI

- docker/Dockerfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2499)
> Don't warn about timestamps in the future

- scion.sh
- tools/ci/test
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2503)
> Fix uploading unit test logs in the CI

- .buildkite/scripts/build_scion_img
- README.md
- docker.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2507)
> Remove obsolete reference to sub subdirectory

- go/lib/infra/common.go
- go/lib/infra/infraenv/infraenv.go
- go/lib/infra/messenger/BUILD.bazel
- go/lib/infra/messenger/messenger.go
- go/lib/infra/messenger/messenger_with_metrics.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2508)
> Decouple metrics from infra messenger

- tools/vendor.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2514)
> Fix external dependency linkfarm

- .gitignore
- go/lib/infra/messenger/messenger_with_metrics.go
- go/lib/infra/modules/db/sqler.go
- go/lib/sciond/mock.go
- scion.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2517)
> Fix linting

- go/lib/revcache/BUILD.bazel
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2513)
> bazel: Enable revcache_test in bazel.

- go/lib/revcache/revcachetest/revcachetest.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2516)
> revcachetest: Add test for Get with nil keys

- tools/linkfarm.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2512)
> Generate symlinks to generated files

- acceptance/discovery_infra_fetches_dynamic_acceptance/test
- acceptance/discovery_util/util.sh
- acceptance/topo_ps_reloads_cs_acceptance/test
- acceptance/topo_sd_reloads_br_acceptance/test
- acceptance/topo_sd_reloads_cs_acceptance/test
- acceptance/topo_sd_reloads_ps_acceptance/test
- docker/perapp/app/Dockerfile.sciond
- python/topology/common.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2524)
> Rename sciond dockerized config file

- BUILD.bazel
- go/lib/pathdb/pathdbtest/pathdbtest.go
- go/lib/pathdb/sqlite/sqlite_test.go
- nogo.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2520)
> Add more nogo checks

- acceptance/cert_renewal_acceptance/test
- acceptance/discovery_util/util.sh
- acceptance/reconnecting_acceptance/test
- acceptance/sigutil/common.sh
- acceptance/topo_br_reload_util/util.sh
- acceptance/topo_invalid_reloads_acceptance/test
- acceptance/topo_ps_reloads_br_acceptance/test
- acceptance/topo_ps_reloads_cs_acceptance/test
- acceptance/topo_sd_reloads_br_acceptance/test
- acceptance/topo_sd_reloads_cs_acceptance/test
- acceptance/topo_sd_reloads_ps_acceptance/test
- scion.sh
- tools/ci/integration
In the CI the code is already built, so no need to do this again.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2525)
> CI: Don't build code for ./scion.sh topology

- .buildkite/steps/acceptance
- go/lib/integration/BUILD.bazel
- go/lib/integration/binary.go
- go/lib/integration/integration.go
Also increase the timer and start it only after the server was started.
Hopefully this makes tests less flaky.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2526)
> Test: Better errors for server timeout.

- BUILD.bazel
- WORKSPACE
- nogo.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2527)
> More nogo checks enabled

- docker/perapp/app/Dockerfile.sig
- python/topology/common.py
- python/topology/sig.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2531)
> SIG: Add default config to Dockerfile

- go/lib/scmp/BUILD.bazel
- go/lib/scmp/info.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2541)
> InfoRevocation string format

- go/beacon_srv/internal/ifstate/BUILD.bazel
- go/beacon_srv/internal/ifstate/ifstate_test.go
Currently the unit test is not run.
This PR enables the unit tests and fixes a bug in the test.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2556)
> BS: Fix ifstate test

- go/beacon_srv/internal/beacon/beacondbsqlite/db.go
- go/beacon_srv/internal/beacon/beacondbtest/beacondbtest.go
- go/beacon_srv/internal/beacon/db.go
Allow beacons to be updated and deleted when expired.
Additionally, extend the tests to cover this.
fixes #2549
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2572)
> BS: Extend BeaconDB interface

- go/cert_srv/internal/reiss/handler.go
- go/lib/infra/modules/trust/trustdb/metrics.go
- go/lib/infra/modules/trust/trustdb/metrics_test.go
- go/lib/infra/modules/trust/trustdb/mock_trustdb/trustdb.go
- go/lib/infra/modules/trust/trustdb/trustdb.go
- go/lib/infra/modules/trust/trustdb/trustdbsqlite/db.go
- go/lib/infra/modules/trust/trustdb/trustdbsqlite/db_test.go
- go/lib/infra/modules/trust/trustdb/trustdbtest/trustdbtest.go
- go/path_srv/internal/cryptosyncer/cryptosyncer.go
- go/tools/scion-custpk-load/customers.go
- go/tools/scion-custpk-load/customers_test.go
Fixes #2473
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2584)
> trustdb: Add GetAll methods

- BUILD.bazel
- WORKSPACE
- scion.sh
- tools/gomocks
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2585)
> Install Go mock generator binaries via Bazel

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2593)
> Readme: Add shields

- go/beacon_srv/internal/config/BUILD.bazel
- go/beacon_srv/internal/config/config.go
- go/beacon_srv/internal/config/config_test.go
- go/beacon_srv/internal/config/sample.go
This PR adds the beacon server config.
Currently, the beacon server specific parts are empty.
They will be filled in as needed.
fixes #2482
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2601)
> BS: Add config

- go/cert_srv/setup.go
- go/lib/infra/infraenv/BUILD.bazel
- go/lib/infra/infraenv/infraenv.go
- go/path_srv/main.go
- go/sciond/main.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2607)
> Clean up messenger init in services

- go/godispatcher/network/overlay.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2609)
> Print SVC address as string in dispatcher log

- go/sig/egress/session/sessmon.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2618)
> SIG: Avoid panic on startup

- go/godispatcher/BUILD.bazel
- go/godispatcher/main.go
- go/lib/util/BUILD.bazel
- go/lib/util/fs.go
- go/sciond/internal/config/config.go
Fixes https://github.com/scionproto/scion/issues/2619.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2620)
> Dispatcher creates parent directory of UNIX socket files

- go/lib/infra/modules/combinator/BUILD.bazel
- go/lib/infra/modules/combinator/graph.go
Fixes https://github.com/scionproto/scion/issues/2621.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2622)
> MTU calculation in path combinator takes links into account

- go/lib/infra/common.go
- go/lib/infra/messenger/messenger.go
- go/lib/infra/messenger/messenger_with_metrics.go
- go/lib/infra/mock_infra/infra.go
- go/path_srv/main.go
We will need this for the BS.
Contributes to #2566
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2624)
> messenger: Add SendRev method

- WORKSPACE
Fixes #2632
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2634)
> Make build work with Bazel 0.25.0

- go/beacon_srv/internal/ifstate/BUILD.bazel
- go/beacon_srv/internal/ifstate/doc.go
- go/beacon_srv/internal/ifstate/handler.go
- go/beacon_srv/internal/ifstate/handler_test.go
- go/beacon_srv/internal/ifstate/revoker.go
- go/border/braccept/parser/ctrl.go
- go/lib/ctrl/path_mgmt/ifstate_infos.go
- go/lib/ctrl/path_mgmt/ifstate_req.go
Add a IfStateReq handler for the go BS.
Fixes #2486
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2633)
> BS: Implement IfStateReq handler

- go/beacon_srv/internal/beaconstorage/BUILD.bazel
- go/beacon_srv/internal/beaconstorage/beaconstoragetest/BUILD.bazel
- go/beacon_srv/internal/beaconstorage/beaconstoragetest/config.go
- go/beacon_srv/internal/beaconstorage/beaconstoragetest/config_test.go
- go/beacon_srv/internal/beaconstorage/config.go
- go/beacon_srv/internal/beaconstorage/sample.go
- go/beacon_srv/internal/config/BUILD.bazel
- go/beacon_srv/internal/config/config.go
- go/beacon_srv/internal/config/config_test.go
- python/topology/common.py
- python/topology/config.py
- python/topology/generator.py
- python/topology/go.py
- python/topology/supervisor.py
This PR enables the topology generator to generate toml configurations
for the beacon server.
contributes to #2569
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2642)
> BS: Generate configuration

- go/beacon_srv/internal/beacon/store.go
- go/beacon_srv/internal/beaconstorage/store.go
Add implementation for the following methods:
InsertRevocations, DeleteRevocation, DeleteExpiredRevocations, DeleteRevokedBeacons
to the beacon store.
Fixes #2559
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2646)
> BS: Implement revocation part of store

- go/beacon_srv/internal/beacon/beacondbsqlite/db.go
- go/lib/infra/modules/db/sqler.go
- go/lib/pathdb/sqlite/sqlite.go
Instead of having to reimplement it in every db implementation offer this in the DB lib.
Also simplify some code around the beacon db.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2659)
> db lib: Add DeleteInTx function

- go/lib/scrypto/cert/chain_test.go
Avoid the leaf issuing time be before issuer issuing time.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2675)
> scrypto: Fix unit tests

- go/lib/infra/messenger/messenger.go
This fixes a number of timeout errors. During RPC calls, clients first detect if the servers supports QUIC. If that is not the case, the request is downgraded to UDP, and converted from a Request/Response model to a Notify model (so, identical to the old UDP control plane model).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2676)
> RPC calls over UDP no longer wait for acks

- go/beacon_srv/internal/beacon/BUILD.bazel
- go/beacon_srv/internal/beacon/beacondbsqlite/db.go
- go/beacon_srv/internal/beacon/metrics.go
- go/beacon_srv/internal/beacon/metrics_test.go
- go/beacon_srv/internal/beaconstorage/config.go
- go/lib/infra/modules/db/BUILD.bazel
- go/lib/infra/modules/db/errors.go
- go/lib/infra/modules/db/metrics.go
- go/lib/infra/modules/db/sqler.go
Fixes #2667
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2671)
> BS: Add metrics for beacon DB

- go/lib/infra/messenger/messenger.go
- go/lib/infra/messenger/quic_handler.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2684)
> Add debug IDs and contexts to QUIC messenger handlers

- go/examples/pingpong/pingpong.go
- go/lib/assert/assert.go
- go/lib/infra/modules/db/BUILD.bazel
- go/lib/infra/modules/db/errors.go
- go/lib/infra/modules/db/errors_test.go
- python/topology/go.py
- python/topology/net.py
Currently they panicked because the interface slice was seen as one argument.
Also add some other small fixes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2687)
> Fix lib/db errors

- go/beacon_srv/internal/beacon/store.go
- go/beacon_srv/internal/beacon/store_test.go
- go/beacon_srv/internal/beaconing/propagator.go
Also don't use transaction in core store getBeacons it isn't really needed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2689)
> BS: Fix error log

- .buildkite/pipeline.sh
- docker/acceptance/sig/Dockerfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2690)
> Acceptance: Smaller SIG docker image

- go/beacon_srv/internal/beaconing/originator.go
- go/beacon_srv/internal/beaconing/originator_test.go
- go/beacon_srv/internal/beaconing/propagator.go
- go/beacon_srv/internal/beaconing/propagator_test.go
- go/beacon_srv/internal/onehop/BUILD.bazel
- go/beacon_srv/internal/onehop/sender.go
- go/beacon_srv/main.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2691)
> Refactor beacon sending in BS originator/propagator

- BUILD.bazel
- go/beacon_srv/internal/beacon/beacondbsqlite/db.go
- go/examples/pingpong/pingpong.go
- go/godispatcher/main.go
- go/lib/infra/modules/trust/trustdb/trustdbsqlite/BUILD.bazel
- go/lib/infra/modules/trust/trustdb/trustdbsqlite/db.go
- go/lib/infra/rpc/rpc.go
- go/lib/pathdb/sqlite/BUILD.bazel
- go/lib/pathdb/sqlite/sqlite.go
- go/lib/sciond/reconn.go
- go/lint/BUILD.bazel
- go/lint/log.go
- go/sig/main.go
- go/tools/scmp/cmn/BUILD.bazel
- go/tools/scmp/cmn/common.go
- go/tools/scmp/echo/BUILD.bazel
- go/tools/scmp/echo/echo.go
- nogo.json
Introduces a linter that verifies that go statements call
a func lit that calls defer log.LogPanicAndExit as first statement.
Fixes #2165
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2655)
> Introduce linter for go function calls.

- go/sig/internal/sigconfig/conf.go
- go/sig/internal/sigconfig/sample.go
See: https://github.com/scionproto/scion/wiki/Default-port-ranges
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2693)
> SIG: Use correct default ports

- python/topology/zk.py
- scion.sh
- tools/ci/integration
Go services don't require zookeeper, if we only generate go service we don't need to start zk.
:elephant: :wave:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2698)
> generator: Make zookeeper optional

- tools/ci/integration
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2699)
> Integration: add stop_containers

- go/lib/common/errors.go
- go/lib/infra/messenger/messenger_with_metrics.go
- go/lib/infra/messenger/metrics.go
- go/sig/sigcmn/common.go
- go/tools/scion-pki/internal/certs/gen.go
- go/tools/scion-pki/internal/trc/gen.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2641)
> Log unclassified RPC errors

- acceptance/bs_add_link_acceptance/test
- acceptance/common/base.py
- acceptance/common/scion.py
Make sure the disable-docker flag is respected and the topology
uses supervisor in that case.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2706)
> Accept: Respect disable-docker flag

- go/lib/pathpol/acl.go
- go/lib/pathpol/policy_test.go
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2709)
> Allow acl rule to be nil

- go/path_srv/internal/handlers/ifstateinfo.go
- go/path_srv/main.go
This includes all references, as far as GitHub Search goes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2713)
>  Fix [typo] of Interface State Info Handler cctor

- go/beacon_srv/main.go
Discovery runner is not a BS specific task and therefore doesn't belong to the BS task group.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2714)
> BS: Start discovery runner separate from other tasks

- go/path_srv/internal/handlers/segreqnoncore.go
This prevents head of line blocking and might speed up the PS slightly.
Fixes #1862
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2716)
> PS: Request core segments in parallel

- go/path_srv/internal/handlers/common.go
- go/path_srv/internal/handlers/segreg.go
- go/path_srv/internal/handlers/segreq.go
- go/path_srv/internal/handlers/segreqnoncore_test.go
- go/path_srv/internal/handlers/segsync.go
Also always check the result of verifyAndStore and act accordingly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2722)
> PS: Do not insert next query if reply was empty

- acceptance/discovery_util/util.sh
- acceptance/sigutil/common.sh
- acceptance/topo_br_reload_util/util.sh
- tools/ci/integration
We have seen several CI failures recently maybe with trace logging we will get more insights.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2726)
> Enable trace logs for tests and CI

- go/sciond/internal/servers/server.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2738)
> SCIOND accept loops stop when socket is closed

- .buildkite/scripts/build_scion_img
- WORKSPACE
- go/lib/xtest/BUILD.bazel
- go/lib/xtest/helpers.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2744)
> Add assert library and AssertError

- go/beacon_srv/main.go
- go/cert_srv/setup.go
- go/lib/infra/modules/trust/config.go
- go/lib/infra/modules/trust/trust.go
- go/lib/infra/modules/trust/trust_test.go
- go/path_srv/main.go
- go/sciond/main.go
Also simplify the truststore API slightly:
-Remove unused error return value
-Add LoadAuthoritativeCrypto method
Fixes #2747
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2750)
> PS: Load authoritative chain on startup

- go/lib/snet/snetproxy/doc.go
Add disclaimer that every IO operation arms a timer.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2755)
> snetproxy: Add disclaimer

- go/sciond/internal/servers/handlers.go
Instead of having the code repeated for all handlers have it once.
The path handlers didn't set a deadline on send, which is also fixed by the commit.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2751)
> sciond: Unify reply code

- go/lib/pathdb/sqlite/sqlite.go
Use QueryRowCotnext where appropriate.
Combine query string already in code instead of during execution.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2756)
> pathdb: Simplify sqlite backend

- go/beacon_srv/internal/beacon/store.go
- go/beacon_srv/internal/beaconstorage/store.go
- go/beacon_srv/main.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2757)
> BS: Close beacon store / db when exiting

- .buildkite/steps/acceptance
- tools/ci/run_acceptance
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2768)
> Fix CI for consistent test names in acceptance/ctl

- python/topology/go.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2772)
> CS reconnects to the dispatcher in default topo

- docker/perapp/Makefile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2771)
> Remove leftovers from perapp makefile

- go/border/setup-posix.go
- go/godispatcher/network/BUILD.bazel
- go/godispatcher/network/app_socket.go
- go/godispatcher/network/dispatcher.go
- go/lib/overlay/conn/BUILD.bazel
- go/lib/overlay/conn/conn.go
Fixes https://github.com/scionproto/scion/issues/2760.
Also added docs and removed dead code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2770)
> Add overflow detection to dispatcher UDP sockets

- acceptance/reconnecting_acceptance/test
- go/beacon_srv/BUILD.bazel
- go/beacon_srv/main.go
- go/lib/addr/appaddr.go
Fixes https://github.com/scionproto/scion/issues/2758
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2780)
> BS: Allow one hop senders reconnecting to dispatcher

- go/beacon_srv/main.go
- go/border/main.go
- go/cert_srv/main.go
- go/godispatcher/main.go
- go/lib/env/env.go
- go/lib/fatal/fatal.go
- go/lib/infra/infraenv/infraenv.go
- go/path_srv/main.go
- go/sciond/main.go
- go/sig/main.go
Fixes https://github.com/scionproto/scion/issues/2754.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2784)
> Use the fatal package to support shutdown signals

- go/sciond/internal/servers/server.go
Fixes https://github.com/scionproto/scion/issues/2782
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2785)
> SCIOND servers no longer start after shutdown is called

- go/cert_srv/main.go
- go/cert_srv/setup.go
Signal handlers are now registered (and signals are processed) while
other resources are still being allocated.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2786)
> CS now sets up signal handlers sooner

- acceptance/brutil/util.sh
- go/border/braccept/compare.go
Fixes #2792
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2795)
> braccept: ignore ttl

- go/sig/egress/BUILD.bazel
- go/sig/egress/interface.go
- go/sig/egress/session/sessmon.go
- go/sig/egress/sesspath.go
- go/sig/egress/sesspathpool.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2804)
> SIG: SessPathPool turned into an interface

- Makefile
- acceptance/brutil/common.sh
- docker/perapp/base/Dockerfile.builder
- go/border/braccept/main.go
- go/border/braccept/shared/init.go
- tools/setcap
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2798)
> Fix issue with setcap braccept not working in CI.

- go/sciond/internal/fetcher/fetcher.go
In case the early trigger fired and we still don't have the TRC cached locally,
we shouldn't just return an error but wait until all paths are verified an try to reply then.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2805)
> sciond: Handle TRC not found after early trigger

- .buildkite/scripts/build_scion_img
- WORKSPACE
- go/tools/buildkite_log_downloader/BUILD.bazel
There were some issues building the base image, which were introduced by #2777 and now fixed in this PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2812)
> Fix base_img build & update base_img

- go/beacon_srv/internal/keepalive/sender.go
This can be helpful for debugging.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2809)
> BS: Trace log sent keepalives

- go/lib/infra/messenger/BUILD.bazel
- go/lib/infra/messenger/messenger_with_metrics.go
- go/lib/infra/messenger/messenger_with_metrics_test.go
- python/topology/jaeger.py
There were some infinite recursions that made cert_renewal tests fail.
Also make the jaeger generator a bit more relaxed about directories existing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2824)
> messenger: Fix messenger with metrics

- go/sig/egress/interface.go
- go/sig/egress/session/sessmon.go
- go/sig/egress/sesspathpool.go
- go/sig/mgmt/pld.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2830)
> SIG: Pass more info about a probe to SessPathPool

- doc/ControlPlanePKI.md
This PR is based on PR #2464.
(Note: will edit commit message before merging)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2831)
> Control-Plane PKI documentation

- go/path_srv/internal/handlers/psdedupe.go
- go/path_srv/internal/handlers/segreq.go
Instead of only deduping the fetching of segments also dedupe the verification and storing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2840)
> PS: Dedupe reply verification as well

- go/beacon_srv/internal/beaconstorage/BUILD.bazel
- go/beacon_srv/internal/beaconstorage/beaconstoragetest/BUILD.bazel
- go/beacon_srv/internal/beaconstorage/beaconstoragetest/config.go
- go/beacon_srv/internal/beaconstorage/config.go
- go/lib/infra/modules/db/limits.go
- go/lib/pathstorage/pathstorage.go
- go/lib/pathstorage/pathstoragetest/BUILD.bazel
- go/lib/pathstorage/pathstoragetest/config.go
- go/lib/truststorage/BUILD.bazel
- go/lib/truststorage/truststorage.go
- go/lib/truststorage/truststoragetest/BUILD.bazel
- go/lib/truststorage/truststoragetest/config.go
Move limit handling to the db package to prevent repeated code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2841)
> Align & simplify storage configurations

- go/lib/env/env.go
- go/lib/env/envtest/config.go
- go/lib/env/sample.go
- python/topology/go.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2844)
> tracing: Disable tracing by default

- .buildkite/steps/common.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2845)
> CI: Detect kernel packet loss during steps

- docker.sh
- tools/ci/get_metrics.sh
- tools/ci/integration
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2861)
> added metrics to integration test artifacts

- .buildkite/pipeline.sh
- tools/ci/integration
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2870)
> Bugfix: CI collect metrics only when not using docker Backend

- go/cert_srv/internal/config/config.go
- go/cert_srv/internal/config/config_test.go
- go/cert_srv/internal/config/sample.go
- go/cert_srv/internal/config/testdata/cs.toml
- go/cert_srv/internal/reiss/requester.go
- go/cert_srv/internal/reiss/self.go
- go/cert_srv/main.go
Fixes #2862
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2868)
> CS: Add config to disable core pusher

- go/tools/logdog/BUILD.bazel
- go/tools/logdog/main.go
Fixes #2863
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2867)
> logdog: Add -level flag to filter by log level

- go/lib/snet/dispatcher.go
- go/lib/snet/packet_conn.go
Fixes #2832
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2873)
> Add scmp header to err if no scmp handler is set

- doc/ControlPlanePKI.md
This PR proposes a series of minor corrections to the control-plane PKI document. Among the more important changes are the following:
- In traditional PKI lingo, a "verifier" would be called a "relying party" (see RFC 3647).
- "Fresh TRC"-> "Initial TRC"
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2872)
> Minor corrections to the Control-Plane PKI document

- go/lib/addr/isdas.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2879)
> lib: Make marshalling invalid AS fail

- proto/common.capnp
- proto/path_mgmt.capnp
- proto/sciond.capnp
Message definitions for the Hidden Path implementation
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2880)
> HP: Add hidden path message definitions

- go/lib/scrypto/defs.go
- go/lib/scrypto/trc/v2/BUILD.bazel
- go/lib/scrypto/trc/v2/signed.go
- go/lib/scrypto/trc/v2/signed_json_test.go
- go/lib/scrypto/trc/v2/signed_test.go
This PR defines decoding/encoding the JWS signed TRC.
fixes #2850
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2881)
> TRC: Define signed format

- go/sig/ingress/rlist.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2900)
> SIG: Better logs related to framing errors

- go/sig/egress/session/BUILD.bazel
- go/sig/egress/session/sessmon.go
- go/sig/metrics/metrics.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2908)
> SIG: Session-related metrics added

- go/lib/ctrl/path_mgmt/BUILD.bazel
- go/lib/ctrl/path_mgmt/hp_cfg.go
- go/lib/ctrl/path_mgmt/hp_seg_recs.go
- go/lib/ctrl/path_mgmt/hp_seg_reply.go
- go/lib/ctrl/path_mgmt/hp_seg_req.go
- go/lib/ctrl/path_mgmt/path_mgmt.go
- go/lib/sciond/types.go
- proto/path_mgmt.capnp
Fixes: #2895
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2901)
> HP: Add go message definitions

- .buildkite/scripts/all_images
- .buildkite/scripts/registry_login
- .buildkite/steps/build_all.yml
- .buildkite/steps/common.sh
- .buildkite/steps/deploy.yml
- .buildkite/steps/setup.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2925)
> Remove ci-registry everywhere for switch to AWS managed ECR

- go/lib/common/BUILD.bazel
- go/lib/common/slice.go
- go/lib/hostinfo/BUILD.bazel
- go/lib/hostinfo/hostinfo.go
- go/lib/sciond/types.go
- go/sig/egress/interface.go
- go/sig/egress/session/sessmon.go
- go/sig/egress/sesspath.go
- go/sig/siginfo/sig.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2924)
> SIG: Fully copy the remote before passing is from sessmon to session

- .buildkite/scripts/build_scion_img
- WORKSPACE
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2930)
> Dep: update go-cache version

- go/sig/ingress/dispatcher.go
- go/sig/ingress/framebuf.go
- go/sig/ingress/worker.go
Get rid of the global variables
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2915)
> SIG: Ingress code cleanup

- go/sig/ingress/BUILD.bazel
- go/sig/ingress/README.md
- go/sig/ingress/framebuf.go
- go/sig/ingress/worker.go
- go/sig/ingress/worker_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2922)
> SIG: Ingress pipeline test

- go/sig/ingress/framebuf.go
- go/sig/ingress/worker.go
Remove the by #2922 introduced `fmt.Printf` calls.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2933)
> SIG: Do not print to stdout

- go/cert_srv/internal/reiss/corepush.go
fixes #2919
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2934)
> CS: Do not retry core push immediately

- go/sig/egress/interface.go
- go/sig/egress/sesspath.go
- go/sig/ingress/framebuf.go
- go/sig/siginfo/sig.go
These should have been added in the past few PRs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2937)
> Add missing copyrights

- go/path_srv/internal/segsyncer/segsyncer.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2935)
> segsyncer: Use ctx logger

- go/lib/infra/messenger/messenger.go
This should improve debugability.
Fixes #2865
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2928)
> messenger: Print request type on request error.

- go/sig/base/core/BUILD.bazel
- go/sig/base/core/as.go
- go/sig/egress/dispatcher/dispatcher.go
- go/sig/egress/interface.go
- go/sig/egress/reader/reader.go
- go/sig/egress/session/BUILD.bazel
- go/sig/egress/session/session.go
- go/sig/egress/worker/worker.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2940)
> SIG: Get rid of egress worker.DefaultFactory

- go/lib/scrypto/cert/v2/BUILD.bazel
- go/lib/scrypto/cert/v2/issuer.go
- go/lib/scrypto/cert/v2/issuer_json_test.go
- go/lib/scrypto/cert/v2/issuer_test.go
This PR adds the issuer certificate with parsing and validation.
contributes to #2853
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2942)
> cert: Add issuer certificate

- go/sig/egress/worker/worker.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2947)
> SIG: Fix an egress bug with frame sequence numbers

- go/lib/pathpol/policy.go
Contributes to #2923 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2917)
> Pathpol: JSON keys should be snake_case

- .buildkite/files/acceptance_trigger_instructions
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2884)
> Acceptance test trigger instructions added partial run

- acceptance/cert_renewal_acceptance/test
- acceptance/discovery_br_fetches_dynamic_acceptance/test
- acceptance/discovery_br_fetches_static_acceptance/test
- acceptance/discovery_infra_fetches_dynamic_acceptance/test
- acceptance/discovery_infra_fetches_static_acceptance/test
- acceptance/sig_reload_acceptance/test
Also move sourcing to the top of the test file and remove double sourcing.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2952)
> Acceptance: Start tester containers for cert_renewal and discovery

- go/lib/infra/mock_infra/infra.go
- go/sig/egress/mock_egress/egress.go
- go/sig/egress/worker/mock_worker/worker.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2958)
> Regenerate mocks with the correct version of mockgen

- go/lib/scrypto/cert/v2/BUILD.bazel
- go/lib/scrypto/cert/v2/as_signed.go
- go/lib/scrypto/cert/v2/as_signed_json_test.go
- go/lib/scrypto/cert/v2/as_signed_test.go
- go/lib/scrypto/cert/v2/base_signed.go
- go/lib/scrypto/defs.go
- go/lib/scrypto/trc/v2/signed.go
- go/lib/scrypto/trc/v2/signed_json_test.go
This PR defines the signed format for the AS certificate according to
the Flattened JWS JSON Serialization Syntax.
contributes to #2853
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2957)
> cert: Define signed AS certificate format

- Makefile
bin/dispatcher isn't created by bazel.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2965)
> Don't delete bin/dispatcher in the bazel make target

- acceptance/topo_br_reload_if_ip_acceptance/test
- acceptance/topo_br_reload_if_port_acceptance/test
- go/lib/topology/topology.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2969)
> Fix topo_br acceptance tests

- doc/ControlPlanePKI.md
- go/lib/scrypto/cert/v2/as.go
- go/lib/scrypto/cert/v2/as_json_test.go
- go/lib/scrypto/cert/v2/as_signed.go
- go/lib/scrypto/cert/v2/as_signed_json_test.go
- go/lib/scrypto/cert/v2/base.go
- go/lib/scrypto/cert/v2/base_json_test.go
- go/lib/scrypto/cert/v2/issuer.go
- go/lib/scrypto/cert/v2/issuer_json_test.go
- go/lib/scrypto/cert/v2/issuer_signed.go
- go/lib/scrypto/cert/v2/issuer_signed_json_test.go
- go/lib/scrypto/keymeta.go
- go/lib/scrypto/keymeta_test.go
- go/lib/scrypto/trc/v2/keychanges.go
- go/lib/scrypto/trc/v2/pop.go
- go/lib/scrypto/trc/v2/primary.go
- go/lib/scrypto/trc/v2/primary_json_test.go
- go/lib/scrypto/trc/v2/signed.go
- go/lib/scrypto/trc/v2/signed_json_test.go
- go/lib/scrypto/trc/v2/trc.go
- go/lib/scrypto/trc/v2/trc_json_test.go
- go/lib/scrypto/trc/v2/trc_test.go
- go/lib/scrypto/trc/v2/update.go
- go/lib/scrypto/trc/v2/update_test.go
- go/lib/scrypto/trc/v2/verify.go
- go/lib/scrypto/trc/v2/verify_test.go
- go/lib/scrypto/validity.go
- go/lib/scrypto/validity_test.go
Move to snake case in all json files (see: #2923)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2970)
> CPPKI: Use snake case

- go/sciond/internal/fetcher/fetcher.go
Fixes acceptance test broken by #2971
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2975)
> sciond: Get crypto from CS

- acceptance/brutil/common.sh
- acceptance/brutil/docker-compose.yml
- go/beacon_srv/BUILD.bazel
- go/beacon_srv/main.go
- go/border/braccept/shared/BUILD.bazel
- go/border/braccept/shared/init.go
- go/border/brconf/BUILD.bazel
- go/border/brconf/conf.go
- go/border/rctx/BUILD.bazel
- go/border/rctx/rctx.go
- go/border/rpkt/extn_onehoppath.go
- go/border/rpkt/path.go
- go/border/setup.go
- go/lib/scrypto/BUILD.bazel
- go/lib/scrypto/mac.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2974)
> BR: Move Hop Field Mac Pool to the Context

- Makefile
- scion.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2961)
> Replace 'scion.sh mocks' by 'make mocks'

- .buildkite/scripts/build_scion_img
- WORKSPACE
- nogo.json
-Update capnproto with analysis fixes
-Update go-yaml to latest v2 version
-Remove no longer required excludes
-Add some upstream prs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2987)
> Nogo housekeeping & lib update

- README.md
- tools/install_bazel
This adds a workaround for where the import path does not match the
repository url.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2995)
> Update to bzlcompat v0.6

- WORKSPACE
https://groups.google.com/forum/#!msg/golang-announce/65QixT3tcmg/DrFiG6vvCwAJ
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2996)
> Update to go 1.11.13

- .buildkite/scripts/build_scion_img
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2999)
> Update scion_base with new go version.

- go/border/rctrl/BUILD.bazel
- go/border/rctrl/ctrl.go
Connection failure between border routere control and dispatcher is a
fatal error.
Fixes #2998
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3001)
> BR: Exit on dispatcher error

- go/sig/config/BUILD.bazel
- go/sig/config/ipnet.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3005)
> SIG: Split IPNet into a separate file

- go/sig/base/core/as.go
- go/sig/base/core/map.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3007)
> SIG: Add a parameter to ASEntry.ReloadConfig

- c/lib/scion/checksum.c
Don't iterate past intended chunk pointers
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3012)
> Fix checksum

- tools/git-version
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3017)
> Switch to more standard git versioning.

- go/beacon_srv/internal/beacon/beacondbsqlite/BUILD.bazel
- go/beacon_srv/internal/beacon/beacondbsqlite/db.go
- go/beacon_srv/internal/beacon/beacondbsqlite/db_test.go
- go/beacon_srv/internal/beacon/beacondbtest/BUILD.bazel
- go/beacon_srv/internal/beacon/beacondbtest/beacondbtest.go
- go/lib/pathdb/sqlite/BUILD.bazel
- go/lib/pathdb/sqlite/sqlite_test.go
- go/tools/scion-pki/internal/conf/BUILD.bazel
- go/tools/scion-pki/internal/conf/as_test.go
- go/tools/scion-pki/internal/conf/isd_test.go
beacondb test suite
beacondb/sqlite
pathdb/sqlite
part of scion-pki
Contributes #2986
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3020)
> Replace more goconvey tests with normal tests

- go/beacon_srv/BUILD.bazel
fixes #3026
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3027)
> BS: Display version

- go/lib/scrypto/trc/v2/verify.go
- go/lib/scrypto/trc/v2/verify_test.go
This extracts the `POPVerifier` from the `UpdateVerifier` to make it
reusable by other calling code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3008)
> TRC: Add proof of possession verifier

- go/border/brconf/BUILD.bazel
- go/border/brconf/conf.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2992)
> brconf: remove unused as_conf

- go/sciond/internal/fetcher/fetcher.go
This fix adds additional context to the error messages.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3035)
> sciond: Improve GetPaths error messages

- go/border/rctrl/ctrl.go
- go/border/rctrl/ifstate.go
- go/lib/common/errors.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3029)
> BR: improve control error messages

- go/sciond/internal/fetcher/fetcher.go
#3035 Introduced a bug that would return errors more often than it should.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3047)
> sciond: Fix bug with new error reporting

- go/lib/hpkt/hpkt_test.go
- go/lib/hpkt/read.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3055)
> hpkt: Error on small-sized packets

- Makefile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3061)
> Use bazel fetch to get everything needed by the go toolchain.

- go/tools/scion-pki/internal/pkicmn/pkicmn.go
- go/tools/scion-pki/internal/v2/trc/BUILD.bazel
- go/tools/scion-pki/internal/v2/trc/cmd.go
- go/tools/scion-pki/internal/v2/trc/sign.go
- go/tools/scion-pki/internal/v2/trc/util.go
This PR adds the capability to sign prototype TRCs to the spki tool.
contributes to #2983
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3056)
> SPKI: Generate TRC signatures

- doc/PathPolicy.md
Mention how policy filtering in PS works.
Also mention relation between acl and sequence.
Fixes #3063
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3070)
> pathpol: Update design doc

- go/lib/pathpol/policy_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3086)
> pathpol: Clean test formatting

- go/path_srv/internal/segreq/BUILD.bazel
- go/path_srv/internal/segreq/handler.go
Instead of silently bailing out.
Fixes #3091
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3092)
> PS: Log & return err from segfetcher

- .buildkite/acceptance-pipeline.sh
- acceptance/sig_failover_acceptance/test
- acceptance/topo_br_reload_if_ip_acceptance/test
- acceptance/topo_br_reload_if_port_acceptance/test
- acceptance/topo_br_reload_util/util.sh
- go/lib/infra/modules/segfetcher/fetcher.go
- go/path_srv/internal/segreq/provider.go
Add sleeps to make sure revocation is expired before checking connectivity again.
Also improve error msg of PS and add a TODO in segfetcher.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3096)
> Fix topo_br_reload_if_* acceptance tests

- go/lib/snet/conn.go
This PR makes the reader and writer conn of snet to point to the correct
base conn.
fixes #3133
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3134)
> snet: Use correct base conn

- .buildkite/scripts/all_images
- python/topology/common.py
- python/topology/go.py
- python/topology/sig.py
With this we should be able to finally get rid of the C dispatcher.
Fixes #2416
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3139)
> topo-gen: Use go dispatcher for SIG

- .bazelrc
- Makefile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3157)
> Use bazelrc to set build options

- go/godispatcher/BUILD.bazel
- go/godispatcher/main.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3163)
> disp: Add missing element ID export

- README.md
because I forget that I need to install unzip every single time :D
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3164)
> Add dependencies to the "install Bazel" step

- go/lib/infra/modules/segverifier/segverifier.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3171)
> SegVerifier: Set TRC version on verifier

- doc/Metrics.md
Add a metrics doc that outlines the way we instrument the code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3162)
> doc: Add metrics doc

- go/beacon_srv/main.go
- go/cert_srv/setup.go
- go/lib/infra/modules/db/metrics.go
- go/lib/infra/modules/trust/BUILD.bazel
- go/lib/infra/modules/trust/handlers.go
- go/lib/infra/modules/trust/internal/metrics/BUILD.bazel
- go/lib/infra/modules/trust/internal/metrics/context.go
- go/lib/infra/modules/trust/internal/metrics/db.go
- go/lib/infra/modules/trust/internal/metrics/handler.go
- go/lib/infra/modules/trust/internal/metrics/labels_test.go
- go/lib/infra/modules/trust/internal/metrics/metrics.go
- go/lib/infra/modules/trust/internal/metrics/store.go
- go/lib/infra/modules/trust/signhelper.go
- go/lib/infra/modules/trust/trust.go
- go/lib/infra/modules/trust/trustdb/BUILD.bazel
- go/lib/infra/modules/trust/trustdb/metrics.go
- go/lib/prom/prom.go
- go/path_srv/main.go
This change adds metrics to the trust store.
The exposed metrics are:
```
truststore_db_queries_total{driver="sqlite",operation="get_chain",result="ok_success"} 13
truststore_db_queries_total{driver="sqlite",operation="get_chain_max",result="ok_success"} 2
truststore_lookups_total{cache_only="false",client="application",req_type="chain_req",result="ok_cached",trigger="sig_verification"} 2295
truststore_lookups_total{cache_only="false",client="application",req_type="trc_req",result="ok_requested",trigger="sig_verification"} 1
truststore_lookups_total{cache_only="true",client="application",req_type="chain_req",result="err_internal",trigger="load"} 1
truststore_lookups_total{cache_only="true",client="application",req_type="trc_req",result="err_not_found",trigger="load"} 1 …
```
> TrustStore: Add metrics

- go/beacon_srv/internal/beaconstorage/beaconstoragetest/BUILD.bazel
- go/beacon_srv/internal/beaconstorage/beaconstoragetest/config.go
- go/beacon_srv/internal/beaconstorage/beaconstoragetest/config_test.go
- go/beacon_srv/internal/config/BUILD.bazel
- go/beacon_srv/internal/config/config_test.go
- go/border/brconf/BUILD.bazel
- go/border/brconf/params_test.go
- go/cert_srv/internal/config/BUILD.bazel
- go/cert_srv/internal/config/config_test.go
- go/godispatcher/internal/config/BUILD.bazel
- go/godispatcher/internal/config/config_test.go
- go/lib/env/envtest/BUILD.bazel
- go/lib/env/envtest/config.go
- go/lib/env/envtest/config_test.go
- go/lib/infra/modules/idiscovery/idiscoverytest/BUILD.bazel
- go/lib/infra/modules/idiscovery/idiscoverytest/config.go
- go/lib/infra/modules/idiscovery/idiscoverytest/config_test.go
- go/lib/pathstorage/pathstoragetest/BUILD.bazel
- go/lib/pathstorage/pathstoragetest/config.go
- go/lib/pathstorage/pathstoragetest/config_test.go
- go/lib/truststorage/truststoragetest/BUILD.bazel
- go/lib/truststorage/truststoragetest/config.go
- go/lib/truststorage/truststoragetest/config_test.go
- go/path_srv/internal/config/BUILD.bazel
- go/path_srv/internal/config/config_test.go
- go/sciond/internal/config/BUILD.bazel
- go/sciond/internal/config/config_test.go
- go/sig/internal/sigconfig/BUILD.bazel
- go/sig/internal/sigconfig/conf_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3179)
> Remove goconvey from config tests

- go/beacon_srv/internal/beacon/policy.go
- go/beacon_srv/internal/beacon/policy_test.go
Disallowing them is something you'd only want to do in very specific
circumstances.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3184)
> Allow "isd loops" by default.

- go/lib/snet/packet_conn.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3192)
> snet: Pass on errors from custom SCMP handlers

- WORKSPACE
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3200)
> bazel: update rules_go

- go/lib/serrors/errors_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3199)
> Add error formatting to serrors examples

- BUILD.bazel
- WORKSPACE
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3215)
> serrorscheck: Use newer revision

- WORKSPACE
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3219)
> serrorscheck: Update revision to support differnt string types

- doc/Metrics.md
Changed package name from prom to prometheus where needed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3204)
> Fix prometheus code in metrics documentation

- go/lib/infra/messenger/addr_test.go
- go/lib/overlay/addr.go
- go/lib/snet/mock_snet/snet.go
- go/lib/snet/router.go
- go/lib/svc/resolver.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3226)
> snet: Copy method added to snet.Path

- go/lib/scrypto/BUILD.bazel
- go/lib/scrypto/asym.go
- go/tools/scion-pki/internal/v2/keys/BUILD.bazel
- go/tools/scion-pki/internal/v2/keys/priv.go
- go/tools/scion-pki/internal/v2/keys/pub.go
- go/tools/scion-pki/internal/v2/keys/pub_test.go
Adds:
- support for generating public keys for all available private keys.
Also:
- fixes license in priv.go
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3227)
> SPKI: Generate public keys

- go/lib/snet/BUILD.bazel
- go/lib/snet/conn.go
- go/lib/snet/dispatcher.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3251)
> snet: Report full info about revocations

- go/godispatcher/internal/metrics/BUILD.bazel
- go/godispatcher/internal/metrics/metrics.go
- go/godispatcher/internal/respool/packet.go
- go/godispatcher/network/app_socket.go
- go/godispatcher/network/dispatcher.go
- go/godispatcher/network/overlay.go
- go/godispatcher/network/table.go
- go/lib/scmp/scmp.go
Also fixes a panic bug in go/lib/scmp.
Fixes https://github.com/scionproto/scion/issues/3101.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3258)
> Add metrics to the Go dispatcher

- go/hidden_path_srv/internal/hpcfgreq/BUILD.bazel
- go/hidden_path_srv/internal/hpcfgreq/handler.go
- go/hidden_path_srv/internal/hpcfgreq/handler_test.go
Fixes https://github.com/scionproto/scion/issues/2892
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3260)
> HP: Add HPGCfgReqHandler

- go/lib/periodic/BUILD.bazel
- go/lib/periodic/periodic_test.go
- go/lib/xtest/helpers.go
Contributes #3267
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3275)
> Periodic: add timeouts in tests

- go/lib/snet/packet_conn.go
- go/lib/snet/writer_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3289)
> snet: Add scmp handler to NewSCIONPacketConn

- go/lib/snet/router.go
This allows to retreive human-readable path representation for
logging and debugging purposes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3290)
> snet: Add stringer to path

- go/sig/main.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3302)
> SIG: Fix malformed logger invocation

- scion.sh
It stops the current topology and started services.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3303)
> scion.sh add topo_clean command

- go/tools/scion-pki/internal/v2/keys/cmd.go
- go/tools/scion-pki/internal/v2/keys/pub.go
Add `keys {public,private}` commands to the scion-pki tool.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3308)
> SPKI: Add key commands

- go/lib/topology/topology.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3320)
> Export types of Topology fields

- go/lib/snet/router.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3324)
> snet: Extract PathReplyEntry from Path

- go/lib/periodic/internal/metrics/metrics_test.go
- go/lib/prom/prom.go
Fixes #3298
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3333)
> metric: do not init label values to an empty string

- go/lib/periodic/BUILD.bazel
- go/lib/periodic/periodic_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3335)
> periodic: increase period and error verbosity

- go/sig/egress/iface/sesspathpool.go
- go/sig/egress/reader/reader.go
- go/sig/egress/session/sessmon.go
- go/sig/metrics/metrics.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3329)
> SIG: Sessmon metrics

- go/beacon_srv/internal/beaconing/handler.go
- go/beacon_srv/internal/ifstate/metrics.go
- go/beacon_srv/internal/ifstate/revoker.go
- go/beacon_srv/internal/metrics/beaconing.go
- go/beacon_srv/internal/metrics/ifstate.go
- go/border/BUILD.bazel
- go/border/internal/metrics/metrics.go
- go/border/io_test.go
- go/lib/prom/prom.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3354)
> Consistently use neigh_ia label name.

- acceptance/sig_reload_acceptance/test
- acceptance/sigutil/common.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3361)
> Acceptance tests: Move reload_sig function to a library

- go/lib/infra/modules/trust/trustdb/trustdbsqlite/db.go
Add transactional chain insert
fixes #3365
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3367)
> trustdb: Use transaction for chain insert

- go/hidden_path_srv/internal/registration/handler.go
- go/lib/infra/modules/segfetcher/fetcher.go
- go/lib/infra/modules/segfetcher/metrics.go
- go/lib/infra/modules/seghandler/result.go
- go/lib/infra/modules/seghandler/seghandler.go
- go/lib/infra/modules/seghandler/seghandler_test.go
- go/lib/infra/modules/segverifier/BUILD.bazel
- go/lib/infra/modules/segverifier/segverifier.go
- go/path_srv/internal/handlers/segreg.go
- go/path_srv/internal/handlers/segsync.go
Also log verification error in all seghandler using code.
Also clean up error and make sure metrics report this correctly.
Fixes #3357
Fixes #3351
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3368)
> seghandler: Report error if all segments fail to verify

- .buildkite/scripts/build_scion_img
- WORKSPACE
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3379)
> Fix workspace for scion image generation

- go/integration/cert_req/BUILD.bazel
- go/integration/cert_req/main.go
- go/lib/addr/appaddr.go
- go/lib/hostinfo/BUILD.bazel
- go/lib/hostinfo/hostinfo.go
- go/lib/infra/modules/itopo/BUILD.bazel
- go/lib/infra/modules/itopo/topology.go
- go/sciond/internal/fetcher/BUILD.bazel
- go/sciond/internal/fetcher/fetcher.go
- go/sciond/internal/servers/handlers.go
- go/sig/egress/session/sessmon.go
- go/sig/internal/base/pollhdlr.go
- go/sig/mgmt/BUILD.bazel
- go/sig/mgmt/addr.go
Instead use *net.UDPAddr
Fixes #3295
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3370)
> Reduce usage of hostinfo.Host

- go/integration/cert_req/main.go
- go/integration/common.go
- go/integration/end2end/main.go
- go/lib/pathmgr/pathmgr.go
- go/lib/snet/internal/metrics/metrics.go
- go/lib/snet/snet.go
Contributes #3348
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3385)
> remove Sciond() method from ScionNetwork

- acceptance/topo_sd_reloads_ps_acceptance/test
Bug introduced by #3396 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3399)
> Fix topo_sd_reloads_ps acceptance test

- go/sig/internal/metrics/metrics.go
Fixes #3393
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3409)
> Improve description for sig_session_health

- python/lib/socket.py
Fixes bug introduced in #3404
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3414)
> Readd settimeout to ReliableSocket

- go/lib/infra/messenger/addr.go
- go/lib/infra/messenger/addr_test.go
- go/lib/infra/messenger/export_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3421)
> messenger: refactor to avoid using addr.AppAddr

- go/lib/infra/messenger/addr_test.go
- go/lib/pathpol/BUILD.bazel
- go/lib/pathpol/pathset.go
- go/lib/pathpol/policy_test.go
- go/lib/sciond/apitypes.go
- go/lib/snet/mock_snet/snet.go
- go/lib/snet/path.go
- go/lib/spath/spathmeta/apppath.go
- go/lib/svc/resolver.go
- go/path_srv/internal/segutil/BUILD.bazel
- go/path_srv/internal/segutil/filter.go
- go/path_srv/internal/segutil/filter_test.go
- go/sciond/internal/fetcher/filter.go
- go/sciond/internal/fetcher/filter_test.go
- go/sig/egress/iface/sesspath.go
- go/sig/egress/iface/sesspathpool.go
- go/sig/internal/pathmgr/pathmgr.go
- go/sig/internal/pathmgr/util_test.go
- go/sig/internal/snetmigrate/path.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3433)
> snet: Add PathFingerprint type

- .buildkite/scripts/build_scion_img
- README.md
- WORKSPACE
- docker/perapp/scion_app.bzl
- nogo.json
- tools/fetch.sh
- tools/install_bazel
Also upgrades all the dependencies for docker images.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3432)
> Upgrade to bazel 1.2.0

- acceptance/sig_reload_acceptance/test
- acceptance/sigutil/common.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3431)
> SIG acceptance tests: Make sure that config is reloaded

- go/sig/internal/metrics/metrics.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3449)
> SIG: Rename IA label to dst_isd_as

- go/sig/egress/iface/sesspath.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3497)
> SIG: SessPath key truncated to 8 characters

- go/lib/infra/modules/trust/v2/main_test.go
Add help message to cryptic errors.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3504)
> TrustStore: Add help message to tests

- go/lib/common/BUILD.bazel
- go/lib/common/defs.go
- go/lib/common/defs_test.go
- go/lib/infra/BUILD.bazel
- go/lib/infra/common.go
- go/lib/infra/common_test.go
Do not panic in common.TypeOf when receiving a non-typed nil.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3506)
> Common: Don't panic on nil

- go/lib/infra/modules/trust/v2/export_test.go
- go/lib/infra/modules/trust/v2/handlers.go
- go/lib/infra/modules/trust/v2/handlers_test.go
Add TRC request handler to the trust store.
fixes #3484
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3499)
> TrustStore: Add TRC request handler

- go/lib/infra/modules/trust/v2/verifier.go
- go/lib/infra/modules/trust/v2/verifier_export_test.go
- go/lib/infra/modules/trust/v2/verifier_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3518)
> Add missing license header

- .buildkite/pipeline.yml
Co-Authored-By: @worxli
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3520)
> CI: Add lint steps to new pipeline

- go/beacon_srv/internal/beaconing/extender_test.go
- go/beacon_srv/internal/beaconing/originator_test.go
- go/beacon_srv/internal/ifstate/revoker_test.go
- go/beacon_srv/internal/revocation/handler_test.go
- go/lib/ctrl/path_mgmt/rev_info.go
- go/lib/ctrl/seg/mock_seg/BUILD.bazel
- go/lib/ctrl/seg/mock_seg/seg.go
- go/lib/ctrl/seg/seg.go
- go/lib/ctrl/seg/seg_test.go
- go/lib/ctrl/signed_util.go
- go/lib/infra/common.go
- go/lib/infra/mock_infra/infra.go
- go/lib/infra/modules/trust/signhelper.go
- go/lib/infra/modules/trust/v2/mock_v2/v2.go
- go/lib/infra/modules/trust/v2/verifier.go
- go/lib/snet/mock_snet/snet.go
Use `[]byte` instead of `common.RawBytes`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3529)
> infra: Refactor signer/verifier

- go/lib/infra/modules/trust/v2/provider.go
- go/lib/infra/modules/trust/v2/provider_test.go
Fixes #3524
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3536)
> TrustStore: Add Implementation for GetASKey

- go/lib/infra/modules/trust/v2/export_test.go
- go/lib/infra/modules/trust/v2/inserter.go
- go/lib/infra/modules/trust/v2/inserter_test.go
- go/lib/infra/modules/trust/v2/inspector.go
- go/lib/infra/modules/trust/v2/inspector_test.go
- go/lib/infra/modules/trust/v2/provider.go
- go/lib/infra/modules/trust/v2/provider_test.go
- go/lib/infra/modules/trust/v2/recurser.go
- go/lib/infra/modules/trust/v2/resolver.go
- go/lib/infra/modules/trust/v2/resolver_test.go
- go/lib/infra/modules/trust/v2/router.go
- go/lib/infra/modules/trust/v2/router_test.go
- go/lib/infra/modules/trust/v2/rpc.go
Export all private types and let the app instantiate the components
as it sees fit.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3530)
> TrustStore: The great export

- BUILD.bazel
- WORKSPACE
- go/tools/udpproxy/BUILD.bazel
- go/tools/udpproxy/udpproxy.go
The proxy can be used to replace border routers in some acceptance
tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3540)
> Add simple UDP proxy written in Go

- .buildkite/hooks/pre-command
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3564)
> CI: move bazel cache bucket name into env

- python/lib/util.py
- python/test/lib/util_test.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3565)
> python: Fix YAMLLoadWarning

- go/acceptance/sigcmn.go
- go/integration/cert_req/main.go
- go/lib/integration/binary.go
- go/lib/integration/docker.go
- go/lib/integration/integration.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3553)
> Do not use appaddr in cert_integration

- .buildkite/pipeline_buildlint.yml
Add python unit tests to new CI pipeline
fixes #3569
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3577)
> CI: Add python unit tests

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3579)
> MD: Update badge

- go/tools/scion-pki/internal/v2/tmpl/topo.go
- go/tools/scion-pki/internal/v2/tmpl/topo_test.go
This fixes template generation bugs introduced by #3586
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3587)
> SPKI: Fix template generation

- .buildkite/pipeline.sh
- .buildkite/pipeline.yml
This gives us a quick idea of what still needs to be ported.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3600)
> Add bazel icon to bazelified pipeline tests

- doc/CertificateRenewal.md
This file defines the certificate renewal request and response messages
and their signatures/verification.
The spec allows issuing ASes to define their own additional policies on
top of the predefined policy.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3598)
> CPPKI: Define certificate renewal interaction

- .buildkite/pipeline.yml
It's helpful to have all the details when debugging issues.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3621)
> ci: Use trace logging in integration tests

- go/godispatcher/network/app_socket.go
- go/godispatcher/network/table.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3614)
> dispatcher: Remove obsolete field

- .buildkite/pipeline.yml
Just to make sure that remote cache is used.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3609)
> ci: announce_rc file in bazel

- go/tools/scion-pki/internal/tmpl/topo.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3596)
> SPKI: tmpl error if no voting/issuing AS is specified

- go/tools/scion-pki/internal/trcs/prototype.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3632)
> SPKI: Return error if keyloading fails

- go/godispatcher/dispatcher/BUILD.bazel
- go/godispatcher/dispatcher/dispatcher.go
- go/godispatcher/dispatcher/overlay.go
- go/godispatcher/dispatcher/overlay_test.go
- go/godispatcher/dispatcher/scmp.go
- go/godispatcher/dispatcher/table.go
- go/godispatcher/internal/respool/packet.go
- go/godispatcher/main.go
- go/godispatcher/network/BUILD.bazel
- go/godispatcher/network/app_socket.go
- go/godispatcher/network/dispatcher.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3634)
> godispatcher: Split out a library that could be linked into apps

- go/godispatcher/dispatcher/dispatcher.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3635)
> dispatcher: Fix bug in dispatcher library read function

- docker/perapp/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3638)
> Document our use of su-exec and why.

- go/lib/sciond/fake/fake.go
- go/lib/sciond/fake/fake_test.go
We are using 1472 as a default averywhere else.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3657)
> Fake SCIOND: Use MTU of 1472

- go/sig/internal/ingress/api.go
- go/sig/internal/ingress/dispatcher.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3659)
> SIG: Make the snet connection in ingress.Dispatcher mockable

- go/border/braccept/br_tests.go
- go/border/braccept/parser/revinfo.go
- go/border/braccept/revocation_tests.go
- go/border/rpkt/path.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3664)
> braccept: expired revocation on interface not owned

- go/lib/pathstorage/sample.go
- go/lib/truststorage/sample.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3666)
> sd: state connection db is required in help

- go/tools/scion-pki/internal/certs/BUILD.bazel
- go/tools/scion-pki/internal/certs/cmd.go
- go/tools/scion-pki/internal/certs/verify.go
- go/tools/scion-pki/internal/certs/verify_test.go
- go/tools/scion-pki/internal/trcs/BUILD.bazel
- go/tools/scion-pki/internal/trcs/cmd.go
- go/tools/scion-pki/internal/trcs/prototype.go
- go/tools/scion-pki/internal/trcs/sign.go
- go/tools/scion-pki/internal/trcs/util.go
- go/tools/scion-pki/internal/trcs/validator.go
- go/tools/scion-pki/internal/trcs/validator_test.go
This PR adds verify commands to the crts and trcs command.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3672)
> SPKI: Add verify commands

- acceptance/brutil/common.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3678)
> BR acceptance test: Add an option to sleep after setup step

- .buildkite/pipeline.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3686)
> Build all in CI

- go/border/BUILD.bazel
- go/border/ifstate/ifstate.go
- go/border/main.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3687)
> br: Add status page

- .buildkite/pipeline.yml
- tools/licenses.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3693)
> Fix nightly build

- CONTRIBUTING.md
- README.md
- doc/ControlPlanePKI.md
- doc/contribute.rst
- scripts/mastersync.sh
Information about how to contribute to the SCION project
was scattered throughout the Github wiki pages. This
PR moves them to the documentation folders, and updates
out of date documentation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3722)
> import the contribution guides from the wiki

- go/cs/main.go
- go/lib/overlay/conn/conn.go
- go/lib/snet/path.go
- go/lib/snet/udpaddr.go
- go/lib/snet/udpaddr_test.go
- go/lib/snet/writer.go
- go/lib/topology/interface.go
- go/lib/topology/json/json.go
- go/lib/topology/mock_topology/topology.go
- go/lib/topology/raw.go
- go/lib/topology/testdata/basic.json
- go/lib/topology/topology.go
- go/lib/topology/topology_test.go
This PR adds support for parsing host addresses that contain a IPv6 zone.
Also slightly cleans up the topology interface and add a copy method for RWTopology.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3725)
> ipv6: support zones

- .gitignore
- doc/Makefile
- doc/conf.py
- doc/index.rst
- doc/make.bat
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3734)
> Initialize RTD project for documentation site

- README.md
Add shield to read the docs.
Switch go doc shield to point to pkg.go.dev
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3740)
> readme: improve shields

- .buildkite/hooks/pre-artifact
- .buildkite/hooks/pre-command
- .buildkite/hooks/pre-exit
- .buildkite/pipeline.sh
- .buildkite/pipeline.yml
- .buildkite/pipeline_lib.sh
- integration/service_filelog/BUILD.bazel
- integration/service_filelog/test.py
- integration/service_filelog/testdata/cs.toml
- tools/package-version
This commit also adds integration test for file logging
to verify that file logging is working.
This will pave the way for removing file logging from our testing
infrastructure.
Co-authored-by: Lukas Vogel <lukedirtwalker@gmail.com>
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3751)
> ci: general improvements

- go/cs/main.go
- go/lib/ctrl/seg/staticinfo_extn.go
Also initialize the beacon originator with the static info config.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3764)
> implement proto.Cerializable for staticinfo extension types.

- doc/extension-header.rst
- doc/index.rst
- doc/scion-header.rst
This PR adds the specifications of the SCION header and extension headers to the documentation.
Fixes #3714 
Fixes #3715 
[doc]
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3760)
> Add specifications for SCION and Extension Headers.

- .buildkite/pipeline.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3767)
> ci: don't run e2e on doc change

- .buildkite/pipeline.yml
- go/sig/main.go
Also fix pipeline untarring: `-k` together with `--overwrite` doesn't make sense.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3775)
> sig: don't add route if addr is empty

- go/border/braccept/br_tests.go
- go/border/braccept/parent_tests.go
- go/border/braccept/parser/helper.go
- go/border/braccept/parser/scmp.go
Add a test for SCMP error BAD_HOST of SCMP packets, ie. SCMP ECHO
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3774)
> braccept: add scmp bad host error from scmp packet

- env/debian/pkgs.txt
Accidentally broke sorted order in #3790.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3791)
> Fix order in env/debian/pkgs.txt

- go/pkg/sig/config/BUILD.bazel
- go/pkg/sig/config/config.go
- go/pkg/sig/config/config_test.go
- go/pkg/sig/config/sample.go
- go/sig/BUILD.bazel
- go/sig/internal/sigcmn/BUILD.bazel
- go/sig/internal/sigcmn/common.go
- go/sig/main.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3804)
> sig: rename sigconfig package to config

- go/pkg/sig/config/BUILD.bazel
- go/pkg/sig/config/config_test.go
- go/pkg/sig/config/configtest/BUILD.bazel
- go/pkg/sig/config/configtest/configtest.go
Refactor config tests to be importable from other locations.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3814)
> sig: improve config tests

- .buildkite/pipeline.yml
- .buildkite/pipeline_lib.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3824)
> ci: shorten step names and merge steps

- Makefile
- WORKSPACE
- go/lib/periodic/internal/metrics/mock_metrics/BUILD.bazel
- tools/gomocks
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3825)
> make gomocks hermetic

- doc/contribute/git.rst
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3830)
> doc: improve commit message guide

- go/lib/sigjson/BUILD.bazel
- go/lib/sigjson/config.go
- go/tools/udpproxy/udpproxy.go
- nogo.json
Enable checks that were disabled due to misconfiguration
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3834)
> nogo: enable checks again

- doc/contribute/git.rst
RTD needs that, otherwise, the message is not rendered.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3837)
> doc: make the message visible

- go/border/io.go
Analogous to scionproto/scion#3448.
When forwarding an incoming packet, `EINVAL` and `EACCESS` can be caused by
trying to send the packet to a "blackhole" or "prohibit" route.
Although not mentioned in extracts from the manual below, `EINVAL` is also
returned for any "martian" addresses during routing; specifically this occurs
when trying to send on a non-loopback device with a localhost source address
(by default, anyway).
As the destination address is controlled by an end host outside the AS,
the router should not abort in this case.
----
Relevant snippets from man **ip**(7):
EINVAL
Invalid argument passed.
For send operations this can be caused by sending to a blackhole route.
EACCES
The user tried to execute an operation without the necessary permissions.
These include: sending a …
> border: ignore EINVAL, EACCES

- go/lib/env/features.go
- python/topology/sig.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3858)
> remove unused feature flag

- docker/caps.bzl
- docker/scion_app.bzl
- docker/setcap.sh.tpl
- docker/sig_tester.bzl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3864)
> bazel: clean up the setcap code

- doc/protocols/index.rst
- doc/protocols/sig.rst
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3865)
> [doc] SIG framing protocol specification

- scion.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3866)
> lint: remove irrenlevant stuff from the output

- go/dispatcher/internal/respool/packet_test.go
- go/integration/braccept_v2/cases/scmp_invalid_pkt.go
- go/integration/braccept_v2/cases/scmp_unknown_hop.go
- go/lib/slayers/scmp.go
- go/lib/slayers/scmp_test.go
- go/lib/slayers/scmp_typecode.go
- go/lib/snet/packet.go
- go/pkg/router/dataplane.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3882)
> small SCMP improvements for the new router

- go/sig/internal/sigcmn/BUILD.bazel
- go/sig/internal/sigcmn/common.go
This was added as possible performance improvement measure. It turns out
that it doesn't improve performance and it isn't used anywhere.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3895)
> gateway: remove dispatcher bypass

- acceptance/topo_cs_reload/testdata/cs.toml
- go/cs/beaconing/originator.go
- go/cs/beaconing/propagator.go
- go/cs/cs.go
- go/dispatcher/network/app_socket.go
- go/lib/env/env.go
- go/lib/env/sample.go
- go/lib/infra/infraenv/infraenv.go
- go/lib/infra/modules/segfetcher/BUILD.bazel
- go/lib/infra/modules/segfetcher/export_test.go
- go/lib/infra/modules/segfetcher/pather.go
- go/lib/infra/modules/segfetcher/pather_test.go
- python/topology/cert.py
- python/topology/go.py
Also changes some Info-level logs to Debug level and improves
the context of some logging lines.
Co-authored-by: Konstantinos Karampogias <karampogias@anapaya.net>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3906)
> cs: QUIC certificates are generated in the app

- go/cs/beaconing/originator.go
Previously, the control server would originate on each interface
sequentially. If one beacon origination takes up the whole context,
all origination attempts on the subsequent interfaces would timeout.
This is especially bad, because we iterate the interfaces in a sorted
order. If the first interface that we want to originate on has a problem
and svc resolution fails consistently, this means we would not originate
any beacon.
With this change, beacon origination is executed in parallel
such that head-of-line blocking is no longer an issue.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3915)
> cs: avoid HOL blocking in beacon origination

- tools/wireshark/scion.lua
Updated Wireshark dissector plugin for the new SCION header format.
Extensions are not yet supported.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3916)
> tools: SCION v2 wireshark plugin

- doc/build/setup.rst
[doc]
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3929)
> doc: fix typo in setup.rst

- .buildkite/hooks/bazel-remote.yml
- .buildkite/hooks/pre-command
- .buildkite/hooks/pre-exit
- bazel-remote.yml
- go/pkg/gateway/control/engine.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/3958)
> Opensourcing

- tools/wireshark/scion.lua
Add dissector for the EPIC path type header to the Wireshark SCION plugin.
Closes #4083
GitOrigin-RevId: 07ca31ad18f1bf1650530f7c209715684e06968b
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/4105)
> epic: wireshark dissector

- .bazelignore
- .editorconfig
- .gitignore
- gateway/routing/internal/fuzz/fuzz.go
- ineffassign.json
- nogo.json
- pkg/private/xtest/graphupdater/main.go
- pkg/scrypto/cppki/certs_test.go
- private/ca/renewal/grpc/delegating_handler.go
- router/control/conf.go
- scion.bzl
- tools/licensechecker.py
- tools/lint.sh
- tools/tools.go
GitOrigin-RevId: f4b252ddaa7c90ff7617965c1e5101d08ded422d
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/4166)
> repo: cleanup leftover references to the go directory

- router/bfd/BUILD.bazel
- router/bfd/common_test.go
- router/bfd/export_test.go
- router/bfd/metrics_test.go
- router/bfd/session.go
- router/bfd/session_test.go
- router/dataplane.go
remove embedded logger and move to logger from context
GitOrigin-RevId: 710329ccfc28e832ed8e948bb74e2de90661d141
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/4201)
> refactor: remove logger struct field from BFD

- .buildkite/pipeline.yml
- .gitattributes
- Makefile
- doc/command/BUILD.bazel
- tools/BUILD.bazel
- tools/gomocks.py
- tools/install_docker
Make a few small changes to that the repository becomes more usable as a dependency.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/4185)
> build: smaller changes to make the repository more usable as dependency

- gateway/control/BUILD.bazel
- gateway/control/engine.go
- gateway/control/session.go
- gateway/pathhealth/BUILD.bazel
- gateway/pathhealth/registration.go
- gateway/pathhealth/selector.go
- go.mod
- go.sum
- go_deps.bzl
- licenses/data/com_github_mattn_go_runewidth/LICENSE
- licenses/data/com_github_olekukonko_tablewriter/LICENSE.md
Until now it was passed around as an unstructured string.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/4206)
> gateway: pass path information around as a data structure

- doc/cryptography/drkey.rst
This PR extends the specification of the DRKey messages format, i.e., their protobuf definitions, with additional details and explanations.
[doc]
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/4247)
> docs: extend drkey message format spec

- doc/contribute/go-style.rst
Update style recommendation for golang mult-line function declarations to what has already been commonly used in code reviews etc.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/4257)
> doc/go-style: update multi-line func declaration

- rules_openapi/tools/yarn.lock
closes #4261
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/4272)
> rules_openapi: upgrade dependencies

- gateway/dataplane/ingressserver.go
When receiving a malformed packet, the gateway should not panic. Rather, the packet should be discarded.
Fixes #4196
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/4291)
> gateway: fix panic on data port

- pkg/slayers/extn.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/4298)
> Fix typo in doc comment for slayers.EndToEndExtnSkipper

- doc/contribute.rst
Add section on the project governance with the TC Implementation, including a list of the current members.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/4312)
> doc: introduce TC Implementation

- README.md
* Setup link
* Contribution link
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/4345)
> Fixing two links in README.md

- doc/dev/git.rst
noticed a couple issues with tense, nouns, and punctuation. simple fixes hope this helps.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/4350)
> doc: fix grammar in git.rst

- doc/command/scion-pki/scion-pki_certificate_renew.rst
- doc/command/scion/scion_address.rst
- doc/command/scion/scion_ping.rst
- doc/command/scion/scion_showpaths.rst
- doc/command/scion/scion_traceroute.rst
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/4355)
> doc: update generated command docs

- dispatcher/internal/registration/table.go
fixes #4379
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/4381)
> dispatcher: support auto-assigned port for SVC registrations

- CONTRIBUTING.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/4393)
> docs: update link in CONTRIBUTING.md

- doc/control-plane.rst
- doc/glossary.rst
- doc/hidden-paths.rst
- doc/protocols/authenticator-option.rst
- doc/protocols/extension-header.rst
- doc/protocols/scion-header.rst
This PR fixes some typos in the documentation.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/4421)
> doc: fix typos

- WORKSPACE
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/4428)
> build: update Go to 1.21.3

- doc/manuals/control/port-table.rst
Had not been updated after https://github.com/scionproto/scion/pull/4376
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/4462)
> Update the port table to reflect current state.

- private/mgmtapi/tools/README.md
- private/mgmtapi/tools/package.json
- private/mgmtapi/tools/pnpm-lock.yaml
Fixes https://github.com/scionproto/scion/security/dependabot/65
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/4463)
> deps: update web tooling deps

- scion-pki/trcs/sign_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/4476)
> scion-pki: drop spurious false in test skip condition

- README.md
Update scionproto Slack invitation link to non-expiring link.
> Update Slack invitation link in README.md

- private/env/BUILD.bazel
- private/env/env.go
> monitoring: give a timeout to our prometheus request handler

- doc/manuals/common.rst
- doc/manuals/router.rst
router.bfd.disabled -> router.bfd.disable
Fixes #4537
> doc: fix the reference to router.bfd.disable

- router/dataplane.go
This was noticed by a reviewer of #4579
> router: clarified cryptic comment

- pkg/scrypto/signed/msg.go
This allows us to profit from some optimizations the standard library does under the hood and simplifies the code.
> scrypto: use ecdsa.VerifyASN1 instead of ecdsa.Verify

- tools/wireshark/scion.lua
This fixes bug #4598  where the first SCION packet in a capture is never dissected as a SCION packet.
The filter function is (only) called on the first packet of the conversation (4-tuple) since we set the dissector for the conversation.
To also dissect the initial packet of a conversation for which a heuristic dissector function is registered, the dissector has to be called explicitly at the end of the filter function when a packet matches.
From the docs:
https://www.wireshark.org/docs/wsdg_html/#lua_fn_proto_register_heuristic_listname__func_
>The function should perform as much verification as possible to ensure
the payload is for it, and **dissect the packet** (including setting TreeItem info and such) only if the payload is for it, before returning true or false.
Also look at the …
> tools: fixup the wireshark lua packet dissector heuristic filter

- private/app/path/path.go
> private/app/path: include IA in Sort function

- .github/workflows/pr-title.yml
> ci: allow dash in subsystem

- doc/dev/contribute.rst
> doc: update slack invite link

- private/mgmtapi/tools/package.json
- private/mgmtapi/tools/pnpm-lock.yaml
Addresses https://github.com/scionproto/scion/security/dependabot/81
> build: address vulnerability reported by depend-a-bot

- go.mod
- go.sum
- go_deps.bzl
- licenses/data/org_golang_x_net/LICENSE
Fixes https://github.com/scionproto/scion/security/dependabot/85
> build: bump golang.org/x/net from 0.25.0 to 0.33.0

- private/mgmtapi/tools/package.json
- private/mgmtapi/tools/pnpm-lock.yaml
resolve several dependabot security alerts:
- https://github.com/scionproto/scion/security/dependabot/91
- https://github.com/scionproto/scion/security/dependabot/90
- https://github.com/scionproto/scion/security/dependabot/89
- https://github.com/scionproto/scion/security/dependabot/79
- https://github.com/scionproto/scion/security/dependabot/78
- https://github.com/scionproto/scion/security/dependabot/77
- https://github.com/scionproto/scion/security/dependabot/58
> chore: upgrade mgmtapi tools dependencies

- doc/tutorials/deploy.rst
- doc/tutorials/deploy/topology3.json
Hi,
minor updates for the freestanding SCION tutorial page.
Best,
Thomas
> docs: fix tutorial configuration and update SCION release version used

- .bazelrc
- .gitignore
- MODULE.bazel.lock
- scion.sh
- tools/topology/docker_utils.py
Fixes https://github.com/scionproto/scion/issues/4739
> chore: delete gen-certs folder

- doc/cryptography/trc-signing-ceremony-builder.rst
Add capability to configure AWS, Azure, and GCP KMS for TRC signing ceremonies.
> doc: improve TRC signing ceremony builder with kms

- go.mod
- go.sum
fixes https://github.com/scionproto/scion/security/dependabot/107
> fix: upgrade go-chi to fix security vulnerability

- .buildkite/hooks/pre-exit
- pkg/connect/happy/happy.go
> rpc: make eyeballs happier

- MODULE.bazel.lock
- doc/requirements.in
- doc/requirements.txt
Fix Dependabot alerts:
- https://github.com/scionproto/scion/security/dependabot/112
- https://github.com/scionproto/scion/security/dependabot/110
- https://github.com/scionproto/scion/security/dependabot/106
- https://github.com/scionproto/scion/security/dependabot/102
> chore: fix pip-related Dependabot alerts

- README.md
- doc/dev/contribute.rst
* Add references to matrix instance
> doc: add pointers to matrix
