scionproto/scion

external/expiring_dict.py
If these conditions are true:
- the dict is full
- an item is being added
- the item to be evicted has already expired
then popitem (which calls __getitem__) can raise an KeyError exception.
This patch handles this case, just ignoring the exception, as it means
the item has been removed.
A trivial way to trigger the bug in the existing code:
d = ExpiringDict(1, 0)
d[1] = 1
d[2] = 2  # Raises exception
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/901)
=> Fix race-condition in ExpiringDict.__setitem__

docker.sh
`./docker.sh clean` currently does almost the same as the old
`clean_full` with the version of docker we're using now. So this change
merges the two into one, and updates it to work properly with this
docker version.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/902)
=> Merge ./docker.sh clean and clean_full, and update.

Dockerfile, circle.yml, deps.sh
Includes the scion-web tests into CircleCI tests to prevent code rot of the local management system.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/898)
=> Add scion-web to CircleCI integrations tests

endhost/dispatcher.c, go/lib/libscion/checksum.go, lib/libscion/checksum.c, lib/libscion/checksum.h, lib/libscion/scmp.c, lib/libscion/udp.c
While the python code includes a zero'd checksum field in the checksum
calculation input, libscion's UDP and SCMP checksum functions did not.
It's unclear why this didn't cause obvious problems with UDP before, but
it completely broke SCMP checksum support in libscion.
Also:
- Change chk_add_chunk to keep an internal index, removing the need for
specifying the index by the caller.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/903)
=> Fix SCMP/UDP checksum calculation.

endhost/ssp/SCIONProtocol.cpp
MPUDP send was returning bytes sent to dispatcher which was obviously not the expected return value
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/905)
=> Fix MPUDP send return value

endhost/scion_proxy.py, endhost/ssp/SCIONSocket.cpp
Calling C code from the main thread of a Python program makes it impossible to run the Python signal handlers.
Proxy will now do all its work in a daemon thread while the main thread stays alert to signals like ctrl+c.
Also, libssock will not install a SIGINT handler if one already exists (e.g. called from Python).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/906)
=> Let proxy do its own signal handling

infrastructure/path_server/base.py, infrastructure/path_server/core.py, infrastructure/scion_elem.py
I believe it fixes #916.
`_send_waiting_queries()` always extracts a reversed path from pcb. This is incorrect when pcb is reversed already (i.e., happens only for SIBRA core-path segments).
However, the bug is older than the TCP support, thus it is quite suspicious that we didn't notice it before.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/917)
=> fix for #916

circle.yml, deps.sh
Before the go external library dependencies can be resolved, the
generated go code for the capnp definitions needs to be in place.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/920)
=> Fix go dependency ordering

endhost/ssp/ConnectionManager.cpp, endhost/ssp/ConnectionManager.h, endhost/ssp/DataStructures.h, endhost/ssp/Extensions.cpp, endhost/ssp/Extensions.h, endhost/ssp/Makefile, endhost/ssp/Mutex.h, endhost/ssp/MutexScion.h, endhost/ssp/OrderedList.cpp, endhost/ssp/OrderedList.h, endhost/ssp/Path.cpp, endhost/ssp/Path.h, endhost/ssp/PathPolicy.cpp, endhost/ssp/PathPolicy.h, endhost/ssp/PathState.cpp, endhost/ssp/PathState.h, endhost/ssp/ProtocolConfigs.h, endhost/ssp/SCIONDefines.h, endhost/ssp/SCIONProtocol.cpp, endhost/ssp/SCIONProtocol.h, endhost/ssp/SCIONSocket.cpp, endhost/ssp/SCIONSocket.h, endhost/ssp/SCIONWrapper.cpp, endhost/ssp/SCIONWrapper.h, endhost/ssp/SocketConfigs.h, endhost/ssp/Utils.cpp, endhost/ssp/Utils.h
To debug correct use of mutexes in multithreaded applications, it's always handy
to use lock annotations:
http://clang.llvm.org/docs/ThreadSafetyAnalysis.html
In order to do this in our C++ code, this commit does the following:
1. Make a wrapper around pthread mutexes that is annotated with the correct
macros (`ACQUIRE()`, `RELEASE()`, `CAPABILITY("mutex")` and so on) (in
`MutexScion.h`)
2. Import the preprocessor macros that are used by the Clang thread safety
analysis tooling (`Mutex.h`, taken from the Apache-2 licensed lmctfy).
3. Change all uses of mutex-reladed pthread functions to use the class from
(1). There are some raw uses of pthread functions left in
`SCIONWrapper.h`/`.cpp` since that code is used with `extern "C"`. Said code
is simple enough to be checked manually.
4. …
=> Fix mutex locking in SSP and related code

Makefile, docker/integration_test.sh
libssocket (./endhost/ssp) has major threading/locking issues. These
prevent it from working at all on the new HP DL20 servers we're starting
to buy. Our best guess is that this is because the servers have
non-hyperthreaded CPUs, and this is somehow triggering otherwise latent
bugs in the thread handling.
Fixing this would involve a major amount of engineering time (and
probably a rewrite). So, this change stops building/testing libssocket
by default. It can still be used as a proof of concept, but is
definitely unsuitable for any kind of production traffic for the time
being.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/927)
=> Deprecate libssocket.

Makefile, README.md, deps.sh, docker/profile, go/Makefile
On ubuntu 16.04, the default golang version is 1.6, and installing the
`golang` package adds a symlink in `/usr/bin`, so there's no need to add
`/usr/lib/go-1.6/bin` to `$PATH` any more.
Also:
- Improve the golang version detection to allow golang >=1.6
- Generate an error if govendor detects any "outside" packages (i.e.
third-party packages that are outside go/vendor/, or missing).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/928)
=> Use `golang` package instead of `golang-1.6`

.gitmodules, README.md
This allows us to switch the submodule urls back to ssh, to be
consistent with everything else.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/930)
=> Add config command to work-around not having github account.

infrastructure/router/main.py
Otherwise it will may get the wrong interface in case there are multiple
border routers running on the same IP.
Fixes https://github.com/netsec-ethz/scion/issues/932
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/940)
=> Find the border router by it's ID instead of the host address.

infrastructure/scion_elem.py, lib/tcp/middleware.h
Seems like we can enable TCP with `TCP_POLLING_TOUT=15` that seems to be optimal for CircleCI (see #939).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/941)
=> Enable TCP

go/border/hsr/hsr.go, go/border/io-hsr.go, go/border/main.go
readHSRInput was changed to keep a static set of packet buffers for
re-use recently, but the packets were still recycled, meaning they were
available for other parts of the router to reuse. This leads to an
interesting and wide variety of strange errors. This change resets the
packet buffers instead, which clears the contents.
Also:
- Fix a ~cosmetic with how hsr.AddrMs is updated that made debugging
much harder than it needed to be. The old version takes a /copy/ of
each element of AddrMs, and modifies the copy, leaving the original
untouched. The new version fixes that.
- Remove the VSS ulimit, as it causes the hsr library to die fatally on
startup without much useful information.
--- …
=> Fix packet recycling with libhsr in the go router.

infrastructure/scion_elem.py
The infrastructure's use of TCP is fundamentally broken, as TCP
connections are made in the middle of the main processing threads. This
means that if any TCP connection attempt doesn't immediately succeed,
the thread is blocked. E.g. beacon servers trying to register downpaths
can block the entire main worker loop.
Also, TCP spews vast amount of noise into the logs, making it very
difficult to debug anything.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/944)
=> Disable TCP for now.

doc/PathReversal.md
The previous version had two mistakes (the normal Ingress->Egress case
claimed the path was incremented, and the peering ingress->egress case
was treated the same as core/shortcut cases). In addition to fixing
that, the wording is now more general than just revocation handling.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/953)
=> Updating/generalizing/fixing PathReversal.md

docker/integration_test.sh, endhost/sciond.py, infrastructure/beacon_server/base.py, infrastructure/scion_elem.py, test/integration/base_cli_srv.py, test/integration/end2end_test.py, test/integration/revocation_test.sh
This PR adds an integration test for revocation. To that end, the test clients have been extended to handle revocations and optionally retry the test packet up to N times with different paths. The test first runs one round of the e2e integration test between all pairs (without any retries of packets), then introduces link failures between 2-23 <-> 2-26 and 1-11 <-> 2-21 (by stopping br2-26-2 and br1-11-3) and runs another round of the e2e integration test between all pairs, retrying a test packet up to 3 times. The failed links are chosen in a way that ensures at least one working path between any two ASes. The test is thus successful, if every AS can still communicate with every other AS (like with the e2e integration test). 
Note: This test is specifically tailored to our default test …
=> Revocation E2E test

circle.yml, deps.sh
Compiling with go1.7 causes our vendored dependencies to fail to build:
vendor/golang.org/x/net/context/context.go:141: undefined: background
vendor/golang.org/x/net/context/context.go:150: undefined: todo
This change adds the ubuntu-specific go 1.6 path to $PATH for circleci,
and checks to make sure the go version is 1.6 (and disallows 1.7 which
was previously accepted).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/958)
=> Circleci now supplies go1.7, which breaks things.

pkgs_debian.txt
This greatly reduces the amount of work that the pycapnp installation
has to do:
With 500M of ram, it takes 3.5mins for pycapnp to install without the
headers, and 35s with the headers. With less than 500M of ram, pycapnp
install will fail without the headers, but with the headers it can
succeed with 275M of ram (although it takes 5.5mins).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/972)
=> Add libcapnp-dev to packages list

go/border/io-hsr.go, go/border/io.go, go/border/router.go, go/border/rpkt/create.go, go/border/rpkt/rpkt.go, go/vendor/vendor.json
This fixes a leap-second crash (#961). Go's std library currently
doesn't allow access to a monotonic time source, so this PR uses a tiny
third-party library that works around that.
Go 1.9 will (probably) have a fix for this. The design doc is at
https://golang.org/design/12914-monotonic.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/973)
=> Switch go code to use monotonic time for measuring durations.

lib/tcp/middleware.c, lib/tcp/middleware.h
Currently, when an app calls `accept()` the middleware calls `netconn_accept()` that blocks. If the app dies the `netconn_accept()` still is blocking, thus no new app cannot bind to the blocked addr, port pair (even when using `SO_REUSE`).
This PR solves the problem, by running `netconn_accep()` in a loop and periodically checking whether the app is alive.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/976)
=> tcmpw_accept() fix

endhost/sciond.py, infrastructure/path_server/base.py, infrastructure/path_server/core.py, infrastructure/path_server/local.py, lib/crypto/hash_tree.py, lib/packet/path.py, lib/packet/path_mgmt/seg_recs.py, lib/packet/pcb.py, lib/rev_cache.py, proto/path_mgmt.capnp, proto/pcb.capnp, test/lib/packet/path_test.py, test/lib/rev_cache_test.py
Simplified peer revocation handling a lot. A path server now adds revocations for peer interfaces to every path reply. Also implemented a revocation cache that for more efficient access to revocations by (ISD_AS, if_id).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/979)
=> New peer revocation handling.

deps.sh, go/vendor/vendor.json
Note that this will still install Go 1.6 on apt-based distributions.
If/when we want to change that, we need further testing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/992)
=> Allow Go 1.7

go/Makefile
With govendor no longer blacklisting the go17 build tag, it pulls in
vendor/golang.org/x/net/context/go17.go, which depends on that "context"
package that is supplied by go 1.7. This file is not built under go 1.6
due to the build tag, but govendor is not aware of this, and hence under
1.6 it lists "context" as a missing dependency. This change specifically
excludes just this case.
("golang.org/x/net/context" was moved into the standard library as
"context" in go 1.7, hence this problem).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/996)
=> Fix the `context` dependency error after allowing go 1.7.

flake8.ini, pkgs_debian.txt, scion.sh, topology/mininet/flake8.ini, topology/mininet/run.sh, topology/mininet/topology.py
- gen/networks.conf no longer has the subnet mask for each entry, so use
the one from the section title instead.
- Fix an encoding issue with the backported ipaddress module we use.
Also include the dispatcher PID in the script output, so it's clear if
it died.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/997)
=> Fix minor issues with mininet.

endhost/sciond.py, test/integration/base_cli_srv.py
This should fix the flaky revocation test. The reason for the flaky test is a client that uses a path containing a revoked interface and the first hop BR is not alive anymore. The client never receives a revocation, thus it retries the same path over and over again until it reaches the maximum number of retries and fails. With this change a client instructs SCIOND to flush all paths first to make it request new path after the client hasn't received a reponse.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1006)
=> Flush paths when retrying after no response has been received.

endhost/sciond.py, lib/sciond_api/br_req.py, lib/sciond_api/host_info.py, lib/sciond_api/parse.py, lib/sciond_api/path_req.py, lib/sciond_api/service_req.py, lib/types.py, proto/sciond.capnp, test/integration/base_cli_srv.py
This PR implements all the remaining SCIOND API messages (`BRInfo` and `ServiceInfo`) (issue #986). Note, they are currently not tested/used anywhere. This will be done in a follow up PR where also an application layer wrapper around the low level SCIOND API will be provided.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1008)
=> Implemented missing calls of SCIOND API

infrastructure/beacon_server/base.py, lib/errors.py, lib/packet/pcb.py, lib/sibra/pcb_ext.py, test/lib/packet/pcb_test.py
Signatures for capnp objects used in PCBs are defined based on the
version of the capnp definition used. I.e. which fields are covered by
the signature (and in which order) is specific to a given capnp
definition version. This means that when new fields are added, a new
signature definition (which fields, in what order) should be specified.
While this doesn't matter for a homogenous test-bed, as soon as there
are changes made in a production protocol, backwards compatibility is
critical.
The version of a capnp object is defined to be the highest field number,
for simplicity. This change simply calculates the current version
number, and checks to make sure that the correct signature method is
being called. This will have to change once we start implementing actual
backwards compatibility, …
=> Check that signatures on capnp objects are versioned correctly.

topology/generator.py
For the normal local testing setup, this will run a sciond per AS. For
mininet, it will run a sciond per infrastructure element.
In the near future CS will require a running sciond to function.
Based on work by https://github.com/Oncilla
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1017)
=> Run sciond's as part of the infrastructure.

infrastructure/cert_server/main.py, lib/packet/cert_mgmt.py, proto/cert_mgmt.capnp
This avoids any circular dependancies between a path server wanting to
verify an up-path and the cert server trying to get a path if it doesn't
have the cert cached already.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1016)
=> Allow cache-only cert/trc requests.

flake8.ini, go/border/rpkt/addr.go, go/border/rpkt/create.go, go/border/rpkt/rpkt.go, go/lib/addr/host.go, go/lib/spkt/cmnhdr.go, go/lib/spkt/cmnhdr_test.go, lib/libscion/packet.c, lib/libscion/packet.h, lib/packet/scion.py, test/integration/scmp_error_test.py, test/lib/packet/scion_test.py
For:
https://github.com/netsec-ethz/scion/issues/980:
- "Move HdrLen just after TotalLen"
https://github.com/netsec-ethz/scion/issues/982:
- "Change address header order and padding"
N.B.: this change only affects the common header. The address header
will be changed in an upcoming PR instead.
Also:
- Add dedicated Go HostAddrType type.
- Unit tests for go/lib/spkt/cmnhdr.go
- Increase max python line length to 100 to match Go.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1019)
=> Reorder the fields in the common header.

endhost/sciond.py, lib/app/sciond.py, lib/socket.py, test/integration/base_cli_srv.py
Adjust socket timeout in `lib.app.sciond` to 3 seconds and the path request timeout it `endhost.sciond` to 2s. Before, it was the case that the socket timeout in `lib.app.sciond` matched the path request timeout in `endhost.sciond`. It could happen that the app closed the socket, but the `SCIOND` try to send a response over the already closed socket.
Also raise an exception in case send fails.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1021)
=> Adjust socket timeout in lib.app.sciond

lib/app/sciond.py, test/integration/base_cli_srv.py, test/integration/cert_req_test.py, test/integration/cli_srv_ext_test.py, test/integration/end2end_test.py, test/integration/mpudp_test.py, test/integration/scmp_echo_test.py, test/integration/scmp_error_test.py, test/integration/sibra_ext_test.py, test/integration/ssp_test.py
Make integration tests use the local SCIOND instance that gets spawned as part of the infrastructure. Also _try_sciond_api now stops trying to get a path when the connection to SCIOND fails.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1034)
=> Integration tests use local SCIOND

lib/requests.py, test/lib/requests_test.py
If lib.requests gets requests for X faster than the requests expire, and
if the first query it sends doesn't succeed, no new query is sent. This
has been seen to cause up to ~30s between path queries sent by sciond,
for example.
This patch is a simple but brute-force fix - every request now causes a
query to be sent. In the future we will want more intelligent handling
of repeated queries, but this will at least fix this bug for now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1044)
=> Fix a long-standing subtle timing bug in lib.requests

infrastructure/beacon_server/base.py, infrastructure/beacon_server/if_state.py
If a BS starts up (or becomes master) when a given interface is down, it
currently stays permenantly marked as INACTIVE, and is never revoked.
This change makes inactive interfaces timeout the same as active ones,
in both the startup and master-election cases.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1050)
=> Fix handling of inactive interfaces in BS.

.circleci/config.yml, docker.sh
This matches the ram limit on circleci, and prevents zookeeper from
running out of space in the default 64MB /dev/shm.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1058)
=> Limit docker to 4G of ram, increase shm size

go/border/rpkt/extn_traceroute.go
Fixed an overflow bug when calculating the total number of hops in the traceroute extension.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1059)
=> Fix overflow in traceroute extension

go/border/rpkt/extn_traceroute.go, go/border/rpkt/parse.go, lib/packet/ext/traceroute.py, tools/pktprint.py
Also fix a logging statement, and switch pktprint to using
SCIONExtPacket so that extension headers are parsed and printed as well.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1063)
=> Fix two type bugs in extension handling in Go

endhost/sciond.py
Sciond currently never removes a timed-out query from
self.requested_paths. This means that any future queries for that
destination will never cause sciond to send queries to the path server.
This change fixes that by switching to an expiring dict, which will
naturally clean up old queries.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1065)
=> Fix handling of timeouts in sciond

infrastructure/beacon_server/base.py, infrastructure/cert_server/main.py, infrastructure/path_server/base.py, lib/zk/zk.py
Callers can now differentiate between "lock was not acquired", "lock was
already acquired", and "lock was just acquired", which simplifies their
logic a bit.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1075)
=> Return finer-grained information from Zookeeper.get_lock

endhost/dispatcher.c, endhost/sciond.py, infrastructure/beacon_server/base.py, infrastructure/beacon_server/core.py, infrastructure/beacon_server/local.py, infrastructure/path_server/base.py, infrastructure/path_server/core.py, infrastructure/path_server/local.py, infrastructure/scion_elem.py, lib/msg_meta.py
This PR:
- increases limit for open files in dispatcher. Dispatcher opens many files and with TCP (during a heavy load) it goes beyond the default limit (1024)
- introduces `_build_meta()` for creating UDP/TCP meta objects
- introduces the `reuse` flag, that allows to indicate that a given msg should be sent via a shared (TCP) socket
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1067)
=> Few prerequisites for #952

lib/zk/party.py
The current code just prints out the base64-encoded ZkID capnp like
this:
`Current party (/1-11/ps/party) members are: ['EApQAQIFCxARBUoRCRf/cHMxLTExLTEAAABRBAEBDQGLdREBIgl/SQ==', 'EApQAQIFCxARBUoRCRf/cHMxLTExLTIAAABRBAEBDQFndREBIgl/Sg==']`
With this change:
`Current party (/1-11/ps/party) members are: ['ISD-AS: 1-11 Id: ps1-11-1 ([127.0.0.73]:30091)']`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1080)
=> Display zk party members usefully.

lib/log.py
This change adds a `> ` prefix to every additional line in a multi-line
log statement, matching the behaviour of the go logging library we use.
As well as being easier to read, this also simplifies some automated
processing of logs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1081)
=> Format multi-line python log messages better.

docker/Dockerfile.base, lib/util.py, lib/zk/zk.py, test/lib/util_test.py, topology/Zookeeper.yml, topology/generator.py
- Restrict the host ZK to 150M heap size under docker/circleci.
- Restrict the managed ZKs to 50M heap size.
- Log the address and port of the zookeeper instance that kazoo
connected to.
- Fix ZK logging to use a rolling log file.
- Set TZ=UTC for all elements (ZK was using localtime until now).
- Change python signal handling to exit(1) after a ctrl-c.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1084)
=> Reduce ZK memory usage, and various fixes.

env/common.sh, tools/ci/build_prep
- `pip freeze` does not include pip, setuptools, distribute, wheel in
the output, which breaks `env/pip3/check` if any of those are
specified in the requirements.txt.
- Run ./env/deps with APTARGS=-y in `tools/ci/build_prep`, otherwise it
will immediately fail because it can't read an answer from stdin.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1086)
=> Fix 2 issues with dependencies.

.gitignore, go/lib/log/log.go, go/tools/logdog/main.go, lib/log.py
This tool reads the logs specified on the command line and re-emits them
interlevead (by timestamp), with a prefix indicating the file the line
came from. It handles log line continuations gracefully and tries to
keep going, even after parse errors.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1090)
=> Add log merger and make logging a bit more consistent

go/border/ifstate/ifstate.go, go/border/revinfo.go, go/border/rpkt/extn_onehoppath.go, go/lib/addr/isdas.go, go/proto/rev_info.go
If a one-hop-path packet causes an error, the reversed packet's
extension will be incorrectly handled by the next router, causing it to
corrupt the hop field. This change adds a check to make sure the hop
field hasn't already been generated, and if it has to skip generating a
new one.
Also:
- Log when interfaces are added/activated/deactivated.
- Add pretty-printing represntation of a revocation info proto object to
reduce the logging noise.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1102)
=> Fix handling of reversed one-hop-path packets in the BR.

go/border/rpkt/path.go, go/lib/crypto/htree.go, infrastructure/beacon_server/base.py, infrastructure/cert_server/main.py, infrastructure/path_server/base.py, infrastructure/scion_elem.py, lib/crypto/hash_tree.py, lib/crypto/symcrypto.py, lib/defines.py, lib/packet/path_mgmt/rev_info.py, lib/sciond_api/path_meta.py, lib/types.py, proto/rev_info.capnp, test/lib/crypto/hash_tree_test.py
BR uses now a tolerance window when verifying a revocation epoch. Reduce tolerance window to 2s (from 5s). Fixes #1077.
Additionally, the `RevInfo` now contains the hash function type needed to verify the revocation (fixes #854) and the `epoch` in `RevInfo` is now relative to 0 UNIX time (instead of the current TTL window). This fixes a bug when verifying the epoch from a different TTL window.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1083)
=> Revocation epoch tolerance window

.circleci/config.yml, docker/Dockerfile.base
Docker 17.x seems to not tolerate a lack of permissions quite as well as
older versions did. Thus, sprinkle a few `sudo`s into the file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1106)
=> Make base Dockerfile work with newer versions of Docker

Makefile
Exclude sub/web/ad_manager/static/js/ as ctags otherwise prints warnings
like:
ctags: Warning: ignoring null tag in sub/web/ad_manager/static/js/d3.min.js
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1110)
=> Add ctags make target

go/border/rpkt/process.go, infrastructure/beacon_server/base.py, infrastructure/cert_server/main.py, infrastructure/path_server/base.py, infrastructure/scion_elem.py, lib/msg_meta.py, test/integration/end2end_test.py, tools/zkcleanslate
The bug can be reproduced by doing:
./test/integration/end2end_test.py 2-24 1-16
./supervisor/supervisor.sh mstop *:br1-13*
./test/integration/end2end_test.py --retries 3 2-24 1-16
That last step should fail to get any path by the third retry, as the
two core links to 1-13 are down. However, as the BS/PS don't receive the
revocations, the BS continues to register segments that passed through
1-13, and the PS continues to hand out these segments.
This change fixes the logic, so that a core AS will notifiy its BS/PS
services of revocations if the destination is a local AS. Running the
above steps with this change causes the second e2e test to (correctly)
fail to get any paths to 1-13.
Also:
- As RevocationInfo now has a `short_desc` method, stop putting them on a new
line in logging …
=> Fix case where core BS/PS aren't informed about revocations.

python/lib/crypto/certificate.py, python/lib/crypto/certificate_chain.py, python/topology/generator.py, topology/Default.topo, topology/Wide.topo
In the current implementation every AS gets a certificate issued by its parent AS, thus creating long certificate chains.
This PR contains the following changes:
- Clear separation between core and non-core AS certificates
- Core AS certificates are signed and verified based on online root keys
- Only core ASes issue certificates
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1117)
=> Cert sync with book

python/path_server/base.py, python/path_server/core.py, python/path_server/local.py
Replace deques in path servers with expiring dicts to prevent them from growing forever. Fixes #1126.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1133)
=> Replace deques in path servers with expiring dicts

c/dispatcher/dispatcher.c, python/scion_elem/scion_elem.py
The dispatcher was copying 0 bytes of the bind address into the bind SVC
entry, and scion_elem was using the wrong parameter name for
ReliableSocket.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1137)
=> Small fixes to bind address support.

python/lib/topology.py
E.g. if a topo file doesn't have a `SibraService` entry, this will
prevent topology parsing from dying with a key error.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1140)
=> Make python.lib.topology gracefully handle partial topology files.

c/dispatcher/dispatcher.c, c/lib/scion/extensions.c, c/lib/scion/opaque_field.c, c/lib/scion/packet.c, c/lib/scion/path.c, c/lib/scion/udp.c, c/lib/scion/udp.h, go/border/error.go, go/border/rpkt/create.go, go/border/rpkt/extn_onehoppath.go, go/border/rpkt/extns.go, go/border/rpkt/l4.go, go/border/rpkt/parse.go, go/border/rpkt/path.go, go/border/rpkt/rpkt.go, go/lib/spath/path.go, go/lib/spath/path_test.go, go/lib/spkt/cmnhdr.go, go/lib/spkt/spkt.go, python/integration/end2end_test.py, python/integration/scmp_error_test.py, python/lib/packet/ext/traceroute.py, python/lib/packet/ext_hdr.py, python/lib/packet/ext_util.py, python/lib/packet/scion.py, python/test/lib/packet/ext/traceroute_test.py, python/test/lib/packet/ext_hdr_test.py, python/test/lib/packet/ext_util_test.py, python/test/lib/packet/scion_test.py
Refactor Lengths/offsets: (addresses issue #981)
CurrINF, CurrHF, HdrLen, ExtHdrLen are all computed as value * 8.
set CurrINF,CurrHF = 0 if no path.
fix TotalLength computation for spkt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1136)
=> Sync CurrINF, CurrHF, HdrLen, ExtHdrLen with Book

python/lib/crypto/certificate.py
Increase Certificate validity to 1 year, since we currently have no system in place to replace old certs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1142)
=> Increase Certificate validity to 1 year

python/lib/packet/pcb.py
Otherwise it is impossible to distinguish between PCBs that use
different interfaces between a pair of ASes.
Example:
`9922531e290e, 2017-07-05 14:34:12+00:00, 1-13 18>68 1-16 33>56 1-19`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1151)
=> Add interface IDs to PCB short descriptions

python/scion_elem/scion_elem.py
TRCRequest expects isd_as for instantiation. It is done correctly
in _request_missing_trcs(), but not in _check_trc_reqs().
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1152)
=> Fix a bug where TRCRequest is not instantiated correctly.

go/border/main.go, go/border/router.go
If the border router process receives a HUP signal on startup, there's a
short window in which this can cause the process to exit immediately.
This change moves catching SIGHUP to the very start of the process, to
make the window as small as possible.
Also:
- Use buffered channels for signals, as otherwise signals can be lost
(https://golang.org/pkg/os/signal/#Notify)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1160)
=> Reduce a race-condition window for SIGHUP on startup.

.gitignore, python/lib/trust_store.py, python/scion_elem/scion_elem.py, python/test/lib/trust_store_test.py, scion.sh
To avoid deleting cached data from `gen/` and thus triggering restarts
via Ansible, move those files to a separate subdirectory, `gen-cache`.
Also fix `scion.sh` to nuke and (re)make the directory if the topology
is (re)generated.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1161)
=> Separate retrieved TRCs and certs in separate directory

python/lib/msg_meta.py, python/lib/path_seg_meta.py, python/scion_elem/scion_elem.py
A flaw in how segment verification was handled when receiving path segments through Zookeeper lead to a memory leak.
On startup of a server it can happen that the first path segments come from Zookeeper. If not all certificates are available the server requests it from the local CS with the cache only flag set. However, the CS doesn't have this certificate yet, which lead to a rerequesting loop. This loop also prevented requesting the certs from the appropriate beacon servers when new path segments were arriving.
Fixed the issue by having newer path segments always overwrite older ones in the unverified segments map.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1159)
=> Fix memory leak in PS and BS.

.gitignore, go/sig/sig.go, go/sig/xnet/xnet.go
This allows the main forwarding traffic to be easily switched to/away
from the SIG (by changing an ip rule). This also allows SIG healthchecks
to always use the SIG, so it can be checked even when it's not
forwarding the main traffic.
Also:
- Add bin/sig to .gitignore
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1168)
=> Make SIG use an alternate routing table.

go/sig/base/asinfo.go, go/sig/base/forward.go, go/sig/lib/scion/scion.go
This simplifies the logic (no need for a state machine). It now loops
over packets, coping them into frames, and sending a frame whenever it
gets full.
NB: this has some FIXME's here to be fixed/removed when the
IngressWorker also implements the proper design.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1170)
=> Rewritten forwarding code (EgressWorker)

go/border/main.go, go/border/rpkt/parse.go, go/border/rpkt/path.go, go/border/rpkt/process.go, go/border/rpkt/route.go, go/border/rpkt/rpkt.go, go/lib/assert/assert.go
Currently `assert.Must` combined with `rp.ErrStr` causes very expensive
string formatting to be done, even with the assertion passes. This
overhead slows the router by a factor of ~10. This change allows ErrStr
to be lazily evaluated, and only in the case of an assertion failure.
Also:
- Enable pprof http support.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1177)
=> Make assertions in the router Much less expensive.

go/sig/lib/scion/scion.go
Also included some comments on why a UDP socket is allocated but never used.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1176)
=> Egress data now passes through the dispatcher

c/dispatcher/Makefile, c/dispatcher/dispatcher.c, go/sig/xnet/xnet.go
This is a bit of a hack, but our netlink library doesn't support setting
this.
Also:
- Fix error when compiling the dispatcher while it's running.
- Disable debug logging in the dispatcher (only really affects sending
logs)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1182)
=> Set tx qlen on tun devices.

go/Makefile, go/vendor/vendor.json
If you're on a branch that requires go packages installed that aren't
required by master, when you switch back to master those packages aren't
removed, and can then cause build failures. This change will check for
this issue and work around it, but it's slightly brute-force: any
unneeded packages are also removed from govendor's cache.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1185)
=> Fix stale dependency handling for govendor.

c/dispatcher/Makefile, c/dispatcher/dispatcher.c
Everytime scmp_parse_payload is called, it mallocs a new SCMPPayload
struct, which was never being freed.
Also:
- Force copy dispatcher to bin/, fixing the error that happens if the
dispatcher is already running.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1184)
=> Fix scmp memory leak in dispatcher

c/lib/scion/checksum.c, c/lib/scion/scmp.c, c/lib/scion/udp.c, go/lib/l4/common.go, go/lib/util/checksum.go, go/lib/util/checksum_test.go, python/lib/packet/scion_udp.py, python/lib/packet/scmp/hdr.py, python/test/lib/packet/scion_udp_test.py, python/test/lib/packet/scmp/hdr_test.py
IMPORTANT: This change is incompatible with previous versions of SCION services.
Also:
* Checksum function is now commutative
* Byte order is correct on wire
* Odd-length chunks are individually padded with a 0 byte at the end
* The SCION/UDP pseudoheader upper protocol type field is padded with a 0 to the left (same as IP)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1190)
=> Added checksums in native Go

go/sig/lib/scion/scion.go
The egress checksum was incompatible with the new version on master (incorrect padding, wrong byte order).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1193)
=> Fixed faulty checksum in SIG egress

c/dispatcher/Makefile, c/dispatcher/dispatcher.c, c/lib/scion/Makefile, c/lib/scion/checksum.c, c/lib/scion/udp.c, c/lib/scion/udp.h
- Instead of allocating a new chk_input struct for each packet inside
`scion_udp_checksum()`, have the caller allocate one and pass it in
repeatedly. This saves a Large number of mallocs/frees.
- Simplify `checksum()`:
- The checksum algorithm is already endian-agnostic, so remove all
byte-swapping.
- With a 32-bit accumulator, overflow is avoided, removing the need
for checks.
Some simple benchmarks of `checksum()` put this at >2x faster than
the existing implementation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1198)
=> Improve checksum performance for dispatcher.

c/dispatcher/Makefile, c/lib/scion/Makefile
This will prevent the dispatcher from segfaulting when libraries are
re-compiled.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1202)
=> Link dispatcher statically against scion libs.

go/lib/sring/rb.go, go/lib/sring/sring.go, go/lib/sring/sring_test.go
On creation, the ring buffer populates itself with buffers. Writers reserve buffers, process them and then write the references back. Readers read buffers, process them and then release the references back to the ring buffer.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1196)
=> Added ring buffer for slice elements

go/sig/base/forward.go, go/sig/base/framebuf.go, go/sig/base/ingress.go, go/sig/base/rlist.go
Logging in the fast path severely impacts performance even if the logs aren't written to files. This PR deletes or comments out all per packet logging.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1208)
=> Clean up SIG ingress/egress logging

go/lib/common/defs.go, go/lib/util/checksum.go, go/lib/util/checksum_test.go
Before: 948 ns/op
After: 455 ns/op
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1209)
=> Increase go checksum performance 2x

go/lib/ringbuf/metrics.go, go/lib/ringbuf/ringbuf.go
This simplifies its use in places where you are passing data through
multiple ring-buffers without copying. This also means it can just be
used as a free buffer pool regardless of how filled buffers are passed
around.
Also:
- Add a `Close()` method, to allow shutting down of go routines who are
blocked reading/writing to the ring buffer.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1214)
=> Re-factor sring to a single ringbuffer

go/border/main.go, go/border/metrics/metrics.go, go/lib/overlay/conn/c.go, go/lib/overlay/conn/conn.go, go/lib/overlay/conn/metrics.go, go/lib/ringbuf/metrics.go
With SO_TIMESTAMP on a socket, the kernel returns when a packet arrived
when readmsg is called.
As the size of `struct timeval` isn't available anywhere in the go std
lib, this change adds a very short cgo file to calculate the sizes, and
also handle conversion of `struct timeval` to `time.Time`.
Also:
- Clean up metrics on overlay/conn - it no longer imports the border
metrics module.
- Add missing subsystem to ringbuf metrics.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1217)
=> Add SO_TIMESTAMP support.

go/lib/overlay/conn/conn.go
When a udp socket is created, conn will now try to set a 1MiB receive
buffer size. If the resulting size is less than requested, a warning is
logged. This change also adds a command-line flag to turn this warning
into a socket error, for use in production environments.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1218)
=> Increase overlay.conn receive buffer sizes.

go/border/metrics/metrics.go, go/border/router.go, go/border/setup.go, go/lib/overlay/conn/metrics.go, go/lib/prom/prom.go, go/lib/ringbuf/metrics.go, go/sig/metrics/metrics.go, go/sig/sig.go, python/topology/generator.py
By making metrics be configured on start rather than at compile time, we
can easily include things like the element ID in all labels a process
exports. It also removes a lot of boiler-plate.
Note: this change adds a mandatory -id flag to the sig.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1221)
=> Refactor prometheus metrics configuration.

go/border/ifstate/ifstate.go, python/beacon_server/base.py, python/lib/packet/path_mgmt/ifstate.py, python/path_server/base.py
Currently, the BR assumes that it always receives a batch of `IFStateInfos` for all interfaces.
Also: Do not include a `RevInfo` if the interface is not revoked. Fixes #865.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1216)
=> Always include IFStates of all interfaces.

go/border/io.go, go/border/router.go, go/border/rpkt/rpkt.go, go/lib/ringbuf/ringbuf.go
When a packet was created by the BR (e.g. via `genPkt()`), references to
this packet would be retained in the egress ringbuf's until overwritten,
preventing it from being GC'd. Over time, this would lead to 1024 64KiB
packet references been kept, causing the RSS to balloon up to a maximum
size of ~200MiB.
This change:
- Clears references from a ringbuf on `Read()`
- Clears references from read/write slices passed to a ringbuf.
Also:
- Reduce the packet buffer size to handle jumbo frames (a 7x reduction),
as there is currently no reason to support packet sizes beyond that.
- Make RtrPkt.Reset() slightly more comprehensive.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1 …
=> Fix a memory leak in br/ringbuf.

tools/pktgen.py
Increases the possibility to test for higher loads since the packet size is limited by the MTU.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1225)
=> Waiting time to be a float instead of int

go/border/rpkt/create.go, go/border/rpkt/payload_ctrl.go, go/border/rpkt/rpkt.go
The packet buffer in the a `RtrPkt` was not reset correctly after use. It didn't bite us, because we were doing it wrong consistently.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1226)
=> Correctly reset rpkt buffer

.gitignore, go/lib/snet/addr.go, go/lib/snet/addr_test.go, go/tools/echo/Readme.md, go/tools/echo/echo.go
This PR adds a simple tool, written in Go, for echo request/reply connectivity tests.
This tool:
- showcases a simple use of the new SCION connection library;
- serves as a starting point for SCION end to end integration tests;
- can be used to test connectivity between any pair of ASes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1233)
=> Add demo/connetivity tool for SCION in Go

go/lib/pathmgr/defines.go, go/lib/pathmgr/pathmgr.go, go/lib/pathmgr/pathmgr_test.go, go/lib/snet/conn.go, go/lib/snet/snet.go
The SCION connection library can only get paths from the resolver by registering source and destination IAs for continuous monitoring. This is expensive, and should only be used for performance critical paths.
This extends the path resolver API with a new function for simple queries. It also moves all path information to the path resolver; this will allow us to put all revocation logic in the path resolver.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1237)
=> Add simple path queries to path resolver

docker/Dockerfile, go/lib/ctrl/path_mgmt/rev_info.go, proto/rev_info.capnp, python/beacon_server/base.py, python/lib/config.py, python/lib/crypto/hash_tree.py, python/lib/defines.py, python/lib/packet/path_mgmt/rev_info.py, python/path_server/base.py, python/test/lib/config_test.py, python/test/lib/crypto/hash_tree_test.py, python/topology/generator.py, tools/ci/build_prep
This PR adds the ability for each AS to configure the TTL of both their path segments and the revocation tree. The revocation tree TTL has to be at least as large as the path segment TTL.
Since each AS now can have a different revocation tree TTL, each revocation needs to include the TTL of the corresponding tree. Fixes #1098.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1164)
=> Make PathSegmentTTL and RevocationTreeTTL configurable.

go/lib/common/errors.go, go/lib/sciond/infra_test.go, go/lib/sciond/sciond.go, go/lib/sciond/sciond.goconvey, go/lib/sciond/sciond_test.go, go/lib/sock/reliable/bench_test.go, go/lib/sock/reliable/reliable.go, go/lib/sock/reliable/reliable.goconvey, go/lib/sock/reliable/reliable_test.go, go/lib/xtest/xtest.go, go/lib/xtest/xtest_test.go, go/proto/cereal.go
Dispatcher registrations and SCIOND queries in Go can block indefinitely, leaking goroutines and making it difficult to implement timeouts in calling code (such as the SCION socket library).
This PR adds timeout and deadline support to SCIOND and dispatcher interactions.
Also:
* CError Data field changed to interface{} to support embedded errors
* Enabled goconvey global test timeouts in some tests which deal with timeouts
* Moved infra tests to a different filename to clearly distinguish them from standard unit tests
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1250)
=> Added timeout support to reliable sock and sciond

Makefile, go/border/rpkt/process.go, go/lib/ctrl/ctrl.go, go/lib/ctrl/path_mgmt/path_mgmt.go, go/lib/sciond/types.go, go/proto/doc.go, go/proto/gen.go, proto/ctrl_pld.capnp, python/beacon_server/base.py, python/cert_server/main.py, python/integration/cert_req_test.py, python/lib/app/sciond.py, python/lib/packet/ctrl_pld.py, python/lib/packet/packet_base.py, python/lib/sciond_api/base.py, python/path_server/base.py, python/path_server/core.py, python/path_server/local.py, python/scion_elem/scion_elem.py, python/sciond/sciond.py, python/sibra_server/main.py
Also:
Rename `contents` to `union` since there can only be one unnamed union in a capnp struct.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1257)
=> Renamed SCION proto to CtrlPld

go/lib/ctrl/seg/hop.go, go/lib/ctrl/seg/seg.go, proto/pcb.capnp, python/lib/packet/pcb.py, python/lib/path_combinator.py, python/lib/path_store.py, python/path_server/base.py, python/test/lib/packet/pcb_test.py, python/test/lib/path_combinator_test.py
Also: Globally renamed in/outIF to remoteIn/remoteOutIF
```
sam@workbox:~/go/src/github.com/netsec-ethz/scion$ git grep '\.inIF'
sam@workbox:~/go/src/github.com/netsec-ethz/scion$ git grep '\.outIF'
sam@workbox:~/go/src/github.com/netsec-ethz/scion$ 
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1260)
=> Fix PS._validate_segment to use the correct interface IDs.

.gitignore, go/lib/ringbuf/ringbuf.go
This prevents data-loss when a writer has finished with the ringbuf and
calls Close().
Also:
- Update .gitignore for echoscion
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1265)
=> Allow reading data from a closed ringbuf.

go/lib/pathmgr/filter_map.go, go/lib/pathmgr/filter_map_test.go, go/lib/pathmgr/pathmgr.go, go/lib/pathmgr/pathmgr_test.go, go/lib/pathmgr/pred.go, go/lib/pathmgr/pred_test.go, go/lib/pktcls/action.go, go/lib/pktcls/action_map_test.go
This will prevent the BR from importing `gopacket` via ctrl->sigmgmt->sigcmn->snet->pathmgr->pktcls->gopacket, and therefore reverse the resident memory usage jump from ~20M to ~40M, which is causing CI to fail due to running out of memory.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1286)
=> Move PathPredicate from pktcls to pathmgr.

go/lib/hpkt/hpkt_test.go, go/lib/hpkt/read.go, go/lib/snet/addr.go, go/lib/snet/conn.go, go/sig/base/as.go, go/sig/base/map.go, go/sig/config/config.go, go/sig/disp/disp.go, go/sig/egress/dispatcher.go, go/sig/egress/session.go, go/sig/egress/sessmon.go, go/sig/egress/worker.go, go/sig/ingress/dispatcher.go, go/sig/ingress/worker.go, go/sig/sig.go
- Have a single, default session per remote AS.
- Add subloggers to various SIG elements, for cleaner logging.
- Take a copy of the src addr when processing ctrl packets, as otherwise the
address gets overwritten by the next packet.
- Make session monitor more robust.
- Update encap header to have session Id, and reorder fields (work by @shitz).:
Also:
- Fix a bug in setting spath offsets when reading a packet.
- Expand snet.Addr's Copy() to copy the path and next hop info.
- Only call InitOffsets on pathmgr-supplied paths in snet.Conn's write()
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1289)
=> SIG updates and trimming.

python/integration/base_cli_srv.py, python/integration/cert_req_test.py
Currently, cert_req_test.py only sends certificate requests, but no TRC requests are issued.
In this PR, cert_req_test.py requests TRC, after CertChain has been successfully received.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1291)
=> Fix cert/trc request test

.circleci/config.yml, env/go/common.sh, env/go/deps
This change removes go 1.8 as a valid choice, as we are likely to soon
be using go1.9-specific features like sync.Map.
Replaces https://github.com/netsec-ethz/scion/pull/1254
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1302)
=> Switch to go 1.9.

go/border/gen.go, go/border/netconf/interface.go, go/border/setup.go
This fixes a bug where generating an IFID packet for a NAT'd interface
will cause an interface id lookup to fail, and currently causes a
nil-pointer panic.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1301)
=> Use public addresses as map keys in BR.

go/lib/ctrl/cert_mgmt/cert_mgmt.go, go/lib/ctrl/cert_mgmt/chain_rep.go, go/lib/ctrl/cert_mgmt/chain_req.go, go/lib/ctrl/ctrl.go
Add support for cert managment payloads to go:
- Add support for chain request
- Add support for chain reply
Not supported yet:
- TRC req
- TRC rep
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1308)
=> Add cert mgmt support to go

go/lib/ctrl/path_mgmt/seg_recs.go, go/lib/ctrl/path_mgmt/seg_reply.go, go/lib/ctrl/path_mgmt/seg_req.go, integration/revocation_test.sh, proto/path_mgmt.capnp, python/lib/packet/path_mgmt/base.py, python/lib/packet/path_mgmt/seg_recs.py, python/lib/packet/path_mgmt/seg_req.py, python/lib/util.py, python/path_server/base.py, python/path_server/core.py, python/path_server/local.py, python/sciond/req.py, python/sciond/sciond.py
Also:
PathReplies now include the PathRequest they are responding to.
PathRecordsSync is now used to propagate path segments to other core PSes and to the master PS.
Fix a race condition in path request handling
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1280)
=> Make SCIOND return multiple paths and not just the first one

go/lib/log/log.go, go/lib/log/syncbuf.go
The existing liblog uses a bufio.Writer to buffer log output, with a
goroutine calling `.Flush()` on it every 5s. However, bufio.Writer is
_not_ thread-safe, so if flush was ever called while a logging statement
was called, the results are undefined.
This issue was discovered while investigating why our go processes
sometimes stop logging permenantly (e.g. a week without logging
anything), and need to be restarted. It's not clear if this is related
to the race-condition, only time will tell.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1312)
=> Fix a logging race-condition.

go/sig/base/as.go, go/sig/egress/sessmon.go, go/sig/egress/worker.go, go/sig/ingress/dispatcher.go, go/sig/ingress/worker.go
As the SIG sequence number is now 24bit, we can't rely on uint32
handling the wrapping for us. This caused the receiving SIG to consider
all frames in an epoch after the first 16mil as "too old", and drop them.
Also:
- Fix a bug that would prevent sigmgr from shutting down.
- Add some extra log statements to mark the start/stop of major go
routines.
- Don't log timeouts if there is no path.
- Simplify ingress worker start/stop/cleanup.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1315)
=> Fix SIG seq nr wrapping.

go/lib/hpkt/read.go, go/lib/pathmgr/apppath.go, go/lib/scmp/info.go, go/lib/snet/conn.go, go/lib/snet/integration_test.go
This PR adds revocation support to the Go application networking stack.
Due to concurrency issues, it depends on the changes suggested by @jpcsmith in https://github.com/netsec-ethz/scion/pull/1253.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1272)
=> Full revocation support in snet

go/lib/scmp/scmp.go, python/lib/packet/scmp/types.py, tools/wireshark/scion.lua
This change parses the SCMP HBH header, and the SCMP l4 header.
Also:
- Separate out HBH and E2E extensions in the tree.
- Remove redundant "SIBRA_" prefix from SIBRA scmp types.
- Validate UDP/SCION length field.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1326)
=> Add scmp header support to wireshark dissector.

go/lib/snet/snet.go
Updated docstring of `snet` to prevent dispatcher deadlocks and silent ignoring of SCMP errors.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1323)
=> Clarify SCMP behavior of snet

go/border/rpkt/route.go, go/border/rpkt/rpkt.go
As Rpkt.Release() is called from multiple goroutines, the reference
decrement needs to be atomic.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1327)
=> Fix a race-condition in Rpkt reference counting.

python/lib/crypto/asymcrypto.py, python/topology/generator.py
pynacl encodes the seed, instead of the actual signing key.
The go library, however, needs the actual key for signing.
Change to naming scheme:
- The seed is now stored in as-sig.seed
- The actual key is stored in as-sig.key
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1329)
=> Store actual ed25519 key in file

go/sig/base/pollhdlr.go, go/sig/disp/disp.go, go/sig/egress/session.go, go/sig/egress/sessmon.go, go/sig/egress/worker.go, go/sig/ingress/dispatcher.go, go/sig/ingress/worker.go, go/sig/mgmt/addr.go, go/sig/mgmt/common.go, go/sig/mgmt/poll.go, go/sig/sigcmn/common.go
go/lib/ctrl depends on go/sig/mgmt, which depends on go/sig/sigcmn,
which depends... on a lot of other things. One symptom is that all go
binaries that included go/lib/ctrl would get the SIG's command-line
flags. This change removes the need for go/sig/mgmt to import
go/sig/sigcmn.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1333)
=> Reduce imports by go/sig/{mgmt,sigcmn}

go/proto/Makefile
Currently if a `proto/*.capnp` file gets renamed, the generated
`go/proto/*.capnp.go` file doesn't get removed, and then compilation
fails as the same type is defined in multiple .go files. This change
allows make to detect and remove these stale files (and without using
shell, so `make -q` has the knowledge).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1335)
=> Make go/proto build cleanly even after proto renaming.

go/lib/ctrl/cert_mgmt/cert_mgmt.go, go/lib/ctrl/cert_mgmt/chain_req.go, go/lib/ctrl/cert_mgmt/trc_rep.go, go/lib/ctrl/cert_mgmt/trc_req.go
Extend support for cert management payloads in go:
- Add support for TRC request
- Add support for TRC reply
(extends PR #1308)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/1339)
=> Add TRC to cert mgmt in go

go/lib/topology/doc.go, go/lib/topology/raw.go, go/lib/topology/testdata/basic.json, go/lib/topology/testdata/core.json, go/lib/topology/topology.go, go/lib/topology/topology_test.go
add field "Core" to topology in go implementation
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1345)
=> Go add 'Core' to topology

go/lib/pathmgr/pathmgr.go, go/lib/pathmgr/pathmgr_test.go, go/lib/snet/snet.go
This allows apps to customize their networking context, e.g., by customizing the path resolver used by the context.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1349)
=> Added support to pass custom networking context to snet

.circleci/config.yml, go/border/io-hsr.go, go/border/io.go, go/border/router.go, go/border/rpkt/create.go, go/border/rpkt/rpkt.go, go/lib/overlay/conn/conn.go, go/lib/sockctrl/sockopt.go, go/lib/topology/addr.go, go/vendor/vendor.json
N.B.: this only works with go 1.9+, and on linux.
Go 1.9 added support for reading and writing batches of packets from
sockets, via golang.org/x/net/ipv4. This patch adds support for this to
overlay/conn, and updates the BR to use it. Some performance testing
shows this gives an extra 4-500MBps performance to the BR.
Also:
- Remove gavv/monotime, now that we're on go1.9 which has monotonic time
handling.
- Fix major bug in sockopt where supplied values were ignored.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1348)
=> Add support for ReadBatch/WriteBatch socket operations.

go/cert_srv/cert.go, go/cert_srv/io.go, go/cert_srv/trc.go, go/lib/ctrl/cert_mgmt/cert_mgmt.go, go/lib/ctrl/cert_mgmt/chain.go, go/lib/ctrl/cert_mgmt/trc.go, go/lib/ctrl/cert_mgmt/trc_req.go, proto/cert_mgmt.capnp, python/cert_server/main.py, python/integration/cert_req_test.py, python/lib/packet/cert_mgmt.py, python/lib/types.py, python/scion_elem/scion_elem.py
Modifies TRCRequest proto to hold only the isd number instead of ISD-AS.
Adds the capability to request the newest CertChain/TRC
- Version == maxUint64 indicates that the newest version shall be returned
- CS responds with the newest in cache
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1354)
=> Modify TRCRequest proto

c/dispatcher/dispatcher.c, c/lib/scion/utils.c
The current dispatcher design will deadlock if an application is failing
to read from its socket and that socket's buffer fills up.
https://github.com/scionproto/scion/issues/1278 is the relevant issue.
This patch adds a 2s read/write timeout for app sockets, after which the
dispatcher will log an error and close the socket. This doesn't fully
fix the issue, but it does mean the dispatcher can recover, and there
will be clear logging to ease debugging, while hopefully avoiding any
packet loss during normal operation.
Also:
- Fix a memory leak in parse_request.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1356)
=> Add send/recv timeouts for the dispatcher on app sockets.

go/lib/infra/messaging/messaging.go, go/lib/infra/messaging/types.go, go/lib/infra/messaging/udp.go, go/lib/infra/messaging/udp_test.go, go/lib/util/bufpool/bufpool.go, go/lib/util/freepool/freepool.go, go/lib/xtest/loopback/loopback.go
Implements a protocol for messages with ACKs on top of a net.PacketConn object.
Also:
- A dummy loopback connection object for simplified testing;
- An elastic free buffer pool that multiple goroutines can share (when batching is not a performance concern yet).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1359)
=> UDP with ACKs for SCION infra

go/lib/common/binary.go, go/lib/common/binary_test.go, go/lib/common/defs.go, go/lib/infra/messaging/types.go, go/sig/egress/worker.go, go/sig/ingress/worker.go
These two methods allow for reading/writing unsigned integers to/from
big-endian ordered bytes with any width from 1 to 8 bytes. This
simplifies logic where the code needs to, say, parse/pack a 3-Byte uint
field.
The SIG encap protocol code is updated to use this new approach.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1360)
=> Add common.Order.{Put,}UintN

.circleci/config.yml, .gitignore, go/lib/snet/squic/squic.go, go/tools/echoscion/echo.go, go/vendor/vendor.json, scion.sh
This is based on the https://github.com/lucas-clemente/quic-go
implementation, with a thin wrapper to work on top of UDP/SCION.
echoscion is updated to use QUIC/SCION as an example application.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1361)
=> Basic QUIC/SCION support for Go.

go/border/io.go, go/lib/common/errors.go
If WriteBatch returns an error, pktsWritten can be -1. This causes the
copy() at the end of the loop to panic with an out of bounds error.
This patch changes the logic when an error occurs:
- If _some_ packets were sent, process those as normal.
- If no packets were sent, and the error is known to be temporary,
retry.
- If no packets were sent, and the error is not known to be temporary,
drop the current batch of packets, and move on.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1364)
=> Fix posixOutput out of bounds error.

python/lib/crypto/util.py, python/topology/generator.py
pynacl encodes the seed, instead of the actual signing key.
The go library, however, needs the actual key for signing.
Change to naming scheme:
The seed is now stored in online-root.seed and offline-root.seed
The actual key is stored in online-root.key and offline-root.key
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1363)
=> Store actual online/offline key in file

python/cert_server/main.py, python/lib/sciond_api/path_meta.py
If a CS needs to send a trc request to a remote AS, it uses `ISD-0` as
the destination AS for the path lookup, which sciond supports. However,
the current code uses the same IA for the data-plane address, which is
illegal.
This patch adds two helpers to `FwdPathMeta` to allow an app to easily
determine the source/destination ASes, and updates the CS to use this
information.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1370)
=> Fix trc req path bug.

go/cert_srv/main.go, go/lib/trust/key_conf.go
Add key configuration to go lib.
The key configuration holds:
- AS decryption key
- AS signing key
- AS online key (for core AS)
- AS offline key (for core AS)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1371)
=> Add KeyConfig

go/lib/crypto/cert/chain.go, go/lib/crypto/trc/trc.go, python/lib/crypto/certificate_chain.py, python/lib/crypto/trc.py
Fix certificate chain verification and TRC active check
- make sure that core certificate can be used to issue certificates
- make sure TRC is only active if not in quarantine
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1381)
=> Fix CertChain/TRC verification

python/sciond/sciond.py
1. _remove_revoked_pcbs() now only removes segments if they have
revoked upstream PCBMarking.
2. handle_revocation now caches directly-received revocations instead of
just using them once and then dropping them.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1382)
=> Fix 2 issues with sciond revocation

go/border/gen.go, go/border/revinfo.go, go/border/rpkt/process.go, go/cert_srv/cert.go, go/cert_srv/trc.go, go/lib/ctrl/cert_mgmt/cert_mgmt.go, go/lib/ctrl/ctrl.go, go/lib/ctrl/ctrl_msg/msg.go, go/lib/ctrl/path_mgmt/path_mgmt.go, go/lib/ctrl/signed.go, go/lib/ctrl/signed_util.go, go/proto/sign.go, go/sig/base/pollhdlr.go, go/sig/egress/sessmon.go, proto/ctrl_pld.capnp, python/lib/packet/ctrl_pld.py
This patch reworks how scion ctrl payloads are created/signed/verified.
By using callbacks, an app can create and sign a ctrl payload and only
have a single error value to check, greatly reducing boiler-plate. It
also becomes much more obvious when a message is not being signed.
This patch also adds support for non-union data at the CtrlPld, CertMgmt
and PathMgmt levels. This allows for a unified approach to things like
request IDs, tracing, and error reporting.
Also:
- Cache the parsed CtrlPld in SignedCtrlPld, to reduce the overhead of
extracting it multiple times.
- Add request ID and trace ID to CtrlPld, though they are currently not
used.
--- …
=> Simplify handling of signed ctrl messages.

go/sig/base/map.go
This caused a very subtle bug in the SIG that only manifests once
you have multiple remote ASes in the config. All ASes configured in a
single config load would end up with the same IA in some parts of the
logic, leading to utter sanity loss.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1387)
=> Don't use a reference to a loop var

go/lib/spkt/spkt.go, go/sig/egress/worker.go
The current SIG code assumes that the address+path headers are <= 40B
long. This only happens to work because the existing environmets have a
single hop involving a core AS, and using IPv4 addresses. This fixes the
SIG to calculate the actual address+path header sizes, and use those.
N.b. it still does not include any extensions that might be in use. That
will eventually depend on snet providing that information.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1388)
=> Include address and path header lengths in SIG frame size calculation.

go/lib/pathmgr/resolver.go
The loop variable, `request`, is re-used, which means that referencing
it later from a closure will not yield the expected value.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1392)
=> Fix loop var reference issue in pathmgr

go/lib/common/errors.go, go/lib/scmp/error.go
This solves the issue of errors being logged without the use of
`FmtError` (which currently would just show the first error in the
stack).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1396)
=> Make custom errors be self-formatting.

go/lib/addr/isdas.go, go/lib/ctrl/seg/as.go, go/lib/ctrl/seg/hop.go, go/lib/ctrl/seg/seg.go, go/lib/pathdb/sqlite/sqlite_test.go
This prevents a malicious AS from removing ASEntries from a PathSegment
during beaconing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1394)
=> Add PathSegment ASEntry-ordering validation.

go/border/rpkt/rpkt_hook_test.go, go/border/rpkt/rpkt_test.go, go/lib/l4/udp_test.go
Here is the new version with (hopefully) all review findings by Scrye applied:
* SoMsg is now used everywhere with the reason explaining the test failure
* The number of blank lines is now much reduced.
* Basically everything is now moved into Convey
* ShouldResemble is consistently used everywhere.
* Underscores are removed from names.
* Cache test is removed from this pull request.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1355)
=> Unit tests for Rpkt and Udp

proto/path_mgmt.capnp, python/beacon_server/base.py, python/cert_server/main.py, python/lib/packet/ctrl_pld.py, python/lib/packet/path_mgmt/seg_req.py, python/lib/util.py, python/path_server/base.py, python/path_server/core.py, python/path_server/local.py, python/scion_elem/scion_elem.py, python/sciond/sciond.py
Also:
- Obsolete SegReq.id, as it's no longer useful.
- Removed a now-unsed random_uint64() function from util, and made a
similar one in ctrl_pld.py (which specifically avoids 0 as a value).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1403)
=> Update python infra to use CtrlPld.reqId

docker.sh, go/Makefile, python/beacon_server/base.py, python/beacon_server/core.py, python/beacon_server/local.py, python/bin/sciond, python/cert_server/main.py, python/lib/main.py, python/path_server/base.py, python/path_server/core.py, python/path_server/local.py, python/scion_elem/scion_elem.py, python/sciond/sciond.py, python/test/lib/main_test.py
- Make spki cache location configurable.
- Make logs dir configurable.
- Enable `make -sC go deps_proto` to be silent if there are no changes.
- Don't load `as.yml` unless necessary.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1421)
=> Various fixes/cleanups.

proto/sciond.capnp, python/lib/app/sciond.py, python/lib/sciond_api/base.py, python/lib/sciond_api/segment_req.py, python/lib/types.py, python/sciond/sciond.py, python/test/lib/app/sciond_test.py
- Adds ability to request detailed segment data after get_paths
succeeds.
- Returns requested segments data (core, up, down).
- Requested segment data can be used to calculate core ASes in paths.
- Requested segment data can be used to calculate path types.
- Useful for visualizations to display core and path types for every AS
routed through.
- Closes #1299.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1383)
=> Adds sciond request for segments used to construct paths

go/cert_srv/cert.go, go/cert_srv/conf/conf.go, go/cert_srv/conf/customers.go, go/cert_srv/main.go, go/cert_srv/trc.go, go/lib/trust/key_conf.go, python/topology/generator.py
Add customer mapping during topology generation.
Core ASes are responsible for all ASes they issue a certificate for.
Core ASes store verifying keys associated with their customers to verify certificate reissuance requests.
The naming convention is ISDx-ASy-Vz.key, where z denotes the first certificate version of AS x-y which authenticates the key. The keys are stored in cs_config_dir/customers.
For each AS, the key with the highest associated version is loaded.
New key files are only written, when the verifying key changes.
If the core AS needs to remove a customer or change the verifying key manually (e.g. key compromise), the key files
are adjusted as desired and a SIG_HUP is sent to the CS-go process to force reload the customer mapping.
Additionally:
- move trust store from …
=> Add customer mapping to CS

go/cert_srv/io.go, go/lib/ctrl/cert_mgmt/cert_mgmt.go, go/lib/ctrl/cert_mgmt/chain_iss_rep.go, go/lib/ctrl/cert_mgmt/chain_iss_req.go, proto/cert_mgmt.capnp
Add certificate chain reissuance request and response.
The requests consists of the desired leaf certificate.
The response consists of the reissued certificate chain.
Request signatures are added to signed payload.
Code for signing an verifying requests will follow in a future PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1401)
=> Add cert reissue req/rep

go/lib/sciond/sciond.go
The documentation strings were on private objects, which means they were not included in the godoc. Now they're moved to interface definitions, making them public.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1422)
=> Fix SCIOND godocs

python/lib/path_store.py
Before: 'Segment dropped due to path policy: Unwanted AS(%s): %s f056531e3b80, 2018-02-22 14:00:35+00:00, 1-11 70'
After: 'Segment dropped due to path policy: Unwanted AS(1-11): f056531e3b80, 2018-02-22 14:02:11+00:00, 1-11 70'
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1416)
=> Fix policy logging

.circleci/config.yml, env/pip3/requirements.txt, go/examples/pingpong/pingpong.go, go/lib/snet/squic/squic.go, go/vendor/vendor.json, python/lib/packet/scion_udp.py, python/lib/packet/scmp/hdr.py, python/test/lib/packet/scion_udp_test.py, python/test/lib/packet/scmp/hdr_test.py
- scapy-python3 uses GPL, so replacing it with pypacker which is
BSD-licensed.
- quic-go unfortunately depends on 4 repos which are unlicensed, so
until this can be remedied, all quic-go support is disabled and the
depdendencies are removed.
Also:
- Remove some unused Go deps.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1435)
=> Dependency licence audit.

go/lib/infra/transport/rudp.go
On 32bit systems `Intn` function gets an overflow. Changed it to explicit int size instead
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1439)
=> Fixed int overflow on 32 bit systems

go/examples/pingpong/pingpong.go
Setting an interval is independent of the number of messages getting sent.
Always use the interval set when non zero.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1430)
=> TRIVIAL: Enable interval flag when count is set

go/lib/infra/transport/packet_transport.go, go/lib/snet/conn.go, go/lib/sock/reliable/appaddr.go, go/lib/sock/reliable/reliable.go, go/lib/sock/reliable/reliable_test.go
Also, the Go implementation of ReliableSocket now implements `net.PacketConn`, making it usable as a infra transport.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1423)
=> Change infra Transport to work with PacketConn

go/lib/addr/isdas.go, go/lib/addr/isdas_test.go, python/lib/packet/scion_addr.py, python/test/lib/packet/scion_addr_test.py
This makes it much easier for humans to parse, which is especially
relevant with 48-bit AS numbers.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1457)
=> Support _-separated AS identifier strings.

go/cert_srv/conf/customers.go, go/lib/addr/isdas.go, go/lib/addr/isdas_test.go, go/lib/pathdb/sqlite/sqlite_test.go, go/lib/pathmgr/pred.go, go/lib/trust/store.go, go/tools/scion-pki/internal/pkicmn/pkicmn.go
- Update string formatting of AS numbers everywhere (mostly %d->%s, but
also %v->%d for pathdb/sqlite).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1462)
=> Separate out AS parsing for use by apps.

go/lib/infra/modules/trust/trustdb/db.go, go/lib/infra/modules/trust/trustdb/db_test.go
Avoid throwing an error for missing max cert/TRC version.
Add unit tests to cover requests for missing max cert/chain/TRC.
Change signature of GetTRC* to take addr.ISD instead of uint16.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1465)
=> Fix GetMaxVersion in trustdb

python/lib/util.py, python/test/lib/util_test.py
This is not supported by python: https://bugs.python.org/issue24283
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1467)
=> Don't log inside the signal handler

.circleci/config.yml, go/examples/pingpong/README.md, go/examples/pingpong/pingpong.go, go/lib/snet/squic/squic.go, go/vendor/vendor.json
Now that https://github.com/lucas-clemente/quic-go/pull/1272 is merged,
we can use quic-go again.
Also:
- Update the instructions, and tweak formatting of RTT values.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1470)
=> Re-enable quic/scion after licensing issue resolved.

go/tools/scion-pki/internal/certs/gen.go
Bugfix OP 149: `scion-pki certs gen <isd-as>` now checks if a cert already exists before creating it. Overwrite works with -f flag.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1471)
=> Make cert gen less eager

go/border/gen.go, go/border/router.go, python/beacon_server/base.py
Keep-alive messages are now sent from the BS to the neighboring BR, instead of from BR to BR. BR further propagate these to their local BS. This fixes #1473.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1476)
=> Keep-alives from BS

go/lib/spath/hop.go
Hop field serialization would break whenever egress IFID values larger than 255 were used.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1508)
=> Fix hop field serialization for large IFIDs

go/cert_srv/conf/conf.go, go/cert_srv/io.go, go/cert_srv/main.go, go/cert_srv/signed_util.go, go/lib/crypto/cert/cert.go, go/lib/crypto/cert/chain.go, go/lib/crypto/trc/trc.go, go/lib/ctrl/seg/seg.go, go/lib/util/time.go, go/proto/sign.go
Enables the go certificate server to create and verify signed payloads.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1431)
=> Add sign/verify capability to CSGO

go/tools/scion-pki/README.md, go/tools/scion-pki/internal/cmd/cmd.go
Currently the support is limited to zsh and bash
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1514)
=> scion-pki: Add support for auto-completing scion-pki commands

go/lib/ctrl/signed_util.go
SignSrcDef parsing now accepts the canonical format of ISD-AS.
This change is also compatible with #1512.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1519)
=> Fix parsing of SignSrcDef

go/lib/spath/path.go, python/beacon_server/base.py, python/lib/defines.py
This PR adds following changes:
- Fix `spath.ExpTimeUnit`
- floor `EXP_TIME_UNIT` to ensure go and python code evaluate to same value
- Make beacon server one hop path expiration time independent of certificate expiration time
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1518)
=> Fix HOF expiration time unit

integration/integration_test.sh
The element names are _-separated, not :-separated, for simplicity with
filenames etc.
Also:
- Increase the startup sleep under circleci, to reduce flakiness.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1535)
=> Fix element names for revocation test.

python/lib/packet/ctrl_pld.py, python/lib/packet/signed_util.py
Add `DefaultSignSrc` for signed control payloads to python code.
Add basic `Signer` to create signed control payloads.
Add basic `Verifier` to verify signed control payloads.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1522)
=> Add sign src to python code

.gitignore
As we'd like to use http://mypy-lang.org/ for some python code, every
python module that's imported needs to have a `__init__.py` file
(otherwise mypy fails with a very cryptic error). This change also adds
an ignore for the mypy cache dir.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1538)
=> Add missing __init__.py files, ignore mypy cache dir.

go/cert_srv/trc.go
Prevents handling of TRC requests to mistakenly access the cache of certificate chain requests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1540)
=> Fix misnamed caches

go/sig/base/as.go, go/sig/base/events.go
Types of events that are being added:
* `NetworkChanged`: `NetworkChanged` is called when a remote network was added or removed from the configuration.
* `SigChanged`: `SigChanged` is called when a remote SIG is was added or removed from the configuration. Note, this event does not get generated yet.
* `RemoteHealthChanged`: `RemoteHealthChanged` is called when the reachability status of a remote AS changed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1551)
=> SIG: Add base events that modules can subscribe to

go/lib/ctrl/signed.go
Return error if buffer is too small to avoid panic.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1552)
=> Avoid panic during SignedPld parsing

go/sig/base/as.go, go/sig/base/events.go
The NetworkChanged event now includes if the remote AS to which the network belongs is reachable or not. Furthermore, `version` keeps track of remote network changes through configuration changes or discoveries.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1557)
=> SIG: Add healthy flag to NetworkChanged event and version to ASEntry

tools/wireshark/scion.lua
As mentioned in [1], a bytes field is always represented in HEX. Later
versions of wireshark treat base.HEX as invalid, so removing it makes it
work correctly everywhere.
[1] https://osqa-ask.wireshark.org/questions/63411/multiple-lua-error-during-loading-issues-reported-after-install-of-win64-version-240/63414
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1559)
=> Remove unnecessary base.HEX from scion.packet in wireshark plugin.

python/sciond/req.py, python/sciond/sciond.py
Grab lock when handling RequestState in handle_path_reply.
Log error on duplicate path reply.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1554)
=> sciond: Avoid failing on duplicate path reply

go/lib/sciond/mock.go, go/lib/sciond/types.go, python/lib/sciond_api/path_meta.py
This change removes the repeated ASes in the output, and instead prints
an AS with the ingress IfID to the left and the egess IfID to the right.
This makes it easier to follow, and more compact.
Go example (from showpaths):
Before:
```
Hops: 1-ff00:0:131#70>1-ff00:0:130#52>1-ff00:0:130#16>1-ff00:0:110#83>1-ff00:0:110#27>1-ff00:0:111#84 Mtu: 1472
```
After:
```
Hops: [1-ff00:0:131 70>52 1-ff00:0:130 16>83 1-ff00:0:110 27>84 1-ff00:0:111] Mtu: 1472
```
Python example (from end2end):
Before:
```
FwdPathMeta: Interfaces: 1-ff00:0:131:70, 1-ff00:0:130:52, 1-ff00:0:130:16, 1-ff00:0:110:83, 1-ff00:0:110:27, 1-ff00:0:111:84 MTU: 1472
```
After:
```
FwdPathMeta: Interfaces: [1-ff00:0:131 70>52 1-ff00:0:130 16>83 1-ff00:0:110 27>84 1-ff00:0:111] MTU: 1472
```
---
This change is [<img …
=> Improve representation of fwd path hops.

go/examples/pingpong/pingpong.go, go/lib/pathmgr/infra_test.go, go/lib/sciond/infra_test.go, go/lib/sciond/sciond.go, go/lib/snet/integration_test.go, go/sig/sigcmn/common.go, go/tools/scmp/main.go, go/tools/showpaths/paths.go, python/lib/app/sciond.py
In order to obtain sciond socket for a given IA a new API is exposed
`GetDefaultSCIONDSocket` which takes an IA and returns the corresponding
socket string.
Fixes #1543
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1571)
=> standardize sciond socket selection process

go/lib/infra/modules/trust/trust_test.go, go/tools/scion-pki/internal/certs/gen.go, go/tools/scion-pki/internal/certs/verify.go, go/tools/scion-pki/internal/cmd/cmd.go, go/tools/scion-pki/internal/keys/gen.go, go/tools/scion-pki/internal/pkicmn/pkicmn.go, go/tools/scion-pki/internal/tmpl/as.go, go/tools/scion-pki/internal/tmpl/isd.go, go/tools/scion-pki/internal/trc/gen.go
Users of `scion-pki` can now specify an output directory for keys, certs, and TRCs using the `-o/--out` cmdline parameter (so far this was the same as the root directory for the configuration files). If not specified, the output directory will be the same as the root directory (`-d/--root`).
Fixes #1575.
Also:
Change `trust_test.go` to use the new capabilities.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1589)
=> scion-pki: Make the output directory separately configurable

go/border/rpkt/create.go, go/border/rpkt/extn_onehoppath.go, go/border/rpkt/hooks.go, go/border/rpkt/parse.go, go/border/rpkt/path.go, go/border/rpkt/route.go, go/border/rpkt/rpkt.go, go/border/rpkt/rpkt_hook_test.go, go/lib/ctrl/seg/seg.go, go/lib/pathdb/sqlite/sqlite.go, go/lib/spath/hop.go, go/lib/spath/info.go, go/lib/spath/path.go, go/lib/spath/path_test.go, python/lib/flagtypes.py, python/lib/packet/opaque_field.py, python/lib/packet/path.py, python/lib/packet/pcb.py, python/lib/path_combinator.py, python/lib/sibra/ext/steady.py, python/lib/sibra/pcb_ext.py, python/sibra_server/util.py, python/test/lib/packet/opaque_field_test.py, python/test/lib/packet/path_test.py, python/test/lib/packet/pcb_test.py, python/test/lib/path_combinator_test.py, python/test/lib/sibra/ext/steady_test.py, tools/wireshark/scion.lua
Make up/down ingress/egress less ambiguous for paths, fixes #1479
- `up` becomes `!consDir` (as the current "up" is the opposite of the construction direction)
- `ingress` becomes `consIngress`
- `egress` becomes `consEgress`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1527)
=> Make up/down ingress/egress less ambiguous for paths

go/lib/infra/disp/disp.go
Whenever the receiver of an infra dispatcher message decides to close the connection (this can happen when receiving a malformed message on a connection that can be closed, e.g., reliable socket), Go will produce an EOF when the sender reads back. The sender logs the message, but continues to try to read, getting stuck in an infinite error print loop.
This PR changes the behavior and makes the sender cleanly shutdown on EOF.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1582)
=> Infra dispatcher now cleanly stops on EOF

go/lib/log/log.go
`log.SetupLogFile` now correctly initializes file logging from function arguments instead of flags.
Also changes the semantics behind a 0 value flush timer from "never flush" to a more intuitive "always flush immediately" (unbuffered logging). The old "never flush" behavior can now be selected by passing in a negative flush timer.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1579)
=> Fix file logging; support for unbuffered logging

go/lib/pathmgr/pathmgr.go, go/lib/snet/conn.go, go/lib/snet/integration_test.go, go/lib/snet/snet.go
SCIOND-less operation is needed for applications that need to talk over the network without sciond access (e.g., the sciond server itself).
Also streamlines the API a bit and deletes some unused fields from `snet` types.
SCIOND-less operation can be selected by passing an empty sciond socket path, or by passing in a nil path resolver.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1580)
=> Enable SCIOND-less operation for snet

go/lib/overlay/conn/conn.go
The OverlayPort in the metadata information when reding packets from
an internal interface was always set to the endhost overlay port.
When a BR uses this information to generate a reply it would use the
wrong overlay port.
Fix this problem by setting the source overlay port to the L4 port of
the received packet.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1592)
=> Fix replies from BR to BR in the same AS

env/common.sh, env/go/deps, env/zlog/deps
- Make curl quiet when stdout is not a console.
- Only display the output of checkinstall if it fails.
- Use make --silent for building zlog.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1599)
=> Reduce env/* output.

.circleci/config.yml, Makefile, c/dispatcher/Makefile, c/dispatcher/dispatcher.c, docker.sh, docker/Dockerfile, docker/Dockerfile.app, docker/Dockerfile.base, env/common.sh, env/go/deps, env/zlog/deps, tools/ci/build_prep
docker:
- Use eatmydata more liberally to speed things up.
- Make a tarball of the pip3/pip2 installation in base for later use.
- Clean up some formatting.
- Add a new Dockerfile (docker/Dockerfile.app) that is based on the
normal docker image, but compiles all the code.
dispatcher:
- Statically link dispatcher against libzlog to ease dockerizing.
- Include the strerror in the output of zlog_init fails.
Also:
- Run ctags by default if it's installed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1605)
=> Some prep work for per-app docker containers

go/lib/ctrl/seg/seg.go, go/proto/sign.go, python/lib/packet/pcb.py, python/lib/packet/proto_sign.py, python/scion_elem/scion_elem.py
Make proto signature equal in go and python
- Add timestamp to sign in python
- Add non-signature fields into signature in go
- Make signature fields order consistent
- Fix ASEntry sign method in python
Fixes #1524. Fixes #1617.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1618)
=> Make protos consistent between go and python

go/cert_srv/cert.go, go/cert_srv/conf/conf.go, go/cert_srv/io.go, go/cert_srv/main.go, go/cert_srv/reiss_handler.go, go/cert_srv/reiss_tasks.go, go/cert_srv/setup.go, go/cert_srv/signed_util.go, go/lib/as_conf/conf.go, go/lib/as_conf/conf_test.go, go/lib/as_conf/testdata/basic.yml, go/lib/trust/store.go, python/beacon_server/base.py
This PR adds certificate reissuance to the infrastructure. (#1183)
Core ASes periodically renew leaf AS and issuer AS certificates.
Non-Core ASes periodically request new certificate chains from their
responsible core AS.
Both these tasks are done on the Certificate Server
Request must be verifiable with the newest verifying key in the
customer mapping of the core AS.
The non-core Certificate Servers start to automatically request
reissued certificate chains one path segment validity time before
expiration to provide optimal coverage.
The reissued certificate chains are disseminated by the Beacon server.
They start polling the certificate server for new certificate chains
when the available certificate no longer covers the desired segment
validity period.
Missing:
Useful integration test …
=> CSGO: Add Certificate Reissuance

go/cert_srv/cert.go, go/cert_srv/reiss_handler.go, go/cert_srv/reiss_tasks.go, go/lib/crypto/cert/cert.go, go/lib/crypto/cert/cert_test.go, go/lib/crypto/cert/chain_test.go, go/lib/crypto/trc/trc.go, go/lib/crypto/trc/trc_test.go, go/lib/ctrl/path_mgmt/rev_info.go, go/lib/sciond/types.go, go/lib/util/time.go, go/proto/sign.go, go/tools/scion-pki/internal/certs/gen.go, go/tools/scion-pki/internal/conf/as.go, go/tools/scion-pki/internal/conf/isd.go, go/tools/scion-pki/internal/trc/gen.go, proto/drkey_mgmt.capnp, proto/rev_info.capnp, proto/sciond.capnp, proto/sign.capnp, python/lib/packet/proto_sign.py
Fixes #1548.
Change `uin64` timestamp units to `uint32` in:
- DRKeyReq/Rep
- RevInfo
- SegTypeHopReplyEntry
- Sign
- TRC
- Certificate
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1634)
=> Consistent timestamps

go/lib/infra/transport/packet_transport.go
If err != nil then return the actual error, that helps a lot while debugging
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1615)
=> Remove shadowing of original error with connection

go/border/rpkt/route.go
Save/restore the refCnt when resetting the metadata of a packet to be
repreprocessed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1662)
=> br: fix panic when reprocessing a packet

python/cert_server/main.py, python/lib/trust_store.py
The Go implementation treats a version of `0` as "give me the newest version". The Python code base was never updated to those semantics. Historically, version `0` was the first version of a cert/chain/TRC. This PR fixes this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1691)
=> Sync newest CertChain/TRC handling in Python with Go

go/border/router.go, go/lib/common/rand.go, go/lib/crypto/rand.go, go/lib/env/env.go, go/lib/env/testdata/ps.toml, go/lib/sciond/sciond.go, go/lib/snet/integration_test.go, go/lib/snet/rpt/rpt.go, go/lib/sock/reliable/bench_test.go, go/tools/scmp/cmn/common.go
This ensures that all uses of math/rand have a reasonably secure seed.
This fixes, e.g.:
- go/border/rpkt/route.go that didn't use a seeded math/rand
- Use of non-goroutine-safe rand.Source's in snet/rpt and scmp/cmn.
- potential for multiple libraries to call rand.Seed().
Also:
- Add 2 convenience functions to get crypto/rand 64-bit integers.
- Drop the "Seed" field from the env.General struct, as it no longer
makes sense.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1715)
=> Seed math/rand's PRNG on start

go/lib/log/logparse/logentry.go, go/lib/log/logparse/logentry_test.go, go/tools/logdog/main.go
So that it can be used for other purposes as well.
For example we will need it for integration testing (#1693).
The functionality is now extended to also parse the log level.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1703)
=> Move logdog Logentry parsing to lib

go/examples/pingpong/pingpong.go, go/examples/pingpong/pp_integration/main.go, go/lib/integration/README.md, go/lib/integration/binary.go, go/lib/integration/integration.go, go/lib/log/log.go, go/lib/log/logparse/logentry.go, go/lib/log/logparse/logentry_test.go, go/lib/util/aslist.go, integration/integration_test.sh
Contributes to #1693
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1694)
=> Initial go integration test framework

topology/PathPolicy.yml
- Accept any PCB that's <= 4 hours old (increased from 60s)
- Allow segments with 30 hops (increased from 10), as the core in the
beginning may not be very tightly meshed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1741)
=> Set PathPolicy defaults to saner values.

go/lib/snet/conn.go
No longer blame all possible errors in snet.Conn.write on the
dispatcher.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1748)
=> Fix misleading snet error

go/cert_srv/reiss_handler.go, go/cert_srv/reiss_tasks.go, go/lib/ctrl/path_mgmt/rev_info.go, go/lib/sciond/mock.go, go/lib/sciond/types.go, go/lib/scrypto/cert/cert.go, go/lib/scrypto/cert/cert_test.go, go/lib/scrypto/cert/chain.go, go/lib/scrypto/cert/chain_test.go, go/lib/scrypto/trc/trc.go, go/lib/scrypto/trc/trc_test.go, go/lib/util/time.go, go/proto/sign.go, go/sciond/internal/fetcher/fetcher.go, go/tools/scion-pki/internal/certs/gen.go, go/tools/scion-pki/internal/conf/isd.go, go/tools/scion-pki/internal/trc/gen.go
- Make conversion from time.Time() to uint32 and vice versa more consistent
- Remove unused `SecsToTime`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1759)
=> Improve time conversion consistency

docker/Dockerfile, integration/integration_test.sh, scion.sh, tools/ci/integration, tools/ci/local, tools/ci/setup_container, tools/quiet
- Don't run ./scion.sh topology in docker/Dockerfile - without knowing
the backend to use it doesn't make much sense. Instead it's run by
tools/ci/local
- integration_test stops if ./scion.sh run fails.
- Always run supervisor.sh shutdown in ./scion.sh topology - it's
idempotent, and avoids failure if gen/ is missing.
- Add tools/quiet to run commands and only show the output if it exits
non-zero.
- Use tools/quiet to shut up supervisor & docker-compose start/stop
messages.
- Don't print errors when /run/shm/{dispatcher,sciond} don't exist on
scion.sh stop.
- Removed unnecessary `set -x`'s.
- Only remove local ci container on success.
--- …
=> Various build/ci fixes

c/dispatcher/Makefile, c/dispatcher/dispatcher.c, c/lib/filter/Makefile, c/lib/hsr/Makefile, c/lib/scion/Makefile
This change adds the -D option to the Makefile such that the C code
would be built with '-gdwarf-2 -O0' cflags.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1774)
=> Support to build C code with debugging cflags

.circleci/config.yml, env/pip3/requirements.txt, go/cert_srv/conf/conf.go, go/cert_srv/setup.go, go/lib/addr/isdas.go, go/lib/ctrl/signed_util.go, go/lib/infra/common.go, go/lib/infra/example/main.go, go/lib/infra/messenger/messenger.go, go/lib/infra/messenger/messenger_test.go, go/lib/infra/modules/combinator/graph.go, go/lib/infra/modules/combinator/testdata/14_compute_path.txt, go/lib/infra/modules/segverifier/segverifier.go, go/lib/infra/modules/trust/handlers.go, go/lib/infra/modules/trust/helpers.go, go/lib/infra/modules/trust/trust.go, go/lib/infra/modules/trust/trust_test.go, go/lib/topology/topology.go, go/lib/util/debugid.go, go/lib/util/trace.go, go/sciond/internal/fetcher/fetcher.go, go/sciond/internal/servers/api.go, go/sciond/internal/servers/handlers.go, go/sciond/internal/servers/server.go, go/sciond/main.go, go/sciond/server_test.go, python/topology/generator.py
Fixes #1709 and #1494.
Also:
- Allows switching between the Go and Python versions of the CS and SCIOND
- Strips trust trail support from a lot of places
- Provides cleaner logging for handlers and network messaging
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1731)
=> Implement verification in SCIOND

c/lib/filter/Makefile, c/lib/hsr/Makefile, c/lib/scion/Makefile, go/Makefile, scion.sh
This means that if you run `make -s`, you'll know what you're entering
your password for. If your sudo credentials are already current, then
you won't see the prompt.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1787)
=> Provide context to sudo password prompts.

go/lib/scrypto/asym.go, go/lib/scrypto/asym_test.go, go/lib/scrypto/rand.go, go/lib/scrypto/rand_test.go, go/lib/xtest/helpers.go, go/tools/scion-pki/internal/keys/gen.go
This PR implements functionality for asymmetric encryption and decryption based on the currently used certificates. This will be required for the first order DRKey exchange.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1594)
=> Wrapper for asym.crypto around nacl/box

go/lib/topology/testdata/udpbr.json, go/lib/topology/topology.go, go/lib/topology/topology_test.go
It is (currently) illegal to specify `OverlayPort` in a BR entry, as the
BR doesn't run on top of the dispatcher. Additionally, calling
`OverlayAddr` on the internal address of a BR should set the overlay
port appropriately (assuming a UDP-based overlay).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1799)
=> Fix overlay port handling for BR in topology.

go/lib/snet/conn.go, go/lib/snet/integration_test.go, go/lib/snet/snet.go, go/lib/snet/squic/squic.go, go/lib/sock/reliable/reliable.go
Support is only added to `Network` objects, because most callers don't care about setting a timeout and will be using the default `Dial`/`Listen` calls.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1804)
=> Add timeout support for custom network snet

c/lib/filter/Makefile, c/lib/hsr/Makefile, c/lib/scion/Makefile, go/Makefile
scionproto/scion#1787 used `sudo -v` as a way to ensure that sudo
credentials are cached before running the desired commands with sudo.
This, however, breaks in an environment where the user in question can
run any command without a password, as `sudo -v` will always prompt for
a password if no sudo credentials are present.
To work around this, this PR changes from using `sudo -vp <prompt>` to
`sudo -p <prompt> true`, which will actually run a (harmless) command.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1807)
=> Don't use sudo -v

go/lib/snet/snet.go
Add more checks to avoid the panix and also provide a default value if
the address has no L4 information.
In such case, the default value would be UDP port 0, meaning that the
application wants a random port.
Fixes #1803
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1806)
=> snet: fix panic in Listen

go/lib/hpkt/write.go, go/lib/spath/path.go
It could be that the s.Path is not nil but empty, then we should also not write CurreInfoF and CurrHopF
These fields will have the same value (0, i.e. offset / common.LineLen) which will lead to a parse error.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1810)
=> Fix writing of offsets in scion packets (go)

python/sciond/req.py
On a CI env we have seen that processing 7 segments can take more than 200ms.
Since the last PCB was the missing piece for the path,
sciond wrongly answered with 0 path, even though
there would have been one if it waited longer.
Increasing the timeout is a temporary fix for this.
We expect the go-sciond to be better in this regard.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1808)
=> sciond: Increase timeout for PathReply processing

go/lib/infra/common.go, go/lib/infra/messenger/messenger.go, go/lib/infra/messenger/mock.go, go/path_srv/internal/handlers/segreq.go, go/path_srv/main.go, go/sciond/internal/fetcher/fetcher.go
Drop Path prefix for Seg* types. Also shorten some postfixes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1826)
=> Rename infra.MessageTypes to shorter names

go/path_srv/internal/periodic/periodic.go, go/path_srv/internal/periodic/periodic_test.go
We will need this for cleaning the pathDB and syncing down segments periodically.
Contributes to #1817, #1818
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1823)
=> Add a periodic task runner

go/lib/xtest/graph/graph.go, go/path_srv/internal/handlers/common.go, go/path_srv/internal/handlers/segreq.go, go/path_srv/internal/handlers/segreqcore.go
* Handle no down segs in core PS handler (fetching coresegs without down segs doesn't make sense).
* Make sure to never return segments that are expired.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1851)
=> PS: Small fixes

.circleci/config.yml, go/Makefile, go/border/rpkt/rpkt_test.go, go/cert_srv/reiss_tasks.go, go/lib/as_conf/master_keys.go, go/lib/log/log.go, go/lib/pathmgr/resolver.go, go/lib/scrypto/cert/chain_test.go, go/lib/xtest/helpers.go, go/sig/ingress/dispatcher.go, go/tools/scmp/echo/echo.go, go/tools/scmp/main.go, go/tools/scmp/recordpath/recordpath.go, go/tools/scmp/traceroute/traceroute.go, go/vendor/vendor.json
impi allows us to lint for import grouping according to our style guide
(stdlib, then thirdparty, then local imports).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1861)
=> Switch from goimports to impi.

.circleci/config.yml, env/pip3/requirements.txt
packaging 16.8 had a latent race-condition that is fixed in later
versions: https://github.com/pypa/packaging/issues/104
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1870)
=> Update to packaging 17.1

go/lib/pathdb/pathdb.go, go/lib/pathdb/sqlite/schema.go, go/lib/pathdb/sqlite/sqlite.go, go/lib/pathdb/sqlite/sqlite_test.go, go/path_srv/internal/handlers/segreq.go, go/path_srv/internal/psconfig/psconfig.go
NextQuery is more flexible.
We can implement different strategies, for example:
* backoff if we repeatedly get no segs
* Use smaller interval if we receive less than k segs
etc.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1869)
=> pathdb: Store next query instead of LastQuery

go/Makefile, go/border/rctrl/ctrl.go, go/lib/env/env.go, go/lib/env/env_test.go, go/lib/env/testdata/ps.toml, go/lib/infra/infraenv/infraenv.go, go/lib/pktdisp/disp.go, go/lib/snet/conn.go, go/lib/snet/integration_test.go, go/lib/snet/interface.go, go/lib/snet/snet.go, go/lib/snet/snetproxy/conn.go, go/lib/snet/snetproxy/conn_io_test.go, go/lib/snet/snetproxy/io.go, go/lib/snet/snetproxy/main_test.go, go/lib/snet/snetproxy/network.go, go/lib/snet/snetproxy/network_test.go, go/lib/snet/snetproxy/reconnecter.go, go/lib/snet/snetproxy/reconnecter_test.go, go/lib/snet/squic/squic.go, go/path_srv/main.go, go/sciond/main.go, go/sig/disp/disp.go, go/sig/egress/interface.go, go/sig/egress/session/session.go, go/sig/ingress/dispatcher.go, go/sig/sigcmn/common.go
Also:
- move `snetproxy` networking-related interfaces into `snet`
- refactor out of SD and PS common networking functionality and move it into a new package `infraenv`
Fixes #1474.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1854)
=> Enable dispatcher reconnection logic in Go infra

go/Makefile, go/lib/infra/modules/itopo/itopo.go, go/lib/infra/modules/trust/config.go, go/lib/infra/modules/trust/trust.go, go/lib/infra/modules/trust/trust_test.go, go/lib/sciond/types.go, go/lib/topology/addr.go, go/lib/topology/topology.go, go/lib/topology/topotestutil/topotestutil.go, go/path_srv/internal/addrutil/addrutil.go, go/path_srv/internal/handlers/common.go, go/path_srv/internal/handlers/segreg.go, go/path_srv/internal/handlers/segreqcore.go, go/path_srv/internal/handlers/segreqnoncore.go, go/path_srv/internal/handlers/segreqnoncore_test.go, go/path_srv/internal/handlers/segsync.go, go/path_srv/internal/segsyncer/segsyncer.go, go/path_srv/main.go, go/sciond/internal/fetcher/fetcher.go, go/sciond/internal/servers/handlers.go, go/sciond/main.go, go/sciond/server_test.go
This is a stepping stone towards implementing topology reloading in Go (see https://github.com/scionproto/scion/issues/1836).
This PR aggregates bits and pieces of topology-related code that were scattered throughout SD and PS.
It also defines a topology interface that can be used together with `gomock` to cleanly integrate the topology in tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1850)
=> Extract common topology-related ops from Go SD and PS

python/cert_server/main.py
If the CS receives a request for the newest version of a TRC or CC,
which it hasn't stored locally it should reply after it got the TRC/CC from the remote CS.
Do this by replying both the request for the specific version,
as well as to requests for the newest version if it the received material is the newest version.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1883)
=> CS: Reply to newest version requests

go/lib/addr/host.go, go/lib/sciond/types.go, go/lib/snet/addr.go, go/lib/snet/addr_test.go, go/lib/topology/addr.go, go/lib/topology/addr_test.go, go/lib/topology/braddr.go, go/lib/topology/raw.go, go/lib/topology/topology.go, go/lib/topology/topology_test.go
- Add a new constructor, addr.HostFromIPStr, which takes a string, and
return a addr.HostIPv4 or addr.HostIPv6 as appropriate.
- Convert unit tests to use/expect 4-byte IPv4 addresses.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1885)
=> Try to ensure that addr.HostIPv4 is 4 bytes.

python/integration/base_cli_srv.py, python/integration/end2end_test.py, python/lib/app/sciond.py
If we receive a revocation it should be enough to wait until sciond has processed it.
In case the PS hasn't processed it yet it could be that we get no paths back and we have to try longer.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1886)
=> End2End: retry earlier if we receive a revocation

go/lib/ctrl/path_mgmt/rev_info.go, go/lib/infra/modules/segsaver/segsaver.go, go/lib/infra/modules/segverifier/segverifier.go, go/lib/revcache/memrevcache/memrevcache.go, go/lib/revcache/revcache.go, go/path_srv/internal/handlers/common.go, go/path_srv/internal/handlers/ifstateinfo.go, go/path_srv/internal/handlers/segreq.go, go/path_srv/internal/handlers/segrevoc.go, go/sciond/internal/fetcher/fetcher.go, go/sciond/internal/servers/handlers.go
* Make sure to call revocation callbacks first. Often they will be inserted in a DB, that should happen before the segments.
* Only verify revocations that are not yet in the cache (SD,PS) contributes #1884
Also in the PS makes sure to sanitize SegReply.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1887)
=> Segverifier, PS, SD fixes/improvements

go/lib/pathdb/sqlite/sqlite.go
If we store only second resolution in the pathdb this can lead to issues.
For example in the down segsync:
1. Down seg inserted at T (1, 100)
2. Sync down segs at T (1, 200)
3. Last sync = T (1)
4. Down seg inserted at T (1, 300)
5. Down seg sync where last update > T (1)
In 5. we miss the segment at step 4 because we only have second resolution.
Changing to store nanoseconds fixes this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1888)
=> PS: Fix race condition in segsyncer, save ns in sqlite

docker.sh, docker/perapp/Makefile
This PR adds build .stamp files in docker.sh, so docker/perapp/Makefile
can depend on them. This removes the need for the order-only scion_hash
target hack.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1913)
=> Allow per-app docker images to be built in parallel.

go/lib/snet/snet.go, go/lib/sock/reliable/reliable.go
The simplified errors are more similar to network errors returned by the standard library, and easier to act on in calling code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1906)
=> Simplify some network errors

go/sig/egress/session/sessmon.go, go/sig/egress/worker/worker.go
Reset the path for the worker immediately if the current path is no longer part of the path set.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1923)
=> SIG: Avoid using path removed from path pool

go/lib/pathdb/sqlite/schema.go
We don't need it, and it isn't recommended to use it if it's not required.
See https://www.sqlite.org/autoinc.html for a more detailed explanation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1930)
=> Drop AUTOINCREMENT from pathdb schema

tools/wireshark/scion.lua
The summary-text argument to the `ProtoExpert`-constructor is now mandatory. Previously, this would default to "Expert Info" (see wireshark/wireshark@862a0b6).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1925)
=> Fix dissector for wireshark>=2.5, add missing summary

python/beacon_server/base.py
Include the offset into the computation to avoid hop fields that expire after the certificate chain.
Fixes #1935 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1934)
=> BS: Fix HopField expiration time computation

go/lib/infra/modules/combinator/combinator.go, go/lib/infra/modules/combinator/expiry_test.go, go/lib/infra/modules/combinator/graph.go, go/lib/spath/hop.go, go/lib/spath/path.go, go/sciond/internal/fetcher/fetcher.go
Also:
- added unit tests for expiry calculation;
- fixed a bug in spath (max value for hop ttl field caused computed ttl to be 0);
- changed ttl computation to reduce rounding errors, and have max ttl be exactly equal to a day;
- cleaned up path combinator a bit.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1944)
=> SCIOND no longer returns expired paths

go/lib/env/duration.go, go/lib/util/duration_wrap.go, go/path_srv/internal/handlers/segreq.go, go/path_srv/internal/psconfig/psconfig.go, go/sciond/internal/fetcher/fetcher.go, go/sciond/internal/sdconfig/sdconfig.go
fixes #1961
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1963)
=> lib: Create duration wrapper

python/topology/generator.py
Otherwise they cannot connect to sciond, since they'll try default.sock.
Running only end2end test with Python infra this problem didn't appear.
When running cert_req_test the problem appeared with Python infra.
When running Go-SD and Go-PS the problem also occured with the end2end test.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1975)
=> Add scion_path arg for python docker services

go/lib/env/flags.go, go/lib/env/sample.go, go/path_srv/internal/psconfig/sample.go, go/path_srv/internal/psconfig/sample_test.go, go/path_srv/main.go, go/sciond/internal/sdconfig/sample.go, go/sciond/internal/sdconfig/sample_test.go, go/sciond/main.go
fixes #1903
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1977)
=> lib: Usage sample for lib/env programs

go/lib/spkt/cmnhdr.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1987)
=> spkt: check for minimum common header length

go/lib/spkt/cmnhdr.go
The following fields are not Bytes:
- header length
- current Info Field offset
- current Hop Field offset
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1985)
=> spkt: correct some common header fields units

go/border/rpkt/path.go
Check for possible errors when incrementing the path before updating the
packet metadata, which can result in an invalid state.
The issue showed up when the border router processes a BadSegment
packet. Because the metadata is updated, when we create the scmp reply
and reverse the packet, we fail to increment the reversed path, not
being able to send the error back.
With this change, the packet metadata is only updated once we have
verified that there are no errors when incrementing the path.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1988)
=> border: check errors before updating metadata

go/border/rpkt/path.go
There might be situations where ifCurr has not been set or cannot be
calculated because, ie. malformed headers.
Currently the border router panics in those situations when trying to
create SCMP path offsets information.
Safe check that ifCurr is set before use.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/1986)
=> border: check ifCurr before dereferencing it

go/lib/revcache/revcache.go
Certain backends might want to store the values as key instead of the string.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2012)
=> Make properties of revcache.Key public

go/lib/env/logging.go, go/path_srv/main.go, go/sciond/main.go
Synchronize init order between services.
Log service startup message 
fixes #2009
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2014)
=> lib: Consistent setup

go/lib/snet/snetproxy/reconnecter.go, go/path_srv/main.go, python/topology/docker.py, python/topology/generator.py
Fixes #2027 
- Use go SD and PS per default
- Drop `restart: always` from compose file
- Add reconnector config
- Add logging when reconnecting
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2031)
=> Change generator defaults to go infra

go/lib/infra/modules/cleaner/cleaner.go, go/lib/sciond/types.go, go/sciond/internal/fetcher/fetcher.go, go/sciond/internal/servers/handlers.go
Fixes #1966
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2026)
=> Clean up sd logging

.circleci/config.yml, docker.sh, go/vendor/vendor.json
Update to a more recent version of gopacket, which includes the
following commit:
Attempt to reduce memory usage caused by enums.go strings.
commit-id: 8c5cfc5ae25c08c58287b22231251f3f9c155ec6
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2035)
=> Update gopacket version

python/beacon_server/base.py, python/beacon_server/core.py, python/bin/beacon_server
Fixes #2037
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2046)
=> Keep segments containing ISD-level loops

go/lib/sciond/sciond.go, go/lib/sciond/types.go, go/sciond/internal/servers/handlers.go
No need to have values.
Also fixes logging where the receiver of String method is a pointer.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2045)
=> Make members of sciond.Pld pointers

acceptance/reconnecting_acceptance/test
Test reconnecting_acceptance was failing due to dispatcher reconnects being enabled twice (now that it is a generator default).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2061)
=> Delete double enabling of dispatcher reconnect

acceptance/reconnecting_acceptance/test
fixes #2067
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2068)
=> accept: Do not assume PYTHONPATH is set

go/lib/snet/conn.go
`snet` currently forwards SCMP revocations back to the app.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2074)
=> Remove misleading comment

go/cert_srv/setup.go, go/lib/infra/modules/trust/config.go, go/lib/infra/modules/trust/resolvers.go, go/lib/infra/modules/trust/trust.go, go/path_srv/main.go
Fixes #2056
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2079)
=> PS: Push cert chain to local CS

go/lib/revcache/revcachetest/revcachetest.go
Since we create the revocations with a method that initializes the revInfo
field in the test we should also make sure that the loaded one has this field initialized.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2033)
=> Init revs before testing resemblance

go/sciond/internal/fetcher/fetcher.go
Fixes #2025
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2084)
=> Enforce MaxPaths in SCIOND

python/lib/path_store.py, python/test/lib/path_store_test.py
If a PCB arrives with a timestamp from the future (which is accepted
due to the changes in #1990), it may result in a zero delay_time value.
The delay_time value is used in a division in the fidelity computation,
which will trigger an exception.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2076)
=> Fix delay_time computation to avoid division by zero

go/border/rctx/io.go, go/lib/overlay/conn/conn.go
When closing a socket, ie. interface change during config reload, with
no traffic, the reader will block forever waiting for packets.
Because we apparently want to flush any in-flight packet in the border
router, although we might already lose packets received by the nic but
not deliver to the application yet, we cannot close the socket at the
start. Thus, we need SetReadDeadline funcitonality to unblock the reader
and allow the proper socket cleanup steps.
Fixes #2078
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2088)
=> border: unblock reader when closing a socket

python/lib/socket.py, python/scion_elem/scion_elem.py
To test run infra with Python SCIOND. Then execute `echo "I expect this to crash the service" | socat STDIN UNIX-CONNECT:/run/shm/sciond/sd2-ff00_0_212.sock`
Fixes #2093
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2094)
=> Gracefully handle malformed dispatcher frames in SCIONElement

go/border/rpkt/l4.go, go/border/rpkt/rpkt.go, go/lib/scmp/pld.go
The border router findL4() method keeps track of the last parsed
header/eextension.
With this approach when generating SCMP quotes, it includes as much
relevant data as possible.
If the border router failed to parse the extensions, thus could not find
the L4 offset, it quotes everything after the last parsed extension as
the L4 quote.
If it found the L4 header but it is an unknown/unsupported protocol,
then it quotes everything from the L4 offset as the L4 quote.
With a best effort approach, if the buffer where the Payload is written
to does not have enough space, it will fail and it is up to the caller
to modify the SCMP quotes to fit in the buffer.
--- …
=> border: best effort approach for scmp error quotes

go/lib/infra/common.go, go/lib/infra/messenger/messenger.go, go/lib/infra/modules/trust/handlers.go, go/lib/log/context.go, go/lib/log/context_test.go, go/path_srv/internal/handlers/common.go, go/path_srv/internal/handlers/ifstateinfo.go, go/path_srv/internal/handlers/segreg.go, go/path_srv/internal/handlers/segreq.go, go/path_srv/internal/handlers/segreqcore.go, go/path_srv/internal/handlers/segreqnoncore.go, go/path_srv/internal/handlers/segreqnoncore_test.go, go/path_srv/internal/handlers/segrevoc.go, go/path_srv/internal/handlers/segsync.go, go/sciond/internal/servers/api.go, go/sciond/internal/servers/handlers.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2103)
=> Propagate loggers via contexts

python/topology/ca.py, python/topology/cert.py, python/topology/common.py, python/topology/config.py, python/topology/docker.py, python/topology/generator.py, python/topology/go.py, python/topology/prometheus.py, python/topology/supervisor.py, python/topology/topo.py, python/topology/utils.py
Make command line arguments more modular
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2092)
=> gen: Refactor command line arguments

docker/perapp/Makefile, docker/perapp/app/Dockerfile.cert, python/topology/config.py, python/topology/docker.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2016)
=> CS.go: Dockerize

.buildkite/deploy.yml, .buildkite/pipeline.sh, go/integration/end2end_integration/main.go, go/lib/infra/disp/disp.go, go/lib/snet/snet.go, go/tools/scmp/cmn/common.go
- Less `Info` logging from `snet`, less clutter in integration tests
- Fix deploy pipeline, stop CI container before deploy step
- Remove unused variable in `end2end` integration test
- Log scmp errors to Stderr, so the integration tests also log the error
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2111)
=> Fix some integration test issues

c/dispatcher/dispatcher.c, c/lib/scion/scmp.c, go/border/rpkt/rpkt.go, go/lib/scmp/info.go, go/lib/scmp/meta.go, go/tools/scmp/cmn/common.go, go/tools/scmp/echo/echo.go, go/tools/scmp/main.go, go/tools/scmp/recordpath/recordpath.go, go/tools/scmp/traceroute/traceroute.go
There are a few issues when processing SCMP errors caused by SCMP packes,
like SCMP echo, by the border router and the dispatcher:
The border router fails to include the SCMP Info field, containing the
ID which is required to deliver the packet to the application.
The dispatcher does not process SCMP errors of SCMP packets.
This change adds the required support to the border router and the
dispatcher as well as modifying the SCMP tool to be able to deal with
SCMP revocations. It also adds a refresh flag to the scmp tool, which
now talks to sciond instead of the path manager.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2052)
=> Process SCMP errors caused by SCMP packets

go/tools/showpaths/paths.go
Fixes #2039
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2108)
=> Path test in showpaths tool

go/integration/cert_req/main.go, go/integration/end2end/main.go, go/lib/infra/disp/disp.go, go/lib/infra/messenger/messenger.go, go/lib/pathmgr/infra_test.go, go/lib/pathmgr/pathmgr.go, go/lib/pathmgr/resolver.go, go/lib/pathpol/policy_test.go, go/lib/pktcls/action_test.go, go/lib/sciond/mock.go, go/lib/sciond/reconn.go, go/lib/sciond/sciond.go, go/lib/snet/snet.go, go/lib/spath/spathmeta/pred_test.go, go/sciond/server_test.go, go/tools/scmp/main.go, go/tools/showpaths/paths.go
The API establishes and tears down the connection to SD for each API call. It is more expensive than the shared connection we had, but it is resilient to SD restarts since there is no persistent connection.
Also in this PR:
- simplified the SCIOND API to no longer have non-context/context variants;
- cleaned up logging during infra dispatcher shutdown;
Known issues:
- an infra dispatcher is initialized over the unix transport to SD; it is not strictly needed as only one message exchange happens on the transport, but it provides context-friendly primitives for talking on the connection. We can optimize in the future and delete it.
This is a prerequisite of the concurrency-friendly path manager.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" …
=> SD client API can now tolerate SD restarts

tools/wireshark/scion.lua
ASes used to only ever contain ints, hence `%d` worked. However, the
newer shortened AS notation may have AS numbers like `9:5:6`, which `%d`
can't be used for. Switch to `%s` to fix this issue.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2132)
=> Fix printing of AS number in scion.lua

go/lib/snet/snetproxy/conn.go, go/lib/snet/snetproxy/errors.go, go/lib/snet/snetproxy/reconnecter.go, go/lib/sock/reliable/errors.go, go/sig/ingress/dispatcher.go, go/sig/main.go
This is a intermediate measure. Eventually, we want to have
proper reconnect functionality but until then it's better
to kill the process instead of keeping it alive and malfunctioning.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2131)
=> SIG dies immediately when if disconnects from dispatcher

go/Makefile, go/lib/overlay/addr.go, go/lib/snet/internal/pathsource/pathsource.go, go/lib/snet/internal/util/util.go, go/lib/snet/reader.go, go/lib/snet/writer.go, go/lib/snet/writer_test.go
This partially fixes #1702.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2145)
=> Refactor snet writer; move path resolution outside main lock

go/sig/ingress/dispatcher.go, go/sig/ingress/worker.go
Using the loop variable in a func literal that is called with go or defer is wrong.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2163)
=> sig: Fix wrong variable captures

go/border/error.go
When generating SCMP errors replies for bad packets, the border router
quotes different parts of the bad packet, this quotes also depend on how
much the border router is able to parse of it.
The issue shows with unsupported procotols, ie. TCP, where the border
router generates an SCMP error reply with Meta L4Type value 0, meaning
None/HopByHop, which is obviously wrong.
The problem arise because we try to retrieve the L4 Type from the parsed
L4 header, which we do not parsed as it is unsupported.
The solution is simple as rpkt already has the L4Type.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2170)
=> border: fix error replies for unsupported L4 protocols

acceptance/lib.sh, go/examples/pingpong/pp_integration/main.go, go/integration/cert_req_integration/main.go, go/integration/cli_srv_ext_pyintegration/main.go, go/integration/end2end_integration/main.go, go/integration/scmp_error_pyintegration/main.go, go/lib/integration/binary.go, go/lib/integration/docker.go, go/lib/integration/integration.go, go/tools/scmp/scmp_integration/main.go, integration/bin_wrapper.sh
In integration tests write logs of child processes in to separate files.
This way we can run clients in parallel and still see what happens.
Also this fixes #2105
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2161)
=> Testing: Write logs to separate files

go/lib/snet/internal/ctxmonitor/ctxmonitor.go, go/lib/snet/internal/ctxmonitor/ctxmonitor_test.go
Context monitor no longer immediately cancels new contexts created with
a deadline that is after the currently set deadline (if it hasn't
expired yet).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2176)
=> snet: Fix bug in context monitor

go/examples/pingpong/pingpong.go, go/lib/snet/squic/squic.go
This PR enables clients to pass a QuicConfig to Dial/Listen methods in the squic package.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2180)
=> Add a QuicConfig to squic Dial/Listen methods

.buildkite/all_images, .buildkite/steps/build_all.yml
Currently the push step might be run from a different agent than the build step. Also after pulling the images from the registry, they need to be tagged again.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2183)
=> Fix buildkite build/push steps order

go/sig/ingress/dispatcher.go, go/sig/main.go
`ingress.Init(tunIO)` was blocking therefore the SIG would never receive the termination signal.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2191)
=> Fix non-terminating SIG

go/lib/snet/reader.go
The SCMP header is sent back to the app, and it can decide whether to
log.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2206)
=> Remove SCMP logging message from snet

.buildkite/steps/setup.yml, .circleci/config.yml, go/Makefile, go/border/braccept/tpkt/overlay.go, go/border/io.go, go/border/rctx/rctx.go, go/border/rpkt/rpkt.go, go/lib/common/errors.go, go/lib/pathpol/policy.go, go/lib/sciond/reconn.go, go/lib/sciond/sciond.go, go/lib/scrypto/cert/cert_test.go, go/lib/scrypto/mac.go, go/lib/snet/writer.go, go/lib/sock/reliable/reliable.go, go/lib/spath/hop.go, go/lib/topology/addr.go, go/path_srv/main.go, go/sig/egress/worker/worker.go, go/tools/topopruner/topopruner.go, go/vendor/vendor.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2209)
=> Fix misspellings and add misspell lint.

go/Makefile, go/border/main.go, go/cert_srv/main.go, go/cert_srv/setup.go, go/lib/env/env.go, go/lib/env/flags.go, go/lib/env/logging.go, go/path_srv/main.go, go/sciond/main.go, go/sig/main.go, go/tools/logdog/main.go, go/tools/scion-pki/internal/version/version.go, go/tools/scmp/cmn/common.go, go/tools/scmp/main.go, go/tools/showpaths/paths.go, go/tools/topopruner/topopruner.go
Contributes to #2169
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2177)
=> Go services: common startup and shutdown message

go/lib/pathstorage/pathstorage.go, go/lib/sqlite/sqlite.go, go/lib/truststorage/truststorage.go
Fixes #2162 
Examples:
Clean setup:
```
2018-11-28 16:07:59.026287+0000 [INFO] Connecting PathDB backend=sqlite connection=gen-cache/ps1-ff00_0_110-1.path.db
2018-11-28 16:07:59.083183+0000 [INFO] Connecting RevCache backend=mem connection=""
2018-11-28 16:07:59.083246+0000 [INFO] Connecting TrustDB backend=sqlite connection=gen-cache/ps1-ff00_0_110-1.trust.db
```
Wrong config:
```
2018-11-28 16:09:13.184397+0000 [CRIT] Unable to initialize path storage err=
>  Invalid pathdb config
>      Empty connection not allowed
```
DB failure:
```
2018-11-28 16:15:42.959491+0000 [INFO] Connecting PathDB backend=sqlite connection=f
2018-11-28 16:15:42.959674+0000 [CRIT] Unable to initialize path storage err=
>  Initial DB ping failed, connection broken?
>      unable to open database file
```
--- …
=> More transparent DB setup

python/topology/topo.py
Make sure that DS is reachable in docker topology
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2220)
=> DS: Docker network allocations

go/cert_srv/main.go, go/godispatcher/main.go, go/lib/env/env.go, go/lib/fatal/fatal.go, go/lib/pktdisp/disp.go, go/path_srv/main.go, go/sciond/main.go, go/sig/main.go
This patch also moves logging the fatal condition into the failing
goroutine and makes servers wait for 1 second before exiting. This
way we can collect multiple fatal errors in the log in case the
first one is not the most informative one.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2208)
=> Use fatal library in path_srv, cert_srv and sciond

go/sig/base/core/as.go, go/sig/egress/interface.go, go/sig/egress/reader/reader.go, go/sig/metrics/metrics.go
Also: Increase remote ringbuf to reduce queue full errors.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2239)
=> SIG: Add EgressRxQueueFull metric

go/lib/addr/host.go, go/sig/base/core/as.go, go/sig/base/events.go, go/sig/base/pollhdlr.go, go/sig/config/config.go, go/sig/config/config_test.go, go/sig/egress/interface.go, go/sig/egress/session/session.go, go/sig/egress/session/sessmon.go, go/sig/egress/worker/worker.go, go/sig/siginfo/sig.go, python/topology/common.py, python/topology/topo.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2155)
=> Dynamic peer SIG discovery

go/cert_srv/main.go, go/godispatcher/main.go, go/lib/env/logging.go, go/lib/log/log.go, go/path_srv/main.go, go/sciond/main.go, go/sig/main.go
log.LogPanicAndExit only works if it is called with defer.
Fixes #2242
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2245)
=> Remove env.CleanupLog, it is wrong

go/lib/fatal/fatal.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2249)
=> Comments in fatal library changed to adhere to Go documentation style

.buildkite/pipeline.sh, .buildkite/steps/acceptance, acceptance/README.md, acceptance/common.sh, acceptance/ctl, acceptance/lib.sh, acceptance/run, acceptance/sig_acceptance/test, acceptance/topo_ps_reloads_br_acceptance/test, acceptance/topo_ps_reloads_cs_acceptance/test, acceptance/topo_sd_reloads_br_acceptance/test, acceptance/topo_sd_reloads_cs_acceptance/test, acceptance/topo_sd_reloads_ps_acceptance/test, python/topology/common.py, python/topology/docker.py, python/topology/go.py, python/topology/prometheus.py, python/topology/sig.py, python/topology/supervisor.py, scion.sh
Also contributes to #2153.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2247)
=> Acceptance tests: Collect and save metrics

tools/pktgen.py
An argument was removed from the base class.
Fixes: 4df2e7a Blocked: Split integration tests into separate processes
(#1683)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2238)
=> Fix Python pktgen

go/border/setup.go
The old sockets should not be closed before the new ones are started successfully.
(partially addresses #2254)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2252)
=> BR: Fix topo reloading

go/Makefile, go/cert_srv/internal/csconfig/customers.go, go/cert_srv/internal/csconfig/state.go, go/cert_srv/internal/csconfig/state_test.go, go/cert_srv/internal/csconfig/testdata/customers/ISD1-ASff00_0_110-V1.key, go/cert_srv/internal/reiss/handler.go, go/cert_srv/setup.go, go/lib/infra/modules/trust/trustdb/trustdb.go, go/lib/infra/modules/trust/trustdb/trustdbsqlite/db.go, go/lib/infra/modules/trust/trustdb/trustdbtest/trustdbtest.go
Only use files to create the initial state and from then on work with the DB.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2241)
=> CS: Store customer keys in trust database

acceptance/topo_br_reload_if_ip_acceptance/test, acceptance/topo_br_reload_if_port_acceptance/test, acceptance/topo_br_reload_util/tinier.topo, acceptance/topo_br_reload_util/two_as.topo, acceptance/topo_br_reload_util/util.sh
Add acceptance tests for BR topology reloading with ip and port changes.
The test checks that changing the local and remote ip and/or port of an
interface works as expected.
To change the remote ip/port, a two step process is necessary.
This will be removed when #2254 is fixed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2258)
=> BR: Acceptance Test for Topology reloading with changed IP and Port

go/lib/infra/messenger/messenger.go
If we need to get a path for a snet.Addr first check if there is already a path, if so use it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2267)
=> messenger: Use path if we already have it

go/lib/sciond/sciond.go
Otherwise it might not be obvious that they come from the sciond API.
For example if an app uses a dispatcher as well it is not clear if the dispatcher error message is from the app or the sciond API.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2269)
=> sciond-API: Wrap errors

go/path_srv/internal/handlers/psdedupe.go
The default interval of 5s is bad for integration tests, example: revoc test 131->212:
• 131 requests down segments at 130
• 130 hits a revocation
• 131 gets a new request but the request is deduplicated until the first one times out (after 5s).
• After the timeout the next request goes to 130 again.
• 130 selects another path to core in isd 2 but again hits a revocation
• 131 is again blocked for 5s
• After that 130 chooses the first path again.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2285)
=> PS: Change dedupe lifetime

go/border/brconf/conf.go, go/border/netconf/interface.go, go/lib/topology/raw.go, go/lib/topology/testdata/basic.json, go/lib/topology/topology.go, go/lib/topology/topology_test.go
Add TTL field to topology file.
TTL indicates for how long the topology is valid in seconds since the timestamp.
Additionally, add CtrlAddrs and InternalAddrs to BRInfo.
(Otherwise this information is lost for border routers without any interfaces)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2287)
=> Topo: Add TTL

go/path_srv/internal/handlers/segreq.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2294)
=> Re-add required log statement

python/topology/config.py, python/topology/generator.py, python/topology/go.py, python/topology/supervisor.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2303)
=> Go dispatcher support for supervisord topo gen

go/lib/env/env.go, go/lib/env/logging.go, go/lib/util/docker.go
The function might also be usable for packages that don't rely on env.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2322)
=> Refactor: Move RunsInDocker from env to util package

go/godispatcher/internal/registration/iatable.go, go/godispatcher/internal/registration/iatable_test.go, go/godispatcher/internal/registration/scmp_table.go, go/godispatcher/internal/registration/scmp_table_test.go, go/godispatcher/internal/registration/table.go
This is a stepping stone to implementing SCMP Echo, TraceRoute, and RecordPath support in the Go dispatcher.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2326)
=> Go dispatcher: Add SCMP ID tracking tables

go/border/rpkt/path.go, go/border/rpkt/route.go
When incrementing the path, there are some errors that contain incorrect
info/hop field offsets, case of verify only fields when there is no
segment change and when switching from down to up segment.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2182)
=> border: report proper info/hop field offsets

python/topology/prometheus.py, tools/dc
So that is easy to run prometheus locally to scrape from the test topology.
Also change the prometheus file paths to be relative so that they can easily be used with prometheus.
To use:
Gen topo:   ./scion.sh topology
Start prom: ./tools/dc prom up -d
Start topo: ./scion.sh run
Note you need to manually stop the prom container again (./tools/dc prom down).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2343)
=> Add prometheus to tools/dc

.buildkite/steps/build.yml, .buildkite/steps/build_all.yml, .buildkite/steps/setup.yml, .buildkite/steps/test.yml
Buildkite: A job will show an exit status of -1 if the connection to the agent is lost. 
When agents haven't been used for some time there can be a race condition between AWS stopping machines and a new build acquiring an agent. Then the agent may be stopped while already running a job again.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2350)
=> BK: Add retry for jobs when an agent failed

go/border/braccept/main.go
Increase timeout for BR acceptance tests s.t. the probability for a timeout decreases, especially on the CI.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2354)
=> BR acceptance tests: Increase timeout

acceptance/topo_br_reload_if_ip_acceptance/test, acceptance/topo_br_reload_if_port_acceptance/test, go/border/brconf/params.go, go/border/brconf/sample.go, go/border/main.go, go/border/setup-posix.go, go/border/setup.go, go/border/setup_test.go
Make context setup during a topology reload transactional.
Either the complete setup completes, or all changes are rolled back to the previous stage.
The context setup is executed in the following phases:
1. setupNet
- reuse unchanged sockets from old context
- setup socket for new changed interfaces
- (if local addr clashes) close socket to allow new socket to bind
2. rollbackNet (if error in setupNet)
- close freshly setup sockets
- restart previously closed sockets
3. teardownNet (if no error in setupNet)
- close no longer used  sockets of old context.
To simplify the handling, the following restrictions are introduced:
1. No address must be reassigned to a different interface.
2. No address must be reassigned from internal to interface,
and vice versa.
Doing these changes requires a …
=> BR: Transactional context setup

.buildkite/steps/build.yml, .buildkite/steps/build_all.yml, .buildkite/steps/setup.yml, .buildkite/steps/test.yml, tools/ci/integration
The buildkite docs are somewhat missleading or the UI is inconsistent with the exit code when agent disconnected, see buildkite/docs#306.
Also docker-integration should not run go_infra.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2366)
=> Fix BK retry status and docker-integration

go/godispatcher/internal/respool/packet.go, go/godispatcher/network/app_socket.go, go/lib/hpkt/read.go, go/lib/spkt/extn_generic.go, go/lib/spkt/extn_onehoppath.go
Specifically:
- make Go SCION parser skip E2E extensions;
- disable validation checks on egress packets in the dispatcher (thus allowing tests to trigger SCMP error conditions by sending malformed packets on the network)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2361)
=> Go dispatcher: make Python integration pass

tools/dc
Since we shift away the first arg we should use the local variable.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2370)
=> tools/dc fix error introduced by #2369

go/lib/pathdb/metrics.go, go/lib/pathdb/metrics_test.go, go/lib/prom/prom.go, go/path_srv/internal/metrics/metrics.go, go/path_srv/main.go
The wrapper can be used to export metrics about any implementation of pathDB.
Rationale: 
The error counters help to detect where an issue of a service might be (i.e. in this case the DB).
The total counters give an idea on the pressure on the DB.
Contributes #2329
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2358)
=> PathDB: Add a metrics wrapper

go/cert_srv/internal/metrics/metrics.go, go/cert_srv/setup.go, go/lib/infra/modules/trust/trustdb/metrics.go, go/lib/infra/modules/trust/trustdb/metrics_test.go, go/lib/infra/modules/trust/trustdb/trustdb.go, go/lib/infra/modules/trust/trustdb/trustdbtest/trustdbtest.go
Rationale:
The error counters help to detect where an issue of a service might be (i.e. in this case the DB).
The total counters give an idea on the pressure on the DB.
Contributes #2329
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2362)
=> TrustDB: Add metrics wrapper

acceptance/topo_br_reload_rollback_acceptance/test, acceptance/topo_br_reload_util/util.sh
Add acceptance test to check failed sighup topology reloads are recovered correctly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2277)
=> BR: Add acceptance test for context reload rollback

acceptance/brutil/common.sh, acceptance/brutil/docker-compose.yml, go/border/braccept/brA.go, go/border/braccept/brB.go, go/border/braccept/brC.go, go/border/braccept/brD.go, go/border/braccept/brtest.go, go/border/braccept/common_tests.go, go/border/braccept/core_brA.go, go/border/braccept/core_brB.go, go/border/braccept/core_brC.go, go/border/braccept/main.go, go/border/braccept/segments.go, go/border/braccept/tpkt/ctrl.go, go/border/braccept/tpkt/extensions.go, go/border/braccept/tpkt/scmp.go, go/border/braccept/tpkt/scnpath.go, go/border/braccept/tpkt/tpkt.go
Add support and test for revocation. For such test, a Pre/Post step was
added to each test, providing the ability to send a packet before and
after (respectivily) the test itself. In the Pre step an IFStateInfo
deactiving an interface is sent to the BR, then a IFStateInfo activing
the same interface is sent in the Post, to restore the original BR
state.
Path segments are now defined as strings using an intuitive syntax,
maintaining all the previous flexibility to define path segments.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2302)
=> braccept: revocation test and rework segment generation

go/border/braccept/brA.go, go/border/braccept/brD.go, go/border/braccept/common_tests.go, go/border/braccept/core_brA.go, go/border/rctrl/ifstate.go, go/border/rctrl/revinfo.go, go/cert_srv/internal/reiss/handler.go, go/cert_srv/internal/reiss/requester.go, go/cert_srv/internal/reiss/self.go, go/cert_srv/main.go, go/cert_srv/setup.go, go/integration/cert_req/main.go, go/lib/ctrl/ctrl.go, go/lib/ctrl/signed.go, go/lib/ctrl/signed_util.go, go/lib/infra/common.go, go/lib/infra/messenger/messenger.go, go/lib/infra/messenger/messenger_test.go, go/lib/infra/modules/trust/helpers.go, go/lib/infra/modules/trust/signhelper.go, go/lib/infra/modules/trust/trust.go, go/sig/base/pollhdlr.go, go/sig/egress/session/sessmon.go
Moves signer and verifier implementation from ctrl to the trust package.
Use infra.Messenger in CS instead of *messenger.Messenger.
Fixes #2030
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2379)
=> infra.Messenger: expose UpdateSigner/UpdateVerifier

go/godispatcher/internal/registration/iatable.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2387)
=> Go dispatcher: fix data race in routing table access

.buildkite/scripts/build_scion_img, go/cert_srv/main.go, go/cert_srv/setup.go, go/lib/env/env.go, go/lib/infra/modules/itopo/cleaner.go, go/lib/infra/modules/itopo/doc.go, go/lib/infra/modules/itopo/itopo.go, go/lib/infra/modules/itopo/itopo_test.go, go/lib/infra/modules/itopo/testdata/topo.json, go/lib/infra/modules/itopo/validate.go, go/lib/infra/modules/itopo/validate_test.go, go/lib/infra/modules/trust/trust.go, go/lib/infra/modules/trust/trust_test.go, go/lib/topology/topology.go, go/path_srv/internal/cryptosyncer/cryptosyncer.go, go/path_srv/internal/handlers/common.go, go/path_srv/internal/segsyncer/segsyncer.go, go/path_srv/main.go, go/sciond/internal/fetcher/fetcher.go, go/sciond/internal/servers/handlers.go, go/sciond/main.go, go/vendor/vendor.json
Split itopo topology into a static and dynamic version.
Currently, only the static topology can be set and fetched.
The code also contains an outline how the dynamic topology
will be used in a future PR.
The services currently only support setting the static
topology through a sighup reload. Querying the discovery
service will be added in a future PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2375)
=> itopo: Split topo in static and dynamic

go/lib/periodic/periodic.go, go/lib/periodic/periodic_test.go
This allows to run a task immediately after periodic creation,
or at any point in time when it is deemed necessary.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2389)
=> periodic: Add TriggerRun method.

acceptance/cert_renewal_acceptance/test
Past experience has shown that untested/unexecuted
code quickly diverges. Automatic certificate renewal
is currently disabled by default.
This acceptance test checks that automatic certificate
renewal is operational.
fixes #1939
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2323)
=> CS: Add cert renewal acceptance test

go/integration/cert_req/main.go, go/lib/ctrl/cert_mgmt/chain.go, go/lib/ctrl/cert_mgmt/trc.go, go/lib/infra/modules/trust/handlers.go, go/lib/infra/modules/trust/trust.go, go/lib/infra/modules/trust/trust_test.go, go/lib/scrypto/cert/chain.go, go/lib/scrypto/trc/trc.go, python/scion_elem/scion_elem.py
In case of a cache only request the serving side should have the possibility to reply with an empty message.
This is helpful for querying whether a certain CS has a chain (used for pushing of chains see #2308)
Fixes #2392
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2396)
=> Allow empty chain&trc replies for cache-only reqs

.buildkite/scripts/build_scion_img, go/border/braccept/brD.go, go/border/braccept/brtest.go, go/border/braccept/main.go, go/vendor/vendor.json
This changes are intended to solve some reliability issues encountered
when running the br acceptance tests in CI.
It adds per test timeout and delay paramenters and replaces libpcap with
AF_PACKET which seems to solve most of the timeout issues seen so far.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2398)
=> braccept: more reliable ci tests

python/lib/packet/cert_mgmt.py
In #2396 we started to allow empty replies for cache only TRC&Chain requests,
we need to handle this properly in python.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2403)
=> Handle empty TRC&Chain messages in python

go/cert_srv/internal/reiss/corepush.go, go/cert_srv/internal/reiss/corepush_test.go, go/cert_srv/internal/reiss/requester.go, go/cert_srv/internal/reiss/self.go, go/cert_srv/internal/reiss/testdata/ISD1-ASff00_0_311-V1.crt, go/cert_srv/main.go, go/lib/xtest/matchers.go, go/lib/xtest/matchers/matchers.go
Each CS periodically pushes the local chain to all core CSes.
This is required to change the lookup logic of CSes (to only look up at cores).
Additionally this will help in the future to list all ASes in an ISD at a core CS.
Fixes #2308
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2399)
=> CS: Push local chain to all core CSes in ISD

acceptance/topo_invalid_reloads_acceptance/test, go/cert_srv/setup.go, go/lib/env/env.go, go/lib/infra/modules/itopo/itopo.go, go/lib/infra/modules/itopo/itopo_test.go, go/lib/infra/modules/itopo/validate.go, go/lib/infra/modules/itopo/validate_test.go, go/lib/infra/modules/trust/trust_test.go, go/lib/topology/topology.go, go/path_srv/main.go, go/sciond/main.go
Add validator for infra services according to `itopo/doc.go`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2402)
=> itopo: Add svc validator

go/border/router.go, go/border/setup.go, go/lib/infra/modules/itopo/itopo.go, go/lib/infra/modules/itopo/itopo_test.go, go/lib/infra/modules/itopo/testdata/topo.json, go/lib/infra/modules/itopo/validate.go, go/lib/infra/modules/itopo/validate_test.go
The split is achieved by using the itopo package.
This change adds a border router specific validator to itopo
which enforces the mutability rules according to `itopo/doc.go`.
On sighup, the border router sets the new static topology of itopo.
The following mechanisms that interact with itopo are implemented later:
- fetching static topology from discovery service
- fetching dynamic topology from discovery service
- dropping expired dynamic topology
`itopo` acts as a mediator between these 4 ways of changing the topology
and shall contain the `truth`.
Since the border router uses `rctx` to atomically get the context for a packet,
this means that the topology in `rctx` and `itopo` need to be kept in sync.
To achieve this, the context setup is done as follows:
1. Get view what the state …
=> BR: Split topology in static and dynamic

go/cert_srv/internal/config/config.go, go/cert_srv/internal/config/config_test.go, go/cert_srv/internal/config/sample.go, go/cert_srv/main.go, go/lib/infra/modules/idiscovery/config.go, go/lib/infra/modules/idiscovery/idiscovery.go, go/lib/infra/modules/itopo/cleaner.go, go/lib/infra/modules/itopo/itopo.go, go/lib/infra/modules/itopo/itopo_test.go, go/path_srv/internal/config/config.go, go/path_srv/internal/config/sample.go, go/path_srv/internal/config/sample_test.go, go/path_srv/main.go, python/topology/go.py
This PR adds dynamic topology fetching from the discovery service
to the certificate and path server.
Fetching can be enabled through the config file.
To mock the discovery service, a simple http server can be started (`go/examples/server.sh`)
```
./scion.sh topology -ds
./go/examples/server.sh gen/ISD1/ASff00_0_111/endhost/topology.json
vim /tmp/tmp.BLAH/discovery/v1/dynamic/full.json 
```
Acceptance tests will be added in a follow-up PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2409)
=> Infra: Add dynamic topology fetching

tools/dc
having $() around the collect log command would execute the output of the command, which is not what we want.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2424)
=> dc: fix collect logs methods.

acceptance/discovery_br_fetches_dynamic_acceptance/test
This acceptance test checks that the border router fetches the
dynamic topology from the discovery service.
The test is structured as follows:
1. Check connectivity
2. Serve dynamic topology with invalid BS address -> link goes down
3. Check connectivity is broken
4. Let dynamic topology expire -> link goes up
5. Check connectivity is up again
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2426)
=> BR: Add dynamic topology fetching acceptance test

acceptance/discovery_br_fetches_dynamic_acceptance/test, acceptance/discovery_infra_fetches_dynamic_acceptance/test, acceptance/discovery_infra_fetches_static_acceptance/test, acceptance/discovery_util/dc.tmpl, acceptance/discovery_util/util.sh, go/cert_srv/internal/config/config_test.go, go/cert_srv/internal/config/sample.go, go/lib/infra/modules/idiscovery/config.go, go/lib/infra/modules/idiscovery/idiscovery.go, go/path_srv/internal/config/sample.go, go/path_srv/internal/config/sample_test.go, python/topology/go.py
This PR adds parameters for static topology fetching from the DS to the config of infra services and modifies `idiscovery` to periodically fetch the static topology if enabled.
Also, an acceptance test is added to check that the static topology is actually fetched by the infra services.
The test gets its own directory because it will become more extensive in the future.
We plan to enable `idiscovery` to write the static topology to disc (when enabled) which will differentiate the test from the `dynamic` counter part.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2429)
=> Infra: Fetch static topology from the discovery service

acceptance/discovery_infra_fetches_static_acceptance/test, go/cert_srv/internal/config/config_test.go, go/cert_srv/internal/config/sample.go, go/examples/discovery_client/client.go, go/lib/discovery/topofetcher/fetcher.go, go/lib/infra/modules/idiscovery/config.go, go/lib/infra/modules/idiscovery/idiscovery.go, go/lib/util/file.go, go/path_srv/internal/config/sample.go, go/path_srv/internal/config/sample_test.go
Infra services can be instructed to write topology updates to file system by configuring the `discovery.static.Filename`.
In case of an empty string, the updated topology is not written.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2430)
=> Infra: Write static topology updates to file system

acceptance/discovery_br_fetches_static_acceptance/test, go/border/brconf/params.go, go/border/brconf/sample.go, go/border/main.go, go/border/setup.go, go/cert_srv/internal/config/sample.go, go/path_srv/internal/config/sample.go
This PR enables static topology fetching from the discovery service.
The BR can be configured to periodically fetch the static topology from the discovery service and, if desired, write the updated version to disk.
Whether modifications to the semi-mutable part (i.e. the interfaces) of the topology are possible, can be enabled and disabled.
Additionally, acceptance tests are added to check that the BR fetches steady topologies as expected.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2435)
=> BR: Fetch static topology 

acceptance/cert_renewal_acceptance/test, acceptance/common.sh, acceptance/discovery_br_fetches_dynamic_acceptance/test, acceptance/discovery_br_fetches_static_acceptance/test, acceptance/discovery_infra_fetches_dynamic_acceptance/test, acceptance/discovery_infra_fetches_static_acceptance/test, acceptance/topo_br_reload_util/util.sh, acceptance/topo_ps_reloads_br_acceptance/test, acceptance/topo_ps_reloads_cs_acceptance/test, acceptance/topo_sd_reloads_br_acceptance/test, acceptance/topo_sd_reloads_cs_acceptance/test, acceptance/topo_sd_reloads_ps_acceptance/test
Add fail function to `acceptance/common.sh` that writes the timestamped message to stderr and exits with code 1.
Refactor all acceptance tests from the `|| { echo blah; exit 1 }` to `|| fail blah` pattern.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2442)
=> Accept: Add fail function

go/examples/discovery_client/client.go, go/examples/discovery_client/server.sh, go/lib/discovery/discovery.go, go/tools/topopruner/topopruner.go
Add a third endpoint called `default`. The discovery service
serves either the full or endhost topology, based on the privilege
of the requesting entity.
This is used specifically in sciond to avoid explicit configuration
on infrastructure nodes.
Additionally, this rename the `reduced` topology to `endpoint` topology.
fixes #2441
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2450)
=> discovery: Add default endpoint

acceptance/discovery_infra_fetches_dynamic_acceptance/test, acceptance/discovery_infra_fetches_static_acceptance/test, acceptance/discovery_util/util.sh, go/sciond/internal/config/config.go, go/sciond/internal/config/sample.go, go/sciond/internal/config/sample_test.go, go/sciond/main.go, python/topology/go.py
This change enables the use of `idiscovery` in sciond.
The requests are sent to the `default` endpoint of the DS.
fixes #2432 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2453)
=> Sciond: Enable idiscovery

.buildkite/scripts/build_scion_img, docker/Dockerfile.base, env/debian/pkgs.txt
Using chown when building a docker image is expensive. It in fact copies
each file that's touched growing the size of the layer a lot.
This particular step resulted in a 84MB layer. After the change it's 422
bytes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2457)
=> Docker base image: Use chown only when needed

go/lib/infra/modules/itopo/itopo_test.go
Currently, the unit test fails occasionally on slow machines
due to the callback not being called in time. This change
increases the sleep period that waits for the callback being
called.
fixes #2455
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2456)
=> itopo: Increase sleep in unit test

go/border/rctrl/ctrl.go, go/cert_srv/setup.go, go/examples/pingpong/pingpong.go, go/integration/common.go, go/lib/infra/infraenv/infraenv.go, go/lib/snet/snet.go, go/lib/sock/reliable/reliable.go, go/sig/sigcmn/common.go, go/tools/showpaths/paths.go
This allows applications to inject custom dispatcher backends (e.g., for
bypass, non-SOCKSTREAM implementations, testing, etc.).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2460)
=> Implement dispatcher service interface

go/lib/sciond/mock.go, go/lib/snet/conn.go, go/lib/snet/dispatcher.go, go/lib/snet/packet_conn.go, go/lib/snet/reader.go, go/lib/snet/snet.go, go/lib/snet/writer.go, go/lib/snet/writer_test.go
Applications can now implement firewalls, shim layers, and specialized
SCMP handling on top of existing snet interfaces.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2462)
=> Socket plugin support for snet

acceptance/common.sh, acceptance/discovery_br_fetches_dynamic_acceptance/test, acceptance/discovery_br_fetches_static_acceptance/test, acceptance/discovery_infra_fetches_dynamic_acceptance/test, acceptance/discovery_infra_fetches_static_acceptance/test, acceptance/discovery_util/util.sh, go/border/brconf/sample.go, go/cert_srv/internal/config/config_test.go, go/cert_srv/internal/config/sample.go, go/lib/infra/modules/idiscovery/config.go, go/lib/infra/modules/idiscovery/idiscovery.go, go/lib/infra/modules/idiscovery/idiscoverytest/config.go, go/lib/periodic/periodic.go, go/path_srv/internal/config/sample.go, go/path_srv/internal/config/sample_test.go, go/sciond/internal/config/sample.go, go/sciond/internal/config/sample_test.go
Enables the `idiscovery` library to initially check that topologies can be successfully fetched from the discovery service.
On start up, the discovery service is queried every second until a valid response is received or the `InitialPeriod` has passed. If that period has passed, and no valid topology has been received,
the process will take the configured fail action:
* `Fatal`: Exit process with error
* `Ignore`: Ignore, and keep the periodic queries running
fixes #2431
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2459)
=> Discovery: Initial connection check

python/beacon_server/base.py
The XOVER flag is only meaningful in a data-plane path.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2475)
=> Don't set XOVER flag in path segments

go/lib/revcache/memrevcache/memrevcache.go, go/lib/revcache/memrevcache/memrevcache_test.go, go/lib/revcache/revcache.go, go/lib/revcache/revcache_test.go, go/lib/revcache/revcachetest/revcachetest.go, go/path_srv/internal/handlers/common_test.go, go/path_srv/internal/segutil/segutil.go, go/path_srv/internal/segutil/segutil_test.go, go/sciond/internal/fetcher/fetcher.go
The old Get and GetAll methods are merged into Get.
Get can now be queried with multiple keys.
The new GetAll returns all entries that are in the cache, provided by a channel.
The channel is used so that we don't have to have all entries in memory.
This also fixes FilterNew function that did a wrong comparison previously.
Fixes #2472
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2480)
=> revcache: Add GetAll, clean up API

go/lib/infra/common.go, go/lib/infra/messenger/messenger.go
Waiting for Acks/Errors can be enabled via a new flag in the Messenger config.
Only two RPC calls are implemented right now, as a proof of concept. The complete PR will implement error support for all calls.
Feedback available on the old issue (#2481).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2490)
=> Add error messages to infra RPC

scion.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2493)
=> Upload bazel test logs

.buildkite/steps/acceptance, .buildkite/steps/docker-integration.yml
Now one can pass ACCEPTANCE_TEST="regex" to the CI and only matching acceptance tests will be executed. The options are:
- `export ACCEPTANCE_TEST="regex"` in pipeline.sh
- ACCEPTANCE_TEST="regex" as env var on the BK UI
Fixes #2438 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2501)
=> BK: Specify Acceptance tests

.buildkite/scripts/build_scion_img, docker/Dockerfile, docker/Dockerfile.base
This decreases the size of scion image by ~1/2 GB
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2497)
=> Save bazel and python caches out of home dir

go/sciond/internal/servers/handlers.go
Instead of logging the address of the pointer to the struct, log the struct.
Also unify the log context name to "req".
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2500)
=> sciond: Fix request logging

go/examples/pingpong/pingpong.go
While there, consolidate the validation of flags.
Without this change, `./bin/pingpong` crashes if I fail to specify the remote port:
```
$ ./bin/pingpong -local 17-ffaa:1:bb9,[127.0.0.1] -remote 19-ffaa:0:1303,[141.44.25.144]
2019-01-28 11:56:39.559543+0100 [CRIT] Panic msg="runtime error: invalid memory address or nil pointer dereference" stack=
>  goroutine 1 [running]:
>  runtime/debug.Stack(0xc4201fbd98, 0xab2780, 0x10be990)
>       /usr/local/go/src/runtime/debug/stack.go:24 +0xa7
>  github.com/scionproto/scion/go/lib/log.LogPanicAndExit()
>       /home/scion/go/src/github.com/scionproto/scion/go/lib/log/log.go:142 +0x6e
>  panic(0xab2780, 0x10be990)
>       /usr/local/go/src/runtime/panic.go:491 +0x283
>  main.main()
> …
```
=> pingpong: check for missing remote port when validating flags

go/integration/cert_req/main.go, go/lib/infra/infraenv/infraenv.go, go/lib/infra/messenger/messenger.go, go/lib/infra/messenger/messenger_test.go, go/lib/infra/modules/trust/trust_test.go
This simplifies integrating the QUIC RPC layer in the Messenger.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2506)
=> Construct Infra Messenger from Configs only

go/lib/pathdb/metrics.go, go/lib/pathdb/metrics_test.go, go/lib/pathdb/pathdb.go, go/lib/pathdb/pathdbtest/pathdbtest.go, go/lib/pathdb/query/query.go, go/lib/pathdb/sqlite/BUILD.bazel, go/lib/pathdb/sqlite/sqlite.go, go/lib/pathdb/sqlite/sqlite_test.go
GetAll can be used to fetch all segments from the DB, via a channel.
Also:
-Return query.Results in Get method.
-Introduce a TestablePathDB interface for the test suite.
This makes the testing slightly simpler.
Fixes #2471
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2511)
=> pathdb: Add GetAll method

BUILD.bazel, WORKSPACE, scion.sh
This adds checks similar to go vet to Go code.
The checks are run during during Bazel build.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2518)
=> Nogo code analyzer

.buildkite/scripts/build_scion_img, tools/fetch.sh
The generated BUILD file which is used for fetching dependencies haven't
contained nogo target that is referenced by WORKSPACE file. This
patch adds a fake no-op target to fix that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2528)
=> Fix docker.sh base

go/cert_srv/main.go, go/cert_srv/setup.go, go/lib/infra/modules/db/BUILD.bazel, go/lib/infra/modules/db/limits.go, go/lib/infra/modules/trust/trustdb/BUILD.bazel, go/lib/infra/modules/trust/trustdb/metrics.go, go/lib/infra/modules/trust/trustdb/trustdb.go, go/lib/infra/modules/trust/trustdb/trustdbsqlite/db.go, go/lib/pathdb/BUILD.bazel, go/lib/pathdb/metrics.go, go/lib/pathdb/pathdb.go, go/lib/pathdb/sqlite/sqlite.go, go/lib/pathstorage/BUILD.bazel, go/lib/pathstorage/pathstorage.go, go/lib/pathstorage/pathstoragetest/config.go, go/lib/pathstorage/sample.go, go/lib/revcache/BUILD.bazel, go/lib/revcache/memrevcache/memrevcache.go, go/lib/revcache/revcache.go, go/lib/truststorage/truststorage.go, go/lib/truststorage/truststoragetest/config.go, go/lib/truststorage/truststoragetest/config_test.go, go/path_srv/internal/handlers/common.go, go/path_srv/main.go, go/sciond/main.go
This PR makes the MaxOpenConns and MaxIdleConns of the trust database,
path database and revocation cache configurable.
Additionally, fixes #2536 and #2537
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2540)
=> DB: Make Max{Open,Idle}Conns configurable

go/beacon_srv/internal/beacon/BUILD.bazel, go/beacon_srv/internal/beacon/policy.go, go/beacon_srv/internal/beacon/policy_test.go, go/beacon_srv/internal/beacon/testdata/policy.yml, go/beacon_srv/internal/beacon/testdata/typedPolicy.yml
Add the `Apply` method to the policy filter. This allows
filtering beacons according to a policy.
Additionally, add the possibility to load the policy from a yaml file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2545)
=> BS: Add Filtering

go/lib/infra/dedupe/dedupe.go, go/lib/infra/dedupe/dedupe_test.go, go/lib/infra/modules/trust/trust.go, go/path_srv/internal/handlers/segreq.go
The context was shadowed in the current implementation anyway.
Furthermore it could lead to weird interactions:
If the first caller of a deduped request has a long timeout and the second one a short one
Only the timeout of the first requestor would be respected.
That is why callers of Request anyway also select on the ctx.Done() channel,
thus we don't have to pass it to the Request method.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2553)
=> Remove ctx from deduper.Request method

go/beacon_srv/internal/ifstate/ifstate.go, go/beacon_srv/internal/ifstate/ifstate_test.go
This PR adds an in-memory data structure to keep track
of the interface state of a given AS.
fixes #2485
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2552)
=> BS: Implement data structure for interface state

Makefile, WORKSPACE, go/integration/BUILD.bazel, go/lib/hpkt/BUILD.bazel, go/lib/infra/modules/trust/BUILD.bazel, go/lib/pathdb/pathdbtest/BUILD.bazel, go/lib/snet/BUILD.bazel, go/lib/snet/snetproxy/BUILD.bazel, go/lib/xtest/p2p/BUILD.bazel, go/path_srv/internal/handlers/BUILD.bazel
Removes the diff from running `gazelle update -index=false -external=external -exclude go/vendor ./go`
Also updated the WORKSPACE so that when running `gazelle update-repos somerepo.com/repo/path` will not cause any additional diffs.
`go/path_srv/internal/handlers/BUILD.bazel` still contained an old gomock call that is now solved by using a dependency.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2574)
=> bazel: cleanup so that BUILD.bazel files match gazelle output

go/beacon_srv/internal/keepalive/BUILD.bazel, go/beacon_srv/internal/keepalive/sender.go, go/beacon_srv/internal/keepalive/sender_test.go, go/beacon_srv/internal/keepalive/testdata/topology.json, go/beacon_srv/internal/onehop/BUILD.bazel, go/beacon_srv/internal/onehop/sender.go, go/beacon_srv/internal/onehop/sender_test.go, go/lib/spath/BUILD.bazel, go/lib/spath/path.go, go/lib/spath/path_test.go
The keepalive sender periodically sends keepalive messages
on all interfaces.
Additionally, add one-hop creation function to `spath`.
fixes #2567
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2573)
=> BS: Add Keepalive sender

Makefile, go/lib/infra/modules/trust/trustdb/mock_trustdb/BUILD.bazel, go/lib/infra/modules/trust/trustdb/trustdbsqlite/BUILD.bazel, go/tools/scion-custpk-load/BUILD.bazel, nogo.json, scion.sh
This PR changes the linter to ensure that the bazel files
do not differ from the auto generated files.
fixes #2582
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2590)
=> Lint: Ensure bazel files are consistent

go/lib/ctrl/BUILD.bazel, go/lib/ctrl/ctrl.go, go/lib/ctrl/seg/seg.go, go/lib/ctrl/union.go, go/lib/infra/messenger/messenger.go, go/lib/spath/BUILD.bazel, go/lib/spath/hop.go, go/lib/spath/hop_test.go
The pcb in the ctrl pld union should be `path_seg.PCB` instead of
`path_seg.PathSegment`.
This change is made to keep compatibility to python code.
Additionally, add `time.Duration` to `ExpTimeType` conversion.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2583)
=> Proto: Add beacon to union

go/beacon_srv/internal/propagation/BUILD.bazel, go/beacon_srv/internal/propagation/config.go, go/beacon_srv/internal/propagation/originator.go, go/beacon_srv/internal/propagation/originator_test.go, go/beacon_srv/internal/propagation/testdata/topology.json, go/lib/ctrl/path_mgmt/seg_recs.go, go/lib/ctrl/seg/as.go, go/lib/ctrl/seg/seg.go, go/lib/infra/modules/trust/helpers.go, go/path_srv/internal/handlers/segreqnoncore_test.go, tools/gomocks
This change adds the beacon originator task.
The originator uses a one-hop sender to send the beacons on all active interfaces of the LinkTo Core/Child type.
The task should only be run by core ASes.
fixes #2564
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2592)
=> BS: Implement beacon originator

go/lib/ctrl/path_mgmt/seg_req.go
Before the output of `SegReq.String()` was:
`1-ff00:0:111 -> 1-ff00:0:110, Flags: {false false}`
Now the output is:
`1-ff00:0:111 -> 1-ff00:0:110, Flags: {Sibra:false CacheOnly:false}`
fixes #2210
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2594)
=> Print SegReqFlags field names

WORKSPACE
We use gazelle diff mode to ensure consistency during lint.
Diff returns an non-zero exit code starting from commit
https://github.com/bazelbuild/bazel-gazelle/commit/386774d
Which is included starting from pre-release 0.17.0
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2603)
=> Gazelle: Update to 0.17.0

go/proto/cereal.go
Catch panics when deserializing capnp messages using pogs.
This could happen on malformed input, see capnproto/go-capnproto2#137
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2605)
=> Proto: Catch pogs panic

go/beacon_srv/internal/beaconing/extender.go, go/beacon_srv/internal/onehop/sender.go, go/border/braccept/parser/scion.go, go/border/rpkt/extn_onehoppath.go, go/lib/scrypto/mac.go, go/lib/spath/BUILD.bazel, go/lib/spath/hop.go, go/lib/spath/path.go, go/lib/spath/path_test.go
The `spath.Hop.CalcMac` unnecessarily returns an error. It is always nil.
This PR removes the error from the returned values and reduces the
error handling branches in the code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2602)
=> MAC: Avoid always-nil error

go/sig/egress/session/sessmon.go
The session monitor stores its working object into the session, instead
of a snaphot object. This can lead to weird interactions, when the
monitoring times out, and the host is set to an SVC address.
This will cause data traffic to reach the ctrl port of the SIG.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2615)
=> SIG: Avoid capturing the remote SIG info in the session

go/lib/infra/common.go, go/lib/infra/messenger/quic_response_writer.go, go/lib/infra/messenger/udp_response_writer.go, go/lib/infra/mock_infra/infra.go
Extend the response writer with SendIfStateInfoReply which is needed to implement the IfStateReq handler.
Contributes #2486
Also fix go calls in QUICResponseWrite to always defer log.LogPanicAndExit().
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2626)
=> messenger: Extend RW with SendIfStateInfoReply

go/beacon_srv/internal/ifstate/BUILD.bazel, go/beacon_srv/internal/ifstate/doc.go, go/beacon_srv/internal/ifstate/revoker.go, go/beacon_srv/internal/ifstate/revoker_test.go, go/beacon_srv/internal/ifstate/testdata/topology.json, go/lib/xtest/BUILD.bazel, go/lib/xtest/topo.go
Adds a Revoker task that issues revocations for interfaces that have timed
and renews evocations for already revoked interfaces periodically.
Fixes #2566
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2625)
=> BS: Add revoker for IFs with missing keepalive

go/beacon_srv/internal/beacon/policy.go, go/beacon_srv/internal/beacon/store.go, go/beacon_srv/internal/beacon/store_test.go, go/beacon_srv/internal/beaconstorage/config.go
This PR makes `beacon.{Core}Store` implement the `beaconstorage.Store`
interface.
This allows us to create the beacon store backed by the configured
database in `BeaconDBConf`.
fixes  #2560
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2648)
=> BS: Create beacon store through beaconstorage

go/beacon_srv/internal/config/config.go, go/cert_srv/internal/config/config.go, go/cert_srv/setup.go, go/lib/env/env.go, go/lib/env/sample.go, go/lib/infra/infraenv/infraenv.go, go/lib/infra/messenger/messenger.go, go/path_srv/internal/config/config.go, go/path_srv/main.go, go/sciond/internal/config/config.go, go/sciond/main.go, python/topology/common.py, python/topology/docker.py, python/topology/generator.py, python/topology/go.py
Also includes topology generator support for QUIC and SVC resolution.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2653)
=> Start QUIC RPC server in control plane speakers

go/cert_srv/internal/reiss/corepush.go, go/cert_srv/main.go, go/lib/infra/modules/idiscovery/idiscovery.go
The core pusher in the certificate server can block up to a minute if there are no paths available.
This can delay the shutdown of the whole certificate server if the task is in blocking state.
This PR fixes this by killing the task instead of waiting for it to finish.
Additionally, the SegPusher now uses go routines to avoid head of line blocking.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2660)
=> CS: Force cancel core pusher

go/beacon_srv/internal/ifstate/revoker_test.go
ShouldBeBetween doesn't include the bound.
In case the revocation was issued the second before the test creates the now value,
the test would fail on the lower bound.
(see https://buildkite.com/scionproto/scionproto-nightly/builds/228#e8f2c1cb-6d69-4852-89fa-d88953df795b)
Fix the check: The revocation can either have
- A timestamp with a second value 1 less than now, or
- A timestamp with the same second value.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2663)
=> BS: Improve unit test for recentness of revocation

c/lib/filter/filter.c
In file `c/lib/filter/filter.c`, there was a missing dependency for the function `be64toh`.  
Including `<endian.h>` fixes this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2657)
=> Added missing dependency for be64toh

go/beacon_srv/internal/beacon/policy.go, go/beacon_srv/internal/beacon/policy_test.go, go/beacon_srv/internal/beacon/store.go, go/beacon_srv/internal/beacon/testdata/policy.yml, go/beacon_srv/internal/beacon/testdata/typedPolicy.yml, go/beacon_srv/internal/beaconing/handler.go, go/beacon_srv/internal/beaconing/handler_test.go, go/beacon_srv/internal/beaconing/mock_beaconing/beaconing.go, go/beacon_srv/internal/beaconing/propagator.go, go/beacon_srv/internal/beaconstorage/store.go, go/beacon_srv/main.go
Add ISD loop filtering to the policy.
By default, ISD loops are not allowed. If desired, they can be allowed
in the policy.
Additionally, add pre-check to beacon store to indicate whether a beacon
will be ingored, so that the caller does not have to spend resources on
further processing the beacon.
fixes #2658
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2662)
=> BS: Filter ISD loops

.buildkite/scripts/build_scion_img, WORKSPACE, acceptance/topo_ps_reloads_cs_acceptance/test, go/examples/pingpong/BUILD.bazel, go/examples/pingpong/pingpong.go, go/lib/infra/messenger/addr.go, go/lib/infra/messenger/addr_test.go, go/lib/infra/messenger/messenger.go, go/lib/infra/rpc/rpc.go, go/path_srv/internal/cryptosyncer/cryptosyncer.go, nogo.json
QUIC is used only if the clients discover that the server supports it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2664)
=> Control-plane clients use QUIC for inter-AS SVC traffic

acceptance/cert_renewal_acceptance/test, acceptance/discovery_br_fetches_static_acceptance/test, acceptance/reconnecting_acceptance/test, acceptance/sigutil/common.sh, acceptance/topo_br_reload_util/util.sh, acceptance/topo_invalid_reloads_acceptance/test, acceptance/topo_ps_reloads_br_acceptance/test, acceptance/topo_ps_reloads_cs_acceptance/test, acceptance/topo_sd_reloads_br_acceptance/test, acceptance/topo_sd_reloads_cs_acceptance/test, acceptance/topo_sd_reloads_ps_acceptance/test, go/path_srv/internal/config/config.go, go/path_srv/internal/config/config_test.go, go/path_srv/internal/config/sample.go, go/path_srv/main.go, integration/integration_test.sh, tools/ci/integration
Since the BS pushes segments way faster since #2672 we don't need to sleep that much.
Also this PR includes a CryptoSyncer config (fixes #2674) so that we can reduce the sleep in `topo_ps_reloads_cs` acceptance test.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2681)
=> Reduce test sleep time

go/beacon_srv/BUILD.bazel, go/beacon_srv/internal/config/config.go, go/beacon_srv/internal/config/config_test.go, go/beacon_srv/internal/config/sample.go, go/beacon_srv/main.go
This PR enables policy loading from file.
The policy file paths are specified in the config toml.
A sample policy can be printed with the `-help-policy` flag.
fixes #2661
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2680)
=> BS: Load policies

go/beacon_srv/internal/beaconing/handler.go, go/beacon_srv/internal/beaconing/originator.go, go/beacon_srv/internal/beaconing/propagator.go, go/beacon_srv/internal/beaconing/registrar.go, go/beacon_srv/internal/beaconing/util.go, go/beacon_srv/main.go
Refactor registrar/originator/propagator to reduce the method signatures and declutter the code.
Additionally, reduce logging statements for normal operation in the BS to be less
verbose by moving many of them to `TRACE`. This allows us to focus
on the errors instead. A summary of all operations is printed at the and of each run.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2665)
=> BS: Reduce logging and refactor registrar/originator/propagator tasks

go/beacon_srv/main.go, go/path_srv/internal/handlers/segreg.go
Beacons and IFStateInfo messages do not support QUIC yet.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2686)
=> Enable QUIC RPC in BS Messenger

go/beacon_srv/internal/beaconing/handler.go, go/beacon_srv/internal/beaconing/metrics/metrics.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2695)
=> BS: Metrics about incoming beacons

python/topology/go.py
We shouldn't log to a single file only.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2697)
=> generator: Fix dispatcher log name in dockerized topo

go/beacon_srv/internal/beaconing/originator_test.go, go/beacon_srv/internal/beaconing/propagator_test.go, go/beacon_srv/internal/beaconing/registrar_test.go
The added tests check that the fast recovery mechanism works as
expected.
fixes #2685
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2694)
=> BS: Add fast recovery unit test

go/godispatcher/internal/registration/BUILD.bazel, go/godispatcher/internal/registration/portlist.go, go/godispatcher/internal/registration/portlist_test.go, go/godispatcher/internal/registration/svctable_test.go
Removing the first entry in the port list wasn't doing the correct action,
which lead to SVC multicast errors.
Portlist was not always nil save which lead to dispatcher panics.
Co-authored-by: Oncilla <roos@anapaya.net>
Co-authored-by: Sergio Gonzalez Monroy <sgmonroy@gmail.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2696)
=> disp: Fix SVC multicast and nil panic

go/godispatcher/network/app_socket.go
When applications sent EOF, the dispatcher wasn't shutting down the
ingress traffic goroutine, thus causing a dangling reference to the
connection.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2705)
=> Fix memory leak in Go dispatcher

go/lib/infra/modules/cleaner/BUILD.bazel, go/lib/infra/modules/cleaner/cleaner.go, go/lib/infra/modules/cleaner/cleaner_test.go
Previously, registering the cleaner with the same sub-system would
cause a panic.
Now, the cleaner registers metrics pointers and provides them as
appropriate.
fixes #2701
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2703)
=> Cleaner: Make safe against double registration

go/lib/infra/messenger/BUILD.bazel, go/lib/infra/messenger/messenger.go, go/lib/infra/messenger/quic_handler.go, go/lib/infra/messenger/quic_response_writer.go, go/lib/infra/rpc/BUILD.bazel, go/lib/infra/rpc/request.go, go/lib/infra/rpc/rpc.go, go/lib/infra/rpc/rpc_test.go, go/proto/cereal.go, go/proto/cereal_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2707)
=> Move message-specific behavior out of generic RPC library

acceptance/bs_add_link_acceptance/test, acceptance/common/README.md, acceptance/common/base.py
As it turns out, plumbum expects every sub-command to be their
own cli.Application. This PR refactors the acceptance framework
and introduces 2 base classes. One for the test definition and
doc string, and one for the sub-commands.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2710)
=> Accept: Refactor command structure

scion.sh
This PR first starts the dispatcher and border routers to ensure
initial connectivity.
Currently, some tests fail because the beacon server are started
before the border routers and the ifid keepalives are not delivered.
By the time the border router has started, the interface is already
revoked. The introduced ordering will avoid this problem.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2717)
=> Ordered topology start

go/lib/infra/messenger/messenger.go, go/sciond/internal/fetcher/fetcher.go
Since everything is triggered from the request we should use the same logger everywhere.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2712)
=> sciond: copy logger from request to extended context

go/sciond/internal/fetcher/fetcher.go
Instead of passing 0 to buildSCIONDReply sometimes just always pass req.MaxPaths.
This prevents errors, also there was one OK case where 0 was wrongly passed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2718)
=> sciond: Make sure maxpaths is always respected

go/lib/infra/modules/trust/trust.go
If we do a routing to a dest ISD we get a path to a specific AS.
So instead of only setting the IA from this path, use directly the whole path.
This saves a request to sciond.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2720)
=> CS: Use path to wildcard AS directly

go/path_srv/internal/handlers/segreq.go, go/path_srv/internal/handlers/segreqcore.go, go/path_srv/internal/handlers/segreqnoncore.go, go/path_srv/internal/handlers/segreqnoncore_test.go
The path server determines whether an AS in a remote ISD is core or
not using the TRC. If the TRC is missing locally, the path server
currently queries the local certificate service for the TRC.
In a non-core AS, the certificate server discovers TRCs for remote ISDs
through the path server. Thus, it is highly unlikely that it already has
the TRC. This causes the certificate server to request a path to the
local core from the path server, leading to many rpc calls and a loop
in addressed services.
With this change, a path server in a non-core AS immediately fetches
the TRC from a local core certificate server to avoid rpc calls
and reduce latency.
--- …
=> PS: Request missing TRC from core CS

go/path_srv/internal/handlers/segrevoc.go
When the border router forks a revocation, the PS will
try to fetch the crypto from the border router that happily
drops these kinds of requests.
By setting nil, the certificate server is queried which makes sense in all cases.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2729)
=> PS: Revocation handler should not query BR

integration/e2e_integration
Increase the timeout to 2.5 seconds, to allow enough time for
querying and verifying path and crypto material on CI.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2731)
=> CI: Increase e2e timeout for core-core

go/lib/infra/modules/trust/trustdb/metrics.go, go/lib/pathdb/BUILD.bazel, go/lib/pathdb/metrics.go
Introduce observe method instead of inc methods.
That is more flexible, it allows to add timing metrics and will make adding tracing easier.
Also do not preinitialize counters we do not use all of them in all services.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2732)
=> Simplify trust-&path-db metrics code

go/beacon_srv/main.go, go/lib/infra/infraenv/infraenv.go, go/lib/snet/dispatcher.go, go/lib/snet/packet_conn.go, go/lib/snet/reader.go, go/lib/snet/snet.go
Also, QUIC sockets for infra RPC no longer propagate SCMP errors back to
the app.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2734)
=> Allow snet users to customize SCMP behavior

Makefile
The new `goenv` make target will generate the go/vendor links, as well as
in-tree links to generated files.
Also:
- Fix up the phony target list
- Remove go/vendor in the `clean` target.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2740)
=> Add goenv (and helper) target(s).

go/beacon_srv/main.go
We should kill all the tasks we start.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2742)
=> BS: Fix killing periodic tasks

acceptance/common/tools.py, acceptance/lib.sh
The scion tester image depends on scion_app_builder container,
thus we should build per-app images first since that also build the scion_app_builder container.
Also use a pipe to collect logs so that we don't have create a file manually.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2743)
=> acceptance: Fix build order

go/lib/infra/modules/trust/signhelper.go
This change adds the payload type information to the signature
verification error.
Before the formatted error looked something like this:
````
>  Sanity check failed
>      SignS is unset
````
Now:
````
>  Sanity check failed pld="Ctrl: Union: CertMgmt: Union: CertificateChain 1-ff00:0:130v1"
>      SignS is unset
````
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2749)
=> Improve verification error output

go/beacon_srv/internal/beaconing/originator.go, go/beacon_srv/internal/beaconing/propagator.go, go/beacon_srv/internal/beaconing/registrar.go
Before, the propagation/origination/registration tasks always logged
the summary if there are stale interfaces.
Now, these tasks only log when successfully beacon on one or multiple
stale interfaces.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2759)
=> BS: Reduce logging

go/path_srv/internal/handlers/segreq.go
Currently, the PS logs that it sent a reply even if it fails sending.
This is the log output currently:
````
2019-06-17 10:34:32.850597+0000 [EROR] [segReqHandler] Failed to send reply! debug_id=185fc30b err="Stream 0 was reset with error code 1"
2019-06-17 10:34:32.850610+0000 [DBUG] [segReqHandler] reply sent debug_id=185fc30b id=8141298586611935543 ups=0 cores=0 downs=4
````
With the change, the PS does not log the second line.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2762)
=> PS: Return immediately if sending the reply failed

go/lib/pathdb/pathdb.go, go/sciond/internal/fetcher/fetcher.go
It doens't make sense to insert the NextQuery if we dind't get a reply,
otherwise we wouldn't request again for a long time eventhough the initial request failed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2761)
=> sciond: Only insert next query if we got a reply

README.md, WORKSPACE
Also change the documentation to recommend that people install this
specific version of bazel, and not just the latest.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2766)
=> Update bazel go rules to work with 0.27.0

acceptance/ctl
`acceptance/ctl grun foo` was not running the proper script file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2767)
=> Fix single acceptance test runner

go/cert_srv/internal/reiss/requester.go, go/lib/common/defs.go, go/lib/ctrl/path_mgmt/rev_info.go, go/lib/ctrl/seg/seg.go, go/lib/scrypto/cert/cert.go, go/lib/scrypto/cert/chain.go, go/lib/scrypto/trc/trc.go, go/lib/spath/info.go, go/lib/util/time.go
This only makes the log noisy.
Example segment before:
`Type: up, Segment: 41187899827c 2019-06-17 12:12:59.000000+0000 1-ff00:0:120 4>3 1-ff00:0:121`
After:
`Type: up, Segment: 41187899827c 2019-06-17 12:11:29+0000 1-ff00:0:120 4>3 1-ff00:0:121`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2763)
=> Do not print millis for timestamps with secs only

.buildkite/scripts/build_scion_img, README.md, docker/Dockerfile.base, tools/install_bazel
Fixes https://github.com/scionproto/scion/issues/2769
Bazel 0.27.0 breaks some of our dependencies. E.g.:
https://github.com/GoogleContainerTools/distroless/pull/373
Bazel 0.26.1 seems to work just fine, so let's go back to it.
Also:
- Update tools/install_bazel to install the correct version of bazel
from github, not apt, so it doesn't get auto-upgraded.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2778)
=> Downgrade to bazel 0.26.1

go/border/rctx/io.go, go/border/router.go
The border router prints the socket to the logs, whil parts can still
be modified by another go routine. This shows up during race detection.
Most of the logged information is pointers, which is not really useful.
This PR reduces the logged information and makes sure no race condition
occur.
Before:
````
2019-06-20 12:21:21.468642+0000 [DBUG] Setting up new local socket. bind=[127.0.0.17]:31008
2019-06-20 12:21:21.468693+0000 [DBUG] Done setting up new local socket. conn=[127.0.0.17]:31008
2019-06-20 12:21:21.468699+0000 [DBUG] Setting up new external socket. intf="&{Id:11 IFAddr:TopoBRAddr{IPv4:{PublicOverlay: [127.0.0.5]:50000 BindOverlay: <nil>},Overlay: UDP/IPv4} RemoteAddr:[127.0.0.4]:50000 RemoteIA:1-ff00:0:110 BW:1000 MTU:1280 Type:parent}"
2019-06-20 12:21:21.468754+0000 [DBUG] …
```
=> BR: Fix racy log

go/lib/infra/infraenv/infraenv.go
Currently, `infraenv.NewRouter` returns a router with a nil sciond
connection, if every attempt fails to connect to sciond.
This happens because the `err` variable is shadowed, and thus never
set in the outer scope.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2790)
=> Infra: Error out if initial sciond connect fails

Makefile, acceptance/brutil/common.sh
`bin/braccept` is only needed for the br acceptance tests, so check/set
capabilities there instead.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2793)
=> Don't prompt for sudo password on every build.

python/lib/crypto/certificate.py, python/topology/cert.py
The generator occasionally issues leaf certificates that are valid
before the issuing Issuer certificate. This can happen, since the
granularity is one second, and the issuing time is simply current time
without considering the enclosing Issuer validity period.
This PR is a "hacky" attempt of solving the problem. As it will not take
any machine that is capable of running the topology more than a second
to generate the certificates, we simply add 2 seconds to the current
time for leaf certificates. This guarantees that the leaf certificates
validity period is covered by the Issuer certificate (given our
reasonable assumption)
To cleanly fix the issue, we should consider addressing #1491, but
this is good enough for now.
---
This change is [<img src="https://reviewable.io/review_button.svg" …
=> Gen: Leaf certificate issuing time workaround

BUILD.bazel, WORKSPACE, go/tools/buildkite_log_downloader/BUILD.bazel, go/tools/buildkite_log_downloader/main.go, nogo.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2777)
=> buildkite: Add tool to download logs

.buildkite/acceptance-pipeline.sh, .buildkite/common.sh, .buildkite/files/acceptance_trigger_instructions, .buildkite/pipeline.sh, .buildkite/scripts/all_images, .buildkite/scripts/run_acceptence_test_curl_command, .buildkite/triggers/acceptance-trigger.yml
The acceptance tests will be triggered for master pushes. Also the pipeline prints instructions how to start the acceptance tests manually or with a curl command.
https://github.com/scionproto/scion/wiki/Buildkite for updated documentation
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2781)
=> Buildkite: Acceptance in separate pipeline

.buildkite/steps/setup.yml
build_scion_img actually calls docker.sh which creates docker/_build/scion.stamp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2811)
=> BK: remove command because it's now unnecessary

.buildkite/scripts/build_scion_img, env/debian/pkgs.txt
It's needed by python3-openssl to handle subjectAltName's on certs.
(It's marked as 'recommended' by python3-openssl, but we use
`--no-install-recommends` to reduce the amount of unnecessary packages
installed.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2823)
=> Add python3-pyasn1 to dependencies.

scion.sh
This helps to easily view traces from a folder,
it will start the jaeger all-in-one container and open the browser to view the traces.
Co-authored-by: Oncilla <roos@anapaya.net>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2825)
=> Add scion.sh traces command to view traces from a folder

go/beacon_srv/main.go, go/lib/periodic/periodic.go, go/path_srv/main.go
* Make sure we call msger.CloseServer()
* PS: Start discorunner separately from other tasks
* Make kill on a nil periodic.Runner a no-op so that we don't have to have ifs in client code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2827)
=> BS,PS: Streamline main

docker.sh
Fixes integration tests running out of memory (on CI)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2828)
=> Remove 4GB memory limit and 1GB shared memory limit from docker.sh 

README.md, doc/ControlPlanePKI.md, doc/PathPolicy.md, doc/PathService.md, tools/md/mdlintstyle.rb
Note that this PR also changes the configuration of the md linter, therefore some other documents changed as well (whitespace only).
The problem is with rule MD007, there is an upstream issue: https://github.com/markdownlint/markdownlint/issues/139
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2839)
=> Add path policies in path lookup design

go/lib/scrypto/BUILD.bazel, go/lib/scrypto/validity.go, go/lib/scrypto/validity_test.go, go/lib/util/BUILD.bazel, go/lib/util/time.go, go/lib/util/time_test.go
This change introduces the validity period.
This will be used for the new TRC and certificate format.
Additionally, adds unix time that marshals and unmarshals in the correct
format (64 bit uint seconds since epoch).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2842)
=> crypto: Introduce validity period

go/lib/infra/modules/trust/handlers.go, go/lib/infra/modules/trust/trustdb/trustdbtest/trustdbtest.go
Chain and TRC push handlers log that they received a msg only at trace level.
On the other hand a new TRC or Chain that was received is logged at info level.
Also make sure that a double insert of a chain in the trustdb return 0 modified rows.
Fixes #2866
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2869)
=> trust store: Reduce log level of push received message

go/lib/scrypto/trc/v2/BUILD.bazel, go/lib/scrypto/trc/v2/keychanges.go, go/lib/scrypto/trc/v2/primary.go, go/lib/scrypto/trc/v2/update.go, go/lib/scrypto/trc/v2/update_test.go
This PR introduces TRC update validation.
The `UpdateValidator` checks that the new TRC contains valid contents
and the update is valid according to the regular/sensitive rules.
The caller has to verify the signatures itself. It must ensure that
all signatures mentioned in TRC.Votes are present and verifiable.
fixes #2849
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/2860)
=> crypto: TRC update validation
